<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2007

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce 2007 Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/ThirdPartyFlatFileDetailCollection">
		<ThirdPartyFlatFileDetailCollection>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation">C:/UpdatedTP/Prana_Final.xsd</xsl:attribute>
			<xsl:for-each select="ThirdPartyFlatFileDetail">
				<ThirdPartyFlatFileDetail>

					<xsl:for-each select="CompanyID">
						<CompanyID>
							<xsl:value-of select="."/>
						</CompanyID>
					</xsl:for-each>
					<xsl:for-each select="ThirdPartyID">
						<ThirdPartyID>
							<xsl:value-of select="."/>
						</ThirdPartyID>
					</xsl:for-each>

					<TaxLotState>
						<xsl:value-of select="TaxLotState"/>
					</TaxLotState>

          <FromDeleted>
            <xsl:value-of select="'false'"/>
          </FromDeleted>
					
					<ClientTradeRef>
						<xsl:value-of select="PBUniqueID"/>
					</ClientTradeRef>

					<AllocationSequenceNumber>
						<xsl:value-of select="AllocationSeqNo"/>
					</AllocationSequenceNumber>

					<xsl:for-each select="AssetID">
						<AssetID>
							<xsl:value-of select="."/>
						</AssetID>
					</xsl:for-each>

					<!-- Starts Asset Type -->
					<xsl:choose>
						<xsl:when test="Asset='EquityOption'">
							<AssetType>
								<xsl:value-of select="'OPTION'"/>
							</AssetType>
						</xsl:when>
						<xsl:otherwise>
							<AssetType>
								<xsl:value-of select="' '"/>
							</AssetType>
						</xsl:otherwise>
					</xsl:choose >

					<!--Ends Asset Type -->

					<xsl:choose>
						<xsl:when test="TaxLotState='Allocated'">
							<TradeState>
								<xsl:value-of select="'ENTER'"/>
							</TradeState>
						</xsl:when>
						<xsl:when test="TaxLotState='Amemded' or TaxLotState='Sent'">
							<TradeState>
								<xsl:value-of select="'UPDATE'"/>
							</TradeState>
						</xsl:when>
						<xsl:when test="TaxLotState='Deleted'">
							<TradeState>
								<xsl:value-of select="'CANCEL'"/>
							</TradeState>
						</xsl:when>
						<xsl:otherwise>
							<TradeState>
								<xsl:value-of select="' '"/>
							</TradeState>
						</xsl:otherwise>
					</xsl:choose >
					

					<CounterPartyID>
						<xsl:value-of select="CounterPartyID"/>
					</CounterPartyID>

					<!--<xsl:choose>
						<xsl:when test ="CounterParty='MS'">
							<Broker>
								<xsl:value-of select="'BARC'"/>
							</Broker>
						</xsl:when>
						<xsl:otherwise >
							<Broker>
								<xsl:value-of select="'BARC'"/>
							</Broker>
						</xsl:otherwise>
					</xsl:choose >-->
					
					<Broker>
						<xsl:value-of select="translate(CounterParty, $vLowercaseChars_CONST , $vUppercaseChars_CONST)"/>						
					</Broker>					

					<Account>
						<xsl:value-of select="FundAccountNo"/>
					</Account>

					<xsl:choose>
						<xsl:when test="Asset ='EquityOption' and UnderLyingID ='1'">
							<AccountType>
								<xsl:value-of select="'MARGIN'"/>
							</AccountType>
						</xsl:when>
						<xsl:when test="Asset = 'EquityOption' and UnderLyingID !='1'">
							<xsl:if test="Side='Sell short' or Side='Buy to Cover' or Side='Buy to Close'">
								<AccountType>
									<xsl:value-of select="'SHORT'"/>
								</AccountType>
							</xsl:if>
							<xsl:if test="Side='Buy' or Side='Sell' or Side='Buy to Open' or Side= 'Sell to Close' or Side='Sell to Open'">
								<AccountType>
									<xsl:value-of select="'MARGIN'"/>
								</AccountType>
							</xsl:if>
						</xsl:when>
						<xsl:when test="Asset !='EquityOption'">
							<xsl:if test="Side='Sell short' or Side='Buy to Cover' or Side='Buy to Close'">
								<AccountType>
									<xsl:value-of select="'SHORT'"/>
								</AccountType>
							</xsl:if>
							<xsl:if test="Side='Buy' or Side='Sell' or Side='Buy to Open' or Side= 'Sell to Close' or Side='Sell to Open'">
								<AccountType>
									<xsl:value-of select="'MARGIN'"/>
								</AccountType>
							</xsl:if>
						</xsl:when>
						<xsl:otherwise >
							<AccountType>
								<xsl:value-of select="'MARGIN'"/>
							</AccountType>
						</xsl:otherwise>
					</xsl:choose >

					<ProductCode>
						<xsl:value-of select="Symbol"/>
					</ProductCode>
					<!--<xsl:choose>
						<xsl:when test="Asset='EquityOption'">							
								<ProductCode>
									<xsl:value-of select ="UnderlyingSymbol"/>
								</ProductCode>
						</xsl:when>
						<xsl:otherwise>
							<ProductCode>
								<xsl:value-of select ="Symbol"/>
							</ProductCode>
						</xsl:otherwise>
					</xsl:choose >-->

					<xsl:for-each select="CurrencyID">
						<CurrencyID>
							<xsl:value-of select="."/>
						</CurrencyID>
					</xsl:for-each>

					<Currency>
						<xsl:value-of select="CurrencySymbol"/>
					</Currency>


					<!-- Side Starts-->
					<xsl:for-each select="SideID">
						<SideID>
							<xsl:value-of select="."/>
						</SideID>
					</xsl:for-each>

					<xsl:choose>
						<xsl:when test="Side='Buy' or Side='Buy to Open'">
							<TransactionType>
								<xsl:value-of select="'BL'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Buy to Close' or Side='Buy to Cover'">
							<TransactionType>
								<xsl:value-of select="'CS'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Sell' or Side='Sell to Close' or Side='Sell to Open'">
							<TransactionType>
								<xsl:value-of select="'SL'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Sell short'">
							<TransactionType>
								<xsl:value-of select="'SS'"/>
							</TransactionType>
						</xsl:when>
						<xsl:otherwise >
							<TransactionType>
								<xsl:value-of select="' '"/>
							</TransactionType>
						</xsl:otherwise>
					</xsl:choose >

					<!--   Side End    -->

					<Quantity>
						<xsl:value-of select="AllocatedQty"/>
					</Quantity>

					<Price>
						<xsl:value-of select="AveragePrice"/>
					</Price>

					<AccruedInterest>
						<xsl:value-of select="'0'"/>
					</AccruedInterest>

					<Principal>
						<xsl:value-of select="GrossAmount"/>
					</Principal>

					<Exchangefee>
						<xsl:value-of select="StampDuty + TransactionLevy + ClearingFee + MiscFees"/>
					</Exchangefee>

					<Commissionfee>
						<xsl:value-of select="CommissionCharged + TaxOnCommissions + OtherBrokerFee"/>	
					</Commissionfee>

					<Taxfee>
						<xsl:value-of select="'0'"/>
					</Taxfee>

					<TotalCurrency>
						<xsl:value-of select="NetAmount"/>
					</TotalCurrency>

					<TradeDate>
						<xsl:value-of select="TradeDate"/>
					</TradeDate>

					<SettlementDate>
						<xsl:value-of select="SettlementDate"/>
					</SettlementDate>

					<ExpiryDate>
						<xsl:value-of select="' '"/>
					</ExpiryDate>
					<Reserved>
						<xsl:value-of select="' '"/>
					</Reserved>
					<Comments>
						<xsl:value-of select="' '"/>
					</Comments>

					<xsl:choose>
						<xsl:when test="Asset='EquityOption'">
							<xsl:if test="PutOrCall='0'">
								<Put_Call>
									<xsl:value-of select ="'PUT'"/>
								</Put_Call>
							</xsl:if >
							<xsl:if test="PutOrCall='1'">
								<Put_Call>
									<xsl:value-of select ="'CALL'"/>
								</Put_Call>
							</xsl:if >
						</xsl:when>
						<xsl:otherwise>
							<Put_Call>
								<xsl:value-of select ="' '"/>
							</Put_Call>
						</xsl:otherwise>
					</xsl:choose >

					<xsl:choose>
						<xsl:when test="Asset='EquityOption'">
							<xsl:variable name="varPriceBefore" 
							select="substring-before(StrikePrice,'.')"/>
							<xsl:if test ="$varPriceBefore != ''">
								<StrikePrice_int>
									<xsl:value-of select ="$varPriceBefore"/>
								</StrikePrice_int>
							</xsl:if >
							<xsl:if test ="$varPriceBefore = ''">
								<StrikePrice_int>
									<xsl:value-of select ="StrikePrice"/>
								</StrikePrice_int>
							</xsl:if >
						</xsl:when>
						<xsl:otherwise>
							<StrikePrice_int>
								<xsl:value-of select ="' '"/>
							</StrikePrice_int>
						</xsl:otherwise>
					</xsl:choose >

					<xsl:choose>
						<xsl:when test="Asset='EquityOption'">
							<xsl:variable name="varPriceAfter" 
							select="substring-after(StrikePrice,'.')"/>
							<xsl:if test ="$varPriceAfter !=''">
								<StrikePrice_Frac>
									<xsl:value-of select ="$varPriceAfter"/>
								</StrikePrice_Frac>
							</xsl:if>
							<xsl:if test ="$varPriceAfter =''">
								<StrikePrice_Frac>
									<xsl:value-of select ="'0'"/>
								</StrikePrice_Frac>
							</xsl:if>
						</xsl:when>
						<xsl:otherwise>
							<StrikePrice_Frac>
								<xsl:value-of select ="' '"/>
							</StrikePrice_Frac>
						</xsl:otherwise>
					</xsl:choose >

					<xsl:choose>
						<xsl:when test="Asset='EquityOption'">
							<ExpiryMonth>
								<xsl:value-of select ="substring-before(ExpirationDate,'/')"/>
							</ExpiryMonth>
						</xsl:when>
						<xsl:otherwise>
							<ExpiryMonth>
								<xsl:value-of select ="' '"/>
							</ExpiryMonth>
						</xsl:otherwise>
					</xsl:choose >

					<xsl:choose>
						<xsl:when test="Asset='EquityOption'">
							<ExpiryYear>
								<xsl:value-of select ="substring(ExpirationDate,7)"/>
							</ExpiryYear>
						</xsl:when>
						<xsl:otherwise>
							<ExpiryYear>
								<xsl:value-of select ="' '"/>
							</ExpiryYear>
						</xsl:otherwise>
					</xsl:choose >
					<ExecutionType>
						<xsl:value-of select ="' '"/>
					</ExecutionType>
					<FillSeqNo>
						<xsl:value-of select ="' '"/>
					</FillSeqNo>

					<!--Id Fields Not for Save -->
					<xsl:for-each select="CompanyFundID">
						<CompanyFundID>
							<xsl:value-of select="."/>
						</CompanyFundID>
					</xsl:for-each>

					<xsl:for-each select="ExchangeID">
						<ExchangeID>
							<xsl:value-of select="."/>
						</ExchangeID>
					</xsl:for-each>

					<xsl:for-each select="UnderLyingID">
						<UnderLyingID>
							<xsl:value-of select="."/>
						</UnderLyingID>
					</xsl:for-each>

					<xsl:for-each select="AUECID">
						<AUECID>
							<xsl:value-of select="."/>
						</AUECID>
					</xsl:for-each>

					<xsl:for-each select="CommissionRateTypeID">
						<CommissionRateTypeID>
							<xsl:value-of select="."/>
						</CommissionRateTypeID>
					</xsl:for-each>

					<xsl:for-each select="CVID">
						<CVID>
							<xsl:value-of select="."/>
						</CVID>
					</xsl:for-each>

					<xsl:for-each select="CompanyFundTypeID">
						<CompanyFundTypeID>
							<xsl:value-of select="."/>
						</CompanyFundTypeID>
					</xsl:for-each>

					<xsl:for-each select="ThirdPartyTypeID">
						<ThirdPartyTypeID>
							<xsl:value-of select="."/>
						</ThirdPartyTypeID>
					</xsl:for-each>

					<xsl:for-each select="CompanyCVID">
						<CompanyCVID>
							<xsl:value-of select="."/>
						</CompanyCVID>
					</xsl:for-each>

					<xsl:for-each select="EntityID">
						<EntityID>
							<xsl:value-of select="."/>
						</EntityID>
					</xsl:for-each>
					<xsl:for-each select="OrderID">
						<OrderID>
							<xsl:value-of select="."/>
						</OrderID>
					</xsl:for-each>
					<xsl:for-each select="TradAccntID">
						<TradAccntID>
							<xsl:value-of select="."/>
						</TradAccntID>
					</xsl:for-each>

				</ThirdPartyFlatFileDetail>
			</xsl:for-each>
		</ThirdPartyFlatFileDetailCollection>
	</xsl:template>

	<!-- variable declaration for lower to upper case -->

	<xsl:variable name="vLowercaseChars_CONST" select="'abcdefghijklmnopqrstuvwxyz'"/>
	<xsl:variable name="vUppercaseChars_CONST" select="'ABCDEFGHIJKLMNOPQRSTUVWXYZ'"/>

	<!-- variable declaration for lower to upper case ENDs -->
	
</xsl:stylesheet>
