truncate table T_AuthModuleResources

	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(0,'None','None');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(1,'SLSU','SLSU');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(2,'AUEC','AUEC');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(3,'CV_Master','CV_Master');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(4,'Third_Party','Third_Party');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(5,'Company_Master','Company_Master');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(6,'Position_Management','Position_Management');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(7,'CommissionForm','CommissionForm');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(8,'SymbolLookUp','SymbolLookUp');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(9,'ReconCancelAmend','ReconCancelAmend');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(10,'User','User');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(11,'FileUpload','FileUpload');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(12,'ImportFileSetupTab','ImportFileSetupTab');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(13,'ImportDataNew','ImportDataNew');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(14,'AdminTradingAcountSetup','AdminTradingAcountSetup');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(15,'SecurityManagement','SecurityManagement');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(16,'PermissionSetup','PermissionSetup');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(17,'AuditTrail','AuditTrail');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(18,'Allocation','Allocation');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(19,'TradingTicket','TradingTicket');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(20,'ReleaseSetup','ReleaseSetup');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(24,'UserPermissionsTab','Showing Permission Tab on User Level');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(25,'ClientPermissionsTab','Showing Permission Tab on Client Level');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(21,'FundLock','FundLock');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(22,'AuditTrailUI','AuditTrailUI');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(23,'MappingForm','MappingForm');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(26,'EnableDisabledItemsTab','EnableDisabledItemsTab');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(27,'Global_Preferences','Global_Preferences');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(28,'CorporateAction','CorporateAction');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(29,'ClosingUI','ClosingUI');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(30,'PricingDataLookUp','PricingDataLookUp');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(31,'ClosingPrefsUI','ClosingPrefsUI');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(32,'MasterDashboard','MasterDashboard');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(33,'CashManagementUI','CashManagementUI');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(34,'CashTransactions','CashTransactions');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(35,'CashAccountsUI','CashAccountsUI');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(36,'Exchanges','Exchanges');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(37,'Assets','Assets');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(38,'Currencies','Currencies');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(39,'Underlyings','Underlyings');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(41,'ThirdPartyManager','ThirdPartyManager');
	INSERT INTO T_AuthModuleResources(ModuleId, ModuleName, ModuleDesc)   Values(42,'LiveFeedValidationForm','LiveFeedValidationForm');