--SET IDENTITY_INSERT T_MODULE ON;
EXEC sp_msforeachtable "ALTER TABLE ? NOCHECK CONSTRAINT ALL";
DELETE FROM T_MODULE;

INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(1,'Portfolio Management')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(2,'Trading Ticket')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(3,'Allocation')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(4,'Compliance Pre Trade')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(5,'Compliance Post Trade')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(6,'Audit Trail')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(7,'Blotter')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(8,'Blotter/Execution Report')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(9,'Corporate Actions')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(10,'General Ledger')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(11,'Create Transaction')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(12,'Accruals')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(13,'Data Mapping')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(14,'Cash Accounts (Account Setup)')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(15,'Server Report Form')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(16,'Third Party Manager')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(17,'Close Positions')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(18,'Daily Valuation')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(19,'Multi Trading Ticket')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(21,'Reconciliation')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(22,'Risk Analysis')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(23,'Security Master')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(24,'Zero Position Alert')

INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(26,'Pricing Inputs')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(27,'Import Data')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(28,'Middleware Manager')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(29,'Missing Trades')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(30,'Generate Report')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(31,'Reconciliation New')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(32,'Auto Import Data')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(33,'Heat Map')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(34,'Rebalancer')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(35,'Allocation (Edit Trade)')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(36,'% Trading Tool')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(37,'Quality Checker')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(38,'Position Management')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(39,'Order Generation')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(40,'User Profile')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(41,'Watchlist')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(42,'Short Locate')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(43,'Allocation (Leveling)')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(44,'Allocation (Pro-rata/NAV)')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(46,'Option Chain')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(47,'Portfolio Analytics')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(48,'Portfolio Dashboard')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(49,'Reporting')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(50,'Quick Trading Ticket')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(51,'Wash Sale On-boarding')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(52,'Compliance Engine (Rule Definitions)')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(53,'Compliance Engine (Alerts history)')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(54,'Compliance Engine (Pending Approval)')
INSERT INTO T_MODULE(ModuleID, ModuleName) VALUES(55,'NAV Lock')
EXEC sp_msforeachtable "ALTER TABLE ? WITH CHECK CHECK CONSTRAINT ALL";
--SET IDENTITY_INSERT T_MODULE OFF