using Prana.BusinessObjects;
using Prana.BusinessObjects.AppConstants;
using Prana.BusinessObjects.SecurityMasterBusinessObjects;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Prana.Interfaces
{
    public interface IClientsCommonDataManager
    {
        List<string> GetAccountsForTheUser(int userID);
        Assets GetCompanyUserAssets(int userID);
        Asset FillCompanyAssets(object[] row, int offSet);
        UnderLying FillUnderLyings(object[] row, int offSet);
        UnderLyings GetUnderLyingsByUserID(int userID);
        UnderLyings GetUnderLyingsByAssetAndUserID(int userID, int assetID);
        AUEC FillCompanyUserAUECDetails(object[] row, int offSet);
        AUECs GetCompanyUserAUECDetails(int companyUserID);
        ClientAccounts GetCompanyClientAccounts(int companyClientID);
        ClearingFirmsPrimeBrokers GetClearingFirmsPrimeBrokers();
        ClearingFirmPrimeBroker FillClearingFirmPrimeBroker(object[] row, int offSet);
        ClientCollection GetClients(int companyID);
        CounterParty FillCounterPartiesForTradingTicket(object[] row, int offSet);
        CounterPartyCollection GetCounterPartiesByAUIDAndUserID(int userID, int AssetID, int UnderlyingID);
        CounterPartyCollection GetCompanyUserCounterParties(int userID);
        CounterPartyCollection GetCompanyCounterParties(int companyID);
        CounterParty FillCompanyCounterParties(object[] row, int offSet);
        ImportTradeXSLTFileCollection GetCompanyEMSSource(int companyID, string path);
        Exchange FillExchangesForTradingTicket(object[] row, int offSet);
        Exchanges GetExchnagesByUserID(int userID);
        Sides GetSides();
        Sides GetOrderSidesByCVAUEC(int assetID, int UnderLyingID, int counterPartyID, int venueID);
        OrderTypes GetOrderTypes();
        OrderTypes GetOrderTypesByAUCVID(int assetID, int underlyingID, int counterPartyID, int venueID);
        TimeInForces GetTimeInForces();
        TimeInForces GetTIFByAUCVID(int assetID, int underlyingID, int counterPartyID, int venueID);
        HandlingInstructions GetHandlingInstructions();
        HandlingInstructions GetHandlingInstructionByAUCVID(int assetID, int underlyingID, int counterPartyID, int venueID);
        ExecutionInstructions GetExecutionInstructions();
        ExecutionInstructions GetExecutionInstructionByAUCVID(int assetID, int underlyingID, int counterPartyID, int venueID);
        Traders GetTraders(int companyClientID);
        Prana.BusinessObjects.VenueCollection GetVenues(int userID, int counterPartyID);
        Prana.BusinessObjects.VenueCollection GetVenuesByAUIDCounterPartyAndUserID(int userID, int counterPartyID, int assetID, int underlyingID);
        List<string> GetAllTradingAccounts();
        Prana.BusinessObjects.TradingAccountCollection GetTradingAccounts(int userID);
        DataTable GetSidesByAsset(int assetID);
        Prana.BusinessObjects.StrategyCollection GetStrategies(int userID);
        Prana.BusinessObjects.StrategyCollection GetStrategies();
        Prana.BusinessObjects.AccountCollection GetAccounts(int userID);
        DataTable GetAllPermittedAccounts(int UserID);
        DataTable GetAllImportTags();
        Prana.BusinessObjects.AccountCollection GetAccounts();
        Prana.BusinessObjects.AccountCollection GetMasterFunds();
        DataSet GetLatestAvailableFxRatesLessThanToday();
        int SavePranaPreferencesinDB(bool? isMasterFundManyToMany, bool? isMasterStrategyManyToMany, bool? isnavLockEnabled, bool? isFeederAccountEnabled, int? pricingSource, bool? isPermanentDeletion, int? SettlementAutoCalculateProperty, bool? isZeroCommissionForSwaps, int? avgPriceRounding, bool? isShowmasterFundAsClient, bool? isShowMasterFundonTT, bool? isEquityOptionManualValidation, bool? isCollateralMarkPriceValidation, bool? isShowTillSettlementDate);
        Dictionary<int, string> GetAllMasterFunds();
        Dictionary<int, int> GetAllMasterFundsTradingAccounts(int companyUserID);
        List<int> GetMasterFundsAndAccount(List<int> accounts);
        DataTable GetCompanyBorrowers(int userID);
        int GetCompanyBaseCurrency(int companyID);
        bool IsSendRealtimeManualOrderViaFix(int companyID);
        bool GetIsInMarketIncludedForTradingRules(int companyID);
        Prana.BusinessObjects.Currency GetCurrencyByAUECID(long AUECID);
        Dictionary<string, SortedDictionary<DateTime, ConversionRate>> GetFXConversionRates();
        ConversionRate GetFXConversionRatesForADateAndAccount(int fromCurrencyId, int toCurrencyId, int accountId, DateTime date);
        Dictionary<int, Dictionary<string, SortedDictionary<DateTime, ConversionRate>>> GetFXConversionRates_New();
        Dictionary<int, Dictionary<string, SortedDictionary<DateTime, ConversionRate>>> GetFXConversionRatesForGivenDate(DateTime startDate, DateTime? endDate);
        //Dictionary<string, List<FxPranaSymbol>> GetFxSymbolMapping();
        DataSet GetAllStandardCurrencyPairs();
        bool GetPMModulePermission(int companyID);
        Dictionary<string, DateTime> GetTaxlotsLatestClosingDates();
        Dictionary<string, Tuple<DateTime, int>> GetTaxlotsLatestCADates();
        Dictionary<string, DateTime> GetExcercisetaxlots();
        bool GetBreakOrderPreference(int CompanyId);
        TranferTradeRules GetTransferTradeRules(int CompanyId);
        Dictionary<string, Dictionary<string, string>> GetExcerciseGroupIDs(string FromAuecDatesString);
        DataSet GetAllAccountTablesFromDB();
        DataSet GetAllAccountsWithRelation(DataSet _masterCategorySubCategory);
        DataSet GetAllActivitiesFromDB();
        SecMasterRequestObj GetAllSymbols();
        string GetApplicationVersionFromDB();
        Dictionary<Tuple<int, string>, int> GetDefaultAUECDict(int companyID);
        Dictionary<int, Tuple<DateTime, bool>> GetCashPreferenceFundsFromDB();
        Dictionary<string, string> GetTransactionTypeFromDB();
        IList<string[]> GetCounterPartyVernuesSymbolConvertions();
        bool CheckPermissionAllAccountsAndTradingAccounts(int userID);
        TradingAccountCollection GetAllUsersTradingAccounts();
        VenueCollection GetAllUsersVenues();
        void DeleteCustomViewPreference(int userID, string tabname);
        string GetInvalidFundsForSymbolLevel(string fundIds, Nullable<DateTime> startDate, Nullable<DateTime> endDate);
        bool IsSymbolTraded(long symbol_pk);
        SecondaryMarketDataProvider GetSecondaryCompanyMarketDataProvider(int companyID);
        MarketDataProvider GetCompanyMarketDataProvider(int companyID);
        bool IsMarketDataBlocked(int companyId);
        int SavePranaPreferencesRevaluationPrefinDB(int dailyProcessDay);
        Dictionary<int, int> GetAccountWiseExecutingBrokerMappingFromDB(int companyID);
        int GetFactSetContractType(int companyID);
    }
}
