<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2007

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce 2007 Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/ThirdPartyFlatFileDetailCollection">
		<ThirdPartyFlatFileDetailCollection>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation">C:/UpdatedTP/Prana_Final.xsd</xsl:attribute>
			<xsl:for-each select="ThirdPartyFlatFileDetail">

				<ThirdPartyFlatFileDetail>

					<xsl:for-each select="CompanyID">
						<CompanyID>
							<xsl:value-of select="."/>
						</CompanyID>
					</xsl:for-each>
					<xsl:for-each select="ThirdPartyID">
						<ThirdPartyID>
							<xsl:value-of select="."/>
						</ThirdPartyID>
					</xsl:for-each>
					<TaxLotState>
						<xsl:value-of select="TaxLotState"/>
					</TaxLotState>

					<TransactionType>
						<xsl:value-of select="'TR001'"/>
					</TransactionType>

					<TransactionStatus>
						<xsl:value-of select="'NEW'"/>
					</TransactionStatus>

					<BuySellIndicator>
						<xsl:value-of select="' '"/>
					</BuySellIndicator>

					<LongShortIndicator>
						<xsl:value-of select="' '"/>
					</LongShortIndicator>

					<!--   Side     -->

					<xsl:for-each select="SideID">
						<SideID>
							<xsl:value-of select="."/>
						</SideID>
					</xsl:for-each>

					<xsl:if test="Side='Buy'">
						<PositionType>
							<xsl:value-of select="'BL'"/>
						</PositionType>
					</xsl:if>

					<xsl:if test="Side='Buy to Open'">
						<PositionType>
							<xsl:value-of select="'BL'"/>
						</PositionType>						
					</xsl:if>

					<xsl:if test="Side='Buy to Close'">
						<PositionType>
							<xsl:value-of select="'BC'"/>
						</PositionType>
					</xsl:if>
					
					<xsl:if test="Side='Buy to Cover'">
						<PositionType>
							<xsl:value-of select="'BC'"/>
						</PositionType>
					</xsl:if>

					<xsl:if test="Side='Sell'">
						<PositionType>
							<xsl:value-of select="'SL'"/>
						</PositionType>
					</xsl:if>

					<xsl:if test="Side='Sell to Close'">
						<PositionType>
							<xsl:value-of select="'SL'"/>
						</PositionType>					
					</xsl:if>

					<xsl:if test="Side='Sell short'">
						<PositionType>
							<xsl:value-of select="'SS'"/>
						</PositionType>
					</xsl:if>

					<xsl:if test="Side='Sell to Open'">
						<PositionType>
							<xsl:value-of select="'SL'"/>
						</PositionType>					
					</xsl:if>

					<!--   Side End    -->

					<TransactionLevel>
						<xsl:value-of select="'A'"/>
					</TransactionLevel>

					<ClientTradeRefNo>
						<xsl:value-of select="TradeRefID"/>
					</ClientTradeRefNo>

					<AssociatedTradeId>
						<xsl:value-of select="' '"/>
					</AssociatedTradeId>

					<ExecutionAccount>
						<xsl:value-of select="' '"/>
					</ExecutionAccount>

					<AccountId>
						<xsl:value-of select="FundMappedName"/>
					</AccountId>

					<CounterPartyID>
						<xsl:value-of select="CounterPartyID"/>
					</CounterPartyID>
					
					<CounterParty>
						<xsl:value-of select="CounterParty"/>
					</CounterParty>

					<xsl:choose>
						<xsl:when test="CUSIP != ''">
							<SecurityIdentifierType>
								<xsl:value-of select="'C'"/>
							</SecurityIdentifierType>
							
							<SecurityIdentifier>
								<xsl:value-of select="CUSIP"/>
							</SecurityIdentifier>							
						</xsl:when>

						<xsl:when test="ISIN != ''">
							<SecurityIdentifierType>
								<xsl:value-of select="'I'"/>
							</SecurityIdentifierType>

							<SecurityIdentifier>
								<xsl:value-of select="ISIN"/>
							</SecurityIdentifier>
						</xsl:when>					

						<xsl:when test="SEDOL != ''">
							<SecurityIdentifierType>
								<xsl:value-of select="'S'"/>
							</SecurityIdentifierType>

							<SecurityIdentifier>
								<xsl:value-of select="SEDOL"/>
							</SecurityIdentifier>
						</xsl:when>

						<xsl:when test="Symbol != ''">
							<SecurityIdentifierType>
								<xsl:value-of select="'T'"/>
							</SecurityIdentifierType>

							<SecurityIdentifier>
								<xsl:value-of select="Symbol"/>
							</SecurityIdentifier>
						</xsl:when>

						<xsl:when test="RIC != ''">
							<SecurityIdentifierType>
								<xsl:value-of select="'R'"/>
							</SecurityIdentifierType>

							<SecurityIdentifier>
								<xsl:value-of select="RIC"/>
							</SecurityIdentifier>
						</xsl:when>						

						<xsl:otherwise>
							<SecurityIdentifierType>
								<xsl:value-of select="'T'"/>
							</SecurityIdentifierType>

							<SecurityIdentifier>
								<xsl:value-of select="Symbol"/>
							</SecurityIdentifier>
						</xsl:otherwise>
					</xsl:choose>

					<xsl:for-each select="Symbol">
						<SecurityDescription>
							<xsl:value-of select="."/>
						</SecurityDescription>
					</xsl:for-each >

					<TradeDate>
						<xsl:value-of select="TradeDate"/>
					</TradeDate>

					<SettlementDate>
						<xsl:value-of select="SettlementDate"/>
					</SettlementDate>

					<xsl:for-each select="CurrencyID">
						<CurrencyID>
							<xsl:value-of select="."/>
						</CurrencyID>
					</xsl:for-each>

					<!--		<xsl:for-each select="CurrencyName">
						<SettleCurrency>
							<xsl:value-of select="."/>
						</SettleCurrency>
					</xsl:for-each>					-->
					<SettlementCCY>
						<xsl:value-of select="CurrencySymbol"/>
					</SettlementCCY>

					<ExchangeCode>
						<xsl:value-of select="' '"/>
					</ExchangeCode>

					<Quantity>
						<xsl:value-of select="AllocatedQty"/>
					</Quantity>

					<PriceAmount>
						<xsl:value-of select="AveragePrice"/>
					</PriceAmount>

					<PriceIndicator>
						<xsl:value-of select="'G'"/>
					</PriceIndicator>

					<Principal>
						<xsl:value-of select="' '"/>
					</Principal>

			<!--    <xsl:for-each select="Commission">
						<Commission>
							<xsl:value-of select="."/>
						</Commission>
					</xsl:for-each>					-->								

					<CommissionAmount>
						<xsl:value-of select="CommissionCharged"/>
					</CommissionAmount>

					<CommissionIndicator>
						<xsl:value-of select="'F'"/>
					</CommissionIndicator>

					<Taxorfees>
						<xsl:value-of select="OtherBrokerFee"/>
					</Taxorfees>

					<Tax2>
						<xsl:value-of select="' '"/>
					</Tax2>
					
					<TaxorfeesIndicator>
						<xsl:value-of select="' '"/>
					</TaxorfeesIndicator>

					<Interest>
						<xsl:value-of select="' '"/>
					</Interest>

					<InterestIndicator>
						<xsl:value-of select="' '"/>
					</InterestIndicator>

					<NetAmount>
						<xsl:value-of select="NetAmount"/>
					</NetAmount>

					<HearsayInd>
						<xsl:value-of select="' '"/>
					</HearsayInd>

					<Custodian>
						<xsl:value-of select="' '"/>
					</Custodian>

					<MoneyManager>
						<xsl:value-of select="' '"/>
					</MoneyManager>

					<BookId>
						<xsl:value-of select="' '"/>
					</BookId>

					<DealId>
						<xsl:value-of select="' '"/>
					</DealId>

					<TaxlotId>
						<xsl:value-of select="' '"/>
					</TaxlotId>

					<OriginalTaxlotTransactionDate>
						<xsl:value-of select="' '"/>
					</OriginalTaxlotTransactionDate>

					<OriginalTaxlotTransactionPrice>
						<xsl:value-of select="' '"/>
					</OriginalTaxlotTransactionPrice>

					<TaxLotCloseoutMethod>
						<xsl:value-of select="' '"/>
					</TaxLotCloseoutMethod>

					<ExchangeRate>
						<xsl:value-of select="' '"/>
					</ExchangeRate>

					<AcquisitionDate>
						<xsl:value-of select="' '"/>
					</AcquisitionDate>

					<Comments>
						<xsl:value-of select="' '"/>
					</Comments>






					<!--<xsl:for-each select="FundName">
						<TranType>
							<xsl:value-of select="'BS'"/>
						</TranType>
					</xsl:for-each>-->
					<!--       FUND          -->


					<xsl:for-each select="CompanyFundID">
						<CompanyFundID>
							<xsl:value-of select="."/>
						</CompanyFundID>
					</xsl:for-each>
					<!--         
					<xsl:for-each select="FundName">
						<FundName>
							<xsl:value-of select="."/>
						</FundName>
					</xsl:for-each>   				
					<xsl:for-each select="FundMappedName">
						<UBSAccount>
							<xsl:value-of select="."/>
						</UBSAccount>
					</xsl:for-each>    -->


					<!--	<xsl:for-each select="FundAccountNo">
						<FundAccountNo>
							<xsl:value-of select="."/>
						</FundAccountNo>
					</xsl:for-each>                   		 -->

					<!--      FUND END       -->
					
					

				

					

					<xsl:for-each select="AssetID">
						<AssetID>
							<xsl:value-of select="."/>
						</AssetID>
					</xsl:for-each>

					<!--<xsl:for-each select="NetAmount">
						<NetAmount>
							<xsl:value-of select="."/>
						</NetAmount>
					</xsl:for-each>-->

				
					
					<!--<xsl:for-each select="Symbol">
						<SecurityDescription>
							<xsl:value-of select="''"/>
						</SecurityDescription>
					</xsl:for-each>-->
					<!--<xsl:for-each select="Symbol">
						<IDType>
							<xsl:value-of select="'RIC'"/>
						</IDType>
					</xsl:for-each>-->
					
					
					<!--<xsl:for-each select="CounterParty">
						<Remark>
							<xsl:value-of select="' '"/>
						</Remark>
					</xsl:for-each>
					<xsl:for-each select="CounterParty">
						<Instruction>
							<xsl:value-of select="' '"/>
						</Instruction>
					</xsl:for-each>
					<xsl:for-each select="CounterParty">
						<BuyCurrency>
							<xsl:value-of select="' '"/>
						</BuyCurrency>
					</xsl:for-each>
					<xsl:for-each select="CounterParty">
						<BuyAmount>
							<xsl:value-of select="' '"/>
						</BuyAmount>
					</xsl:for-each>


					<xsl:for-each select="CounterParty">
						<SellCurrency>
							<xsl:value-of select="' '"/>
						</SellCurrency>
					</xsl:for-each>


					<xsl:for-each select="CounterParty">
						<SellAmount>
							<xsl:value-of select="' '"/>
						</SellAmount>
					</xsl:for-each>
					<xsl:for-each select="CounterParty">
						<Rate>
							<xsl:value-of select="' '"/>
						</Rate>
					</xsl:for-each>
					<xsl:for-each select="CurrencySymbol">
						<TradeCurrency>
							<xsl:value-of select="."/>
						</TradeCurrency>
					</xsl:for-each>
					<xsl:for-each select="CounterParty">
						<ExchangeRate>
							<xsl:value-of select="' '"/>
						</ExchangeRate>
					</xsl:for-each>
					<xsl:for-each select="CounterParty">
						<LiquidMethod>
							<xsl:value-of select="' '"/>
						</LiquidMethod>
					</xsl:for-each>
					<xsl:for-each select="CounterParty">
						<StampTax>
							<xsl:value-of select="' '"/>
						</StampTax>
					</xsl:for-each>
					<xsl:for-each select="CounterParty">
						<Interest>
							<xsl:value-of select="' '"/>
						</Interest>
					</xsl:for-each>-->
					<!--			<xsl:if test="Asset='Equity'">  
					<xsl:for-each select="Asset">
						<ProductType>
							<xsl:value-of select="'EQ'"/>
						</ProductType>
					</xsl:for-each>
			</xsl:if>  
			
			<xsl:if test="Asset='EquityOption'">  
					<xsl:for-each select="Asset">
						<ProductType>
							<xsl:value-of select="'OP'"/>
						</ProductType>
					</xsl:for-each>
			</xsl:if>  					

			
			<xsl:if test="Asset='FutureOption'">  
					<xsl:for-each select="Asset">
						<ProductType>
							<xsl:value-of select="'FO'"/>
						</ProductType>
					</xsl:for-each>
			</xsl:if> 

			
			<xsl:if test="Asset='Future'">  
					<xsl:for-each select="Asset">
						<ProductType>
							<xsl:value-of select="'FU'"/>
						</ProductType>
					</xsl:for-each>
			</xsl:if>  
		 			

					<xsl:for-each select="Symbol">
						<SecurityCodeType>
							<xsl:value-of select="'SY-Symbol'"/>
						</SecurityCodeType>
					</xsl:for-each>  					-->

					<xsl:for-each select="ExchangeID">
						<ExchangeID>
							<xsl:value-of select="."/>
						</ExchangeID>
					</xsl:for-each>
					<!--				<xsl:for-each select="Exchange">
						<Exchange>
							<xsl:value-of select="."/>
						</Exchange>
					</xsl:for-each>                              -->
					<!--			<xsl:for-each select="OrderTypeTag">
						<OrderTypeTag>
							<xsl:value-of select="."/>
						</OrderTypeTag>
					</xsl:for-each>					
					<xsl:for-each select="OrderType">
						<OrderType>
							<xsl:value-of select="."/>
						</OrderType>
					</xsl:for-each>					-->
					<xsl:for-each select="UnderLyingID">
						<UnderLyingID>
							<xsl:value-of select="."/>
						</UnderLyingID>
					</xsl:for-each>
					<!--			<xsl:for-each select="UnderLying">
						<UnderLying>
							<xsl:value-of select="."/>
						</UnderLying>
					</xsl:for-each>      -->
					<xsl:for-each select="AUECID">
						<AUECID>
							<xsl:value-of select="."/>
						</AUECID>
					</xsl:for-each>
					<!--		<xsl:for-each select="SecFees">
						<SecFees>
							<xsl:value-of select="."/>
						</SecFees>
					</xsl:for-each>     
					<xsl:for-each select="ClearingFee">
						<ClearingFee>
							<xsl:value-of select="."/>
						</ClearingFee>
					</xsl:for-each>                                
									-->
					<!--				<xsl:for-each select="SecurityIDType">
						<SecurityIDType>
							<xsl:value-of select="."/>
						</SecurityIDType>
					</xsl:for-each>	
				-->
					<xsl:for-each select="CommissionRateTypeID">
						<CommissionRateTypeID>
							<xsl:value-of select="."/>
						</CommissionRateTypeID>
					</xsl:for-each>
					<!--		<xsl:for-each select="CommissionRateType">
						<CommissionRateType>
							<xsl:value-of select="."/>
						</CommissionRateType>
					</xsl:for-each>				-->

					<!--				<xsl:for-each select="SavePath">
						<SavePath>
							<xsl:value-of select="."/>
						</SavePath>
					</xsl:for-each>
					<xsl:for-each select="NamingConvention">
						<NamingConvention>
							<xsl:value-of select="."/>
						</NamingConvention>
					</xsl:for-each>                               -->
					<xsl:for-each select="CVID">
						<CVID>
							<xsl:value-of select="."/>
						</CVID>
					</xsl:for-each>
					<!-- 			<xsl:for-each select="CVName">
						<CVName>
							<xsl:value-of select="."/>
						</CVName>
					</xsl:for-each>				
					<xsl:for-each select="CVIdentifier">
						<CVIdentifier>
							<xsl:value-of select="."/>
						</CVIdentifier>
					</xsl:for-each>					 -->
					<xsl:for-each select="CompanyFundTypeID">
						<CompanyFundTypeID>
							<xsl:value-of select="."/>
						</CompanyFundTypeID>
					</xsl:for-each>
					<!-- 			<xsl:for-each select="CompanyFundType">
						<CompanyFundType>
							<xsl:value-of select="."/>
						</CompanyFundType>
					</xsl:for-each>					 -->
					<xsl:for-each select="ThirdPartyTypeID">
						<ThirdPartyTypeID>
							<xsl:value-of select="."/>
						</ThirdPartyTypeID>
					</xsl:for-each>
					<!--			<xsl:for-each select="ThirdPartyType">
						<ThirdPartyType>
							<xsl:value-of select="."/>
						</ThirdPartyType>
					</xsl:for-each>    				  
					<xsl:for-each select="CompanyIdentifier">
						<CompanyIdentifier>
							<xsl:value-of select="."/>
						</CompanyIdentifier>
					</xsl:for-each>    				 
					<xsl:for-each select="Percentage">
						<Percentage>
							<xsl:value-of select="."/>
						</Percentage> 
					</xsl:for-each>    				  -->
					<!--<xsl:for-each select="TradingAccount">
						<TradingAccount>
							<xsl:value-of select="."/>
						</TradingAccount>
					</xsl:for-each>-->
					<xsl:for-each select="CompanyCVID">
						<CompanyCVID>
							<xsl:value-of select="."/>
						</CompanyCVID>
					</xsl:for-each>
					<!--			<xsl:for-each select="VenueID">
						<VenueID>
							<xsl:value-of select="."/>
						</VenueID>
					</xsl:for-each>
					<xsl:for-each select="VenueName">
						<VenueName>
							<xsl:value-of select="."/>
						</VenueName>
					</xsl:for-each>
					<xsl:for-each select="OrderQty">
						<OrderQty>
							<xsl:value-of select="."/>
						</OrderQty>
					</xsl:for-each>					  -->
					<xsl:for-each select="EntityID">
						<EntityID>
							<xsl:value-of select="."/>
						</EntityID>
					</xsl:for-each>
					<xsl:for-each select="OrderID">
						<OrderID>
							<xsl:value-of select="."/>
						</OrderID>
					</xsl:for-each>
					<xsl:for-each select="TradAccntID">
						<TradAccntID>
							<xsl:value-of select="."/>
						</TradAccntID>
					</xsl:for-each>
				</ThirdPartyFlatFileDetail>
			</xsl:for-each>
		</ThirdPartyFlatFileDetailCollection>
	</xsl:template>
</xsl:stylesheet>
