//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace NirvanaDataAccessSample.NirvanaDataAccess {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NirvanaDASoap", Namespace="Nirvana")]
    public partial class NirvanaDA : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AllocatedTradesOperationCompleted;
        
        private System.Threading.SendOrPostCallback TaxlotSnapshotOperationCompleted;
        
        private System.Threading.SendOrPostCallback UnallocatedTradesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SODPositionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback SymbolListOperationCompleted;
        
        private System.Threading.SendOrPostCallback SymbolCountOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NirvanaDA() {
            this.Url = global::NirvanaDataAccessSample.Properties.Settings.Default.NirvanaDataAccessSample;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AllocatedTradesCompletedEventHandler AllocatedTradesCompleted;
        
        /// <remarks/>
        public event TaxlotSnapshotCompletedEventHandler TaxlotSnapshotCompleted;
        
        /// <remarks/>
        public event UnallocatedTradesCompletedEventHandler UnallocatedTradesCompleted;
        
        /// <remarks/>
        public event SODPositionsCompletedEventHandler SODPositionsCompleted;
        
        /// <remarks/>
        public event SymbolListCompletedEventHandler SymbolListCompleted;
        
        /// <remarks/>
        public event SymbolCountCompletedEventHandler SymbolCountCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Nirvana/AllocatedTrades", RequestNamespace="Nirvana", ResponseNamespace="Nirvana", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AllocatedTrades[] AllocatedTrades(System.DateTime date, string errorMessage, int errorNumber) {
            object[] results = this.Invoke("AllocatedTrades", new object[] {
                        date,
                        errorMessage,
                        errorNumber});
            return ((AllocatedTrades[])(results[0]));
        }
        
        /// <remarks/>
        public void AllocatedTradesAsync(System.DateTime date, string errorMessage, int errorNumber) {
            this.AllocatedTradesAsync(date, errorMessage, errorNumber, null);
        }
        
        /// <remarks/>
        public void AllocatedTradesAsync(System.DateTime date, string errorMessage, int errorNumber, object userState) {
            if ((this.AllocatedTradesOperationCompleted == null)) {
                this.AllocatedTradesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllocatedTradesOperationCompleted);
            }
            this.InvokeAsync("AllocatedTrades", new object[] {
                        date,
                        errorMessage,
                        errorNumber}, this.AllocatedTradesOperationCompleted, userState);
        }
        
        private void OnAllocatedTradesOperationCompleted(object arg) {
            if ((this.AllocatedTradesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllocatedTradesCompleted(this, new AllocatedTradesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Nirvana/TaxlotSnapshot", RequestNamespace="Nirvana", ResponseNamespace="Nirvana", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TaxlotSnapshot[] TaxlotSnapshot(System.DateTime date, string errorMessage, int errorNumber) {
            object[] results = this.Invoke("TaxlotSnapshot", new object[] {
                        date,
                        errorMessage,
                        errorNumber});
            return ((TaxlotSnapshot[])(results[0]));
        }
        
        /// <remarks/>
        public void TaxlotSnapshotAsync(System.DateTime date, string errorMessage, int errorNumber) {
            this.TaxlotSnapshotAsync(date, errorMessage, errorNumber, null);
        }
        
        /// <remarks/>
        public void TaxlotSnapshotAsync(System.DateTime date, string errorMessage, int errorNumber, object userState) {
            if ((this.TaxlotSnapshotOperationCompleted == null)) {
                this.TaxlotSnapshotOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTaxlotSnapshotOperationCompleted);
            }
            this.InvokeAsync("TaxlotSnapshot", new object[] {
                        date,
                        errorMessage,
                        errorNumber}, this.TaxlotSnapshotOperationCompleted, userState);
        }
        
        private void OnTaxlotSnapshotOperationCompleted(object arg) {
            if ((this.TaxlotSnapshotCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TaxlotSnapshotCompleted(this, new TaxlotSnapshotCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Nirvana/UnallocatedTrades", RequestNamespace="Nirvana", ResponseNamespace="Nirvana", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UnallocatedTrades[] UnallocatedTrades(System.DateTime date, string errorMessage, int errorNumber) {
            object[] results = this.Invoke("UnallocatedTrades", new object[] {
                        date,
                        errorMessage,
                        errorNumber});
            return ((UnallocatedTrades[])(results[0]));
        }
        
        /// <remarks/>
        public void UnallocatedTradesAsync(System.DateTime date, string errorMessage, int errorNumber) {
            this.UnallocatedTradesAsync(date, errorMessage, errorNumber, null);
        }
        
        /// <remarks/>
        public void UnallocatedTradesAsync(System.DateTime date, string errorMessage, int errorNumber, object userState) {
            if ((this.UnallocatedTradesOperationCompleted == null)) {
                this.UnallocatedTradesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUnallocatedTradesOperationCompleted);
            }
            this.InvokeAsync("UnallocatedTrades", new object[] {
                        date,
                        errorMessage,
                        errorNumber}, this.UnallocatedTradesOperationCompleted, userState);
        }
        
        private void OnUnallocatedTradesOperationCompleted(object arg) {
            if ((this.UnallocatedTradesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UnallocatedTradesCompleted(this, new UnallocatedTradesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Nirvana/SODPositions", RequestNamespace="Nirvana", ResponseNamespace="Nirvana", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SODPositions[] SODPositions(System.DateTime date, string errorMessage, int errorNumber) {
            object[] results = this.Invoke("SODPositions", new object[] {
                        date,
                        errorMessage,
                        errorNumber});
            return ((SODPositions[])(results[0]));
        }
        
        /// <remarks/>
        public void SODPositionsAsync(System.DateTime date, string errorMessage, int errorNumber) {
            this.SODPositionsAsync(date, errorMessage, errorNumber, null);
        }
        
        /// <remarks/>
        public void SODPositionsAsync(System.DateTime date, string errorMessage, int errorNumber, object userState) {
            if ((this.SODPositionsOperationCompleted == null)) {
                this.SODPositionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSODPositionsOperationCompleted);
            }
            this.InvokeAsync("SODPositions", new object[] {
                        date,
                        errorMessage,
                        errorNumber}, this.SODPositionsOperationCompleted, userState);
        }
        
        private void OnSODPositionsOperationCompleted(object arg) {
            if ((this.SODPositionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SODPositionsCompleted(this, new SODPositionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Nirvana/SymbolList", RequestNamespace="Nirvana", ResponseNamespace="Nirvana", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Symbollist[] SymbolList(int addonId, string errorMessage, int errorNumber) {
            object[] results = this.Invoke("SymbolList", new object[] {
                        addonId,
                        errorMessage,
                        errorNumber});
            return ((Symbollist[])(results[0]));
        }
        
        /// <remarks/>
        public void SymbolListAsync(string errorMessage, int errorNumber) {
            this.SymbolListAsync(errorMessage, errorNumber, null);
        }
        
        /// <remarks/>
        public void SymbolListAsync(string errorMessage, int errorNumber, object userState) {
            if ((this.SymbolListOperationCompleted == null)) {
                this.SymbolListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSymbolListOperationCompleted);
            }
            this.InvokeAsync("SymbolList", new object[] {
                        errorMessage,
                        errorNumber}, this.SymbolListOperationCompleted, userState);
        }
        
        private void OnSymbolListOperationCompleted(object arg) {
            if ((this.SymbolListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SymbolListCompleted(this, new SymbolListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("Nirvana/SymbolCount", RequestNamespace="Nirvana", ResponseNamespace="Nirvana", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SymbolCount(int addonId, string errorMessage, int errorNumber) {
            object[] results = this.Invoke("SymbolCount", new object[] {
                        addonId,
                        errorMessage,
                        errorNumber});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SymbolCountAsync(string errorMessage, int errorNumber) {
            this.SymbolCountAsync(errorMessage, errorNumber, null);
        }
        
        /// <remarks/>
        public void SymbolCountAsync(string errorMessage, int errorNumber, object userState) {
            if ((this.SymbolCountOperationCompleted == null)) {
                this.SymbolCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSymbolCountOperationCompleted);
            }
            this.InvokeAsync("SymbolCount", new object[] {
                        errorMessage,
                        errorNumber}, this.SymbolCountOperationCompleted, userState);
        }
        
        private void OnSymbolCountOperationCompleted(object arg) {
            if ((this.SymbolCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SymbolCountCompleted(this, new SymbolCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Nirvana")]
    public partial class AllocatedTrades {
        
        private string groupIDField;
        
        private string taxLotIDField;
        
        private string fundNameField;
        
        private string strategyNameField;
        
        private string symbolField;
        
        private string securityNameField;
        
        private string brokerNameField;
        
        private string sideField;
        
        private double avgPriceField;
        
        private double allocatedQtyField;
        
        private System.DateTime tradeDateField;
        
        private System.DateTime allocationDateField;
        
        private System.DateTime settlementDateField;
        
        private double otherBrokerFeesField;
        
        private double stampDutyField;
        
        private double transactionLevyField;
        
        private double clearingFeeField;
        
        private double taxonCommissionsField;
        
        private double miscFeesField;
        
        private double commissionField;
        
        private string underlyingSymbolField;
        
        private string putOrCallField;
        
        private double strikePriceField;
        
        private double multiplierField;
        
        private string assetNameField;
        
        private System.DateTime expirationDateField;
        
        private string currencySymbolField;
        
        private string userNameField;
        
        private string primeBrokerCodeField;
        
        private string primeBrokerNameField;
        
        private string uDAAssetNameField;
        
        private string uDASecurityTypeNameField;
        
        private string uDASectorNameField;
        
        private string uDASubSectorNameField;
        
        private string uDACountryNameField;
        
        private string bloombergSymbolField;
        
        private string oSISymbolField;
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string TaxLotID {
            get {
                return this.taxLotIDField;
            }
            set {
                this.taxLotIDField = value;
            }
        }
        
        /// <remarks/>
        public string FundName {
            get {
                return this.fundNameField;
            }
            set {
                this.fundNameField = value;
            }
        }
        
        /// <remarks/>
        public string StrategyName {
            get {
                return this.strategyNameField;
            }
            set {
                this.strategyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityName {
            get {
                return this.securityNameField;
            }
            set {
                this.securityNameField = value;
            }
        }
        
        /// <remarks/>
        public string BrokerName {
            get {
                return this.brokerNameField;
            }
            set {
                this.brokerNameField = value;
            }
        }
        
        /// <remarks/>
        public string Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
        
        /// <remarks/>
        public double AvgPrice {
            get {
                return this.avgPriceField;
            }
            set {
                this.avgPriceField = value;
            }
        }
        
        /// <remarks/>
        public double AllocatedQty {
            get {
                return this.allocatedQtyField;
            }
            set {
                this.allocatedQtyField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TradeDate {
            get {
                return this.tradeDateField;
            }
            set {
                this.tradeDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AllocationDate {
            get {
                return this.allocationDateField;
            }
            set {
                this.allocationDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SettlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
            }
        }
        
        /// <remarks/>
        public double OtherBrokerFees {
            get {
                return this.otherBrokerFeesField;
            }
            set {
                this.otherBrokerFeesField = value;
            }
        }
        
        /// <remarks/>
        public double StampDuty {
            get {
                return this.stampDutyField;
            }
            set {
                this.stampDutyField = value;
            }
        }
        
        /// <remarks/>
        public double TransactionLevy {
            get {
                return this.transactionLevyField;
            }
            set {
                this.transactionLevyField = value;
            }
        }
        
        /// <remarks/>
        public double ClearingFee {
            get {
                return this.clearingFeeField;
            }
            set {
                this.clearingFeeField = value;
            }
        }
        
        /// <remarks/>
        public double TaxonCommissions {
            get {
                return this.taxonCommissionsField;
            }
            set {
                this.taxonCommissionsField = value;
            }
        }
        
        /// <remarks/>
        public double MiscFees {
            get {
                return this.miscFeesField;
            }
            set {
                this.miscFeesField = value;
            }
        }
        
        /// <remarks/>
        public double Commission {
            get {
                return this.commissionField;
            }
            set {
                this.commissionField = value;
            }
        }
        
        /// <remarks/>
        public string UnderlyingSymbol {
            get {
                return this.underlyingSymbolField;
            }
            set {
                this.underlyingSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string PutOrCall {
            get {
                return this.putOrCallField;
            }
            set {
                this.putOrCallField = value;
            }
        }
        
        /// <remarks/>
        public double StrikePrice {
            get {
                return this.strikePriceField;
            }
            set {
                this.strikePriceField = value;
            }
        }
        
        /// <remarks/>
        public double Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        public string AssetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencySymbol {
            get {
                return this.currencySymbolField;
            }
            set {
                this.currencySymbolField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string PrimeBrokerCode {
            get {
                return this.primeBrokerCodeField;
            }
            set {
                this.primeBrokerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PrimeBrokerName {
            get {
                return this.primeBrokerNameField;
            }
            set {
                this.primeBrokerNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDAAssetName {
            get {
                return this.uDAAssetNameField;
            }
            set {
                this.uDAAssetNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASecurityTypeName {
            get {
                return this.uDASecurityTypeNameField;
            }
            set {
                this.uDASecurityTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASectorName {
            get {
                return this.uDASectorNameField;
            }
            set {
                this.uDASectorNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASubSectorName {
            get {
                return this.uDASubSectorNameField;
            }
            set {
                this.uDASubSectorNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDACountryName {
            get {
                return this.uDACountryNameField;
            }
            set {
                this.uDACountryNameField = value;
            }
        }
        
        /// <remarks/>
        public string BloombergSymbol {
            get {
                return this.bloombergSymbolField;
            }
            set {
                this.bloombergSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string OSISymbol {
            get {
                return this.oSISymbolField;
            }
            set {
                this.oSISymbolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Nirvana")]
    public partial class Symbollist {
        
        private string bloombergSymbolField;
        
        private string cUSIPSymbolField;
        
        private string sEDOLSymbolField;
        
        private string tickerSymbolField;
        
        private string iSINSymbolField;
        
        private string reutersSymbolField;
        
        /// <remarks/>
        public string BloombergSymbol {
            get {
                return this.bloombergSymbolField;
            }
            set {
                this.bloombergSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string CUSIPSymbol {
            get {
                return this.cUSIPSymbolField;
            }
            set {
                this.cUSIPSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string SEDOLSymbol {
            get {
                return this.sEDOLSymbolField;
            }
            set {
                this.sEDOLSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string TickerSymbol {
            get {
                return this.tickerSymbolField;
            }
            set {
                this.tickerSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string ISINSymbol {
            get {
                return this.iSINSymbolField;
            }
            set {
                this.iSINSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string ReutersSymbol {
            get {
                return this.reutersSymbolField;
            }
            set {
                this.reutersSymbolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Nirvana")]
    public partial class SODPositions {
        
        private string fundNameField;
        
        private string strategyNameField;
        
        private string symbolField;
        
        private string securityNameField;
        
        private double openQtyField;
        
        private double avgPriceField;
        
        private string underlyingSymbolField;
        
        private string putOrCallField;
        
        private double strikePriceField;
        
        private double multiplierField;
        
        private string assetNameField;
        
        private System.DateTime expirationDateField;
        
        private string primeBrokerCodeField;
        
        private string primeBrokerNameField;
        
        private string uDAAssetNameField;
        
        private string uDASecurityTypeNameField;
        
        private string uDASectorNameField;
        
        private string uDASubSectorNameField;
        
        private string uDACountryNameField;
        
        private string bloombergSymbolField;
        
        private string oSISymbolField;
        
        private double closingMarkField;
        
        private string positionSideField;
        
        private string tradeCurrencyField;
        
        private double fXRateField;
        
        /// <remarks/>
        public string FundName {
            get {
                return this.fundNameField;
            }
            set {
                this.fundNameField = value;
            }
        }
        
        /// <remarks/>
        public string StrategyName {
            get {
                return this.strategyNameField;
            }
            set {
                this.strategyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityName {
            get {
                return this.securityNameField;
            }
            set {
                this.securityNameField = value;
            }
        }
        
        /// <remarks/>
        public double OpenQty {
            get {
                return this.openQtyField;
            }
            set {
                this.openQtyField = value;
            }
        }
        
        /// <remarks/>
        public double AvgPrice {
            get {
                return this.avgPriceField;
            }
            set {
                this.avgPriceField = value;
            }
        }
        
        /// <remarks/>
        public string UnderlyingSymbol {
            get {
                return this.underlyingSymbolField;
            }
            set {
                this.underlyingSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string PutOrCall {
            get {
                return this.putOrCallField;
            }
            set {
                this.putOrCallField = value;
            }
        }
        
        /// <remarks/>
        public double StrikePrice {
            get {
                return this.strikePriceField;
            }
            set {
                this.strikePriceField = value;
            }
        }
        
        /// <remarks/>
        public double Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        public string AssetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string PrimeBrokerCode {
            get {
                return this.primeBrokerCodeField;
            }
            set {
                this.primeBrokerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PrimeBrokerName {
            get {
                return this.primeBrokerNameField;
            }
            set {
                this.primeBrokerNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDAAssetName {
            get {
                return this.uDAAssetNameField;
            }
            set {
                this.uDAAssetNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASecurityTypeName {
            get {
                return this.uDASecurityTypeNameField;
            }
            set {
                this.uDASecurityTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASectorName {
            get {
                return this.uDASectorNameField;
            }
            set {
                this.uDASectorNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASubSectorName {
            get {
                return this.uDASubSectorNameField;
            }
            set {
                this.uDASubSectorNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDACountryName {
            get {
                return this.uDACountryNameField;
            }
            set {
                this.uDACountryNameField = value;
            }
        }
        
        /// <remarks/>
        public string BloombergSymbol {
            get {
                return this.bloombergSymbolField;
            }
            set {
                this.bloombergSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string OSISymbol {
            get {
                return this.oSISymbolField;
            }
            set {
                this.oSISymbolField = value;
            }
        }
        
        /// <remarks/>
        public double ClosingMark {
            get {
                return this.closingMarkField;
            }
            set {
                this.closingMarkField = value;
            }
        }
        
        /// <remarks/>
        public string PositionSide {
            get {
                return this.positionSideField;
            }
            set {
                this.positionSideField = value;
            }
        }
        
        /// <remarks/>
        public string TradeCurrency {
            get {
                return this.tradeCurrencyField;
            }
            set {
                this.tradeCurrencyField = value;
            }
        }
        
        /// <remarks/>
        public double FXRate {
            get {
                return this.fXRateField;
            }
            set {
                this.fXRateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Nirvana")]
    public partial class UnallocatedTrades {
        
        private string groupIDField;
        
        private string symbolField;
        
        private string securityNameField;
        
        private string brokerNameField;
        
        private string sideField;
        
        private double orderQuantityField;
        
        private double filledQuantityField;
        
        private double avgPriceField;
        
        private System.DateTime tradeDateField;
        
        private System.DateTime settlementDateField;
        
        private string underlyingSymbolField;
        
        private string putOrCallField;
        
        private double strikePriceField;
        
        private double multiplierField;
        
        private string currencySymbolField;
        
        private string assetNameField;
        
        private System.DateTime expirationDateField;
        
        private string userNameField;
        
        private string uDAAssetNameField;
        
        private string uDASecurityTypeNameField;
        
        private string uDASectorNameField;
        
        private string uDASubSectorNameField;
        
        private string uDACountryNameField;
        
        private string bloombergSymbolField;
        
        private string oSISymbolField;
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityName {
            get {
                return this.securityNameField;
            }
            set {
                this.securityNameField = value;
            }
        }
        
        /// <remarks/>
        public string BrokerName {
            get {
                return this.brokerNameField;
            }
            set {
                this.brokerNameField = value;
            }
        }
        
        /// <remarks/>
        public string Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
        
        /// <remarks/>
        public double OrderQuantity {
            get {
                return this.orderQuantityField;
            }
            set {
                this.orderQuantityField = value;
            }
        }
        
        /// <remarks/>
        public double FilledQuantity {
            get {
                return this.filledQuantityField;
            }
            set {
                this.filledQuantityField = value;
            }
        }
        
        /// <remarks/>
        public double AvgPrice {
            get {
                return this.avgPriceField;
            }
            set {
                this.avgPriceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TradeDate {
            get {
                return this.tradeDateField;
            }
            set {
                this.tradeDateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime SettlementDate {
            get {
                return this.settlementDateField;
            }
            set {
                this.settlementDateField = value;
            }
        }
        
        /// <remarks/>
        public string UnderlyingSymbol {
            get {
                return this.underlyingSymbolField;
            }
            set {
                this.underlyingSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string PutOrCall {
            get {
                return this.putOrCallField;
            }
            set {
                this.putOrCallField = value;
            }
        }
        
        /// <remarks/>
        public double StrikePrice {
            get {
                return this.strikePriceField;
            }
            set {
                this.strikePriceField = value;
            }
        }
        
        /// <remarks/>
        public double Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        public string CurrencySymbol {
            get {
                return this.currencySymbolField;
            }
            set {
                this.currencySymbolField = value;
            }
        }
        
        /// <remarks/>
        public string AssetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDAAssetName {
            get {
                return this.uDAAssetNameField;
            }
            set {
                this.uDAAssetNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASecurityTypeName {
            get {
                return this.uDASecurityTypeNameField;
            }
            set {
                this.uDASecurityTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASectorName {
            get {
                return this.uDASectorNameField;
            }
            set {
                this.uDASectorNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASubSectorName {
            get {
                return this.uDASubSectorNameField;
            }
            set {
                this.uDASubSectorNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDACountryName {
            get {
                return this.uDACountryNameField;
            }
            set {
                this.uDACountryNameField = value;
            }
        }
        
        /// <remarks/>
        public string BloombergSymbol {
            get {
                return this.bloombergSymbolField;
            }
            set {
                this.bloombergSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string OSISymbol {
            get {
                return this.oSISymbolField;
            }
            set {
                this.oSISymbolField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="Nirvana")]
    public partial class TaxlotSnapshot {
        
        private string groupIDField;
        
        private string taxLotIDField;
        
        private string fundNameField;
        
        private string strategyNameField;
        
        private string symbolField;
        
        private string securityNameField;
        
        private string sideField;
        
        private double openQtyField;
        
        private double avgPriceField;
        
        private System.DateTime taxlotDateField;
        
        private double openTotalCommissionandFeesField;
        
        private string underlyingSymbolField;
        
        private string putOrCallField;
        
        private double strikePriceField;
        
        private double multiplierField;
        
        private string assetNameField;
        
        private System.DateTime expirationDateField;
        
        private string primeBrokerCodeField;
        
        private string primeBrokerNameField;
        
        private string uDAAssetNameField;
        
        private string uDASecurityTypeNameField;
        
        private string uDASectorNameField;
        
        private string uDASubSectorNameField;
        
        private string uDACountryNameField;
        
        private string bloombergSymbolField;
        
        private string oSISymbolField;
        
        private double closingMarkField;
        
        private string fundShortNameField;
        
        private System.DateTime asOfDateField;
        
        private double fXClosingMarkField;
        
        private string tradeCurrencyField;
        
        /// <remarks/>
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        public string TaxLotID {
            get {
                return this.taxLotIDField;
            }
            set {
                this.taxLotIDField = value;
            }
        }
        
        /// <remarks/>
        public string FundName {
            get {
                return this.fundNameField;
            }
            set {
                this.fundNameField = value;
            }
        }
        
        /// <remarks/>
        public string StrategyName {
            get {
                return this.strategyNameField;
            }
            set {
                this.strategyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string SecurityName {
            get {
                return this.securityNameField;
            }
            set {
                this.securityNameField = value;
            }
        }
        
        /// <remarks/>
        public string Side {
            get {
                return this.sideField;
            }
            set {
                this.sideField = value;
            }
        }
        
        /// <remarks/>
        public double OpenQty {
            get {
                return this.openQtyField;
            }
            set {
                this.openQtyField = value;
            }
        }
        
        /// <remarks/>
        public double AvgPrice {
            get {
                return this.avgPriceField;
            }
            set {
                this.avgPriceField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime TaxlotDate {
            get {
                return this.taxlotDateField;
            }
            set {
                this.taxlotDateField = value;
            }
        }
        
        /// <remarks/>
        public double OpenTotalCommissionandFees {
            get {
                return this.openTotalCommissionandFeesField;
            }
            set {
                this.openTotalCommissionandFeesField = value;
            }
        }
        
        /// <remarks/>
        public string UnderlyingSymbol {
            get {
                return this.underlyingSymbolField;
            }
            set {
                this.underlyingSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string PutOrCall {
            get {
                return this.putOrCallField;
            }
            set {
                this.putOrCallField = value;
            }
        }
        
        /// <remarks/>
        public double StrikePrice {
            get {
                return this.strikePriceField;
            }
            set {
                this.strikePriceField = value;
            }
        }
        
        /// <remarks/>
        public double Multiplier {
            get {
                return this.multiplierField;
            }
            set {
                this.multiplierField = value;
            }
        }
        
        /// <remarks/>
        public string AssetName {
            get {
                return this.assetNameField;
            }
            set {
                this.assetNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        public string PrimeBrokerCode {
            get {
                return this.primeBrokerCodeField;
            }
            set {
                this.primeBrokerCodeField = value;
            }
        }
        
        /// <remarks/>
        public string PrimeBrokerName {
            get {
                return this.primeBrokerNameField;
            }
            set {
                this.primeBrokerNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDAAssetName {
            get {
                return this.uDAAssetNameField;
            }
            set {
                this.uDAAssetNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASecurityTypeName {
            get {
                return this.uDASecurityTypeNameField;
            }
            set {
                this.uDASecurityTypeNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASectorName {
            get {
                return this.uDASectorNameField;
            }
            set {
                this.uDASectorNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDASubSectorName {
            get {
                return this.uDASubSectorNameField;
            }
            set {
                this.uDASubSectorNameField = value;
            }
        }
        
        /// <remarks/>
        public string UDACountryName {
            get {
                return this.uDACountryNameField;
            }
            set {
                this.uDACountryNameField = value;
            }
        }
        
        /// <remarks/>
        public string BloombergSymbol {
            get {
                return this.bloombergSymbolField;
            }
            set {
                this.bloombergSymbolField = value;
            }
        }
        
        /// <remarks/>
        public string OSISymbol {
            get {
                return this.oSISymbolField;
            }
            set {
                this.oSISymbolField = value;
            }
        }
        
        /// <remarks/>
        public double ClosingMark {
            get {
                return this.closingMarkField;
            }
            set {
                this.closingMarkField = value;
            }
        }
        
        /// <remarks/>
        public string FundShortName {
            get {
                return this.fundShortNameField;
            }
            set {
                this.fundShortNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime AsOfDate {
            get {
                return this.asOfDateField;
            }
            set {
                this.asOfDateField = value;
            }
        }
        
        /// <remarks/>
        public double FXClosingMark {
            get {
                return this.fXClosingMarkField;
            }
            set {
                this.fXClosingMarkField = value;
            }
        }
        
        /// <remarks/>
        public string TradeCurrency {
            get {
                return this.tradeCurrencyField;
            }
            set {
                this.tradeCurrencyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void AllocatedTradesCompletedEventHandler(object sender, AllocatedTradesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllocatedTradesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllocatedTradesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AllocatedTrades[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AllocatedTrades[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void TaxlotSnapshotCompletedEventHandler(object sender, TaxlotSnapshotCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TaxlotSnapshotCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TaxlotSnapshotCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TaxlotSnapshot[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TaxlotSnapshot[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void UnallocatedTradesCompletedEventHandler(object sender, UnallocatedTradesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UnallocatedTradesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UnallocatedTradesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UnallocatedTrades[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UnallocatedTrades[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SODPositionsCompletedEventHandler(object sender, SODPositionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SODPositionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SODPositionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SODPositions[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SODPositions[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SymbolListCompletedEventHandler(object sender, SymbolListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SymbolListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SymbolListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Symbollist[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Symbollist[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void SymbolCountCompletedEventHandler(object sender, SymbolCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SymbolCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SymbolCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591