UPDATE T_Country 
SET ISOCode = 
CASE WHEN CountryName = 'United States'
THEN 'USA'
WHEN CountryName = 'HongKong'
THEN 'HKG'
WHEN CountryName = 'Japan'
THEN 'JPN'
WHEN CountryName = 'United Kingdom'
THEN 'GBR'
WHEN CountryName = 'Singapore'
THEN 'SGP'
WHEN CountryName = 'Norway'
THEN 'NOR'
WHEN CountryName = 'Germany'
THEN 'DEU'
WHEN CountryName = 'France'
THEN 'FRA'
WHEN CountryName = 'Austria'
THEN 'AUT'
WHEN CountryName = 'Belgium'
THEN 'BEL'
WHEN CountryName = 'Brazil'
THEN 'BRA'
WHEN CountryName = 'Denmark'
THEN 'DNK'
WHEN CountryName = 'Finland'
THEN 'FIN'
WHEN CountryName = 'Ireland'
THEN 'IRL'
WHEN CountryName = 'Netherlands'
THEN 'NLD'
WHEN CountryName = 'Portugal'
THEN 'PRT'
WHEN CountryName = 'South Africa'
THEN 'ZAF'
WHEN CountryName = 'Spain'
THEN 'ESP'
WHEN CountryName = 'Switzerland'
THEN 'CHE'
WHEN CountryName = 'Greece'
THEN 'GRC'
WHEN CountryName = 'Italy'
THEN 'ITA'
WHEN CountryName = 'Russia'
THEN 'RUS'
WHEN CountryName = 'Sweden'
THEN 'SWE'
WHEN CountryName = 'Australia'
THEN 'AUS'
WHEN CountryName = 'China'
THEN 'CHN'
WHEN CountryName = 'Korea'
THEN 'KOR'
WHEN CountryName = 'Bangladesh'
THEN 'BGD'
WHEN CountryName = 'Thailand'
THEN 'THA'
WHEN CountryName = 'Vietnam'
THEN 'VNM'
WHEN CountryName = 'India'
THEN 'IND'
WHEN CountryName = 'Canada'
THEN 'CAN'
WHEN CountryName = 'Taiwan'
THEN 'TWN'
WHEN CountryName = 'Mexico'
THEN 'MEX'
WHEN CountryName = 'United Arab Emirates'
THEN 'ARE'
WHEN CountryName = 'Jordan'
THEN 'JOR'
WHEN CountryName = 'Bahrain'
THEN 'BHR'
WHEN CountryName = 'Croatia'
THEN 'HRV'
WHEN CountryName = 'Poland'
THEN 'POL'
WHEN CountryName = 'New Zealand'
THEN 'NZL'
WHEN CountryName = 'Malaysia'
THEN 'MYS'
WHEN CountryName = 'Turkey'
THEN 'TUR'
WHEN CountryName = 'Hungary'
THEN 'HUN'
WHEN CountryName = 'Saudi Arabia'
THEN 'SAU'
WHEN CountryName = 'Tunisia'
THEN 'TUN'
WHEN CountryName = 'Qatar'
THEN 'QAT'
WHEN CountryName = 'Oman'
THEN 'OMN'
WHEN CountryName = 'Nigeria'
THEN 'NGA'
WHEN CountryName = 'Morocco'
THEN 'MAR'
WHEN CountryName = 'Kuwait'
THEN 'KWT'
WHEN CountryName = 'Kenya'
THEN 'KEN'
WHEN CountryName = 'Israel'
THEN 'ISR'
WHEN CountryName = 'Egypt'
THEN 'EGY'
WHEN CountryName = 'SriLanka'
THEN 'LKA'
WHEN CountryName = 'Cyprus'
THEN 'CYP'
WHEN CountryName = 'Argentina'
THEN 'ARG'
WHEN CountryName = 'Venezuela'
THEN 'VEN'
WHEN CountryName = 'Peru'
THEN 'PER'
WHEN CountryName = 'Slovakia'
THEN 'SVK'
WHEN CountryName = 'Colombia'
THEN 'COL'
WHEN CountryName = 'Chile'
THEN 'CHL'
WHEN CountryName = 'Serbia'
THEN 'SRB'
WHEN CountryName = 'Slovenia'
THEN 'SVN'
WHEN CountryName = 'Romania'
THEN 'ROU'
WHEN CountryName = 'Macedonia'
THEN 'MKD'
WHEN CountryName = 'Czech Republic'
THEN 'CZE'
WHEN CountryName = 'Estonia'
THEN 'EST'
WHEN CountryName = 'Bulgaria'
THEN 'BGR'
WHEN CountryName = 'Philippines'
THEN 'PHL'
WHEN CountryName = 'Indonesia'
THEN 'IDN'
ELSE 
ISOCode
END

