using Prana.Allocation.Client.Constants;
using Prana.BusinessObjects;
using Prana.BusinessObjects.AppConstants;
using Prana.LogManager;
using System;
using System.Windows;

namespace Prana.Allocation.Client.Helper
{
    internal class EditTradeValidation
    {
        /// <summary>
        /// Checks the group status.
        /// </summary>
        /// <param name="groupStatus">The group status.</param>
        /// <param name="isGroup">if set to <c>true</c> [is group].</param>
        /// <returns></returns>
        internal static bool CheckGroupStatus(PostTradeEnums.Status groupStatus, string fieldName, string transactionType, ref string msg)
        {
            bool isEditContinue = true;
            try
            {
                switch (groupStatus)
                {
                    case PostTradeEnums.Status.CorporateAction:
                        msg = "Corporate Action has been Applied. First undo the corporate action to make any changes. ";
                        isEditContinue = false;
                        break;

                    case PostTradeEnums.Status.Closed:
                        if (transactionType.Equals(TradingTransactionType.Exercise.ToString()) || transactionType.Equals(TradingTransactionType.Assignment.ToString()))
                        {
                            msg = "This Group is generated by Exercise/Assignement.";
                            isEditContinue = false;
                        }
                        break;
                    case PostTradeEnums.Status.Exercise:
                    case PostTradeEnums.Status.ExerciseAssignManually:
                        switch (fieldName)
                        {
                            case AllocationUIConstants.COMMISSION:
                            case AllocationUIConstants.SOFT_COMMISSION:
                            case AllocationUIConstants.TAX_ON_COMMISSIONS:
                            case AllocationUIConstants.SEC_FEE:
                            case AllocationUIConstants.STAMP_DUTY:
                            case AllocationUIConstants.CLEARING_BROKER_FEE:
                            case AllocationUIConstants.OTHER_BROKER_FEES:
                            case AllocationUIConstants.OCC_FEE:
                            case AllocationUIConstants.ORF_FEE:
                            case AllocationUIConstants.CLEARING_FEE:
                            case AllocationUIConstants.MISC_FEES:
                            case AllocationUIConstants.COUNTERPARTY_NAME:
                            case AllocationUIConstants.VENUE:
                            case AllocationUIConstants.CAPTION_DESCRIPTION:
                            case AllocationUIConstants.INTERNAL_COMMENTS:
                            case AllocationUIConstants.TradeAttribute1:
                            case AllocationUIConstants.TradeAttribute2:
                            case AllocationUIConstants.TradeAttribute3:
                            case AllocationUIConstants.TradeAttribute4:
                            case AllocationUIConstants.TradeAttribute5:
                            case AllocationUIConstants.TradeAttribute6:
                            case string field when IsAdditionalTradeAttribute(field):
                                break;
                            default:
                                msg = "This Group is generated by Exercise.";
                                isEditContinue = false;
                                break;
                        }
                        break;
                }
            }
            catch (Exception ex)
            {
                bool rethrow = Logger.HandleException(ex, LoggingConstants.POLICY_LOGANDTHROW);
                if (rethrow)
                    throw;
            }
            return isEditContinue;
        }

        /// <summary>
        /// Validations the on field.
        /// </summary>
        /// <param name="fieldName">Name of the field.</param>
        /// <param name="cellText">The cell text.</param>
        /// <param name="gParent">The g parent.</param>
        /// <param name="groupStatus">The group status.</param>
        /// <returns></returns>
        internal static bool ValidationOnField(string fieldName, AllocationGroup gParent, PostTradeEnums.Status groupStatus, ref string msg)
        {
            bool isEditContinue = true;
            try
            {
                int CurrencyID = gParent.CurrencyID;
                int SettlementCurrencyID = gParent.SettlementCurrencyID;
                bool isAutoCalMsg = false;

                switch (fieldName)
                {
                    case AllocationUIConstants.AVGPRICE:
                        //Average Price is to be auto calculated. Avg price should be calculated using the settlement fx rate and settlement amount
                        if (SettlementCachePreferences.SettlementAutoCalculateField == SettlementAutoCalculateField.AveragePrice)
                            isAutoCalMsg = true;
                        break;

                    case AllocationUIConstants.TRANSACTION_TYPE:
                        if (groupStatus.Equals(PostTradeEnums.Status.Closed))
                        {
                            msg = "Transaction Type cannot be changed on partially or fully closed trades. Please unwind before changing the Transaction Type.";
                            isEditContinue = false;
                        }
                        break;
                    case AllocationUIConstants.NIRVANA_PROCESS_DATE:
                        if (groupStatus.Equals(PostTradeEnums.Status.Closed))
                        {
                            msg = "Prana Process Date cannot be changed on partially or fully closed trades. Please unwind before changing the trade date.";
                            isEditContinue = false;
                        }
                        break;
                }
                if (CurrencyID != SettlementCurrencyID && isAutoCalMsg)
                {
                    msg = AllocationUIConstants.MSG_AUTO_CALCULATE_FIELD;
                    isEditContinue = false;
                }
            }
            catch (Exception ex)
            {
                bool rethrow = Logger.HandleException(ex, LoggingConstants.POLICY_LOGANDTHROW);
                if (rethrow)
                    throw;
            }
            return isEditContinue;
        }

        /// <summary>
        /// Validations the on dates field.
        /// </summary>
        /// <param name="fieldName">Name of the field.</param>
        /// <param name="cellText">The cell text.</param>
        /// <param name="gParent">The g parent.</param>
        /// <returns></returns>
        internal static bool ValidationOnDatesField(string fieldName, string cellText, AllocationGroup gParent)
        {
            bool isEditContinue = true;
            try
            {
                switch (fieldName)
                {
                    case AllocationUIConstants.PROCESS_DATE:
                        DateTime processDate = Convert.ToDateTime(cellText);
                        if (processDate.Date < gParent.AUECLocalDate.Date)
                        {
                            MessageBox.Show("Process Date cannot be less than Trade Date, it will be reverted to last valid value", AllocationClientConstants.ALLOCATION_MESSAGEBOX_CAPTION, MessageBoxButton.OK, MessageBoxImage.Warning);
                            isEditContinue = false;
                        }
                        if (processDate.Date > gParent.SettlementDate.Date)
                        {
                            MessageBox.Show("Process Date cannot be greater than Settlement Date, it will be reverted to last valid value", AllocationClientConstants.ALLOCATION_MESSAGEBOX_CAPTION, MessageBoxButton.OK, MessageBoxImage.Warning);
                            isEditContinue = false;
                        }
                        break;

                    case AllocationUIConstants.ORIGINAL_PURCHASE_DATE:
                        DateTime originalPurchaseDate = Convert.ToDateTime(cellText);
                        // original purchase is dependent on process date, it cannot be greater than the process date.
                        if (originalPurchaseDate.Date > gParent.ProcessDate.Date)
                        {
                            MessageBox.Show("OriginalPurchase Date cannot be greater than Process Date,it will be reverted to last valid value", AllocationClientConstants.ALLOCATION_MESSAGEBOX_CAPTION, MessageBoxButton.OK, MessageBoxImage.Warning);
                            isEditContinue = false;
                        }
                        break;
                    case AllocationUIConstants.SETTLEMENT_DATE:
                        DateTime settlementDate = Convert.ToDateTime(cellText);
                        //Setllement date can not be less than the trade date.
                        if (settlementDate < gParent.ProcessDate.Date)
                        {
                            MessageBox.Show("Settlement Date cannot be less than Process Date,it will be reverted to last valid value", AllocationClientConstants.ALLOCATION_MESSAGEBOX_CAPTION, MessageBoxButton.OK, MessageBoxImage.Warning);
                            isEditContinue = false;
                        }
                        break;
                    case AllocationUIConstants.NIRVANA_PROCESS_DATE:
                        if (gParent.TaxLots.Count > 0 && DateTime.Compare(Convert.ToDateTime(cellText), gParent.TaxLots[0].NirvanaProcessDate) < 0)
                        {
                            MessageBox.Show("Prana Process Date cannot be less than Trade Date, it will be reverted to last valid value.", AllocationClientConstants.ALLOCATION_MESSAGEBOX_CAPTION, MessageBoxButton.OK, MessageBoxImage.Warning);
                            isEditContinue = false;
                        }
                        break;
                }
            }
            catch (Exception ex)
            {
                bool rethrow = Logger.HandleException(ex, LoggingConstants.POLICY_LOGANDTHROW);
                if (rethrow)
                    throw;
            }
            return isEditContinue;
        }

        /// <summary>
        /// Determines whether the given field name represents an additional tradeAttribute (TradeAttribute7 through TradeAttribute45).      
        /// </summary>
        private static bool IsAdditionalTradeAttribute(string fieldName)
        {
            if (fieldName.StartsWith(AllocationUIConstants.TradeAttribute))
            {
                if (int.TryParse(fieldName.Substring(AllocationUIConstants.TradeAttribute.Length), out int num) && num >= 7)
                {
                    return true;
                }
            }
            return false;
        }
    }
}
