<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2007

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce 2007 Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/ArrayOfPosition">
		<ArrayOfPosition>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation">C:\Documents and Settings\bhupeshbareja\Desktop\XSLT_Tora\Tora.xsd</xsl:attribute>
			<xsl:for-each select="Position">
				<Position>

					<!--   PositionStartQuantity -->

					<xsl:for-each select="PositionStartQuantity">
						<PositionQuantity>
							<xsl:value-of select="."/>
						</PositionQuantity>
					</xsl:for-each>

					<!--   AveragePrice -->

					<xsl:for-each select="AveragePrice">
						<Price>
							<xsl:value-of select="."/>
						</Price>
					</xsl:for-each>

					<!--   Side -->

					<xsl:for-each select="Side">
						<Type>
							<xsl:value-of select="'CS'"/>
						</Type>
					</xsl:for-each>



					<!--   Symbol -->

					<xsl:for-each select="Symbol">
						<Product>
							<xsl:value-of select="."/>
						</Product>
					</xsl:for-each>


					<xsl:for-each select="AUECID">
						<UserId>
							<xsl:value-of select="' '"/>
						</UserId>
					</xsl:for-each>


					<xsl:for-each select="StrategyID">
						<Group>
							<xsl:value-of select="'YUNZEI'"/>
						</Group>
					</xsl:for-each>


					<xsl:for-each select="ClosedQty">
						<Broker>
							<xsl:value-of select="' '"/>
						</Broker>
					</xsl:for-each>


					<xsl:for-each select="Status">
						<Exchange>
							<xsl:value-of select="' '"/>
						</Exchange>
					</xsl:for-each>



					<xsl:for-each select="Multiplier">
						<Multiplier>
							<xsl:value-of select="."/>
						</Multiplier>
					</xsl:for-each>




				</Position>
			</xsl:for-each>
		</ArrayOfPosition>
	</xsl:template>
</xsl:stylesheet>
