using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Nirvana.TestAutomation.Utilities
{
    public static class MandatoryColumns
    {
        // List to store column names
        private static List<string> columns;

        // Constructor to initialize the columns
        public static List<string> OrderGrid()
        {
            columns = new List<string>
        {
            "Actual User", 
            "Symbol",
            "TIF", 
            "Put/Call", 
            "Side", 
            "Status", 
            "Account",
            "Broker",
            "Target Qty",
            "Total Executed Qty",
            "Working Qty",
            "Uncommitted Qty",
            "% Executed",
            "Last Fill Price (Local)",
            "Avg Fill Price (Local)",
            "Order Type",
            "Rebalancer File Name",
            "Limit Price",
            "Stop Price",
            "Strike Price",
            "Last Shares",
            "Algo",
            "Start of Day Qty",
            "Day Executed Qty",
            "Day Average Price",
            "Leaves",
            "Avg Fill Price (Base)",
            "Asset Class",
            "Trader",
            "Current User",
            "Venue",
            "FX Conversion Operator",
            "FX Rate",
            "Trade Attribute 01",
            "Trade Attribute 02",
            "Trade Attribute 03",
            "Trade Attribute 04",
            "Trade Attribute 05",
            "Trade Attribute 06",
            "Internal Comments",
            "Borrower ID",
            "Borrow Rate(%)",
            "Borrow Broker"
        };
            return columns;
        }

        public static List<string> AllocationGrid()
        {
            columns = new List<string>
        {
            "Symbol",
            "Side",
            "Executed Qty",
            "Broker",
            "Net Amount( Local)",
            "Total Commission",
            "Avg Price(Local)",
            "Net Amount( Base)",
            "FX Conversion Operator",
            "Principal Amount( Local)",
            "Principal Amount( Base)",
            "Trade Attribute 01",
            "Trade Attribute 02",
            "Trade Attribute 03",
            "Trade Attribute 04",
            "Trade Attribute 05",
            "Trade Attribute 06",
            "Settlement Currency",
            "Total Commission And Fee",
            "Option Premium Adjustment",
            "User",
            "FX Rate",
            "Asset Category",
            "Put Or Call",
            "Allocated Qty",
            "UnAllocatedQty",
            "Commission",
            "Soft Commission",
            "Other Broker Fees",
            "Clearing Broker Fee",
            "Transaction Levy",
            "Stamp Duty",
            "AUEC Fee1",
            "Tax On Commissions",
            "AUEC Fee2",
            "SEC Fee",
            "OCC Fee",
            "ORF Fee",
            "Commission Per Share",
            "Soft Commission Per Share",
            "Total Commission Per Share",
            "Closing Status",
            "Closing Method",
            "Quantity",
            "Avg Price(Base)",
            "Underlying",
            "Exchange",
            "Currency",
            "Trading Account",
            "Venue",
            "Contract Multiplier",
            "Company",
            "Underlying Symbol",
            "Accrued Interest",
            "Borrower Id",
            "Borrow Rate(%)",
            "Borrow Broker",
            "Master Fund",
            "Account Name",
            "Strategy Name"
        };
            // to get the list of columns
            return columns;
        }

        public static List<String> AllocationTaxlot()
        {
            columns = new List<string>
            {
                "Account Name",
            "Percentage",
            "Commission",
            "Taxlot Qty",
            "FX Conversion Operator",
            "Soft Commission",
            "Closing Status",
            "Net Amount(Local)",
            "Net Amount(Base)",
            "Principal Amount(Local)",
            "Principal Amount(Base)",
            "Settlement Currency",
            "Trade Attribute 01",
            "Trade Attribute 02",
            "Trade Attribute 03",
            "Strategy Name",
            "AvgPriceBase",
            "Trade Attribute 04",
            "Trade Attribute 05",
            "Trade Attribute 06",
            "Other Broker Fees",
            "Clearing Broker Fees",
            "Transaction Levy",
            "Stamp Duty",
            "AUEC Fee1",
            "Tax On Commissions",
            "AUEC Fee2",
            "SEC Fee",
            "OCC Fee",
            "ORF Fee",
            "Option Premium Adjustment",
            "External Transaction ID",
            "Accrued Interest",
            "FXRate"
            };
            return columns;
        }

        public static List<String> PmColumns()
        {
            columns = new List<string> 
            {
            "Symbol",
            "Bloomberg",
            "Position Side",
            "Position",
            "% Net Exposure (Base)",
            "Market Value (Local)",
            "MasterFund",
            "Px Selected Feed (Base)",
            "Market Value (Base)",
            "Net Exposure (Base)",
            "Gross Exposure (Base)",
            "Day P&L (Base)",
            "Cost Basis P&L (Base)",
            "Account",
            "% Change",
            "Cost Basis",
            "Prime Broker",
            "Security Name",
            "Closing Mark",
            "Px Last",
            "Asset Class",
            "Trade Currency",
            "FX Rate",
            "Vs Currency",
            "Lead Currency",
            "Px Ask",
            "Px Bid",
            "Closing Price",
            "Px Mid",
            "Net Exposure (Local)",
            "Exposure (Local)",
            "Delta Adj. Position",
            "Exposure (Base)",
            "Beta Adj. Exposure (Local)",
            "Beta Adj. Exposure (Base)",
            "Exposure (BP)(Base)",
            "Day P&L (Local)",
            "Order Side",
            "Transaction Side",
            "Underlying Symbol",
            "Underlying Price",
            "FX Rate On Trade Date",
            "Cost Basis P&L (Local)",
            "Day Interest",
            "Cash Impact (Local)",
            "User Asset",
            "Security Type",
            "Sector",
            "Sub Sector",
            "Country",
            "Market Cap",
            "Shares Outstanding (MM)",
            "Avg Volume 20 Day",
            "% Avg Volume (Delta Adj.)",
            "Cash Impact (Base)",
            "Volatility (%)",
            "User",
            "Broker",
            "Strike Price",
            "Beta Adj. Gross Exposure (Base)",
            "Gross Market Value (Base)",
            "Px Selected Feed (Local)",
            "% Avg Volume",
            "Day P&L (Base)(Price Gain)",
            "Day P&L (Base)(FX Gain)",
            "Cost Basis P&L (Base)(FX Gain)",
            "Cost Basis P&L (Base)(Price Gain)",
            "IDCO",
            "OSI",
            "SEDOL",
            "CUSIP",
            "ISIN",
            "Proxy Symbol",
            "Gross Exposure (Local)",
            "Closing Mark (Underlying)",
            "Closing Market Value (Local)",
            "Closing Market Value (Base)",
            "Closing FX Rate",
            "Analyst",
            "Country Of Risk",
            "Security Type",
            "Issuer",
            "Market Cap UDA",
            "Risk Currency",
            "FX Rate (Display)",
            "% Gross Exposure (Base)",
            "% Exposure (Base)",
            "Gross Exposure (Underlying) (Base)",
            "Gross Exposure (Underlying)",
            "Start of Day NAV",
            "% Gross Market Value (Base)",
            "NAV",
            "% Net Market Value (Base)",
            "NAV (Touch)",
            "ITM/OTM",
            "% of ITM/OTM",
            "Intrinsic value",
            "Days to Expiry",
            "Gain/Loss if Ex./Assign",
            "FactSet Symbol",
            "ACTIV Symbol",
            "Day Traded Position",
            "Total Volume",
            "Custom UDA8",
            "Custom UDA9",
            "Custom UDA10",
            "Custom UDA11",
            "Custom UDA12",
            "Custom UDA1",
            "Custom UDA2",
            "Custom UDA3",
            "Custom UDA4",
            "Custom UDA5",
            "Custom UDA6",
            "Custom UDA7",
            };
            return columns;
        }

        public static List<String> SubOrder()
        {
            columns = new List<string> 
            {
                "Side",
            "Quantity",
            "Status",
            "Broker",
            "Working Qty",
            "Executed Qty",
            "Unexecuted Qty",
            "Last Shares",
            "Last Fill Price (Local)",
            "Avg Fill Price (Local)",
            "Account",
            "Allocation Status",
            "Current User",
            "Limit Price",
            "Stop Price",
            "TIF",
            "Status (With Rollover)",
            "Strike Price",
            "Uncommitted Qty",
            "Algo",
            "% Completed",
            "Start of Day Qty",
            "Day Executed Qty",
            "Day Average Price",
            "Master Fund",
            "Strategy",
            "% Executed",
            "Order Type",
            "Avg Fill Price (Base)",
            "Asset Class",
            "Trader",
            "Actual User",
            "Venue",
            "FX Conversion Operator",
            "Underlying Symbol",
            "Put/Call",
            "FX Rate",
            "Trade Attribute 01",
            "Trade Attribute 02",
            "Trade Attribute 03",
            "Trade Attribute 04",
            "Trade Attribute 05",
            "Trade Attribute 06",
            "Internal Comments",
            "Borrower ID",
            "Borrow Rate(%)",
            "Borrow Broker",
            };
            return columns;
        }

        public static List<String> Closing()
        {
            columns = new List<string> 
            { 
             "Account",
            "Strategy",
            "Position Type",
            "Asset Class",
            "Symbol",
            "Qty Closed",
            "Opening Price",
            "Closing Price",
            "ClosingTotalCommissionandFees",
            "Realized PNL(C.B.)",
            "Opening Fees & Commission",
            "Currency"
            };
            return columns;
        }

        public static List<String> LongShortGrid()
        {
            columns = new List<string> 
            {
                "Account",
            "Side",
            "Symbol",
            "Security Name",
            "Quantity",
            "Net Notional",
            "UnitCost",
            "Opening Price",
            "Total Fees and Commission",
            "Strategy",
            "PositionTag",
            "Unit Cost(Base)",
            "ExternalTransId",
            "Asset Class",
            "UnderlyingName",
            "AUECID",
            "Settlement Currency",
            "Transaction Type",
            "CustomUDA8",
            "CustomUDA9",
            "CustomUDA10",
            "CustomUDA11",
            "CustomUDA12"
            };
            return columns;
        }

        public static List<String> ExpiredSettleGrid()
        {
            columns = new List<string> 
            {
                "Account",
            "AccruedINterest",
            "Asset",
            "Auec Fee1 and 2",
            "Average Price",
            "Clearing Broker fees",
            "Commission",
            "Closed QTY",
            "Currency",
            "Description",
            "Expired Qty",
            "FX Rate",
            "FX Rate operator",
            "If pay/receive changes",
            "Multipleir",
            "notional value",
            "occ fee",
            "option premium adjustment",
            "orf fee",
            "other broker fees",
            "pay/recive",
            "position type",
            "quantity",
            "sec fee",
            "settlement currency",
            "side",
            "soft commission",
            "stampduty",
            "status",
            "strategy",
            "strike price",
            "symbol",
            "tax on commission",
            };
            return columns;
        }
    }
}
