#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Historical.Pricing.Library
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Historicals")]
	public partial class HistoricalsDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertFileSpec(FileSpec instance);
    partial void UpdateFileSpec(FileSpec instance);
    partial void DeleteFileSpec(FileSpec instance);
    partial void InsertFlatFile(FlatFile instance);
    partial void UpdateFlatFile(FlatFile instance);
    partial void DeleteFlatFile(FlatFile instance);
    partial void InsertQuery(Query instance);
    partial void UpdateQuery(Query instance);
    partial void DeleteQuery(Query instance);
    partial void InsertSecurity(Security instance);
    partial void UpdateSecurity(Security instance);
    partial void DeleteSecurity(Security instance);
    partial void InsertServer(Server instance);
    partial void UpdateServer(Server instance);
    partial void DeleteServer(Server instance);
    partial void InsertMailSetting(MailSetting instance);
    partial void UpdateMailSetting(MailSetting instance);
    partial void DeleteMailSetting(MailSetting instance);
    partial void InsertProvider(Provider instance);
    partial void UpdateProvider(Provider instance);
    partial void DeleteProvider(Provider instance);
    partial void InsertSubscription(Subscription instance);
    partial void UpdateSubscription(Subscription instance);
    partial void DeleteSubscription(Subscription instance);
    partial void InsertServiceControl(ServiceControl instance);
    partial void UpdateServiceControl(ServiceControl instance);
    partial void DeleteServiceControl(ServiceControl instance);
    partial void InsertDailyBar(DailyBar instance);
    partial void UpdateDailyBar(DailyBar instance);
    partial void DeleteDailyBar(DailyBar instance);
    partial void InsertRegistration(Registration instance);
    partial void UpdateRegistration(Registration instance);
    partial void DeleteRegistration(Registration instance);
    partial void InsertVWAPS(VWAPS instance);
    partial void UpdateVWAPS(VWAPS instance);
    partial void DeleteVWAPS(VWAPS instance);
    #endregion
		
		public HistoricalsDataContext() : 
				base(global::Historical.Pricing.Library.Properties.Settings.Default.HistoricalsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HistoricalsDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HistoricalsDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HistoricalsDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HistoricalsDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<FileSpec> FileSpecs
		{
			get
			{
				return this.GetTable<FileSpec>();
			}
		}
		
		public System.Data.Linq.Table<FlatFile> FlatFiles
		{
			get
			{
				return this.GetTable<FlatFile>();
			}
		}
		
		public System.Data.Linq.Table<Query> Queries
		{
			get
			{
				return this.GetTable<Query>();
			}
		}
		
		public System.Data.Linq.Table<Security> Securities
		{
			get
			{
				return this.GetTable<Security>();
			}
		}
		
		public System.Data.Linq.Table<Server> Servers
		{
			get
			{
				return this.GetTable<Server>();
			}
		}
		
		public System.Data.Linq.Table<MailSetting> MailSettings
		{
			get
			{
				return this.GetTable<MailSetting>();
			}
		}
		
		public System.Data.Linq.Table<Provider> Providers
		{
			get
			{
				return this.GetTable<Provider>();
			}
		}
		
		public System.Data.Linq.Table<Subscription> Subscriptions
		{
			get
			{
				return this.GetTable<Subscription>();
			}
		}
		
		public System.Data.Linq.Table<ServiceControl> ServiceControls
		{
			get
			{
				return this.GetTable<ServiceControl>();
			}
		}
		
		public System.Data.Linq.Table<DailyBar> DailyBars
		{
			get
			{
				return this.GetTable<DailyBar>();
			}
		}
		
		public System.Data.Linq.Table<BarStat> BarStats
		{
			get
			{
				return this.GetTable<BarStat>();
			}
		}
		
		public System.Data.Linq.Table<Registration> Registrations
		{
			get
			{
				return this.GetTable<Registration>();
			}
		}
		
		public System.Data.Linq.Table<VWAPS> VWAPS
		{
			get
			{
				return this.GetTable<VWAPS>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spGetAverageVolume")]
		public ISingleResult<spGetAverageVolumeResult> spGetAverageVolume([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> fromDate, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AverageDays", DbType="Int")] System.Nullable<int> averageDays, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Provider", DbType="Int")] System.Nullable<int> provider)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fromDate, averageDays, provider);
			return ((ISingleResult<spGetAverageVolumeResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FileSpecs")]
	public partial class FileSpec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FileSpecId;
		
		private string _Delimiter;
		
		private string _DateFormat;
		
		private System.Nullable<long> _Heading;
		
		private System.Nullable<int> _Symbol;
		
		private System.Nullable<int> _Date;
		
		private System.Nullable<int> _Open;
		
		private System.Nullable<int> _High;
		
		private System.Nullable<int> _Low;
		
		private System.Nullable<int> _Close;
		
		private System.Nullable<int> _Volume;
		
		private System.Nullable<int> _Interest;
		
		private System.Nullable<int> _SplitRatio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFileSpecIdChanging(string value);
    partial void OnFileSpecIdChanged();
    partial void OnDelimiterChanging(string value);
    partial void OnDelimiterChanged();
    partial void OnDateFormatChanging(string value);
    partial void OnDateFormatChanged();
    partial void OnHeadingChanging(System.Nullable<long> value);
    partial void OnHeadingChanged();
    partial void OnSymbolChanging(System.Nullable<int> value);
    partial void OnSymbolChanged();
    partial void OnDateChanging(System.Nullable<int> value);
    partial void OnDateChanged();
    partial void OnOpenChanging(System.Nullable<int> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<int> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<int> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<int> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<int> value);
    partial void OnVolumeChanged();
    partial void OnInterestChanging(System.Nullable<int> value);
    partial void OnInterestChanged();
    partial void OnSplitRatioChanging(System.Nullable<int> value);
    partial void OnSplitRatioChanged();
    #endregion
		
		public FileSpec()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSpecId", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FileSpecId
		{
			get
			{
				return this._FileSpecId;
			}
			set
			{
				if ((this._FileSpecId != value))
				{
					this.OnFileSpecIdChanging(value);
					this.SendPropertyChanging();
					this._FileSpecId = value;
					this.SendPropertyChanged("FileSpecId");
					this.OnFileSpecIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Delimiter", DbType="NVarChar(255)")]
		public string Delimiter
		{
			get
			{
				return this._Delimiter;
			}
			set
			{
				if ((this._Delimiter != value))
				{
					this.OnDelimiterChanging(value);
					this.SendPropertyChanging();
					this._Delimiter = value;
					this.SendPropertyChanged("Delimiter");
					this.OnDelimiterChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateFormat", DbType="NVarChar(255)")]
		public string DateFormat
		{
			get
			{
				return this._DateFormat;
			}
			set
			{
				if ((this._DateFormat != value))
				{
					this.OnDateFormatChanging(value);
					this.SendPropertyChanging();
					this._DateFormat = value;
					this.SendPropertyChanged("DateFormat");
					this.OnDateFormatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Heading", DbType="BigInt")]
		public System.Nullable<long> Heading
		{
			get
			{
				return this._Heading;
			}
			set
			{
				if ((this._Heading != value))
				{
					this.OnHeadingChanging(value);
					this.SendPropertyChanging();
					this._Heading = value;
					this.SendPropertyChanged("Heading");
					this.OnHeadingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="Int")]
		public System.Nullable<int> Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this.OnSymbolChanging(value);
					this.SendPropertyChanging();
					this._Symbol = value;
					this.SendPropertyChanged("Symbol");
					this.OnSymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="Int")]
		public System.Nullable<int> Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Int")]
		public System.Nullable<int> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Int")]
		public System.Nullable<int> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Int")]
		public System.Nullable<int> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Int")]
		public System.Nullable<int> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Int")]
		public System.Nullable<int> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interest", DbType="Int")]
		public System.Nullable<int> Interest
		{
			get
			{
				return this._Interest;
			}
			set
			{
				if ((this._Interest != value))
				{
					this.OnInterestChanging(value);
					this.SendPropertyChanging();
					this._Interest = value;
					this.SendPropertyChanged("Interest");
					this.OnInterestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SplitRatio", DbType="Int")]
		public System.Nullable<int> SplitRatio
		{
			get
			{
				return this._SplitRatio;
			}
			set
			{
				if ((this._SplitRatio != value))
				{
					this.OnSplitRatioChanging(value);
					this.SendPropertyChanging();
					this._SplitRatio = value;
					this.SendPropertyChanged("SplitRatio");
					this.OnSplitRatioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.FlatFiles")]
	public partial class FlatFile : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _FlatFileId;
		
		private string _FileSpecId;
		
		private string _Path;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFlatFileIdChanging(string value);
    partial void OnFlatFileIdChanged();
    partial void OnFileSpecIdChanging(string value);
    partial void OnFileSpecIdChanged();
    partial void OnPathChanging(string value);
    partial void OnPathChanged();
    #endregion
		
		public FlatFile()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlatFileId", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string FlatFileId
		{
			get
			{
				return this._FlatFileId;
			}
			set
			{
				if ((this._FlatFileId != value))
				{
					this.OnFlatFileIdChanging(value);
					this.SendPropertyChanging();
					this._FlatFileId = value;
					this.SendPropertyChanged("FlatFileId");
					this.OnFlatFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileSpecId", DbType="NVarChar(255)")]
		public string FileSpecId
		{
			get
			{
				return this._FileSpecId;
			}
			set
			{
				if ((this._FileSpecId != value))
				{
					this.OnFileSpecIdChanging(value);
					this.SendPropertyChanging();
					this._FileSpecId = value;
					this.SendPropertyChanged("FileSpecId");
					this.OnFileSpecIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Path", DbType="NVarChar(255)")]
		public string Path
		{
			get
			{
				return this._Path;
			}
			set
			{
				if ((this._Path != value))
				{
					this.OnPathChanging(value);
					this.SendPropertyChanging();
					this._Path = value;
					this.SendPropertyChanged("Path");
					this.OnPathChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Queries")]
	public partial class Query : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _QueryId;
		
		private string _Query1;
		
		private System.Nullable<int> _Type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQueryIdChanging(string value);
    partial void OnQueryIdChanged();
    partial void OnQuery1Changing(string value);
    partial void OnQuery1Changed();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    #endregion
		
		public Query()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueryId", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string QueryId
		{
			get
			{
				return this._QueryId;
			}
			set
			{
				if ((this._QueryId != value))
				{
					this.OnQueryIdChanging(value);
					this.SendPropertyChanging();
					this._QueryId = value;
					this.SendPropertyChanged("QueryId");
					this.OnQueryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="Query", Storage="_Query1", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Query1
		{
			get
			{
				return this._Query1;
			}
			set
			{
				if ((this._Query1 != value))
				{
					this.OnQuery1Changing(value);
					this.SendPropertyChanging();
					this._Query1 = value;
					this.SendPropertyChanged("Query1");
					this.OnQuery1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Securities")]
	public partial class Security : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SecurityID;
		
		private string _Ticker;
		
		private string _Symbol;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSecurityIDChanging(int value);
    partial void OnSecurityIDChanged();
    partial void OnTickerChanging(string value);
    partial void OnTickerChanged();
    partial void OnSymbolChanging(string value);
    partial void OnSymbolChanged();
    #endregion
		
		public Security()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int SecurityID
		{
			get
			{
				return this._SecurityID;
			}
			set
			{
				if ((this._SecurityID != value))
				{
					this.OnSecurityIDChanging(value);
					this.SendPropertyChanging();
					this._SecurityID = value;
					this.SendPropertyChanged("SecurityID");
					this.OnSecurityIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticker", DbType="NVarChar(255)")]
		public string Ticker
		{
			get
			{
				return this._Ticker;
			}
			set
			{
				if ((this._Ticker != value))
				{
					this.OnTickerChanging(value);
					this.SendPropertyChanging();
					this._Ticker = value;
					this.SendPropertyChanged("Ticker");
					this.OnTickerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="NVarChar(255)")]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this.OnSymbolChanging(value);
					this.SendPropertyChanging();
					this._Symbol = value;
					this.SendPropertyChanged("Symbol");
					this.OnSymbolChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Servers")]
	public partial class Server : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _External;
		
		private string _Internal;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnExternalChanging(string value);
    partial void OnExternalChanged();
    partial void OnInternalChanging(string value);
    partial void OnInternalChanged();
    #endregion
		
		public Server()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[External]", Storage="_External", DbType="NVarChar(255)")]
		public string External
		{
			get
			{
				return this._External;
			}
			set
			{
				if ((this._External != value))
				{
					this.OnExternalChanging(value);
					this.SendPropertyChanging();
					this._External = value;
					this.SendPropertyChanged("External");
					this.OnExternalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Internal", DbType="NVarChar(255)")]
		public string Internal
		{
			get
			{
				return this._Internal;
			}
			set
			{
				if ((this._Internal != value))
				{
					this.OnInternalChanging(value);
					this.SendPropertyChanging();
					this._Internal = value;
					this.SendPropertyChanged("Internal");
					this.OnInternalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MailSettings")]
	public partial class MailSetting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _MailFrom;
		
		private string _MailTo;
		
		private string _MailSmtp;
		
		private string _MailSubject;
		
		private string _MailBody;
		
		private int _MailPort;
		
		private string _MailUser;
		
		private string _MailPassword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnMailFromChanging(string value);
    partial void OnMailFromChanged();
    partial void OnMailToChanging(string value);
    partial void OnMailToChanged();
    partial void OnMailSmtpChanging(string value);
    partial void OnMailSmtpChanged();
    partial void OnMailSubjectChanging(string value);
    partial void OnMailSubjectChanged();
    partial void OnMailBodyChanging(string value);
    partial void OnMailBodyChanged();
    partial void OnMailPortChanging(int value);
    partial void OnMailPortChanged();
    partial void OnMailUserChanging(string value);
    partial void OnMailUserChanged();
    partial void OnMailPasswordChanging(string value);
    partial void OnMailPasswordChanged();
    #endregion
		
		public MailSetting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailFrom", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MailFrom
		{
			get
			{
				return this._MailFrom;
			}
			set
			{
				if ((this._MailFrom != value))
				{
					this.OnMailFromChanging(value);
					this.SendPropertyChanging();
					this._MailFrom = value;
					this.SendPropertyChanged("MailFrom");
					this.OnMailFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailTo", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string MailTo
		{
			get
			{
				return this._MailTo;
			}
			set
			{
				if ((this._MailTo != value))
				{
					this.OnMailToChanging(value);
					this.SendPropertyChanging();
					this._MailTo = value;
					this.SendPropertyChanged("MailTo");
					this.OnMailToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailSmtp", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MailSmtp
		{
			get
			{
				return this._MailSmtp;
			}
			set
			{
				if ((this._MailSmtp != value))
				{
					this.OnMailSmtpChanging(value);
					this.SendPropertyChanging();
					this._MailSmtp = value;
					this.SendPropertyChanged("MailSmtp");
					this.OnMailSmtpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailSubject", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MailSubject
		{
			get
			{
				return this._MailSubject;
			}
			set
			{
				if ((this._MailSubject != value))
				{
					this.OnMailSubjectChanging(value);
					this.SendPropertyChanging();
					this._MailSubject = value;
					this.SendPropertyChanged("MailSubject");
					this.OnMailSubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailBody", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MailBody
		{
			get
			{
				return this._MailBody;
			}
			set
			{
				if ((this._MailBody != value))
				{
					this.OnMailBodyChanging(value);
					this.SendPropertyChanging();
					this._MailBody = value;
					this.SendPropertyChanged("MailBody");
					this.OnMailBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailPort", DbType="Int NOT NULL")]
		public int MailPort
		{
			get
			{
				return this._MailPort;
			}
			set
			{
				if ((this._MailPort != value))
				{
					this.OnMailPortChanging(value);
					this.SendPropertyChanging();
					this._MailPort = value;
					this.SendPropertyChanged("MailPort");
					this.OnMailPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailUser", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MailUser
		{
			get
			{
				return this._MailUser;
			}
			set
			{
				if ((this._MailUser != value))
				{
					this.OnMailUserChanging(value);
					this.SendPropertyChanging();
					this._MailUser = value;
					this.SendPropertyChanged("MailUser");
					this.OnMailUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailPassword", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MailPassword
		{
			get
			{
				return this._MailPassword;
			}
			set
			{
				if ((this._MailPassword != value))
				{
					this.OnMailPasswordChanging(value);
					this.SendPropertyChanging();
					this._MailPassword = value;
					this.SendPropertyChanged("MailPassword");
					this.OnMailPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Providers")]
	public partial class Provider : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ProviderId;
		
		private string _Name;
		
		private string _Process;
		
		private string _LogFile;
		
		private bool _Enabled;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnProviderIdChanging(int value);
    partial void OnProviderIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnProcessChanging(string value);
    partial void OnProcessChanged();
    partial void OnLogFileChanging(string value);
    partial void OnLogFileChanged();
    partial void OnEnabledChanging(bool value);
    partial void OnEnabledChanged();
    #endregion
		
		public Provider()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderId", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ProviderId
		{
			get
			{
				return this._ProviderId;
			}
			set
			{
				if ((this._ProviderId != value))
				{
					this.OnProviderIdChanging(value);
					this.SendPropertyChanging();
					this._ProviderId = value;
					this.SendPropertyChanged("ProviderId");
					this.OnProviderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Process", DbType="NVarChar(255)")]
		public string Process
		{
			get
			{
				return this._Process;
			}
			set
			{
				if ((this._Process != value))
				{
					this.OnProcessChanging(value);
					this.SendPropertyChanging();
					this._Process = value;
					this.SendPropertyChanged("Process");
					this.OnProcessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LogFile", DbType="NVarChar(MAX)")]
		public string LogFile
		{
			get
			{
				return this._LogFile;
			}
			set
			{
				if ((this._LogFile != value))
				{
					this.OnLogFileChanging(value);
					this.SendPropertyChanging();
					this._LogFile = value;
					this.SendPropertyChanged("LogFile");
					this.OnLogFileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enabled", DbType="Bit NOT NULL")]
		public bool Enabled
		{
			get
			{
				return this._Enabled;
			}
			set
			{
				if ((this._Enabled != value))
				{
					this.OnEnabledChanging(value);
					this.SendPropertyChanging();
					this._Enabled = value;
					this.SendPropertyChanged("Enabled");
					this.OnEnabledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Subscriptions")]
	public partial class Subscription : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SubscriberID;
		
		private System.Nullable<System.DateTime> _Time;
		
		private System.Nullable<int> _ProviderId;
		
		private System.Nullable<bool> _Sun;
		
		private System.Nullable<bool> _Mon;
		
		private System.Nullable<bool> _Tue;
		
		private System.Nullable<bool> _Wed;
		
		private System.Nullable<bool> _Thu;
		
		private System.Nullable<bool> _Fri;
		
		private System.Nullable<bool> _Sat;
		
		private string _FlatFileId;
		
		private System.Nullable<System.DateTime> _NextRun;
		
		private System.Nullable<System.DateTime> _LastRun;
		
		private string _Messages;
		
		private System.Nullable<int> _ExitCode;
		
		private System.Nullable<bool> _Enabled;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSubscriberIDChanging(string value);
    partial void OnSubscriberIDChanged();
    partial void OnTimeChanging(System.Nullable<System.DateTime> value);
    partial void OnTimeChanged();
    partial void OnProviderIdChanging(System.Nullable<int> value);
    partial void OnProviderIdChanged();
    partial void OnSunChanging(System.Nullable<bool> value);
    partial void OnSunChanged();
    partial void OnMonChanging(System.Nullable<bool> value);
    partial void OnMonChanged();
    partial void OnTueChanging(System.Nullable<bool> value);
    partial void OnTueChanged();
    partial void OnWedChanging(System.Nullable<bool> value);
    partial void OnWedChanged();
    partial void OnThuChanging(System.Nullable<bool> value);
    partial void OnThuChanged();
    partial void OnFriChanging(System.Nullable<bool> value);
    partial void OnFriChanged();
    partial void OnSatChanging(System.Nullable<bool> value);
    partial void OnSatChanged();
    partial void OnFlatFileIdChanging(string value);
    partial void OnFlatFileIdChanged();
    partial void OnNextRunChanging(System.Nullable<System.DateTime> value);
    partial void OnNextRunChanged();
    partial void OnLastRunChanging(System.Nullable<System.DateTime> value);
    partial void OnLastRunChanged();
    partial void OnMessagesChanging(string value);
    partial void OnMessagesChanged();
    partial void OnExitCodeChanging(System.Nullable<int> value);
    partial void OnExitCodeChanged();
    partial void OnEnabledChanging(System.Nullable<bool> value);
    partial void OnEnabledChanged();
    #endregion
		
		public Subscription()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriberID", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SubscriberID
		{
			get
			{
				return this._SubscriberID;
			}
			set
			{
				if ((this._SubscriberID != value))
				{
					this.OnSubscriberIDChanging(value);
					this.SendPropertyChanging();
					this._SubscriberID = value;
					this.SendPropertyChanged("SubscriberID");
					this.OnSubscriberIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime")]
		public System.Nullable<System.DateTime> Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderId", DbType="Int")]
		public System.Nullable<int> ProviderId
		{
			get
			{
				return this._ProviderId;
			}
			set
			{
				if ((this._ProviderId != value))
				{
					this.OnProviderIdChanging(value);
					this.SendPropertyChanging();
					this._ProviderId = value;
					this.SendPropertyChanged("ProviderId");
					this.OnProviderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sun", DbType="Bit")]
		public System.Nullable<bool> Sun
		{
			get
			{
				return this._Sun;
			}
			set
			{
				if ((this._Sun != value))
				{
					this.OnSunChanging(value);
					this.SendPropertyChanging();
					this._Sun = value;
					this.SendPropertyChanged("Sun");
					this.OnSunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mon", DbType="Bit")]
		public System.Nullable<bool> Mon
		{
			get
			{
				return this._Mon;
			}
			set
			{
				if ((this._Mon != value))
				{
					this.OnMonChanging(value);
					this.SendPropertyChanging();
					this._Mon = value;
					this.SendPropertyChanged("Mon");
					this.OnMonChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tue", DbType="Bit")]
		public System.Nullable<bool> Tue
		{
			get
			{
				return this._Tue;
			}
			set
			{
				if ((this._Tue != value))
				{
					this.OnTueChanging(value);
					this.SendPropertyChanging();
					this._Tue = value;
					this.SendPropertyChanged("Tue");
					this.OnTueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wed", DbType="Bit")]
		public System.Nullable<bool> Wed
		{
			get
			{
				return this._Wed;
			}
			set
			{
				if ((this._Wed != value))
				{
					this.OnWedChanging(value);
					this.SendPropertyChanging();
					this._Wed = value;
					this.SendPropertyChanged("Wed");
					this.OnWedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thu", DbType="Bit")]
		public System.Nullable<bool> Thu
		{
			get
			{
				return this._Thu;
			}
			set
			{
				if ((this._Thu != value))
				{
					this.OnThuChanging(value);
					this.SendPropertyChanging();
					this._Thu = value;
					this.SendPropertyChanged("Thu");
					this.OnThuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fri", DbType="Bit")]
		public System.Nullable<bool> Fri
		{
			get
			{
				return this._Fri;
			}
			set
			{
				if ((this._Fri != value))
				{
					this.OnFriChanging(value);
					this.SendPropertyChanging();
					this._Fri = value;
					this.SendPropertyChanged("Fri");
					this.OnFriChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sat", DbType="Bit")]
		public System.Nullable<bool> Sat
		{
			get
			{
				return this._Sat;
			}
			set
			{
				if ((this._Sat != value))
				{
					this.OnSatChanging(value);
					this.SendPropertyChanging();
					this._Sat = value;
					this.SendPropertyChanged("Sat");
					this.OnSatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FlatFileId", DbType="NVarChar(255)")]
		public string FlatFileId
		{
			get
			{
				return this._FlatFileId;
			}
			set
			{
				if ((this._FlatFileId != value))
				{
					this.OnFlatFileIdChanging(value);
					this.SendPropertyChanging();
					this._FlatFileId = value;
					this.SendPropertyChanged("FlatFileId");
					this.OnFlatFileIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NextRun", DbType="DateTime")]
		public System.Nullable<System.DateTime> NextRun
		{
			get
			{
				return this._NextRun;
			}
			set
			{
				if ((this._NextRun != value))
				{
					this.OnNextRunChanging(value);
					this.SendPropertyChanging();
					this._NextRun = value;
					this.SendPropertyChanged("NextRun");
					this.OnNextRunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastRun", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastRun
		{
			get
			{
				return this._LastRun;
			}
			set
			{
				if ((this._LastRun != value))
				{
					this.OnLastRunChanging(value);
					this.SendPropertyChanging();
					this._LastRun = value;
					this.SendPropertyChanged("LastRun");
					this.OnLastRunChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Messages", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Messages
		{
			get
			{
				return this._Messages;
			}
			set
			{
				if ((this._Messages != value))
				{
					this.OnMessagesChanging(value);
					this.SendPropertyChanging();
					this._Messages = value;
					this.SendPropertyChanged("Messages");
					this.OnMessagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExitCode", DbType="Int")]
		public System.Nullable<int> ExitCode
		{
			get
			{
				return this._ExitCode;
			}
			set
			{
				if ((this._ExitCode != value))
				{
					this.OnExitCodeChanging(value);
					this.SendPropertyChanging();
					this._ExitCode = value;
					this.SendPropertyChanged("ExitCode");
					this.OnExitCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enabled", DbType="Bit")]
		public System.Nullable<bool> Enabled
		{
			get
			{
				return this._Enabled;
			}
			set
			{
				if ((this._Enabled != value))
				{
					this.OnEnabledChanging(value);
					this.SendPropertyChanging();
					this._Enabled = value;
					this.SendPropertyChanged("Enabled");
					this.OnEnabledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ServiceControl")]
	public partial class ServiceControl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Flags;
		
		private bool _Enabled;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFlagsChanging(string value);
    partial void OnFlagsChanged();
    partial void OnEnabledChanging(bool value);
    partial void OnEnabledChanged();
    #endregion
		
		public ServiceControl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flags", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Flags
		{
			get
			{
				return this._Flags;
			}
			set
			{
				if ((this._Flags != value))
				{
					this.OnFlagsChanging(value);
					this.SendPropertyChanging();
					this._Flags = value;
					this.SendPropertyChanged("Flags");
					this.OnFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Enabled", DbType="Bit NOT NULL")]
		public bool Enabled
		{
			get
			{
				return this._Enabled;
			}
			set
			{
				if ((this._Enabled != value))
				{
					this.OnEnabledChanging(value);
					this.SendPropertyChanging();
					this._Enabled = value;
					this.SendPropertyChanged("Enabled");
					this.OnEnabledChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DailyBars")]
	public partial class DailyBar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Symbol;
		
		private System.DateTime _Date;
		
		private long _ProviderId;
		
		private System.Nullable<double> _Open;
		
		private System.Nullable<double> _High;
		
		private System.Nullable<double> _Low;
		
		private System.Nullable<double> _Close;
		
		private System.Nullable<double> _Volume;
		
		private System.Nullable<double> _Interest;
		
		private System.Nullable<long> _Flags;
		
		private System.Nullable<System.DateTime> _SettlementDate;
		
		private System.Nullable<double> _SettlementPrice;
		
		private System.Nullable<double> _SplitRatio;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSymbolChanging(string value);
    partial void OnSymbolChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnProviderIdChanging(long value);
    partial void OnProviderIdChanged();
    partial void OnOpenChanging(System.Nullable<double> value);
    partial void OnOpenChanged();
    partial void OnHighChanging(System.Nullable<double> value);
    partial void OnHighChanged();
    partial void OnLowChanging(System.Nullable<double> value);
    partial void OnLowChanged();
    partial void OnCloseChanging(System.Nullable<double> value);
    partial void OnCloseChanged();
    partial void OnVolumeChanging(System.Nullable<double> value);
    partial void OnVolumeChanged();
    partial void OnInterestChanging(System.Nullable<double> value);
    partial void OnInterestChanged();
    partial void OnFlagsChanging(System.Nullable<long> value);
    partial void OnFlagsChanged();
    partial void OnSettlementDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSettlementDateChanged();
    partial void OnSettlementPriceChanging(System.Nullable<double> value);
    partial void OnSettlementPriceChanged();
    partial void OnSplitRatioChanging(System.Nullable<double> value);
    partial void OnSplitRatioChanged();
    #endregion
		
		public DailyBar()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="NVarChar(255) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this.OnSymbolChanging(value);
					this.SendPropertyChanging();
					this._Symbol = value;
					this.SendPropertyChanged("Symbol");
					this.OnSymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderId", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long ProviderId
		{
			get
			{
				return this._ProviderId;
			}
			set
			{
				if ((this._ProviderId != value))
				{
					this.OnProviderIdChanging(value);
					this.SendPropertyChanging();
					this._ProviderId = value;
					this.SendPropertyChanged("ProviderId");
					this.OnProviderIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Open]", Storage="_Open", DbType="Float")]
		public System.Nullable<double> Open
		{
			get
			{
				return this._Open;
			}
			set
			{
				if ((this._Open != value))
				{
					this.OnOpenChanging(value);
					this.SendPropertyChanging();
					this._Open = value;
					this.SendPropertyChanged("Open");
					this.OnOpenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_High", DbType="Float")]
		public System.Nullable<double> High
		{
			get
			{
				return this._High;
			}
			set
			{
				if ((this._High != value))
				{
					this.OnHighChanging(value);
					this.SendPropertyChanging();
					this._High = value;
					this.SendPropertyChanged("High");
					this.OnHighChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Low", DbType="Float")]
		public System.Nullable<double> Low
		{
			get
			{
				return this._Low;
			}
			set
			{
				if ((this._Low != value))
				{
					this.OnLowChanging(value);
					this.SendPropertyChanging();
					this._Low = value;
					this.SendPropertyChanged("Low");
					this.OnLowChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Close]", Storage="_Close", DbType="Float")]
		public System.Nullable<double> Close
		{
			get
			{
				return this._Close;
			}
			set
			{
				if ((this._Close != value))
				{
					this.OnCloseChanging(value);
					this.SendPropertyChanging();
					this._Close = value;
					this.SendPropertyChanged("Close");
					this.OnCloseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Volume", DbType="Float")]
		public System.Nullable<double> Volume
		{
			get
			{
				return this._Volume;
			}
			set
			{
				if ((this._Volume != value))
				{
					this.OnVolumeChanging(value);
					this.SendPropertyChanging();
					this._Volume = value;
					this.SendPropertyChanged("Volume");
					this.OnVolumeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Interest", DbType="Float")]
		public System.Nullable<double> Interest
		{
			get
			{
				return this._Interest;
			}
			set
			{
				if ((this._Interest != value))
				{
					this.OnInterestChanging(value);
					this.SendPropertyChanging();
					this._Interest = value;
					this.SendPropertyChanged("Interest");
					this.OnInterestChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flags", DbType="BigInt")]
		public System.Nullable<long> Flags
		{
			get
			{
				return this._Flags;
			}
			set
			{
				if ((this._Flags != value))
				{
					this.OnFlagsChanging(value);
					this.SendPropertyChanging();
					this._Flags = value;
					this.SendPropertyChanged("Flags");
					this.OnFlagsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettlementDate", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> SettlementDate
		{
			get
			{
				return this._SettlementDate;
			}
			set
			{
				if ((this._SettlementDate != value))
				{
					this.OnSettlementDateChanging(value);
					this.SendPropertyChanging();
					this._SettlementDate = value;
					this.SendPropertyChanged("SettlementDate");
					this.OnSettlementDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SettlementPrice", DbType="Float")]
		public System.Nullable<double> SettlementPrice
		{
			get
			{
				return this._SettlementPrice;
			}
			set
			{
				if ((this._SettlementPrice != value))
				{
					this.OnSettlementPriceChanging(value);
					this.SendPropertyChanging();
					this._SettlementPrice = value;
					this.SendPropertyChanged("SettlementPrice");
					this.OnSettlementPriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SplitRatio", DbType="Float")]
		public System.Nullable<double> SplitRatio
		{
			get
			{
				return this._SplitRatio;
			}
			set
			{
				if ((this._SplitRatio != value))
				{
					this.OnSplitRatioChanging(value);
					this.SendPropertyChanging();
					this._SplitRatio = value;
					this.SendPropertyChanged("SplitRatio");
					this.OnSplitRatioChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BarStats")]
	public partial class BarStat
	{
		
		private string _Symbol;
		
		private System.Nullable<System.DateTime> _StartDate;
		
		private System.Nullable<System.DateTime> _EndDate;
		
		private System.Nullable<int> _DaySpan;
		
		private System.Nullable<int> _BarCount;
		
		private long _ProviderId;
		
		public BarStat()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this._Symbol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> StartDate
		{
			get
			{
				return this._StartDate;
			}
			set
			{
				if ((this._StartDate != value))
				{
					this._StartDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EndDate
		{
			get
			{
				return this._EndDate;
			}
			set
			{
				if ((this._EndDate != value))
				{
					this._EndDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DaySpan", DbType="Int")]
		public System.Nullable<int> DaySpan
		{
			get
			{
				return this._DaySpan;
			}
			set
			{
				if ((this._DaySpan != value))
				{
					this._DaySpan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCount", DbType="Int")]
		public System.Nullable<int> BarCount
		{
			get
			{
				return this._BarCount;
			}
			set
			{
				if ((this._BarCount != value))
				{
					this._BarCount = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProviderId", DbType="BigInt NOT NULL")]
		public long ProviderId
		{
			get
			{
				return this._ProviderId;
			}
			set
			{
				if ((this._ProviderId != value))
				{
					this._ProviderId = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Registrations")]
	public partial class Registration : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _RegistrationId;
		
		private string _Server;
		
		private string _Database;
		
		private string _UserName;
		
		private string _Password;
		
		private string _QueryId;
		
		private string _SubscriberId;
		
		private int _KeyColumn;
		
		private int _AssetColumn;
		
		private int _TickerColumn;
		
		private string _Column;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnRegistrationIdChanging(int value);
    partial void OnRegistrationIdChanged();
    partial void OnServerChanging(string value);
    partial void OnServerChanged();
    partial void OnDatabaseChanging(string value);
    partial void OnDatabaseChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnQueryIdChanging(string value);
    partial void OnQueryIdChanged();
    partial void OnSubscriberIdChanging(string value);
    partial void OnSubscriberIdChanged();
    partial void OnKeyColumnChanging(int value);
    partial void OnKeyColumnChanged();
    partial void OnAssetColumnChanging(int value);
    partial void OnAssetColumnChanged();
    partial void OnTickerColumnChanging(int value);
    partial void OnTickerColumnChanged();
    partial void OnColumnChanging(string value);
    partial void OnColumnChanged();
    #endregion
		
		public Registration()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegistrationId", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int RegistrationId
		{
			get
			{
				return this._RegistrationId;
			}
			set
			{
				if ((this._RegistrationId != value))
				{
					this.OnRegistrationIdChanging(value);
					this.SendPropertyChanging();
					this._RegistrationId = value;
					this.SendPropertyChanged("RegistrationId");
					this.OnRegistrationIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Server", DbType="NVarChar(255)")]
		public string Server
		{
			get
			{
				return this._Server;
			}
			set
			{
				if ((this._Server != value))
				{
					this.OnServerChanging(value);
					this.SendPropertyChanging();
					this._Server = value;
					this.SendPropertyChanged("Server");
					this.OnServerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Database]", Storage="_Database", DbType="NVarChar(255)")]
		public string Database
		{
			get
			{
				return this._Database;
			}
			set
			{
				if ((this._Database != value))
				{
					this.OnDatabaseChanging(value);
					this.SendPropertyChanging();
					this._Database = value;
					this.SendPropertyChanged("Database");
					this.OnDatabaseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(255)")]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(255)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QueryId", DbType="NVarChar(255)")]
		public string QueryId
		{
			get
			{
				return this._QueryId;
			}
			set
			{
				if ((this._QueryId != value))
				{
					this.OnQueryIdChanging(value);
					this.SendPropertyChanging();
					this._QueryId = value;
					this.SendPropertyChanged("QueryId");
					this.OnQueryIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubscriberId", DbType="NVarChar(255)")]
		public string SubscriberId
		{
			get
			{
				return this._SubscriberId;
			}
			set
			{
				if ((this._SubscriberId != value))
				{
					this.OnSubscriberIdChanging(value);
					this.SendPropertyChanging();
					this._SubscriberId = value;
					this.SendPropertyChanged("SubscriberId");
					this.OnSubscriberIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeyColumn", DbType="Int NOT NULL")]
		public int KeyColumn
		{
			get
			{
				return this._KeyColumn;
			}
			set
			{
				if ((this._KeyColumn != value))
				{
					this.OnKeyColumnChanging(value);
					this.SendPropertyChanging();
					this._KeyColumn = value;
					this.SendPropertyChanged("KeyColumn");
					this.OnKeyColumnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssetColumn", DbType="Int NOT NULL")]
		public int AssetColumn
		{
			get
			{
				return this._AssetColumn;
			}
			set
			{
				if ((this._AssetColumn != value))
				{
					this.OnAssetColumnChanging(value);
					this.SendPropertyChanging();
					this._AssetColumn = value;
					this.SendPropertyChanged("AssetColumn");
					this.OnAssetColumnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TickerColumn", DbType="Int NOT NULL")]
		public int TickerColumn
		{
			get
			{
				return this._TickerColumn;
			}
			set
			{
				if ((this._TickerColumn != value))
				{
					this.OnTickerColumnChanging(value);
					this.SendPropertyChanging();
					this._TickerColumn = value;
					this.SendPropertyChanged("TickerColumn");
					this.OnTickerColumnChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Column]", Storage="_Column", DbType="NVarChar(255)")]
		public string Column
		{
			get
			{
				return this._Column;
			}
			set
			{
				if ((this._Column != value))
				{
					this.OnColumnChanging(value);
					this.SendPropertyChanging();
					this._Column = value;
					this.SendPropertyChanged("Column");
					this.OnColumnChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	public partial class VWAPS : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Symbol;
		
		private System.DateTime _Date;
		
		private double _VWAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSymbolChanging(string value);
    partial void OnSymbolChanged();
    partial void OnDateChanging(System.DateTime value);
    partial void OnDateChanged();
    partial void OnVWAPChanging(double value);
    partial void OnVWAPChanged();
    #endregion
		
		public VWAPS()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="Varchar(255) No Null", CanBeNull=false, IsPrimaryKey=true)]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this.OnSymbolChanging(value);
					this.SendPropertyChanging();
					this._Symbol = value;
					this.SendPropertyChanged("Symbol");
					this.OnSymbolChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Date
		{
			get
			{
				return this._Date;
			}
			set
			{
				if ((this._Date != value))
				{
					this.OnDateChanging(value);
					this.SendPropertyChanging();
					this._Date = value;
					this.SendPropertyChanged("Date");
					this.OnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VWAP", DbType="Float No Null")]
		public double VWAP
		{
			get
			{
				return this._VWAP;
			}
			set
			{
				if ((this._VWAP != value))
				{
					this.OnVWAPChanging(value);
					this.SendPropertyChanging();
					this._VWAP = value;
					this.SendPropertyChanged("VWAP");
					this.OnVWAPChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class spGetAverageVolumeResult
	{
		
		private string _Symbol;
		
		private System.Nullable<double> _AverageVolume;
		
		public spGetAverageVolumeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Symbol", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Symbol
		{
			get
			{
				return this._Symbol;
			}
			set
			{
				if ((this._Symbol != value))
				{
					this._Symbol = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AverageVolume", DbType="Float")]
		public System.Nullable<double> AverageVolume
		{
			get
			{
				return this._AverageVolume;
			}
			set
			{
				if ((this._AverageVolume != value))
				{
					this._AverageVolume = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
