CREATE TABLE [dbo].[T_AUEC] (
    [AUECID]                         INT            NOT NULL,
    [AssetID]                        INT            NOT NULL,
    [UnderLyingID]                   INT            NOT NULL,
    [ExchangeID]                     INT            NULL,
    [FullName]                       NVARCHAR (100) NULL,
    [DisplayName]                    NVARCHAR (50)  NULL,
    [ExchangeIdentifier]             NVARCHAR (50)  NULL,
	[MarketDataProviderExchangeIdentifier]             NVARCHAR (50)  NULL,
    [UnitID]                         INT            NULL,
    [TimeZone]                       NVARCHAR (100) NULL,
    [TimeZoneOffSet]                 FLOAT (53)     NULL,
    [PreMarket]                      INT            NULL,
    [PreMarketTradingStartTime]      DATETIME       NULL,
    [PreMarketTradingEndTime]        DATETIME       NULL,
    [RegularTime]                    INT            NULL,
    [RegularTradingStartTime]        DATETIME       NULL,
    [RegularTradingEndTime]          DATETIME       NULL,
    [LunchTime]                      INT            NULL,
    [LunchTimeStartTime]             DATETIME       NULL,
    [LunchTimeEndTime]               DATETIME       NULL,
    [PostMarket]                     INT            NULL,
    [PostMarketTradingStartTime]     DATETIME       NULL,
    [PostMarketTradingEndTime]       DATETIME       NULL,
    [DayLightSaving]                 NVARCHAR (50)  NULL,
    [Country]                        INT            NULL,
    [StateID]                        INT            NULL,
    [CountryFlagID]                  INT            NULL,
    [ExchangeLogoID]                 INT            NULL,
    [CurrencyConversion]             INT            NULL,
    [SymbolConventionID]             INT            NULL,
    [BaseCurrencyID]                 INT            NULL,
    [OtherCurrencyID]                INT            NULL,
    [Multiplier]                     FLOAT (53)     NULL,
    [IsShortSaleConfirmation]        INT            NULL,
    [ProvideFundNameWithTrade]       INT            NULL,
    [ProvideIdentifierNameWithTrade] INT            NULL,
    [IdentifierID]                   INT            NULL,
    [PurchaseSecFees]                FLOAT (53)     NULL,
    [SaleSecFees]                    FLOAT (53)     NULL,
    [PurchaseStamp]                  FLOAT (53)     NULL,
    [SaleStamp]                      FLOAT (53)     NULL,
    [PurchaseLevy]                   FLOAT (53)     NULL,
    [SaleLevy]                       FLOAT (53)     NULL,
    [SettlementDaysBuy]              INT            NULL,
    [SettlementDaysSell]             INT            NULL,
    CONSTRAINT [PK__T_AUEC__0F624AF8] PRIMARY KEY CLUSTERED ([AUECID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK__T_AUEC__AssetID__151B244E] FOREIGN KEY ([AssetID]) REFERENCES [dbo].[T_Asset] ([AssetID]),
    CONSTRAINT [FK__T_AUEC__UnderLyi__160F4887] FOREIGN KEY ([UnderLyingID]) REFERENCES [dbo].[T_UnderLying] ([UnderLyingID])
);

