CREATE TABLE [dbo].[T_DA_AddOns](
	[AddOnId] [int] IDENTITY(1,1) NOT NULL,
	[SymbolsAUECIDs] [varchar](max) NULL,
	[SpecificSymbols] [varchar](max) NULL,
PRIMARY KEY CLUSTERED 
(
	[AddOnId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
