CREATE TABLE [dbo].[T_SMSymbolLookUpTable_temp] (
    [TickerSymbol]     VARCHAR (100)    NOT NULL,
    [AssetID]          INT              NULL,
    [UnderLyingID]     INT              NULL,
    [AUECID]           INT              NULL,
    [BloombergSymbol]  VARCHAR (100)    NULL,
    [ISINSymbol]       VARCHAR (20)     NULL,
    [SEDOLSymbol]      VARCHAR (20)     NULL,
    [CUSIPSymbol]      VARCHAR (20)     NULL,
    [OSISymbol]        VARCHAR (25)     CONSTRAINT [DF_T_SMSymbolLookUpTabletemp_OSISymbol] DEFAULT ('') NULL,
    [IDCOSymbol]       VARCHAR (25)     CONSTRAINT [DF_T_SMSymbolLookUpTabletemp_IDCOSymbol] DEFAULT ('') NULL,
    [OpraSymbol]       VARCHAR (20)     CONSTRAINT [DF_T_SMSymbolLookUpTabletemp_OpraSymbol] DEFAULT ('') NULL,
    [ExchangeID]       INT              NULL,
    [CountryID]        INT              NULL,
    [CreationDate]     DATETIME         NULL,
    [Symbol_PK]        BIGINT           NOT NULL,
    [Sector]           VARCHAR (20)     NULL,
    [UnderLyingSymbol] VARCHAR (20)     NULL,
    [ModifiedDate]     NCHAR (10)       NULL,
    [CurrencyID]       INT              NULL,
    [EffectiveDate]    DATETIME         NULL,
    [CorpActionID]     UNIQUEIDENTIFIER NULL,
    [DataSource]       INT              NULL,
    [RoundLot]         INT              DEFAULT ((1)) NOT NULL,
    CONSTRAINT [PK_T_SMSymbolLookUpTabletemp] PRIMARY KEY CLUSTERED ([Symbol_PK] ASC),
    CONSTRAINT [FK_T_SMSymbolLookUpTabletemp_T_Asset] FOREIGN KEY ([AssetID]) REFERENCES [dbo].[T_Asset] ([AssetID]),
    CONSTRAINT [FK_T_SMSymbolLookUpTabletemp_T_AUEC] FOREIGN KEY ([AUECID]) REFERENCES [dbo].[T_AUEC] ([AUECID]),
    CONSTRAINT [FK_T_SMSymbolLookUpTabletemp_T_Currency] FOREIGN KEY ([CurrencyID]) REFERENCES [dbo].[T_Currency] ([CurrencyID]),
    CONSTRAINT [FK_T_SMSymbolLookUpTabletemp_T_Exchange] FOREIGN KEY ([ExchangeID]) REFERENCES [dbo].[T_Exchange] ([ExchangeID]),
    CONSTRAINT [FK_T_SMSymbolLookUpTabletemp_T_UnderLying] FOREIGN KEY ([UnderLyingID]) REFERENCES [dbo].[T_UnderLying] ([UnderLyingID])
);

