using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Data;
using System.Text;
using System.Windows.Forms;
using Nirvana.Admin.PositionManagement.BusinessObjects;
using Nirvana.Admin.PositionManagement.Classes;
using Infragistics.Win.UltraWinGrid;


namespace Nirvana.Admin.PositionManagement.Controls
{
    public partial class CtrlRunUploadSetup : UserControl
    {

        private RunUploadSetUpSummary _runUploadSetUpSummaryData = new RunUploadSetUpSummary();

        private SortableSearchableList<RunUploadSetup> _runUploadData = new SortableSearchableList<RunUploadSetup>();

        //private RunUploadSetUpSummary RunUploadSetUpSummaryData
        //{
        //    get 
        //    {
        //        if (_runUploadSetUpSummaryData != null)
        //        {
        //            _runUploadSetUpSummaryData = new RunUploadSetUpSummary();
        //        }
        //        return _runUploadSetUpSummaryData; 
        //    }
        //    set { _runUploadSetUpSummaryData = value; }
        //}
        
	
        UltraGridBand _gridBandRunUploadSetUp = null;
	
	


        #region Grid Column Names

        const string COL_CompanyNameID = "CompanyNameID";
        const string COL_DataSourceNameID = "DataSourceNameID";
        const string COL_EnableAutoTime = "EnableAutoTime";
        const string COL_AutoTime = "AutoTime";
        const string COL_FTPServer = "FTPServer";
        const string COL_ServerPort = "ServerPort";
        const string COL_UserName = "UserName";
        const string COL_Password = "Password";
        const string COL_DirPath = "DirPath";
        const string COL_FileName = "FileName";

        #endregion Grid Column Names



        /// <summary>
        /// Initializes a new instance of the <see cref="CtrlRunUploadSetup"/> class.
        /// Contains InitializeComponent() method which is generated by the designer itself. 
        /// </summary>
        public CtrlRunUploadSetup()
        {
            InitializeComponent();
        }

        /// <summary>
        /// Handles the Load event of the CtrlRunUploadSetup control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void CtrlRunUploadSetup_Load(object sender, EventArgs e)
        {

        }

        /// <summary>
        /// Handles the Click event of the btnCancel control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void btnCancel_Click(object sender, EventArgs e)
        {

        }

        /// <summary>
        /// Handles the Click event of the btnRemove control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void btnRemove_Click(object sender, EventArgs e)
        {

        }

        /// <summary>
        /// Handles the Click event of the btnSave control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void btnSave_Click(object sender, EventArgs e)
        {
            //ToDo--- 
        }

        /// <summary>
        /// Handles the Click event of the btnEdit control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void btnEdit_Click(object sender, EventArgs e)
        {

        }

        /// <summary>
        /// Clears the control.
        /// </summary>
        public void ClearControl()
        {
            PopulateUploadSetUpDetails(0);
        }

        /// <summary>
        /// Populates the upload set up details.
        /// </summary>
        /// <param name="selectedTreeNodeID">The selected tree node ID.</param>
        public void PopulateUploadSetUpDetails(int uploadClientID)
        {
            _runUploadSetUpSummaryData = RunUploadManager.GetRunUploadSetUpDataForUploadClientID(uploadClientID);
            bindingSourceRunUploadSetUp.DataSource = _runUploadSetUpSummaryData;

             _runUploadData = _runUploadSetUpSummaryData.RunUploadSetUp;

             

            gridRunUploadSetUp.DataMember = "RunUploadSetUp";
            gridRunUploadSetUp.DataSource = _runUploadSetUpSummaryData;
            BindGridComboBoxes();

            foreach (RunUploadSetup runUploadSetUp in _runUploadData)
            {
                AddComboDataBindings(runUploadSetUp);
            }
            //lblDataSource.DataBindings.Add("Text", _formBindingSource, "DataSource");
            //RunUploadSetUpSummaryData.runUploadSetUP
            //gridRunUploadSetUp = "RunUploadSetUp";
            //gridRunUploadSetUp.DataSource = RunUploadSetUpSummaryData;
            //grdexception.datamember = "exceptionreportentrylist";
            //grdexception.datasource = _formbindingsource;

           // grdUnknown.DataMember = "UnknownRecordList";
           // grdUnknown.DataSource = _formBindingSource;
        }

        /// <summary>
        /// Adds the combo data bindings.
        /// </summary>
        /// <param name="runUploadSetUp">The run upload set up.</param>
        private void AddComboDataBindings(RunUploadSetup runUploadSetUp)
        {
            
            cmbDataSources.DataBindings.Clear();
            cmbDataSources.DataBindings.Add(new System.Windows.Forms.Binding("Text", runUploadSetUp, "DataSourceNameID.ShortName", true));

            cmbCompanies.DataBindings.Clear();
            cmbCompanies.DataBindings.Add(new System.Windows.Forms.Binding("Text", runUploadSetUp, "CompanyNameID.ShortName", true));


        }

        /// <summary>
        /// Binds the grid combo boxes.
        /// </summary>
        private void BindGridComboBoxes()
        {
            DataSourceNameIDList.GetInstance().SelectItemRequired = true;
            DataSourceNameIDList.GetInstance().IsAllDataSourceAvailable = false;
            cmbDataSources.DataSource = DataSourceNameIDList.GetInstance().Retrieve;
            cmbDataSources.DisplayMember = "ShortName";
            cmbDataSources.ValueMember = "ID";
            Utils.UltraDropDownFilter(cmbDataSources, "ShortName");
            
            
            cmbCompanies.DataSource = CompanyNameIDList.Retrieve();            
            cmbCompanies.DisplayMember = "ShortName";
            cmbCompanies.ValueMember = "ID";
            Utils.UltraDropDownFilter(cmbCompanies, "ShortName");

        }

        /// <summary>
        /// Handles the InitializeLayout event of the gridRunUploadSetUp control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="Infragistics.Win.UltraWinGrid.InitializeLayoutEventArgs"/> instance containing the event data.</param>
        private void gridRunUploadSetUp_InitializeLayout(object sender, InitializeLayoutEventArgs e)
        {
            gridRunUploadSetUp.DisplayLayout.AutoFitStyle = AutoFitStyle.ResizeAllColumns;
            gridRunUploadSetUp.DisplayLayout.ScrollBounds = ScrollBounds.ScrollToLastItem;
            gridRunUploadSetUp.DisplayLayout.Override.AllowAddNew = AllowAddNew.Yes;
            gridRunUploadSetUp.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            gridRunUploadSetUp.DisplayLayout.Override.AllowGroupBy = Infragistics.Win.DefaultableBoolean.False;
            gridRunUploadSetUp.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.True;
            gridRunUploadSetUp.DisplayLayout.Override.AllowColSwapping = AllowColSwapping.NotAllowed;
            gridRunUploadSetUp.DisplayLayout.Override.HeaderAppearance.TextHAlign = Infragistics.Win.HAlign.Center;


            _gridBandRunUploadSetUp = gridRunUploadSetUp.DisplayLayout.Bands[0];
            _gridBandRunUploadSetUp.Override.AllowColSwapping = AllowColSwapping.NotAllowed;


            UltraGridColumn colCompanyNameID = _gridBandRunUploadSetUp.Columns[COL_CompanyNameID];
            colCompanyNameID.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.DropDown;
            colCompanyNameID.ButtonDisplayStyle = ButtonDisplayStyle.Always;
            //Get the list of all companies.
            colCompanyNameID.ValueList = cmbCompanies;
            colCompanyNameID.Header.Caption = "Company";
            colCompanyNameID.Header.VisiblePosition = 1;

            UltraGridColumn colDataSourceNameID = _gridBandRunUploadSetUp.Columns[COL_DataSourceNameID];
            colDataSourceNameID.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.DropDown;
            colDataSourceNameID.ButtonDisplayStyle = ButtonDisplayStyle.Always;
            colDataSourceNameID.ValueList = cmbDataSources;
            colDataSourceNameID.Header.Caption = "Upload Source";
            colDataSourceNameID.Header.VisiblePosition = 2;

            UltraGridColumn colEnableAutoTime = _gridBandRunUploadSetUp.Columns[COL_EnableAutoTime];
            colEnableAutoTime.Header.Caption = "";            
            //colEnableAutoTime.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.CheckBox;
            
            colEnableAutoTime.Header.VisiblePosition = 3;

            UltraGridColumn colAutoTime = _gridBandRunUploadSetUp.Columns[COL_AutoTime];
            colAutoTime.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.TimeWithSpin;
            colAutoTime.Header.Caption = "Auto Time";
            colAutoTime.Header.VisiblePosition = 4;

            UltraGridColumn colFTPServer = _gridBandRunUploadSetUp.Columns[COL_FTPServer];
            colFTPServer.Header.Caption = "FTP Server";
            colFTPServer.Header.VisiblePosition = 5;

            UltraGridColumn colServerPort = _gridBandRunUploadSetUp.Columns[COL_ServerPort];
            colServerPort.Header.Caption = "Server Port";
            colServerPort.Header.VisiblePosition = 6;

            UltraGridColumn colUserName = _gridBandRunUploadSetUp.Columns[COL_UserName];
            colUserName.Header.Caption = "User Name";
            colUserName.Header.VisiblePosition = 7;

            UltraGridColumn colPassword = _gridBandRunUploadSetUp.Columns[COL_Password];
            colPassword.Header.Caption = "Password";
            colPassword.Header.VisiblePosition = 8;

            UltraGridColumn colDirPath = _gridBandRunUploadSetUp.Columns[COL_DirPath];
            colDirPath.Header.VisiblePosition = 9;
            colDirPath.Header.Caption = "Dir Path";

            UltraGridColumn colFileName = _gridBandRunUploadSetUp.Columns[COL_FileName];
            colFileName.Header.VisiblePosition = 10;
            colFileName.Header.Caption = "File Name";            
            

        }

        #region Dummy data
        //private ExceptionReportSummary RetrieveExceptionReportSummary(DataSourceNameID dataSource)
        //{
        //    ExceptionReportSummary summary = null;

        //    if (dataSource.ID == 1)
        //    {
        //        summary = RetrieveDataSourceId1(dataSource);
        //    }
        //    return summary;
        //}


        //private ExceptionReportSummary RetrieveDataSourceId1(DataSourceNameID dataSource)
        //{
        //    _exceptionReportSummary = new ExceptionReportSummary();
        //    _exceptionReportSummary.DataSource = dataSource;
        //    _exceptionReportSummary.ExceptionReportEntryList = RetrieveExceptionReportEntryList();
        //    _exceptionReportSummary.UnknownRecordList = RetrieveUnknownRecordList();

        //    return _exceptionReportSummary;
        //}

        //private BindingList<ExceptionReportEntry> RetrieveExceptionReportEntryList()
        //{
        //    BindingList<ExceptionReportEntry> exceptionReportEntryList = new BindingList<ExceptionReportEntry>();

        //    ExceptionReportEntry exceptionReportEntry = new ExceptionReportEntry();
        //    exceptionReportEntry.IsSelected = false;
        //    exceptionReportEntry.Symbol = "Dell";
        //    exceptionReportEntry.Fund = "Long";
        //    exceptionReportEntry.ColumnName = "Position";
        //    exceptionReportEntry.ApplicationData = "1000";
        //    exceptionReportEntry.SourceData = "1200";
        //    exceptionReportEntry.ManualEntry = "";
        //    exceptionReportEntry.Status = ReconStatus.Open;
        //    exceptionReportEntryList.Add(exceptionReportEntry);

        //    exceptionReportEntry = new ExceptionReportEntry();
        //    exceptionReportEntry.IsSelected = false;
        //    exceptionReportEntry.Symbol = "Msft";
        //    exceptionReportEntry.Fund = "Short";
        //    exceptionReportEntry.ColumnName = "Trade Date";
        //    exceptionReportEntry.ApplicationData = "1-Jan";
        //    exceptionReportEntry.SourceData = "2-Jan";
        //    exceptionReportEntry.ManualEntry = "";
        //    exceptionReportEntry.Status = ReconStatus.Closed;
        //    exceptionReportEntryList.Add(exceptionReportEntry);

        //    exceptionReportEntry = new ExceptionReportEntry();
        //    exceptionReportEntry.IsSelected = false;
        //    exceptionReportEntry.Symbol = "1.Hk";
        //    exceptionReportEntry.Fund = "Arb";
        //    exceptionReportEntry.ColumnName = "Average Price";
        //    exceptionReportEntry.ApplicationData = "122.55";
        //    exceptionReportEntry.SourceData = "122.58";
        //    exceptionReportEntry.ManualEntry = "";
        //    exceptionReportEntry.Status = ReconStatus.Closed;
        //    exceptionReportEntryList.Add(exceptionReportEntry);

        //    exceptionReportEntry = new ExceptionReportEntry();
        //    exceptionReportEntry.IsSelected = false;
        //    exceptionReportEntry.Symbol = "6501.TSE";
        //    exceptionReportEntry.Fund = "Arb";
        //    exceptionReportEntry.ColumnName = "Position";
        //    exceptionReportEntry.ApplicationData = "1000";
        //    exceptionReportEntry.SourceData = "1200";
        //    exceptionReportEntry.ManualEntry = "";
        //    exceptionReportEntry.Status = ReconStatus.Closed;
        //    exceptionReportEntryList.Add(exceptionReportEntry);

        //    return exceptionReportEntryList;
        //}

        //private BindingList<ExceptionReportEntry> RetrieveUnknownRecordList()
        //{
        //    BindingList<ExceptionReportEntry> exceptionReportEntryList = new BindingList<ExceptionReportEntry>();

        //    ExceptionReportEntry exceptionReportEntry = new ExceptionReportEntry();
        //    exceptionReportEntry.Symbol = "AABB";
        //    exceptionReportEntry.Fund = "Unknown";
        //    exceptionReportEntry.ColumnName = "Split";
        //    exceptionReportEntry.ApplicationData = "Unknown";
        //    exceptionReportEntry.SourceData = "200";

        //    exceptionReportEntryList.Add(exceptionReportEntry);
        //    return exceptionReportEntryList;
        //}


        #endregion

    }
}
