<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2007

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce 2007 Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/ThirdPartyFlatFileDetailCollection">
		<ThirdPartyFlatFileDetailCollection>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation">C:/UpdatedTP/Prana_Final.xsd</xsl:attribute>
			<xsl:for-each select="ThirdPartyFlatFileDetail">
				<ThirdPartyFlatFileDetail>

					<!--<GroupAllocationReq>
						<xsl:value-of select ="'true'"/>
					</GroupAllocationReq>-->
					<FileHeader>
						<xsl:value-of select ="'true'"/>
					</FileHeader>
					<FileFooter>
						<xsl:value-of select ="'true'"/>
					</FileFooter>
					<RowHeader>
						<xsl:value-of select ="'true'"/>
					</RowHeader>

					<TaxlotState>
						<xsl:value-of select ="TaxLotState"/>
					</TaxlotState>

					<TransactionID>
						<xsl:value-of select="''"/>
					</TransactionID>

					<!-- Side Starts-->

					<xsl:choose>
						<xsl:when test="Side='Buy'">
							<TransactionType>
								<xsl:value-of select="'B'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Buy to Open' ">
							<TransactionType>
								<xsl:value-of select="'BTO'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Buy to Cover'">
							<TransactionType>
								<xsl:value-of select="'BC'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Buy to Close' and Asset='Equity'">
							<TransactionType>
								<xsl:value-of select="'BC'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Buy to Close' and Asset='EquityOption'">
							<TransactionType>
								<xsl:value-of select="'BTC'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Sell'">
							<TransactionType>
								<xsl:value-of select="'S'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Sell to Open'">
							<TransactionType>
								<xsl:value-of select="'STO'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Sell to Close'">
							<TransactionType>
								<xsl:value-of select="'STC'"/>
							</TransactionType>
						</xsl:when>
						<xsl:when test="Side='Sell short'">
							<TransactionType>
								<xsl:value-of select="'SS'"/>
							</TransactionType>
						</xsl:when>
						<xsl:otherwise >
							<TransactionType>
								<xsl:value-of select="''"/>
							</TransactionType>
						</xsl:otherwise>
					</xsl:choose >					

					<Symbol>
						<xsl:value-of select="Symbol"/>
					</Symbol>

					<CUSIP>
						<xsl:value-of select="''"/>
					</CUSIP>

					<Quantity>
						<xsl:value-of select ="AllocatedQty"/>
					</Quantity>

					<xsl:choose>
						<xsl:when test ="CounterParty='BMCI'">
							<Broker>
								<xsl:value-of select="'YORKTON'"/>
							</Broker>
						</xsl:when>
						<xsl:when test ="CounterParty='Bofa'">
							<Broker>
								<xsl:value-of select="'BOFA'"/>
							</Broker>
						</xsl:when>
						<xsl:when test ="CounterParty='Cant'">
							<Broker>
								<xsl:value-of select="'CANTOR'"/>
							</Broker>
						</xsl:when>
						<xsl:otherwise >
							<Broker>
								<xsl:value-of select="CounterParty"/>
							</Broker>
						</xsl:otherwise>
					</xsl:choose >

					<Currency>
						<xsl:value-of select="CurrencySymbol"/>
					</Currency>

					<Currency2>
						<xsl:value-of select="''"/>
					</Currency2>

					<Price>
						<xsl:value-of select="AveragePrice"/>
					</Price>

					<AllocationAccount>
						<xsl:value-of select="FundAccountNo"/>
					</AllocationAccount>

					<xsl:variable name = "varTradeMth" >
						<xsl:value-of select="substring(TradeDate,1,2)"/>
					</xsl:variable>
					<xsl:variable name = "varTradeDay" >
						<xsl:value-of select="substring(TradeDate,4,2)"/>
					</xsl:variable>
					<xsl:variable name = "varTradeYR" >
						<xsl:value-of select="substring(TradeDate,7,4)"/>
					</xsl:variable>
					<TradeDate>
						<xsl:value-of select="concat($varTradeYR,'',$varTradeMth,'',$varTradeDay)"/>
					</TradeDate>

					<xsl:variable name = "varSettleMth" >
						<xsl:value-of select="substring(SettlementDate,1,2)"/>
					</xsl:variable>
					<xsl:variable name = "varSettleDay" >
						<xsl:value-of select="substring(SettlementDate,4,2)"/>
					</xsl:variable>
					<xsl:variable name = "varSettleYR" >
						<xsl:value-of select="substring(SettlementDate,7,4)"/>
					</xsl:variable>
					<SettleDate>
						<xsl:value-of select="concat($varSettleYR,'',$varSettleMth,'',$varSettleDay)"/>
					</SettleDate>

					<!-- Starts Asset Type -->
					<xsl:choose>
						<xsl:when test="Asset='Equity'">
							<security_type>
								<xsl:value-of select="'Stock'"/>
							</security_type>
						</xsl:when>
						<xsl:when test="Asset='EquityOption'">
							<security_type>
								<xsl:value-of select="'Option'"/>
							</security_type>
						</xsl:when>
						<xsl:when test="Asset='FX'">
							<security_type>
								<xsl:value-of select="'FX'"/>
							</security_type>
						</xsl:when>
						<xsl:otherwise >
							<security_type>
								<xsl:value-of select="''"/>
							</security_type>
						</xsl:otherwise>
					</xsl:choose>

					<Interest>
						<xsl:value-of select="0"/>
					</Interest>

					<Comment1>
						<xsl:value-of select ="''"/>
					</Comment1>

					<Comment2>
						<xsl:value-of select ="''"/>
					</Comment2>

					<CommissionType>
						<xsl:value-of select="'G'"/>
					</CommissionType>
					<Commission>
						<xsl:value-of select ="CommissionCharged + TaxOnCommissions + OtherBrokerFee + StampDuty + TransactionLevy + ClearingFee + MiscFees"/>
					</Commission>

					<NetAmount>
						<xsl:value-of select="NetAmount"/>
					</NetAmount>

					<Comment3>
						<xsl:value-of select ="''"/>
					</Comment3>
					
					<ALLOCQTY>
						<xsl:value-of select ="AllocatedQty"/>
					</ALLOCQTY>
					
					<EntityID>
						<xsl:value-of select="EntityID"/>
					</EntityID>

				</ThirdPartyFlatFileDetail>
			</xsl:for-each>
		</ThirdPartyFlatFileDetailCollection>
	</xsl:template>
</xsl:stylesheet>
