namespace Prana.ESignalAdapter
{
    /// <summary>
    /// Summary description for LastRecordType.
    /// </summary>
    public class LastRecordType
    {
        // defines for last record type
        public LastRecordType()
        {

        }

        /// <summary>
        ///  OSI symbology's first 6 bytes represents root symbol.
        /// </summary>
        public const short OSI_ROOT_LENGTH = 6;
        public const short TYPE_THELAST = 101;

        public const short LRT_STRIKE_QUALIFIER_NORMAL = 0;
        public const short LRT_STRIKE_QUALIFIER_DIFFERENCIAL = 1;
        public const short LRT_STRIKE_QUALIFIER_PERCENTAGE = 2;

        public const short LRT_EXERCISESTYLE_NONE = 0;
        public const short LRT_EXERCISESTYLE_AMERICAN = 1;
        public const short LRT_EXERCISESTYLE_EUROPEAN = 2;

        public const short LRT_UPDATERULE_NONE = 0;
        public const short LRT_UPDATERULE_IGNOREOPENSTATE = 1;
        //public  const short LRT_UPDATERULE_REQUIRED = &HFFF;
        //public  const short LRT_UPDATERULE_IGNOREALLSTATE = &HFFF + 1;

        // LRT_DEFINE_...relate to LRT_TYPE_TOPICFMT field - or values
        public const short LRT_DEFINE_FMTASCII = 1;
        public const short LRT_DEFINE_FMTBINARY = 2;
        public const short LRT_DEFINE_FMTLRT = 4;
        public const short LRT_DEFINE_FMTPARTIAL = 8;
        public const short LRT_DEFINE_FMTLRTFUTURE = 10;
        public const short LRT_DEFINE_FMTPULSE = 20;
        public const short LRT_DEFINE_FMTSHORT = 40;
        public const short LRT_DEFINE_FMTSHORT_STOCKOPTIONS = 80;
        public const short LRT_DEFINE_FMTREGIONALSEXT = 100;
        public const short LRT_DEFINE_FMTREGIONALSINT = 200;
        public const short LRT_DEFINE_FMTSHORT_FUT = 400;
        public const short LRT_DEFINE_FMTSHORT_DEL = 800;
        public const short LRT_DEFINE_FMTSOPTMONTAGE = 1000;
        public const short LRT_DEFINE_FMTLRTFUND = 2000;
        public const short LRT_DEFINE_FMTLRT2 = 4000;
        public const short LRT_DEFINE_FMTLRTINDICE = 8000;
        public const short LRT_DEFINE_FMTLRTFUTOPT = LRT_DEFINE_FMTLRTINDICE;
        public const short LRT_DEFINE_FMTCID = 10000;
        public const short LRT_DEFINE_MREC = 20000;

        public const short LRT_ACTION_INSERT = 1;
        public const short LRT_ACTION_DELETE = 2;
        public const short LRT_ACTION_REQUEST = 3;
        public const short LRT_ACTION_VISIBLE = 4;
        public const short LRT_ACTION_INVISIBLE = 5;
        public const short LRT_ACTION_OPEN = 6;
        public const short LRT_ACTION_CLOSE = 7;
        public const short LRT_ACTION_AMCLOSING = 8;
        public const short LRT_ACTION_STOCKOPTION_MONTH = 9;
        public const short LRT_ACTION_PASSTHRU = 10;
        public const short LRT_ACTION_DELIVERY = 11;
        public const short LRT_ACTION_TIMESYNC = 12;
        public const short LRT_ACTION_TIMEUNSYNC = 13;
        public const short LRT_ACTION_DELETEALLDATA_SYMBOL = 14;
        public const short LRT_ACTION_DELETEPRICEDATA_SYMBOL = 15;
        public const short LRT_ACTION_ADDAPPLICATION = 16;
        public const short LRT_ACTION_REMOVEAPPLICATION = 17;
        public const short LRT_ACTION_DELETE_1_USERAPPLICATION = 18;
        public const short LRT_ACTION_DELETE_ALL_USERAPPLICATION = 19;
        public const short LRT_ACTION_DISCONNECTALL = 20;
        public const short LRT_ACTION_USEOLDCM = 21;
        public const short LRT_ACTION_USEDLLCM = 22;
        public const short LRT_ACTION_FULLSERVER = 23;
        public const short LRT_ACTION_SAVEWDS = 24;
        public const short LRT_ACTION_BEACON_ENABLE = 25;
        public const short LRT_ACTION_BEACON_DISABLE = 26;
        public const short LRT_ACTION_SYMBOLDB_ENABLE = 27;
        public const short LRT_ACTION_SYMBOLDB_DISABLE = 28;
        public const short LRT_ACTION_DISALLOWVERSION = 29;
        public const short LRT_ACTION_SMMS_CREATE = 36;
        public const short LRT_ACTION_SMMS_DESTROY = 37;
        public const short LRT_ACTION_SMMS_START = 38;
        public const short LRT_ACTION_SMMS_STOP = 39;
        public const short LRT_ACTION_SMMS_FMTIL = 40;
        public const short LRT_ACTION_SMMS_FMTIF = 41;
        public const short LRT_ACTION_RELOAD_OCC = 42;
        public const short LRT_ACTION_MIDNIGHT_STOCK = 43;
        public const short LRT_ACTION_MIDNIGHT_STOCKREG = 44;
        public const short LRT_ACTION_RIP_CLEAR = 45;
        public const short LRT_ACTION_RIP_PURGEDAYS = 46;
        public const short LRT_ACTION_RIP_ENABLE = 47;
        public const short LRT_ACTION_RIP_DISABLE = 48;
        public const short LRT_ACTION_RIP_ADDSYMBOL = 49;
        public const short LRT_ACTION_RIP_DELSYMBOL = 50;
        public const short LRT_ACTION_OCC_FILTERMODE = 51;
        public const short LRT_ACTION_NOINVALIDBITS_ENABLE = 52;
        public const short LRT_ACTION_NOINVALIDBITS_DISABLE = 53;
        public const short LRT_ACTION_FAILOVERTO_TCP = 54; // ttp 3947	

        public const uint LRT_TYPE_END = 0; // end of lrt record
        public const uint LRT_TYPE_CATEGORY = 1; // (byte) basic parsing branch ie. CATETGORY_STOCK, CATEGORY_FUTURE, CATEGORY_INFO, etc
        public const uint LRT_TYPE_HEADLINE = 2; // (string)
        public const uint LRT_TYPE_FILENAME = 3; // (string)
        public const uint LRT_TYPE_SYMBOLS = 4; // (stringarray) groups of symbols related to record
        public const uint LRT_TYPE_CATEGORYS = 5; // (stringarray) groups of categorys (not category codes) related to record
        public const uint LRT_TYPE_ACODES = 6; // (stringarray) groups of authenticating codes
        public const uint LRT_TYPE_ACTION = 7; // (word) indicates type of action to be performed or is being performed
        public const uint LRT_TYPE_FILETYPE = 8; // (word) file identifer
        public const uint LRT_TYPE_STORYTIMEZONE = 9; // (string)
        public const uint LRT_TYPE_STORYSOURCE = 10; // (string)
        public const uint LRT_TYPE_STORYID = 11; // (string)
        public const uint LRT_TYPE_STORYSERVICE = 12; // (string)
        public const uint LRT_TYPE_KEY = 13; // (dword) indicates db key for recrod
        public const uint LRT_TYPE_DATETIMEDATA = 14; // (datetime) time stamp issued by feed (not in all records)
        public const uint LRT_TYPE_DATETIMEUPDATE = 15; // (datetime) time stamped by servers when data has changed in any way
        public const uint LRT_TYPE_DATETIMERT = 16; // (datetime) time stamped by servers when a real time event occurs such as rt trade/bid/ask
        public const uint LRT_TYPE_STATUS = 17; // (string) bit mapped status bytes for record (where rt flags, open flags, etc are delivered)
        public const uint LRT_TYPE_REMOTEFILENAME = 18; // (string)
        public const uint LRT_TYPE_LAST = 19; // (baselong)
        public const uint LRT_TYPE_BID = 20; // (baselong)
        public const uint LRT_TYPE_ASK = 21; // (baselong)
        public const uint LRT_TYPE_HIGH = 22; // (baselong)
        public const uint LRT_TYPE_LOW = 23; // (baselong)
        public const uint LRT_TYPE_OPEN = 24; // (baselong)
        public const uint LRT_TYPE_PREV = 25; // (baselong)
        public const uint LRT_TYPE_CHANGE = 26; // (baselong)
        public const uint LRT_TYPE_MIDPRICE = 27; // (baselong)
        public const uint LRT_TYPE_TRADESIZE = 28; // (long)
        public const uint LRT_TYPE_TOTALVOL = 29; // (long)
        public const uint LRT_TYPE_BIDSIZE = 30; // (long)
        public const uint LRT_TYPE_ASKSIZE = 31; // (long)
        public const uint LRT_TYPE_BIDEXG = 32; // (string)
        public const uint LRT_TYPE_ASKEXG = 33; // (string)
        public const uint LRT_TYPE_TRADEEXG = 34; // (string)
        public const uint LRT_TYPE_LISTEXG = 35; // (string)
        public const uint LRT_TYPE_BASE = 36; // (byte)   base code for converting baselone formats to doubles
        //public  const uint LRT_TYPE_DATERT	  =	 37
        //public  const uint LRT_TYPE_TIMERT	   =	38
        public const uint LRT_TYPE_TICKS = 39; // (long) number of real time trades for current day as calculated by server
        public const uint LRT_TYPE_UPDOWNTICKS = 40; // (string) updownticks for last 4 trades eg. +-+-
        //public  const uint LRT_TYPE_DATEUP	  =	 41
        //public  const uint LRT_TYPE_TIMEUP	   =	42
        public const uint LRT_TYPE_NEWSCOUNT = 43; // (long) not used
        public const uint LRT_TYPE_NEWSTIMEINMINUTES = 44; // (long) not used
        public const uint LRT_TYPE_NEWSDAY = 45; // (long) not used
        public const uint LRT_TYPE_HEADLINECOUNT = 46; // (long) headlines related to symbol
        public const uint LRT_TYPE_MINUTESDELAYED = 47; // (long) minutes delayed by customers authorization
        public const uint LRT_TYPE_SUBCATEGORY = 48; // (byte) further distinguishing value for categoryCodes. ie. 'F' and 'G' distinuguish forex and garvin from CATEGORY_FUTURE
        public const uint LRT_TYPE_TRADETYPE = 49; // (byte)
        public const uint LRT_TYPE_52WEEKHIGH = 50; // (baselong)
        public const uint LRT_TYPE_52WEEKLOW = 51; // (baselong)
        public const uint LRT_TYPE_EPS = 52; // (double)
        public const uint LRT_TYPE_DIVIDEND = 53; // (double)
        public const uint LRT_TYPE_XDIVDATE = 54; // (datetime)
        public const uint LRT_TYPE_DIVYIELD = 55; // (double)
        public const uint LRT_TYPE_DIVINTERVAL = 56; // (long)
        public const uint LRT_TYPE_PERATIO = 57; // (long)
        public const uint LRT_TYPE_COMPANY = 58; // (string) company name
        public const uint LRT_TYPE_TOPIC = 59; // (string) advise or request subject
        public const uint LRT_TYPE_TOPICFMT = 60; // (long)
        public const uint LRT_TYPE_TOPICFIELDS = 61; // not used
        public const uint LRT_TYPE_TOPICAFTERDATE = 62; // (datetime) qualifies topic for after this data/time
        public const uint LRT_TYPE_FILEPATH = 63; // (string)
        public const uint LRT_TYPE_URL = 64; // (string)
        public const uint LRT_TYPE_IDFUSERNAME = 65; // (string)
        public const uint LRT_TYPE_IDFPASSWORD = 66; // (string)
        public const uint LRT_TYPE_NEWSAUTHS = 67; // (stringarray) news authorizations for server
        public const uint LRT_TYPE_TICKAUTHS = 68; // (stringarray) tick authorizations for server
        public const uint LRT_TYPE_NEWSDAYS = 69; // (long) number of days for new app to save news
        public const uint LRT_TYPE_NEWSDATAPATH = 70; // (string) datapath for news app db
        public const uint LRT_TYPE_TICKDATAPATH = 71; // (string) datapath for tick app db
        public const uint LRT_TYPE_TICKSYMBOLS = 72; // (stringarray) symbols for tick app to monitor
        public const uint LRT_TYPE_FORUSERNAME = 73; // (stringarray) request,etc is for this username
        public const uint LRT_TYPE_TICKDAYS = 74; // (long) number of days for tick app to save ticks
        public const uint LRT_TYPE_STORYSOURCELIST = 75; // (stringarray) uint long source names for news storys
        public const uint LRT_TYPE_USERNAME = 76; // (string) generic username (authsrv)
        public const uint LRT_TYPE_PASSWORD = 77; // (string) generic password (authsrv)
        public const uint LRT_TYPE_ENTITLEMENTS1 = 78; // (string) entitlements string bits 0-79 (authsrv)
        public const uint LRT_TYPE_ENTITLEMENTS2 = 79; // (string) entitlements string bits 80-179 (authsrv)
        public const uint LRT_TYPE_EXENTITLEMENT = 80; // (string) extended entitlement (authsrv)
        public const uint LRT_TYPE_REALM = 81; // (string) authentication realm (authsrv)
        public const uint LRT_TYPE_RET = 82; // (long) indicating return value (see LRT_RET_??? above)
        public const uint LRT_TYPE_AUTHLEVEL = 83; // (long) Authorization Level (connection manager)
        public const uint LRT_TYPE_STORYTEXT = 84; // (string) Story text or body (connection manager)
        public const uint LRT_TYPE_PORT = 85; // (dword) TCP/IP Port (connection manager)
        public const uint LRT_TYPE_52HIGHDATE = 86; // (datetime) fundamental data (52 week high date -date/time-)
        public const uint LRT_TYPE_52LOWDATE = 87; // (datetime) fundamental data (52 week low date -date/time- )
        public const uint LRT_TYPE_SHARES = 88; // (long) fundamental data (shares outstanding -long-)
        public const uint LRT_TYPE_CONNCOUNT = 89; // (long) Connection count (connection manager)
        public const uint LRT_TYPE_OTHERAUTHS = 90; // (stringarray) misclaneous authorizations for server
        public const uint LRT_TYPE_HISTDAYS = 91; // (long) number of days for new app to save news
        public const uint LRT_TYPE_HISTDATAPATH = 92; // (string) datapath for news app db
        public const uint LRT_TYPE_HISTCDPATH = 93; // (string) datapath for news app db

        public const uint LRT_TYPE_MSGTYPE = 94; // (??)
        public const uint LRT_TYPE_KEYWORD = 95; // (??)
        public const uint LRT_TYPE_SEQUENCEID = 96; // (??)
        public const uint LRT_TYPE_NEWS_SEARCH_OPTION = 97; // (??)
        public const uint LRT_TYPE_STORYLOCATOR1 = 98; // (long) part of tandem story id's retrieved from headline to get story
        public const uint LRT_TYPE_STORYLOCATOR2 = 99; // (long) part of tandem story id's retrieved from headline to get story
        public const uint LRT_TYPE_TOKEN = 100; // (??)
        public const uint LRT_TYPE_TOKENTYPE = 101; // (??)
        public const uint LRT_TYPE_OPERATOR = 102; // (??)
        public const uint LRT_TYPE_HLNLIST_END = 103; // (??)

        public const uint LRT_TYPE_HISTAUTHS = 104; // (stringarray) authorizations for history app
        public const uint LRT_TYPE_IPADDRESS = 105; // (string) TCP/IP Address (Connection Manager)
        public const uint LRT_TYPE_CONNTIME = 106; // (datetime) Time Connection Was Started (Conneciton Manager)
        public const uint LRT_TYPE_REASON = 107; // (dword) Disconnect reason code (Connection Manager)
        // Use LRT_REASON_ codes
        public const uint LRT_TYPE_CPU_PERCENTAGE = 108; // (byte) CPU Usage (0 - 100)

        // some option and future field types
        public const uint LRT_TYPE_OPENINTEREST = 109; // (long)
        public const uint LRT_TYPE_COUPON = 110; // (long)
        public const uint LRT_TYPE_OPENRANGE = 111; // (baselong) first value of open range (maybe same as open)
        public const uint LRT_TYPE_OPENRANGE2 = 112; // (baselong) second value of open range
        public const uint LRT_TYPE_YIELD = 113; // (long)
        public const uint LRT_TYPE_TRADEYIELD = 114; // (long)
        public const uint LRT_TYPE_BIDYIELD = 115; // (long)
        public const uint LRT_TYPE_ASKYIELD = 116; // (long)

        public const uint LRT_TYPE_ROSBINRECORD = 114; // (blob)
        public const uint LRT_TYPE_ROSASCIIRECORD = 115; // (blob)
        public const uint LRT_TYPE_GENERALLONG = 116; // (blob)
        public const uint LRT_TYPE_OPTION_MONTHS = 117; // (stringarray)
        public const uint LRT_TYPE_PROGRAM_NAME = 118; // (string) Program name and version (Connection Manager)

        // OCC Options information
        public const uint LRT_TYPE_UNDERLYING = 119; // (string)
        public const uint LRT_TYPE_PORC = 120; // (byte)
        public const uint LRT_TYPE_ONNPRODUCT = 121; // (string)
        public const uint LRT_TYPE_EXPIRATIONDATE = 122; // (string) yyyymmdd
        public const uint LRT_TYPE_STRIKE = 123; // (double)
        public const uint LRT_TYPE_EXCHANGECODES = 124; // (string)
        public const uint LRT_TYPE_EXERCISESTYLE = 125; // (byte)
        public const uint LRT_TYPE_POSLIMIT = 126; // (long)
        public const uint LRT_TYPE_NEARTERMPOSLIMIT = 127; // (long)
        public const uint LRT_TYPE_ROOTINFO = 128; // (stringarray)
        public const uint LRT_TYPE_STRANGE = 129; // (long)
        public const uint LRT_TYPE_SENDERTRACE = 130; // (stringarray)
        public const uint LRT_TYPE_STOCKOPTION_SHORTSYMBOL = 131; // (string)

        public const uint LRT_TYPE_CUSIP = 132; // (string)
        public const uint LRT_TYPE_SKIPME = 133; // (long)
        public const uint LRT_TYPE_FORMT = 134; // (baselong)
        public const uint LRT_TYPE_MSTATUS = 135; // (long)
        public const uint LRT_TYPE_DELIVERY = 136; // (blob)
        public const uint LRT_TYPE_STORYRESPONSE = 137; // (blob)
        public const uint LRT_TYPE_STORYINPUT = 138; // (??)
        public const uint LRT_TYPE_TURNAROUND = 141; // (long)
        public const uint LRT_TYPE_BINHEADER = 142; // (blob)
        public const uint LRT_TYPE_MSG1 = 143; // (??)
        public const uint LRT_TYPE_MSG2 = 144; // (??)
        public const uint LRT_TYPE_DMHEADLINEINFO3 = 145; // (??)
        public const uint LRT_TYPE_INTERNATIONALLONG = 146; // (blob)
        public const uint LRT_TYPE_WRTYPE = 147; // (??)
        public const uint LRT_TYPE_DATETIMEPC = 148; // (datetime)
        public const uint LRT_TYPE_ENTITLEMENT_BYTES = 149; // (??)
        public const uint LRT_TYPE_ENTITLEMENT_WORDS = 150; // (??)
        public const uint LRT_TYPE_GAINERLONG = 151; // (blob)
        public const uint LRT_TYPE_MESSAGE = 152; // (blob)
        public const uint LRT_TYPE_FUNDLONG = 153; // (blob)
        public const uint LRT_TYPE_MATURITYDATE = 154; // (long)
        public const uint LRT_TYPE_CONTINUOUS = 155; // (string)
        public const uint LRT_TYPE_UPGRADE = 156; // (long)
        public const uint LRT_TYPE_RESTART = 157; // (long)
        public const uint LRT_TYPE_OASUPPORT = 158; // (double)
        public const uint LRT_TYPE_OAGRADE = 159; // (double)
        public const uint LRT_TYPE_HISTRELPE = 160; // (double)
        public const uint LRT_TYPE_EPSTRENDGR = 161; // (double)
        public const uint LRT_TYPE_SOES = 162; // (double)
        public const uint LRT_TYPE_PEI = 163; // (double)
        public const uint LRT_TYPE_PEIHIGH = 164; // (double)
        public const uint LRT_TYPE_PEILOW = 165; // (double)
        public const uint LRT_TYPE_REGIONALS_STOCK = 166; // (blob)
        public const uint LRT_TYPE_STRIKES_SOPT = 167; // (blob)
        public const uint LRT_TYPE_STRIKES_SNAP = 168; // (blob)
        public const uint LRT_TYPE_TDBINDICE = 169; // (blob)
        public const uint LRT_TYPE_ROSHEADER = 170; // (blob)
        public const uint LRT_TYPE_SHORTRECORD = 171; // (blob)
        public const uint LRT_TYPE_SHORT2RECORD = 172; // (blob)
        public const uint LRT_TYPE_TDBMUTUAL = 173; // (blob)
        public const uint LRT_TYPE_TDBMONEY = 174; // (blob)
        public const uint LRT_TYPE_TDBSTOCK = 175; // (blob)
        public const uint LRT_TYPE_TDBSTOCKPLUS = 176; // (blob)
        public const uint LRT_TYPE_TDBSTOCKREG = 177; // (blob)
        public const uint LRT_TYPE_TDBSTOCKMULTIPLE = 178; // (blob)
        public const uint LRT_TYPE_SIDE = 179; // (long)
        public const uint LRT_TYPE_TDBSOPT = 180; // (blob)
        public const uint LRT_TYPE_TDBSOPTROOT = 181; // (blob)
        public const uint LRT_TYPE_TDBSOPTPLUS = 182; // (??)
        public const uint LRT_TYPE_TDBSOPTMULTIPLE = 183; // (blob)
        public const uint LRT_TYPE_TDBSOPTREG = 184; // (blob)
        public const uint LRT_TYPE_USERAPPLICATIONNAME = 185; // (string)
        public const uint LRT_TYPE_TDBGAINER = 186; // (blob)
        public const uint LRT_TYPE_TDBFUTURE = 187; // (blob)
        public const uint LRT_TYPE_TDBFUTUREROOT = 188; // (blob)
        public const uint LRT_TYPE_TDBBOND = 189; // (blob)
        public const uint LRT_TYPE_TDBFX = 190; // (blob)
        public const uint LRT_TYPE_TDBFUTOPT = 191; // (blob)
        public const uint LRT_TYPE_TDBFUTOPTROOT = 192; // (blob)
        public const uint LRT_TYPE_CRSYMBOL = 193; // (blob)
        public const uint LRT_TYPE_AVERAGEVOLUME = 194; // (double)
        public const uint LRT_TYPE_BROADFILEN = 195; // (blob)
        public const uint LRT_TYPE_BROADFILEO = 196; // (blob)
        public const uint LRT_TYPE_BCFILENAME = 197; // (blob)
        public const uint LRT_TYPE_CURRENCYCODEASCII = 198; // (string)
        public const uint LRT_TYPE_CURRENCYUNIT = 199; // (long)
        public const uint LRT_TYPE_CURRENCYCODE = 200; // (long)
        public const uint LRT_TYPE_AUTHCODE = 201; // (long)
        public const uint LRT_TYPE_KASSAPRICE = 202; // (baselong)
        public const uint LRT_TYPE_DESCRIPTION = 203; // (string)
        public const uint LRT_TYPE_CLOSE = 204; // (baselong)
        public const uint LRT_TYPE_SOPTMONTAGE = 205; // (blob)
        public const uint LRT_TYPE_STRIKES_SOPTMONTAGE = 206; // (blob)
        public const uint LRT_TYPE_SOPTMONTAGE_SNAP = 207; // (blob)
        public const uint LRT_TYPE_STRIKES_SOPTMONTAGE_SNAP = 208; // (blob)
        public const uint LRT_TYPE_SEDOL = 209; // (string)
        public const uint LRT_TYPE_FTEX = 210; // (string)
        public const uint LRT_TYPE_ESYMBOL = 211; // (string)
        public const uint LRT_TYPE_ISIN = 212; // (string)
        public const uint LRT_TYPE_VALOREN = 213; // (string)
        public const uint LRT_TYPE_WKN = 214; // (string)
        public const uint LRT_TYPE_DATETIMETRADE = 215; // (datetime)
        public const uint LRT_TYPE_DATETIMEBID = 216; // (datetime)
        public const uint LRT_TYPE_DATETIMEASK = 217; // (datetime)
        public const uint LRT_TYPE_NOMATCH = 218; // (string)
        public const uint LRT_TYPE_BETA = 219; // (double) (stocks) (Beta, five year monthly)
        public const uint LRT_TYPE_TTMEBITD = 220; // (double) (stocks) (EBITD. trailing 12 months)
        public const uint LRT_TYPE_TTMDEPSCF = 221; // (double) (stocks) (Depreciation expense (SCF), trailing 12 months
        public const uint LRT_TYPE_DIVGR = 222; // (double) (stocks) (Growth rate%, dividend)
        public const uint LRT_TYPE_DIVGRYRS = 223; // (long) (stocks) (Growth rate# of years, dividend)
        public const uint LRT_TYPE_VOL10DAVG = 224; // (double) (stocks) (Volume, average trading volumne for last 10 days)
        public const uint LRT_TYPE_APRICE2BK = 225; // (double) (stocks) (Price to Book, last fiscal year)
        public const uint LRT_TYPE_TTMCFSHR = 226; // (double) (stocks) (Cash Flow per Share, Trailing 12 months)
        public const uint LRT_TYPE_ACURRATIO = 227; // (double) (stocks) (Current ratio, fiscal year end)
        public const uint LRT_TYPE_TTMROE = 228; // (double) (stocks) (Return on average common equity, trailing 12 months)
        public const uint LRT_TYPE_TTMROA = 229; // (double) (stocks) (Return on average common assets, trailing 12 months)
        public const uint LRT_TYPE_ALTD2EQ = 230; // (double) (stocks) (LT debt/equity, fiscal year end)
        public const uint LRT_TYPE_REVTRENDGR = 231; // (double) (stocks) (Revenue growth rate, 5 year)
        public const uint LRT_TYPE_DIVTRENDGR = 232; // (double) (stocks) (Dividend growth rate, 5 year)
        public const uint LRT_TYPE_IACGR = 233; // (double) (stocks) (Growth rate%, adjusted income available to common)
        public const uint LRT_TYPE_IACGRYRS = 234; // (long) (stocks) (Growth rate # of years, asj. Income avail to common)
        public const uint LRT_TYPE_APEPSINCXORZ = 235; // (double) (stocks) (EPS primary/basic in(cluding extraordinary items, latest fiscal year)
        public const uint LRT_TYPE_AREV = 236; // (double) (stocks) (Revenue - most recent fiscal year)
        public const uint LRT_TYPE_STATUSTYPE = 237; // (string) (stocks) (Internal)
        public const uint LRT_TYPE_DIVANN = 238; // (double) (stocks) (Indicated Annual dividend)
        public const uint LRT_TYPE_DIVPTC = 239; // (byte) (stocks) (Payment Type Code)
        public const uint LRT_TYPE_DIVPOSF = 240; // (byte) (stocks) (Payment Order Scaling factor)
        public const uint LRT_TYPE_DIV2AMT = 241; // (double) (stocks) (Dividend amount rate)
        public const uint LRT_TYPE_DIV2DATE = 242; // (datetime) (stocks) (Ex-distribution /dividend date )
        public const uint LRT_TYPE_DIV2PTC = 243; // (byte) (stocks) (Payment type code)
        public const uint LRT_TYPE_DIV2POSF = 244; // (byte) (stocks) (Payment Order Scaling factor)
        public const uint LRT_TYPE_DIV2FREQ = 245; // (long) (stocks) (??? not used ???)
        public const uint LRT_TYPE_ISSUENAME = 246; // (string) (stocks) (Issue description) (note:company name is issuername)
        public const uint LRT_TYPE_ISSUETYPE = 247; // (byte) (stocks) (Issue type code)
        public const uint LRT_TYPE_UNIQUENESS = 248; // (byte) (stocks) (Uniqueness code)
        public const uint LRT_TYPE_DATEUPDATED = 249; // (datetime) (stocks) (Fundamental data date updated)
        public const uint LRT_TYPE_CONTRACTHIGH = 250; // (double) (futures)
        public const uint LRT_TYPE_CONTRACTHIGHDATE = 251; // (datetime) (futures)
        public const uint LRT_TYPE_CONTRACTHIGHVOL = 252; // (double) (futures)
        public const uint LRT_TYPE_CONTRACTLOW = 253; // (double) (futures)
        public const uint LRT_TYPE_CONTRACTLOWDATE = 254; // (datetime) (futures)
        public const uint LRT_TYPE_CONTRACTLOWVOL = 255; // (double) (futures)
        public const uint LRT_TYPE_CACHEDMID = 256; // (string)
        public const uint LRT_TYPE_CACHEDMUSERID = 257; // (string)
        public const uint LRT_TYPE_CACHEDMSERVICES = 258; // (string) (ascii hex representations of service bits)
        public const uint LRT_TYPE_NAV = 259; // (baselong) (mutual funds)
        public const uint LRT_TYPE_OFFER = 260; // (baselong) (mutual funds)
        public const uint LRT_TYPE_DAY = 261; // (long) (mutual/money funds)
        public const uint LRT_TYPE_7DAYYIELD = 262; // (baselong) (money funds)
        public const uint LRT_TYPE_EFFECTIVEYIELD = 263; // (baselong) (money funds)
        public const uint LRT_TYPE_MATURITY = 264; // (baselong) (money funds)
        public const uint LRT_TYPE_ASSETS = 265; // (baselong) (money funds)
        public const uint LRT_TYPE_DOUBLEVOLUME = 266; // (double)
        public const uint LRT_TYPE_ACCVOL = LRT_TYPE_DOUBLEVOLUME;
        public const uint LRT_TYPE_VWAP = 267; // (double)
        public const uint LRT_TYPE_CLOSERANGE = 268; //(baselong) (fut/futopts)
        public const uint LRT_TYPE_CLOSERANGE2 = 269; //(baselong) (fut/futopts)
        public const uint LRT_TYPE_VOLUME_PRIOR = 270; //(double)   (fut/futopts)
        public const uint LRT_TYPE_TRADINGRANGE_HIGH = 271; //(baselong) (fut/futopts)
        public const uint LRT_TYPE_TRADINGRANGE_LOW = 272; //(baselong) (fut/futopts)
        public const uint LRT_TYPE_SETTLEMENT = 273; //(baselong) (fut/futopts)
        public const uint LRT_TYPE_DATE_EXPIRATION = 274;   //(long mmddyyyy) (fut/futopts)
        public const uint LRT_TYPE_DATE_FIRSTTRADINGDAY = 275; //(long mmddyyyy) (fut/futopts)
        public const uint LRT_TYPE_DATE_LASTTRADINGDAY = 276;  //(long mmddyyyy) (fut/futopts)
        public const uint LRT_TYPE_DATETIME_SETTLEMENT = 277; //(time_t) (fut/futopts)
        public const uint LRT_TYPE_DATETIME_OPENINTEREST = 278; //(time_t) (fut/futopts)
        public const uint LRT_TYPE_DATETIME_PRIORVOLUME = 279; //(time_t) (fut/futopts)
        public const uint LRT_TYPE_DATE_NOTICE = 280; //(long mmddyyyy) (fut/futopts)
        public const uint LRT_TYPE_DATETIME_TRADINGRANGE_HIGH = 281; //(time_t) (fut/futopts)
        public const uint LRT_TYPE_DATETIME_TRADINGRANGE_LOW = 282; //(time_t) (fut/futopts)
        public const uint LRT_TYPE_DATETIME_OPEN = 283; //(time_t) (fut/futopts)
        public const uint LRT_TYPE_DATETIME_OPEN2 = 284; //(time_t) (fut/futopts)
        public const uint LRT_TYPE_DATETIME_CLOSE = 285; //(time_t) (fut/futopts)
        public const uint LRT_TYPE_DATETIME_CLOSE2 = 286; //(time_t) (fut/futopts)
        public const uint LRT_TYPE_ROOTS_DESCRIPTIONS = 287; //(stringarray) (option info)
        public const uint LRT_TYPE_OPTION_NONSTANDARD_DESCRIPTION = 288; //(string) (option info)
        public const uint LRT_TYPE_CONTRACT_SIZE = 289; //(long)
        public const uint LRT_TYPE_DBCAPIRECORD = 290; //(blob)
        public const uint LRT_TYPE_TDBSOPTPLUSARRAY = 291; //(blob)
        public const uint LRT_TYPE_TDBSTOCKPLUSARRAY = 292; //(blob)
        public const uint LRT_TYPE_APIDELIVERY = 293; //(blob)
        public const uint LRT_TYPE_PIPE_ANONOMOUS_READHANDLE = 294; //(dword)
        public const uint LRT_TYPE_PIPE_NAME = 295; //(string)
        public const uint LRT_TYPE_PROCESS_ID = 296; //(dword)
        public const uint LRT_TYPE_SMMS_NAME = 297; //(string) (internal use)
        public const uint LRT_TYPE_SMMS_RECNUM = 298; //(long) (internal use)
        public const uint LRT_TYPE_USERCONNCOUNT = 299; //(dword) User connection count (connection manager)
        public const uint LRT_TYPE_FNLRT = 300; //(blob)
        public const uint LRT_TYPE_FNROSHEADER = 301; //(blob)
        public const uint LRT_TYPE_CID_ORIG_LAST = 302; //(baselong) original last price in case of cid ; //s
        public const uint LRT_TYPE_CID_ORIG_TRADESIZE = 303; //(unsigned long) see above for orig explanation
        public const uint LRT_TYPE_CID_ORIG_TRADEQUALIFIER = 304; //(string) see above for orig explanation
        public const uint LRT_TYPE_CID_ORIG_TRADETIME = 305; //(time_t) see above for orig explanation
        public const uint LRT_TYPE_CID_ORIG_BID = 306; //(baselong) original bid price in case of cid ; //s
        public const uint LRT_TYPE_CID_ORIG_BIDSIZE = 307; //(unsigned long) see above for orig explanation
        public const uint LRT_TYPE_CID_ORIG_BIDQUALIFIER = 308; //(string) see above for orig explanation
        public const uint LRT_TYPE_CID_ORIG_BIDTIME = 309; //(time_t) see above for orig explanation
        public const uint LRT_TYPE_CID_ORIG_ASK = 310; //(baselong) original ask price in case of cid ; //s
        public const uint LRT_TYPE_CID_ORIG_ASKSIZE = 311; //(unsigned long) see above for orig explanation
        public const uint LRT_TYPE_CID_ORIG_ASKQUALIFIER = 312; //(string) see above for orig explanation
        public const uint LRT_TYPE_CID_ORIG_ASKTIME = 313; //(time_t) see above for orig explanation

        public const uint LRT_TYPE_CID_CORR_LAST = 314; //(baselong) corrected last price in case of cid ; //s
        public const uint LRT_TYPE_CID_CORR_TRADESIZE = 315; //(unsigned long) see above for corrected  explanation
        public const uint LRT_TYPE_CID_CORR_TRADEQUALIFIER = 316; //(string) see above for corrected explanation
        public const uint LRT_TYPE_CID_CORR_TRADETIME = 317; //(time_t) see above for corrected explanation
        public const uint LRT_TYPE_CID_CORR_BID = 318; //(baselong) corrected bid price in case of cid ; //s
        public const uint LRT_TYPE_CID_CORR_BIDSIZE = 319; //(unsigned long) see above for corrected explanation
        public const uint LRT_TYPE_CID_CORR_BIDQUALIFIER = 320; //(string) see above for corrected explanation
        public const uint LRT_TYPE_CID_CORR_BIDTIME = 321; //(time_t) see above for corrected explanation
        public const uint LRT_TYPE_CID_CORR_ASK = 322; //(baselong) corrected ask price in case of cid ; //s
        public const uint LRT_TYPE_CID_CORR_ASKSIZE = 323; //(unsigned long) see above for corrected explanation
        public const uint LRT_TYPE_CID_CORR_ASKQUALIFIER = 324; //(string) see above for corrected explanation
        public const uint LRT_TYPE_CID_CORR_ASKTIME = 325; //(time_t) see above for corrected explanation
        public const uint LRT_TYPE_CID_SEQUENCE_NUMBER = 326; //sequence number to be deleted/revise or number of messge to be inserted before
        public const uint LRT_TYPE_FLOWRECORD = 327; //(blob)
        public const uint LRT_TYPE_DAILYCAPTURE_SIG = 328;
        public const uint LRT_TYPE_CLOSERANGE1 = 329;
        public const uint LRT_TYPE_CIDDATA_MRRT = 330; // Most recent CID data for this issue; includes security qualifiers

        public const uint LRT_TYPE_CIDR_LAST = 331; // cidfielddata
        public const uint LRT_TYPE_CIDR_BID = 332; // cidfielddata
        public const uint LRT_TYPE_CIDR_ASK = 333; // cidfielddata
        public const uint LRT_TYPE_CIDR_LAST_PAST = 334; // cidfielddata
        public const uint LRT_TYPE_CIDR_BID_PAST = 335; // cidfielddata
        public const uint LRT_TYPE_CIDR_ASK_PAST = 336; // cidfielddata
        public const uint LRT_TYPE_CIDR_CIDDATA = 337; // ciddata
        public const uint LRT_TYPE_CIDR_CIDDATA_PAST = 338; // ciddata
        public const uint LRT_TYPE_CIDR_TYPE = 339; // word
        public const uint LRT_TYPE_CIDR_FLAGS = 340; // dword

        public const uint LRT_TYPE_TDBCIDR = 341; // cidr db type
        public const uint LRT_TYPE_SHORTCIDRECORD = 342;

        public const uint LRT_TYPE_VOLUME_QUALIFIERS = 343; // blob (4 bytes)
        public const uint LRT_TYPE_OPENINTEREST_QUALIFIERS = 344; // blob (4 bytes)
        public const uint LRT_TYPE_SYMBOL = 345; // (string)
        public const uint LRT_TYPE_QUALIFIEDTRADE = 346; // cidfielddata or baselong
        public const uint LRT_TYPE_SESSION = 347; // (long)
        public const uint LRT_TYPE_DTE = 348; // (long) days to expiration (future options)
        public const uint LRT_TYPE_DTE_TD = 349; // (long) trading days to expiration (future options)
        public const uint LRT_TYPE_OPTION_FLAGS = 350; // (dword) flags such as use DTE or use DTD_TD, yield base..
        public const uint LRT_TYPE_FUND_FLAGS = 351; // (dword) fund flags
        public const uint LRT_TYPE_FUND_TYPE = 352; // (long) type of fund..
        public const uint LRT_TYPE_PCT_CHANGE = 353; // (baselong)
        public const uint LRT_TYPE_BASE_ALT = 354; // (byte) base code for pct change for gainers
        public const uint LRT_TYPE_NUMBER = 355; // (long) number of gainer in its position
        public const uint LRT_TYPE_SECURITY_STATUS = 356; // (for old lrt formats, if secstatus is wanted without converting to new lrt formats) = 4 bytes shifted into a dword
        public const uint LRT_TYPE_CASHENERGYCATEGORY = 357; // added for cash energy (platts)
        public const uint LRT_TYPE_CASHENERGYCATEGORYNAME = 358; // "    "
        public const uint LRT_TYPE_UNIT = 359; // "    "
        public const uint LRT_TYPE_FREQUENCY = 360; // "    "
        public const uint LRT_TYPE_STRIKE_QUALIFIER = 361; // strike price qualifier -- see lrt_strikez_qualifiera_ enums above      ; // byte, word or long
        public const uint LRT_TYPE_TRADE_1 = 362; // trade just before the current trade. (cidfield data, double or baselong)
        public const uint LRT_TYPE_TRADE_2 = 363; // trade just before trade_1 above (cidfield data, double or baselong)
        public const uint LRT_TYPE_TRADE_3 = 364; // trade just before trade_2 above (cidfield data, double or baselong)
        public const uint LRT_TYPE_BID_1 = 365; // bid just before the current bid. (cidfield data, double or baselong)
        public const uint LRT_TYPE_BID_2 = 366; // bid just before bid_1 above (cidfield data, double or baselong)
        public const uint LRT_TYPE_BID_3 = 367; // bid just before ask_2 above (cidfield data, double or baselong)
        public const uint LRT_TYPE_ASK_1 = 368; // ask just before the current ask. (cidfield data, double or baselong)
        public const uint LRT_TYPE_ASK_2 = 369; // ask just before ask_1 above (cidfield data, double or baselong)
        public const uint LRT_TYPE_ASK_3 = 370; // ask just before ask_2 above (cidfield data, double or baselong)
        public const uint LRT_TYPE_TRADE_1_TIME = 371; // time of trade just before the current trade. (time_t) utc
        public const uint LRT_TYPE_TRADE_2_TIME = 372; // time of trade just before trade_1 above (time_t) utc
        public const uint LRT_TYPE_TRADE_3_TIME = 373; // time of trade just before trade_2 above (time_t) utc
        public const uint LRT_TYPE_BID_1_TIME = 374; // time of bid just before the current bid. (time_t) utc
        public const uint LRT_TYPE_BID_2_TIME = 375; // time of bid just before bid_1 above (time_t) utc
        public const uint LRT_TYPE_BID_3_TIME = 376; // time of bid just before ask_2 above (time_t) utc
        public const uint LRT_TYPE_ASK_1_TIME = 377; // time of ask just before the current ask. (time_t) utc
        public const uint LRT_TYPE_ASK_2_TIME = 378; // time of ask just before ask_1 above (time_t) utc
        public const uint LRT_TYPE_ASK_3_TIME = 379; // time of ask just before ask_2 above (time_t) utc
        public const uint LRT_TYPE_FORWARD_MONTH = 380; // !n value for futures forward contracts
        public const uint LRT_TYPE_FORWARD_TIME = 381; // time_t of rollover for the forward month
        public const uint LRT_TYPE_TABLEID_ROOT = 382; // id/index into root table
        public const uint LRT_TYPE_TABLEID_ROLL = 383; // id/index into roll table
        public const uint LRT_TYPE_TABLEID_EXPIRE = 384; // id/index into expire table
        public const uint LRT_TYPE_TABLEID_HOLIDAY = 385; // id/index into holiday table
        public const uint LRT_TYPE_TABLEID_SESSION = 386; // id/index into session table
        public const uint LRT_TYPE_UPDATERULE = 387; // nonstandard transaction processing required
        public const uint LRT_TYPE_EXPIRATIONTIME = 388; // time_t (utc) to expire a contract, distinct from EXPIRATIONDATE which contains the date in exchange time.
        public const uint LRT_TYPE_SECURITYGROUP = 389; // // string, group sector
        public const uint LRT_TYPE_SPREAD_TYPE = 390; // string
        public const uint LRT_TYPE_LEGS_CNT = 391; // long/word/byte/dword number of spread legs
        public const uint LRT_TYPE_LEG_SYMBOL = 392; // leg symbol in spread
        public const uint LRT_TYPE_BUYSELL = 393; // indicator (byte) for spreads
        public const uint LRT_TYPE_DELIVERYDATE = 394; // yyyymmdd (if dd == 0 ), then day is unknown
        public const uint LRT_TYPE_TDBFORWARD = 395; // internal processing type
        public const uint LRT_TYPE_TDBSPREAD = 396; // internal processing type
        public const uint LRT_TYPE_DISPLAY_KEY = 397; // used for forwards to indicate symbol of forward for this particular future
        public const uint LRT_TYPE_FORWARD_CURRENT = 398; // for forward list; //s (debugging) (string)
        public const uint LRT_TYPE_FORWARD_PREVIOUS = 399; // for forward list; //s (debugging) (string)
        public const uint LRT_TYPE_MARKET_TIER = 400; // market tier... (string)
        public const uint LRT_TYPE_SPREAD_LEG_NUMBER = 401; // indicates which leg following data is for
        public const uint LRT_TYPE_SPREAD_LEG_LAST = 402; // last for a leg
        public const uint LRT_TYPE_SPREAD_LEG_BID = 403; // bid for a leg
        public const uint LRT_TYPE_SPREAD_LEG_ASK = 404; // ask for a leg
        public const uint LRT_TYPE_SPREAD_LEG_INSTRUMENT = 405; // instrument type for a leg..
        public const uint LRT_TYPE_TRADING_DAY_CURRENT = 406; // yyyymmdd
        public const uint LRT_TYPE_TRADING_DAY_NEXT = 407; // yyyymmdd
        public const uint LRT_TYPE_TRADING_DAY_ROLLTIME = 408; // time_t
        public const uint LRT_TYPE_SYMBOL_ALTERNATIVE = 409; // (internal) for fnet->rosServer processing
        public const uint LRT_TYPE_POINT_VALUE = 410; // long
        public const uint LRT_TYPE_MIN_MOVE = 411; // long
        public const uint LRT_TYPE_FRACTION_ID = 412; // string
        public const uint LRT_TYPE_SUFX = 413; // string (internal--2nd half of symbol for filtering)
        public const uint LRT_TYPE_GAMMA_EXP = 414; // byte, word, long
        public const uint LRT_TYPE_SYNTHETIC_SYMBOL = 415; // string
        public const uint LRT_TYPE_ESIGNAL_SYMBOL = 416; // string
        public const uint LRT_TYPE_FORMATTING_CODE = 417; // byte, word, long or dword
        public const uint LRT_TYPE_CID_BEACONTIME = 418; // dword of the time beacon.
        public const uint LRT_TYPE_BROADCAST_ADDRESS = 419; // address of dmclient for bdm to send data on ttp 3740
        public const uint LRT_TYPE_LIST_BUNDLE = 495; // stringarray
        public const uint LRT_TYPE_LISTCOUNT = 496; // long
        public const uint LRT_TYPE_OPTION_TYPE = 497; // string
        public const uint LRT_TYPE_SYMBOL_OSI = 506;               // string (-->JUX 100116C00027000)
        public const uint LRT_TYPE_SYMBOL_IDCO = 507;             // string (-->JUX 100116C00027000U)
        public const uint LRT_TYPE_TICKAUTHS_EXT = 1107;

        public const uint LRT_FMT_END = 0;
        public const uint LRT_FMT_BYTE = 1;
        public const uint LRT_FMT_CSTRING = 2;
        public const uint LRT_FMT_CSTRINGARRAY = 3; // for ocx users this will be a retrieved as a delimited string with | as delimiter
        public const uint LRT_FMT_WORD = 4;
        public const uint LRT_FMT_DWORD = 5;
        public const uint LRT_FMT_LONG = 6;
        public const uint LRT_FMT_DOUBLE = 7;
        public const uint LRT_FMT_BASELONG = 8;
        public const uint LRT_FMT_TIME = 9;
        public const uint LRT_FMT_BYTEARRAY = 10;
        // 11 and 12 are used by fnlrt; //s leave these unused here
        //public const short LRT_FMT_SFIELD_DOUBLE = 11; // double, with time_t and 4 qualifier bytes (values >= FLT_MAX or =< FLT_MIN use this as opposed to LRT_FMT_SFIELD_FLOAT)
        //public const short LRT_FMT_SFIELD_FLOAT = 12; // float, with time_t and 4 qualifier bytes
        public const uint LRT_FMT_UI64 = 13; // this is reserved in fnlrt so this will be ok as iit is.

        // NOTE: all new format defined in this file should start after = 64 (for compatibility with fnlrt formats)
        public const uint LRT_FMT_SFIELD_DOUBLE = 65; // double, with time_t and 4 qualifier bytes (values >= FLT_MAX or =< FLT_MIN use this as opposed to LRT_FMT_SFIELD_FLOAT)
        public const uint LRT_FMT_SFIELD_FLOAT = 66; // float, with time_t and 4 qualifier bytes
        public const uint LRT_FMT_CIDDATA = 67; // used for struct ciddata defined in cidbin.h
        public const uint LRT_FMT_CIDFIELDDATA = 68; // used for struct cidfielddata defined in cidbin.h
        public const uint LRT_FMT_CIDPRICEFIELDDATA = 69; // used for struct cidpricefielddata defined in cidbin.h

        public const short LRT_RET_OK = 0;
        public const short LRT_RET_UNKTYPE = -1;
        public const short LRT_RET_UNKFMT = -2;
        public const short LRT_RET_BADARG = -3;
        public const short LRT_RET_EXCEEDBUFFER = -4;
        public const short LRT_RET_OUTOFMEM = -5;
        public const short LRT_RET_BADDATA = -6;
        public const short LRT_RET_ENDOFDATA = -7;
        public const short LRT_RET_NOTTHERE = -8;        // username not authorized (hist apps)
        public const short LRT_RET_USERNAMENOTAUTH = -9;        // username authorized, but no password
        public const short LRT_RET_WRONGPASSWORD = -10;

        public const short LRT_REASON_NORMAL = 0; // Normal disconnect initiated by user.
        public const short LRT_REASON_ADMIN = 1; // Administrator caused disconnect.
        public const short LRT_REASON_TIMEOUT = 2; // Timeout, connection closed.
        public const short LRT_REASON_SOCKERROR = 3; // Socket error, connection closed.
        public const short LRT_REASON_SHUTDOWN = 4;// Server is shutting down, socket closed.

        // defines for LRT_TYPE_FILETYPE
        public const short STORY_FMT_TEXT = 1;
        public const short STORY_FMT_PCX = 2;
        public const short STORY_FMT_HTM = 3;
        public const short STORY_FMT_TAB = 4;
        public const short STORY_FMT_HEADLINE = 5;

        // define translations for cidshort/long/lrt formats to the lrt_type_... type codes
        // pd price codes..
        public const short CID_XPRICE_SETTLEMENT = 1;
        public const short CID_XPRICE_ROLLAST1 = 2;
        public const short CID_XPRICE_ROLLAST2 = 3;
        public const short CID_XPRICE_ROLLAST3 = 4;
        public const short CID_XPRICE_ROLBID1 = 5;
        public const short CID_XPRICE_ROLBID2 = 6;
        public const short CID_XPRICE_ROLBID3 = 7;
        public const short CID_XPRICE_ROLASK1 = 8;
        public const short CID_XPRICE_ROLASK2 = 9;
        public const short CID_XPRICE_ROLASK3 = 10;
        public const short CID_XPRICE_QUALIFIEDTRADE = 11;
        public const short CID_XPRICE_SPREAD_LEG_LAST = 12;
        public const short CID_XPRICE_SPREAD_LEG_BID = 13;
        public const short CID_XPRICE_SPREAD_LEG_ASK = 14;
        public const short CID_XPRICE_MAX = 15

        ; // po price codes...
        public const short CID_PRICE_SETTLEMENT = 1; // cidprice (base code can be applied)
        public const short CID_PRICE_HIGH_LIMIT = 2; // double
        public const short CID_PRICE_LOW_LIMIT = 3; // double
        public const short CID_PRICE_HIGH_52WEEK = 4; // double
        public const short CID_PRICE_LOW_52WEEK = 5; // double
        public const short CID_PRICE_CONTRACT_HIGH = 6; // double
        public const short CID_PRICE_CONTRACT_LOW = 7; // double
        public const short CID_PRICE_EARNINGS = 8;
        public const short CID_PRICE_PERATIO = 9;
        public const short CID_PRICE_DIVIDEND = 11;
        public const short CID_PRICE_YIELD = 12;
        public const short CID_PRICE_HISTRELPE = 13;
        public const short CID_PRICE_EPSTRENDGR = 14;
        public const short CID_PRICE_SOES = 15;
        public const short CID_PRICE_PEI = 16;
        public const short CID_PRICE_PEIHIGH = 17;
        public const short CID_PRICE_PEILOW = 18;
        public const short CID_PRICE_52WHIGH = 19;
        public const short CID_PRICE_52WLOW = 20;
        public const short CID_PRICE_BETA = 21;
        public const short CID_PRICE_TTMEBITD = 22;
        public const short CID_PRICE_TTMDEPSCF = 23;
        public const short CID_PRICE_DIVGR = 24;
        public const short CID_PRICE_VOL10DAVG = 25;
        public const short CID_PRICE_APRICE2BK = 26;
        public const short CID_PRICE_TTMCFSHR = 27;
        public const short CID_PRICE_ACURRATIO = 28;
        public const short CID_PRICE_TTMROE = 29;
        public const short CID_PRICE_TTMROA = 30;
        public const short CID_PRICE_REVTRENDGR = 31;
        public const short CID_PRICE_DIVTRENDGR = 32;
        public const short CID_PRICE_IACGR = 33;
        public const short CID_PRICE_APEPSINCXORZ = 34;
        public const short CID_PRICE_AREV = 35;
        public const short CID_PRICE_DIVANN = 36;
        public const short CID_PRICE_DIV2AMT = 37;
        public const short CID_PRICE_CHANGE = 38;
        public const short CID_PRICE_ASSETS = 39;
        public const short CID_PRICE_MATURITY = 40;
        public const short CID_PRICE_PCTCHANGE = 41;
        public const short CID_PRICE_DIVYIELD = 42;
        public const short CID_PRICE_ALTD2EQ = 43;
        public const short CID_PRICE_MAX = 44;

        // now do volumes .. includes time_t; //s (dword)  -- also include price fields that don; //t go with base code (doubles).
        public const short CID_VOL_PRIORVOL = 1; // qvol
        public const short CID_VOL_TOTALVOL = 2; // qvol
        public const short CID_VOL_OPENINTEREST = 3; // qvol
        public const short CID_VOL_DIVINT = 4;
        public const short CID_VOL_CONTRACT_HIGH_VOL = 5; // double
        public const short CID_VOL_HEADLINE_COUNT = 6; // long
        public const short CID_VOL_CONTRACT_LOW_VOL = 7; // double
        public const short CID_VOL_SESSION = 8; // int
        public const short CID_VOL_STRIKE = 9; // int
        public const short CID_VOL_AUTHCODE = 10; // int
        public const short CID_VOL_DATE_MATURITY = 11; // int yyyymmdd
        public const short CID_VOL_DATE_NOTICE = 12; // int yyyymmdd
        public const short CID_VOL_DATE_TRADE_FIRST = 13; // int yyyymmdd
        public const short CID_VOL_DATE_TRADE_LAST = 14; // int yyyymmdd
        public const short CID_VOL_DATE_EXPIRATION = 15; // int yyyymmdd
        public const short CID_VOL_DATE_OPENINTEREST = 16; // time_t
        public const short CID_VOL_DATE_VOLUME = 17; // time_t
        public const short CID_VOL_DATE_CONTRACT_HIGH = 18; // time_t
        public const short CID_VOL_DATE_CONTRACT_LOW = 19; // time_t
        public const short CID_VOL_DATE_HIGH_52WEEK = 20; // time_t
        public const short CID_VOL_DATE_LOW_52WEEK = 21; // time_t
        public const short CID_VOL_YIELD = 22; // int = 1/1000
        public const short CID_VOL_COUPON = 23; // int = 1/1000
        public const short CID_VOL_DATETIME_RT = 24; // time_t
        public const short CID_VOL_DATETIME_CHANGE = 25; // time_t
        public const short CID_VOL_DATETIME_DATA = 26; // time_t
        public const short CID_VOL_MSTATUS = 27; // dword
        public const short CID_VOL_TICKS = 28; // int
        public const short CID_VOL_MINUTESDELAYED = 29; // int
        public const short CID_VOL_XDIVDATE = 30;
        public const short CID_VOL_DATEUPDATED = 31;
        public const short CID_VOL_52WHIGHDATE = 32;
        public const short CID_VOL_52WLOWDATE = 33;
        public const short CID_VOL_SHARES = 34;
        public const short CID_VOL_AVEVOL = 35;
        public const short CID_VOL_DIVGYRS = 36;
        public const short CID_VOL_IACGRYRS = 37;
        public const short CID_VOL_DIV2DATE = 38;
        public const short CID_VOL_DIV2FREQ = 39;
        //public  const short CID_VOL_ALTD2EQ = 40;
        public const short CID_VOL_UNUSED = 40; // use this later
        public const short CID_VOL_CURRENCYCODE = 41;
        public const short CID_VOL_ORIG_CIDSEQUENCE = 42;
        public const short CID_VOL_CIDR_TYPE = 43;
        public const short CID_VOL_DATETIME_TRADE = 44;
        public const short CID_VOL_DATETIME_BID = 45;
        public const short CID_VOL_DATETIME_ASK = 46;
        public const short CID_VOL_DAY = 47;
        public const short CID_VOL_NUMBER = 48;
        public const short CID_VOL_FUNDFLAGS = 49;
        public const short CID_VOL_FUNDTYPE = 50;
        public const short CID_VOL_DATETIME_SETTLEMENT = 51;
        public const short CID_VOL_DTE = 52;
        public const short CID_VOL_DTE_TD = 53;
        public const short CID_VOL_XRSIZESTYLE = 54;
        public const short CID_VOL_STRIKEQUALIFIER = 55;
        public const short CID_VOL_OPTION_FLAGS = 56;
        public const short CID_VOL_FORWARD_MONTH = 57;
        public const short CID_VOL_FORWARD_TIME = 58;
        public const short CID_VOL_DELIVERY_DATE = 59;
        public const short CID_VOL_SPREAD_LEG_COUNT = 60;
        public const short CID_VOL_SPREAD_LEG_NUMBER = 61;
        public const short CID_VOL_TRADING_DAY_CURRENT = 62;
        public const short CID_VOL_TURNAROUND = 63;
        public const short CID_VOL_POINT_VALUE = 64;
        public const short CID_VOL_MIN_MOVE = 65;
        public const short CID_VOL_GAMMA_EXP = 66;
        public const short CID_VOL_FORMATTING_CODE = 67;
        public const short CID_VOL_MAX = 68;

        // now do byte arrays/bstr; //s included
        public const short CID_BYTES_CATCODESTATUS = 1; // 6Status,4upDownTick, Cat,SubCat (12 bytes)
        public const short CID_BYTES_MONTHYEARCODES = 2; // 2 bytes
        public const short CID_BYTES_LEXG = 3;
        public const short CID_BYTES_CUSIP = 4;
        public const short CID_BYTES_UNDERLYING = 5;
        public const short CID_BYTES_STATUSTYPE = 6; // 6 bytes
        public const short CID_BYTES_ISSUETYPE = 7; // 1 bytes
        public const short CID_BYTES_DIVPTC = 8; // 1 bytes
        public const short CID_BYTES_DIVPOSF = 9; // 1 bytes
        public const short CID_BYTES_UNIQUENESS = 10; // 1 bytes
        public const short CID_BYTES_REGIONALS = 11; // ? bytes
        public const short CID_BYTES_DESCRIPTION = 12; // ?
        public const short CID_BYTES_COMPANY = 13;
        public const short CID_BYTES_ISSUENAME = 14;
        public const short CID_BYTES_IEXG = 15;
        public const short CID_BYTES_CURRENCY = 16;
        public const short CID_BYTES_SYMBOL = 17;
        public const short CID_BYTES_DIV2PTC = 18; // 1 bytes
        public const short CID_BYTES_DIV2POSF = 19; // 1 bytes
        public const short CID_BYTES_BASE_ALT = 20; // 1 bytes
        public const short CID_BYTES_DISPLAY_KEY = 21; // string
        public const short CID_BYTES_SECURITYGROUP = 22; // string
        public const short CID_BYTES_SPREAD_TYPE = 23; // string
        public const short CID_BYTES_SPREAD_LEG_SYMBOL = 24; // string
        public const short CID_BYTES_SPREAD_LEG_TYPE = 25; // 1 bytes
        public const short CID_BYTES_SPREAD_LEG_BUYSELL = 26; // 1 bytes
        public const short CID_BYTES_MARKET_TIER = 27;
        public const short CID_BYTES_FRACTION_ID = 28; // string (8 bytes)
        public const short CID_BYTES_MAX = 29; //

        public const short CID_BYTES_CATCODESTATUS_LEN = 12;

        // flag definitions for LRT_TYPE_OPTION_FLAGS,
        //public  const short LRT_OPTIONFLAG_YIELDBASED = &H1     ; // option on treasuries
        //public  const short LRT_OPTIONFLAG_YIELDBASEDVALID = &H2;
        //public  const short LRT_OPTIONFLAG_USE_DTE_TD = &H4      ; // uses trading days to exp
        //public  const short LRT_OPTIONFLAG_DTETD_VALID = &H8;
        //public  const short LRT_OPTIONFLAG_PUT = &H40           ; // put/call z/nz
        //public  const short LRT_OPTIONFLAG_PUTVALID = &H80      ; // call contract
    }
}
