using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Prana.SAPIAdapter
{
    public class SAPIConstants
    {
        public const string Const_FXCrncy = "Currency";
        public const string Const_ForexAppendString = ".TF";
        public const string Const_Msg = "message";
        public const string Const_Put = "Put";
        public const string Const_Call = "Call";
        public const string Const_ReferenceDataRequest = "ReferenceDataRequest";
        public const string Const_RefData = "//blp/refdata";
        public const string Const_Mktdata = "//blp/mktdata";
        public const string Const_ApiAuth = "//blp/apiauth";
        public const string Const_RefreshInterval = "RefreshInterval";
        public const string Const_MinIntervalTime = "0.1";
        public const string Const_MaxIntervalTime = "86400";
        public const string Const_Options_Interval = "interval=";
        public const string Const_Securities = "securities";
        public const string Const_Fields = "fields";
        public const string Const_FieldStr = "OPT_MULTIPLIER,NAME,OPT_UNDL_TICKER,DVD_SH_12M,BC_ANNUALIZED_DIVIDEND_YIELD,PX_OPEN,ID_SEDOL1,EQY_RAW_BETA,DELTA,PX_EXCH_CODE_BID_ALL_SESSION,PX_EXCH_CODE_ASK_ALL_SESSION,LAST_DPS_GROSS,NET_CHANGE_ON_DAY_TODAY_RT,EQY_DVD_SH_12M_NET,LAST_TICK_DIRECTION_RT,LAST_DPS_GROSS,OPEN_INT,OPT_PUT_CALL,OPT_EXPIRE_DT,OPT_STRIKE_PX,FUT_CONT_SIZE,FUT_CONTRACT_DT,OCC_SYMBOL,BPIPE_REFERENCE_SECURITY_CLASS, TICKER,VWAP,ID_CUSIP,ID_ISIN,VOLUME_AVG_20D,VOLUME_AVG_10D,PX_LAST,VOLUME,PX_VOLUME,PX_BID,BID_SIZE_CR,CUR_MKT_CAP,PX_ASK,ASK_SIZE_CR,PX_HIGH,PX_LOW,HIGH_52WEEK,LOW_52WEEK,EQY_SH_OUT,COUNTRY_ISO,TIME,LAST_UPDATE,DVD_FREQ,DVD_EX_DT,CRNCY,PX_ROUND_LOT_SIZE,EQY_PRIM_EXCH_SHRT,MATURITY,MATURITY_RT,ISSUE_DT,CPN,COUPON_RT,DAY_CNT_DES,CPN_FREQ,MARKET_SECTOR_DES,REAL_FIRST_CPN_DT,EID,IS_DELAYED_STREAM,EXCHANGE_DELAY";
        public const string Const_ResponseError = "responseError";
        public const string Const_SecurityData = "securityData";
        public const string Const_Security = "security";
        public const string Const_SequenceNumber = "sequenceNumber";
        public const string Const_SecurityError = "securityError";
        public const string Const_OPEN_INTEREST = "OPEN_INT";
        public const string Const_RT_OPEN_INTEREST = "RT_OPEN_INTEREST";
        public const string Const_FieldData = "fieldData";
        public const string Const_TICKER = " TICKER";
        public const string Const_VWAP = "VWAP";
        public const string Const_ID_CUSIP = "ID_CUSIP";
        public const string Const_ID_CUSIP_RT = "CUSIP_NUMBER_REALTIME";
        public const string Const_ID_ISIN = "ID_ISIN";
        public const string Const_ID_ISIN_RT = "ISIN_REALTIME";
        public const string Const_VOLUME_AVG_10D = "VOLUME_AVG_10D";
        public const string Const_VOLUME_AVG_20D = "VOLUME_AVG_20D";
        public const string Const_VOLUME_AVG_10D_RT = "20_DAY_AVERAGE_VOLUME_AT_TIME_RT";
        public const string Const_VOLUME_AVG_20D_RT = "10_DAY_AVERAGE_VOLUME_AT_TIME_RT";
        public const string Const_LAST_PRICE = "PX_LAST";
        public const string Const_LAST_PRICE_RT = "LAST_PRICE";
        public const string Const_VOLUME = "PX_VOLUME";
        public const string Const_VOLUME_RT = "VOLUME";
        public const string Const_BID = "PX_BID";
        public const string Const_BID_RT = "BID";
        public const string Const_BID_SIZE = "BID_SIZE_CR";
        public const string Const_BID_SIZE_RT = "BID_SIZE";
        public const string Const_BID_EXCHANGE = "EXCH_CODE_BID";
        public const string Const_CUR_MKT_CAP = "CUR_MKT_CAP";
        public const string Const_ASK = "PX_ASK";
        public const string Const_ASK_RT = "ASK";
        public const string Const_ASK_SIZE = "ASK_SIZE_CR";
        public const string Const_ASK_SIZE_RT = "ASK_SIZE";
        public const string Const_ASK_EXCHANGE = "EXCH_CODE_ASK";
        public const string Const_HIGH = "PX_HIGH";
        public const string Const_LOW = "PX_LOW";
        public const string Const_HIGH_RT = "HIGH";
        public const string Const_LOW_RT = "LOW";
        public const string Const_HIGH_52WEEK = "HIGH_52WEEK";
        public const string Const_LOW_52WEEK = "LOW_52WEEK";
        public const string Const_HIGH_52WEEK_RT = "PRICE_52_WEEK_HIGH_RT";
        public const string Const_LOW_52WEEK_RT = "PRICE_52_WEEK_LOW_RT";
        public const string Const_CURRENT_SHARES_OUTSTANDING = "EQY_SH_OUT";
        public const string Const_CURRENT_SHARES_OUTSTANDING_RT = "CURRENT_SHARES_OUTSTANDING_RT";
        public const string Const_COUNTRY_ISO = "COUNTRY_ISO";
        public const string Const_PREV_CLOSE_VALUE = "PREV_CLOSE_VAL";
        public const string Const_PREV_CLOSE_VALUE_REALTIME = "PREV_CLOSE_VALUE_REALTIME";
        public const string Const_LAST_UPDATE = "LAST_UPDATE";
        public const string Const_TIME = "TIME";
        public const string Const_AssetClass = "BPIPE_REFERENCE_SECURITY_CLASS";
        public const string Const_OptionType = "OPT_PUT_CALL";
        public const string Const_StrikePrice = "OPT_STRIKE_PX";
        public const string Const_OpenInterest = "OPEN_INT";
        public const string Const_OpenInterest_RT = "RT_OPEN_INTEREST";
        public const string Const_ExpDate = "OPT_EXPIRE_DT";
        public const string Const_OptionType_RT = "PUT_CALL_INDICATOR_REALTIME";
        public const string Const_StrikePrice_RT = "STRIKE_PRICE_REALTIME";
        public const string Const_ExpDate_RT = "EXPIRATION_DATE_REALTIME";
        public const string Const_RoundLot = "PX_ROUND_LOT_SIZE";
        public const string Const_RoundLot_RT = "ROUND_LOT_SIZE_REALTIME";
        public const string Const_DividendGross = "LAST_DPS_GROSS";
        public const string Const_DividendExDate = "DVD_EX_DT";
        public const string Const_DividendType_RT = "DIVIDEND_TYPE_REALTIME";
        public const string Const_DividendGross_RT = "DPS_LAST_GROSS_REALTIME";
        public const string Const_DividendExDate_RT = "DIVIDEND_EX_DATE_REALTIME";
        public const string Const_LastTick = "LAST_TICK_DIRECTION";
        public const string Const_LastTick_RT = "LAST_TICK_DIRECTION_RT";
        public const string Const_Change = "NET_CHANGE_ON_DAY_TODAY_RT";
        public const string Const_BidExch = "PX_EXCH_CODE_BID_ALL_SESSION";
        public const string Const_AskExch = "PX_EXCH_CODE_ASK_ALL_SESSION";
        public const string Const_TotalVol = "PREVIOUS_TOTAL_VOLUME_RT";
        public static string Const_Beta = "EQY_RAW_BETA";
        public static string Const_Delta = "DELTA";
        public const string Const_Currency = "CRNCY";
        public const string Const_Currency_RT = "CURRENCY_RT";
        public const string Const_Sedol = "ID_SEDOL1";
        public const string Const_Open = "PX_OPEN";
        public const string Const_OSIOptSym = "OCC_SYMBOL";
        public const string Const_DivYield = "DIVIDEND_INDICATED_YIELD";
        public const string Const_DivYield_RT = "BC_ANNUALIZED_DIVIDEND_YIELD";
        public const string Const_AnnualDividend = "DVD_SH_12M";
        public const string Const_AnnualDividend_RT = "EQY_DVD_SH_12M_NET";
        public const string Const_Exch = "EQY_PRIM_EXCH_SHRT";
        public const string Const_Exch_RT = "PRIMARY_EXCHANGE_CODE_REALTIME";
        public const string Const_UnderlyingTicker = "OPT_UNDL_TICKER";
        public const string Const_UnderLyingTicker_RT = "UNDERLYING_TICKER_REALTIME";
        public const string Const_LastUpdateTime = "TIME";
        public const string Const_Country_RT = "COUNTRY_DOMICILE_REALTIME";
        public const string Const_CompanyName = "NAME";
        public const string Const_CompanyName_RT = "LONG_COMP_NAME";
        public const string Const_DivInterval = "DVD_FREQ";
        public const string Const_FutureContractSize = "FUT_CONT_SIZE";
        public const string Const_FutureContractExpDate = "FUT_CONTRACT_DT";
        public const string Const_Token = "token";
        public const string Const_Snapshot = "Snapshot";
        public const string Const_Subscription = "Subscription";
        public const string Const_Equity = "Equity";
        public const string Const_EquityOption = "EquityOption";
        public const string Const_Future = "Future";
        public const string Const_FutureOption = "FutureOption";
        public const string Const_FX = "FX";
        public const string Const_FXForward = "FXForward";
        public const string Const_FixedIncome = "FixedIncome";
        public const string Const_Index = " INDEX";
        public const string Const_Comdty = " COMDTY";
        public const string Const_Option = "Option";
        public const string Const_index = "Index";
        public const string Const_Curncy = " CURNCY";
        public const string Const_Comp_Code = "COMPOSITE_EXCH_CODE";
        public const string Const_AuthenticationOption = "AuthenticationMode=USER_AND_APPLICATION;AuthenticationType=MANUAL;ApplicationAuthenticationType=APPNAME_AND_KEY;ApplicationName=";
        public const string Const_MaturityDate = "MATURITY";
        public const string Const_MaturityDate_RT = "MATURITY_RT";
        public const string Const_IssueDate = "ISSUE_DT";
        public const string Const_IssueDate_RT = "ISSUE_DATE_REALTIME";
        public const string Const_AccuralBasis = "DAY_CNT_DES";
        public const string Const_CouponFrequency = "CPN_FREQ";
        public const string Const_Coupon = "CPN";
        public const string Const_Coupon_RT = "COUPON_RT";
        public const string Const_BondType = "MARKET_SECTOR_DES";
        public const string Const_FirstCouponDate = "REAL_FIRST_CPN_DT";
        public const string Fut_Expiration_Date = "FUT_CONTRACT_DT";
        public const string Fut_Multiplier = "FUT_CONT_SIZE";
        public const string Option_Multiplier = "OPT_MULTIPLIER";
        public const string Option_Multiplier_RT = "OPTION_MULTIPLIER_REALTIME";
        public const string Const_EID = "eidData";
        public const string Const_EidSubscription = "EID";
        public const string Const_IS_DELAYED_STREAM = "IS_DELAYED_STREAM";
        public const string Const_EXCHANGE_DELAY = "EXCHANGE_DELAY";

        #region Samsara SAPI constants
        public const string GRANT_TYPE = "grant_type";
        public const string CODE = "code";
        public const string CODE_VERIFIER = "code_verifier";
        public const string CLIENT_ID = "client_id";
        public const string REDIRECT_URI = "redirect_uri";
        public const string USER_ID = "userId";
        public const string SAMSARA = "Samsara";
        public const string CLIENT = "Client";
        #endregion
    }
}
