DELETE from T_PRANAUSERPREFS where FileName like '%backup%'
DELETE from T_PRANAUSERPREFS where FileName like '% - Copy%'
DELETE from T_PRANAUSERPREFS where FileName like '%.zip%'
DELETE from T_PRANAUSERPREFS where FileName like '%.rar%'
DELETE from T_PRANAUSERPREFS where FileName like '%_BeforeAc%'
DELETE from T_PRANAUSERPREFS where FileName like '%FundDashboard%'
DELETE from T_PRANAUSERPREFS where FileName like '%OpenBlotterGridLayout%'
DELETE from T_PRANAUSERPREFS where FileName like '%ClosedBlotterGridLayout%'
DELETE from T_PRANAUSERPREFS where FileName like '%AllBlotterGridLayout%'
DELETE from T_PRANAUSERPREFS where FileName like '%Blotter Preferences.dat%'
DELETE from T_PRANAUSERPREFS where FileName like '%old%'