UPDATE T_Country 
SET BloombergCountryCode = 
CASE WHEN CountryName = 'United States'
THEN 'US'
WHEN CountryName = 'HongKong'
THEN 'HK'
WHEN CountryName = 'Japan'
THEN 'JP'
WHEN CountryName = 'United Kingdom'
THEN 'GB'
WHEN CountryName = 'Singapore'
THEN 'SG'
WHEN CountryName = 'Norway'
THEN 'NO'
WHEN CountryName = 'Germany'
THEN 'DE'
WHEN CountryName = 'France'
THEN 'FR'
WHEN CountryName = 'Austria'
THEN 'AT'
WHEN CountryName = 'Belgium'
THEN 'BE'
WHEN CountryName = 'Brazil'
THEN 'BR'
WHEN CountryName = 'Denmark'
THEN 'DK'
WHEN CountryName = 'Finland'
THEN 'FI'
WHEN CountryName = 'Ireland'
THEN 'IE'
WHEN CountryName = 'Netherlands'
THEN 'NL'
WHEN CountryName = 'Portugal'
THEN 'PT'
WHEN CountryName = 'South Africa'
THEN 'ZA'
WHEN CountryName = 'Spain'
THEN 'ES'
WHEN CountryName = 'Switzerland'
THEN 'CH'
WHEN CountryName = 'Greece'
THEN 'GR'
WHEN CountryName = 'Italy'
THEN 'IT'
WHEN CountryName = 'Russia'
THEN 'RU'
WHEN CountryName = 'Sweden'
THEN 'SE'
WHEN CountryName = 'Australia'
THEN 'AU'
WHEN CountryName = 'China'
THEN 'CN'
WHEN CountryName = 'Korea'
THEN 'KR'
WHEN CountryName = 'Bangladesh'
THEN 'BD'
WHEN CountryName = 'Thailand'
THEN 'TH'
WHEN CountryName = 'Vietnam'
THEN 'VN'
WHEN CountryName = 'India'
THEN 'IN'
WHEN CountryName = 'Canada'
THEN 'CA'
WHEN CountryName = 'Taiwan'
THEN 'TW'
WHEN CountryName = 'Mexico'
THEN 'MX'
WHEN CountryName = 'United Arab Emirates'
THEN 'AE'
WHEN CountryName = 'Jordan'
THEN 'JO'
WHEN CountryName = 'Bahrain'
THEN 'BH'
WHEN CountryName = 'Croatia'
THEN 'HR'
WHEN CountryName = 'Poland'
THEN 'PL'
WHEN CountryName = 'New Zealand'
THEN 'NZ'
WHEN CountryName = 'Malaysia'
THEN 'MY'
WHEN CountryName = 'Turkey'
THEN 'TR'
WHEN CountryName = 'Hungary'
THEN 'HU'
WHEN CountryName = 'Saudi Arabia'
THEN 'SA'
WHEN CountryName = 'Tunisia'
THEN 'TN'
WHEN CountryName = 'Qatar'
THEN 'QA'
WHEN CountryName = 'Oman'
THEN 'OM'
WHEN CountryName = 'Nigeria'
THEN 'NG'
WHEN CountryName = 'Morocco'
THEN 'MA'
WHEN CountryName = 'Kuwait'
THEN 'KW'
WHEN CountryName = 'Kenya'
THEN 'KE'
WHEN CountryName = 'Israel'
THEN 'IL'
WHEN CountryName = 'Egypt'
THEN 'EG'
WHEN CountryName = 'SriLanka'
THEN 'LK'
WHEN CountryName = 'Cyprus'
THEN 'CY'
WHEN CountryName = 'Argentina'
THEN 'AR'
WHEN CountryName = 'Venezuela'
THEN 'VE'
WHEN CountryName = 'Peru'
THEN 'PE'
WHEN CountryName = 'Slovakia'
THEN 'SK'
WHEN CountryName = 'Colombia'
THEN 'CO'
WHEN CountryName = 'Chile'
THEN 'CL'
WHEN CountryName = 'Serbia'
THEN 'RS'
WHEN CountryName = 'Slovenia'
THEN 'SI'
WHEN CountryName = 'Romania'
THEN 'RO'
WHEN CountryName = 'Macedonia'
THEN 'MK'
WHEN CountryName = 'Czech Republic'
THEN 'CZ'
WHEN CountryName = 'Estonia'
THEN 'EE'
WHEN CountryName = 'Bulgaria'
THEN 'BG'
WHEN CountryName = 'Philippines'
THEN 'PH'
WHEN CountryName = 'Indonesia'
THEN 'ID'
ELSE 
BloombergCountryCode
END

