UPDATE T_AUECMapping SET BloombergCompositeCode='US', BloombergExchangeCode='UQ'  WHERE ExchangeIdentifier ='NASD-Equity' or ExchangeIdentifier ='NASD-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='US', BloombergExchangeCode='UN' WHERE ExchangeIdentifier ='NYSE-Equity' or ExchangeIdentifier ='NYSE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='JP', BloombergExchangeCode='JT' WHERE ExchangeIdentifier ='TSE-Equity' or ExchangeIdentifier ='TSE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='JP', BloombergExchangeCode='JT' WHERE ExchangeIdentifier ='OSE-Equity' or ExchangeIdentifier ='OSE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='PW' WHERE ExchangeIdentifier ='WSC-Equity' or ExchangeIdentifier ='WSC-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='SP' WHERE ExchangeIdentifier ='SES-Equity' or ExchangeIdentifier ='SES-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='NO' WHERE ExchangeIdentifier ='OSL-Equity' or ExchangeIdentifier ='OSL-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='GR', BloombergExchangeCode='GF' WHERE ExchangeIdentifier ='DBG-Equity' or ExchangeIdentifier ='DBG-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='LN' WHERE ExchangeIdentifier ='LON-Equity' or ExchangeIdentifier ='LON-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='FP' WHERE ExchangeIdentifier ='EEB-Equity' or ExchangeIdentifier ='EEB-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='AV' WHERE ExchangeIdentifier ='VIE-Equity' or ExchangeIdentifier ='VIE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='DC' WHERE ExchangeIdentifier ='CSE' or ExchangeIdentifier='CSE-Equity' or ExchangeIdentifier ='CSE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='FH' WHERE ExchangeIdentifier ='HEL-Equity' or ExchangeIdentifier ='HEL-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='SM' WHERE ExchangeIdentifier ='MAC-Equity' or ExchangeIdentifier ='MAC-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='GA' WHERE ExchangeIdentifier ='ATH-Equity' or ExchangeIdentifier ='ATH-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='TG' WHERE ExchangeIdentifier ='GTS-Equity' or ExchangeIdentifier ='GTS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='SS' WHERE ExchangeIdentifier ='OMX-Equity' or ExchangeIdentifier ='OMX-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='SJ' WHERE ExchangeIdentifier ='JSE-Equity'    or ExchangeIdentifier='JSE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='SW', BloombergExchangeCode='SE' WHERE ExchangeIdentifier ='SWS-Equity'	 or ExchangeIdentifier='SWS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CH', BloombergExchangeCode='CG' WHERE ExchangeIdentifier ='SHG-Equity'	 or ExchangeIdentifier='SHG-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='KS', BloombergExchangeCode='KP' WHERE ExchangeIdentifier ='KOR-Equity'	 or ExchangeIdentifier='KOR-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='VN', BloombergExchangeCode='VM' WHERE ExchangeIdentifier ='HCM-Equity'	 or ExchangeIdentifier='HCM-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='IN', BloombergExchangeCode='IS' WHERE ExchangeIdentifier ='NSE-Equity'	 or ExchangeIdentifier='NSE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='IN', BloombergExchangeCode='IB' WHERE ExchangeIdentifier ='BOM-Equity'	 or ExchangeIdentifier='BOM-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CH', BloombergExchangeCode='CS' WHERE ExchangeIdentifier ='SHE-Equity'	 or ExchangeIdentifier='SHE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CN', BloombergExchangeCode='CV' WHERE ExchangeIdentifier ='VC-Equity'	 or ExchangeIdentifier='VC-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='JP', BloombergExchangeCode='JT' WHERE ExchangeIdentifier ='NAG-Equity'	 or ExchangeIdentifier='NAG-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='TT' WHERE ExchangeIdentifier ='TAI-Equity'	 or ExchangeIdentifier='TAI-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='MM' WHERE ExchangeIdentifier ='MEX-Equity'	 or ExchangeIdentifier='MEX-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='IJ' WHERE ExchangeIdentifier ='JKT-Equity'	 or ExchangeIdentifier='JKT-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='PW' WHERE ExchangeIdentifier ='WAR-Equity'	 or ExchangeIdentifier='WAR-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='HK' WHERE ExchangeIdentifier ='HKG-Equity' or ExchangeIdentifier='HKG-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='LN' WHERE ExchangeIdentifier ='LON-Equity' or ExchangeIdentifier='LON-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='MK' WHERE ExchangeIdentifier ='KLS-Equity'	 or ExchangeIdentifier='KLS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CP', BloombergExchangeCode='CK' WHERE ExchangeIdentifier ='PRA-Equity'	 or ExchangeIdentifier='PRA-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CZ', BloombergExchangeCode='ZA' WHERE ExchangeIdentifier ='ZAG-Equity'	 or ExchangeIdentifier='ZAG-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='' WHERE ExchangeIdentifier ='LSEP-Equity'	 or ExchangeIdentifier='LSEP-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='SV' WHERE ExchangeIdentifier ='LJS-Equity'	 or ExchangeIdentifier='LJS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='LI' WHERE ExchangeIdentifier ='LSIN-Equity'	 or ExchangeIdentifier='LSIN-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='RM', BloombergExchangeCode='RX' WHERE ExchangeIdentifier ='MOS-Equity'	 or ExchangeIdentifier='MOS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CI', BloombergExchangeCode='CC' WHERE ExchangeIdentifier ='SGO-Equity'	 or ExchangeIdentifier='SGO-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='AB' WHERE ExchangeIdentifier ='SAU-Equity'	 or ExchangeIdentifier='SAU-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='PE' WHERE ExchangeIdentifier ='LIM-Equity'	 or ExchangeIdentifier='LIM-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='AR', BloombergExchangeCode='AF' WHERE ExchangeIdentifier ='BUE-Equity'	 or ExchangeIdentifier='BUE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='US', BloombergExchangeCode='UF' WHERE ExchangeIdentifier ='BATS-Equity' or ExchangeIdentifier='BATS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='RM', BloombergExchangeCode='RX' WHERE ExchangeIdentifier ='MOB-Equity'	 or ExchangeIdentifier='MOB-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='SM' WHERE ExchangeIdentifier ='MRE-Equity'	 or ExchangeIdentifier='MRE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='KS', BloombergExchangeCode='KQ' WHERE ExchangeIdentifier ='KOQ-Equity'	 or ExchangeIdentifier='KOQ-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='SL' WHERE ExchangeIdentifier ='COL-Equity'	 or ExchangeIdentifier='COL-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='' WHERE ExchangeIdentifier ='KOE-Equity'		 or ExchangeIdentifier='KOE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='UH', BloombergExchangeCode='DB' WHERE ExchangeIdentifier ='DFM-Equity'	 or ExchangeIdentifier='DFM-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='BI' WHERE ExchangeIdentifier ='BAH-Equity'	 or ExchangeIdentifier='BAH-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='VN', BloombergExchangeCode='VH' WHERE ExchangeIdentifier ='HNX-Equity'	 or ExchangeIdentifier='HNX-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='IT' WHERE ExchangeIdentifier ='TAE-Equity'	 or ExchangeIdentifier='TAE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='JR' WHERE ExchangeIdentifier ='AMM-Equity'	 or ExchangeIdentifier='AMM-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='KN' WHERE ExchangeIdentifier ='NAI-Equity'	 or ExchangeIdentifier='NAI-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='KK' WHERE ExchangeIdentifier ='KUW-Equity'	 or ExchangeIdentifier='KUW-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='MC' WHERE ExchangeIdentifier ='CAS-Equity'	 or ExchangeIdentifier='CAS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='NL' WHERE ExchangeIdentifier ='NSA-Equity'	 or ExchangeIdentifier='NSA-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='OM' WHERE ExchangeIdentifier ='MSM-Equity'	 or ExchangeIdentifier='MSM-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='QD' WHERE ExchangeIdentifier ='DSM-Equity'	 or ExchangeIdentifier='DSM-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='' WHERE ExchangeIdentifier ='BUL-Equity'		 or ExchangeIdentifier='BUL-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='RO', BloombergExchangeCode='RE' WHERE ExchangeIdentifier ='BUB-Equity'	 or ExchangeIdentifier='BUB-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='RM', BloombergExchangeCode='RX' WHERE ExchangeIdentifier ='MIS-Equity'	 or ExchangeIdentifier='MIS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CB', BloombergExchangeCode='CX' WHERE ExchangeIdentifier ='BUC-Equity'	 or ExchangeIdentifier='BUC-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='SW', BloombergExchangeCode='SE'  WHERE ExchangeIdentifier ='SWX-Equity' or ExchangeIdentifier='SWX-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='TI' WHERE ExchangeIdentifier ='IST-Equity'	 or ExchangeIdentifier='IST-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='' WHERE ExchangeIdentifier ='CAR-Equity'		 or ExchangeIdentifier='CAR-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='BZ', BloombergExchangeCode='BS' WHERE ExchangeIdentifier ='BSP-Equity'	 or ExchangeIdentifier='BSP-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='US', BloombergExchangeCode='' WHERE ExchangeIdentifier ='AMEX-Equity'	 or ExchangeIdentifier='AMEX-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='ID' WHERE ExchangeIdentifier ='DUB-Equity'	 or ExchangeIdentifier='DUB-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='' WHERE ExchangeIdentifier ='OT-Equity'		 or ExchangeIdentifier='OT-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='' WHERE ExchangeIdentifier ='XET-Equity'		 or ExchangeIdentifier='XET-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='LN' WHERE ExchangeIdentifier ='LON-Equity'	 or ExchangeIdentifier='LON-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='PM' WHERE ExchangeIdentifier ='PHS-Equity'	 or ExchangeIdentifier='PHS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='AV' WHERE ExchangeIdentifier ='VIE-Equity'	 or ExchangeIdentifier='VIE-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='US', BloombergExchangeCode='UP' WHERE ExchangeIdentifier ='ARCX-Equity' or ExchangeIdentifier='ARCX-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='SM' WHERE ExchangeIdentifier ='MAC-Equity'	 or ExchangeIdentifier='MAC-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='NZ' WHERE ExchangeIdentifier ='NZX-Equity'	 or ExchangeIdentifier='NZX-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='IM' WHERE ExchangeIdentifier ='MIL-Equity'	 or ExchangeIdentifier='MIL-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CN', BloombergExchangeCode='QF' WHERE ExchangeIdentifier ='QNL-Equity'	 or ExchangeIdentifier='QNL-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='AU', BloombergExchangeCode='AT' WHERE ExchangeIdentifier ='ASX-Equity'	 or ExchangeIdentifier='ASX-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='GR', BloombergExchangeCode='GS' WHERE ExchangeIdentifier ='STU-Equity'	 or ExchangeIdentifier='STU-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='US', BloombergExchangeCode='UV' WHERE ExchangeIdentifier ='OTC-Equity'	 or ExchangeIdentifier='OTC-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='TB' WHERE ExchangeIdentifier ='SET-Equity'	 or ExchangeIdentifier='SET-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CN', BloombergExchangeCode='CT' WHERE ExchangeIdentifier ='VC-Equity'	 or ExchangeIdentifier='VC-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='PW' WHERE ExchangeIdentifier ='WAR-Equity'	 or ExchangeIdentifier='WAR-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CZ', BloombergExchangeCode='ZA' WHERE ExchangeIdentifier ='ZAG-Equity'	 or ExchangeIdentifier='ZAG-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='HB' WHERE ExchangeIdentifier ='BUD-Equity'	 or ExchangeIdentifier='BUD-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='BB' WHERE ExchangeIdentifier ='BEL-Equity'	 or ExchangeIdentifier='BEL-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='CY' WHERE ExchangeIdentifier ='CYS-Equity'	 or ExchangeIdentifier='CYS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='GR', BloombergExchangeCode='GB' WHERE ExchangeIdentifier ='DBR-Equity'	 or ExchangeIdentifier='DBR-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='UH', BloombergExchangeCode='DU' WHERE ExchangeIdentifier ='ADX-Equity'	 or ExchangeIdentifier='ADX-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='UH', BloombergExchangeCode='DH' WHERE ExchangeIdentifier ='NQD-Equity'	 or ExchangeIdentifier='NQD-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='EY', BloombergExchangeCode='EC' WHERE ExchangeIdentifier ='EGX-Equity'	 or ExchangeIdentifier='EGX-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='US', BloombergExchangeCode='UQ' WHERE ExchangeIdentifier='OPTS-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CN', BloombergExchangeCode='CT' WHERE ExchangeIdentifier ='TC-Equity'	 or ExchangeIdentifier='TC-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='RO', BloombergExchangeCode='RE' WHERE ExchangeIdentifier ='BVB-Equity'	 or ExchangeIdentifier='BVB-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='SP' WHERE ExchangeIdentifier ='SESDAQ-Equity' or ExchangeIdentifier='SESDAQ-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='', BloombergExchangeCode='BB' WHERE ExchangeIdentifier ='BELs-Equity' or ExchangeIdentifier='BELs-EquityOption'
UPDATE T_AUECMapping SET BloombergCompositeCode='CB', BloombergExchangeCode='CX' WHERE ExchangeIdentifier ='BVC-Equity' or ExchangeIdentifier='BVC-EquityOption'