CREATE TABLE [dbo].[AlgoSyntheticReplaceOrders] (
    [ClOrderID]              VARCHAR (50)  NULL,
    [TransactionTime]        VARCHAR (50)  NULL,
    [DiscretionOffset]       FLOAT (53)    NULL,
    [ExecInst]               VARCHAR (50)  NULL,
    [HandlingInst]           CHAR (10)     NULL,
    [MsgType]                VARCHAR (50)  NULL,
    [OrderID]                VARCHAR (500)  NULL,
    [Side]                   CHAR (10)     NULL,
    [OrderStatus]            CHAR (10)     NULL,
    [OrderType]              CHAR (10)     NULL,
    [OrigClOrderID]          VARCHAR (50)  NULL,
    [PegDiff]                FLOAT (53)    NULL,
    [PNP]                    INT           NULL,
    [Price]                  FLOAT (53)    NULL,
    [Quantity]               FLOAT (53)    NULL,
    [StopPrice]              FLOAT (53)    NULL,
    [Symbol]                 VARCHAR (100) NULL,
    [TargetCompID]           VARCHAR (50)  NULL,
    [TargetSubID]            VARCHAR (50)  NULL,
    [TimeInForce]            CHAR (10)     NULL,
    [Venue]                  INT           NULL,
    [ParentClOrderID]        VARCHAR (50)  NULL,
    [LocateReqd]             BIT           NULL,
    [BorrowerID]             VARCHAR (50)  NULL,
    [ShortRebate]            FLOAT (53)    NULL,
    [TradingAccountID]       INT           NULL,
    [CompanyUserID]          INT           NULL,
    [CounterPartyID]         INT           NULL,
    [AuecID]                 INT           NULL,
    [StagedID]               VARCHAR (50)  NULL,
    [NirvanaMsgType]         INT           NULL,
    [OrderText]              VARCHAR (200) NULL,
    [StrategyID]             INT           NULL,
    [FundID]                 INT           NULL,
    [SecurityType]           VARCHAR (20)  NULL,
    [PutOrCall]              INT           NULL,
    [MaturityMonthYear]      VARCHAR (20)  NULL,
    [StrikePrice]            FLOAT (53)    NULL,
    [OpenClose]              CHAR (10)     NULL,
    [ParentClientOrderID]    VARCHAR (50)  NULL,
    [ClientOrderID]          VARCHAR (50)  NULL,
    [Cmta]                   VARCHAR (20)  NULL,
    [GiveUp]                 VARCHAR (20)  NULL,
    [UnderlyingSymbol]       VARCHAR (50)  NULL,
    [ExpirationDate]         DATETIME      NULL,
    [SettlementDate]         DATETIME      NULL,
    [AlgoStrategyID]         VARCHAR (10)  NULL,
    [AlgoStrategyParameters] VARCHAR (500) NULL,
    [InsertionTime]          VARCHAR (50)  NOT NULL,
    [AlgoSyntheticRPLParent] VARCHAR (50)  NULL
);

