CREATE TABLE [dbo].[PM_Company] (
    [PMCompanyID]               INT            IDENTITY (1, 1) NOT NULL,
    [NOMSCompanyID]             INT            NOT NULL,
    [Address1]                  NVARCHAR (100) NULL,
    [Address2]                  NVARCHAR (100) NULL,
    [CountryID]                 INT            NULL,
    [StateID]                   INT            NULL,
    [ZipNumber]                 NVARCHAR (50)  NULL,
    [WorkNumber]                NVARCHAR (50)  NULL,
    [FaxNumber]                 NVARCHAR (50)  NULL,
    [NofUserLicenses]           INT            CONSTRAINT [DF_PM_Company_NofUserLicenses] DEFAULT ((1)) NULL,
    [AdminContactFirstName]     NVARCHAR (50)  NULL,
    [AdminContactLastName]      NVARCHAR (50)  NULL,
    [AdminContactTitle]         NVARCHAR (100) NULL,
    [AdminContactUserID]        INT            NULL,
    [AdminUserName]             NVARCHAR (50)  NULL,
    [AdminPassword]             NVARCHAR (50)  NULL,
    [AdminContactEmail]         NVARCHAR (100) NULL,
    [AdminContactWorkPhone]     NVARCHAR (50)  NULL,
    [AdminContactCellPhone]     NVARCHAR (50)  NULL,
    [AdminContactPagerNumber]   NVARCHAR (50)  NULL,
    [AdminContactHomeNumber]    NVARCHAR (50)  NULL,
    [AdminContactFaxNumber]     NVARCHAR (50)  NULL,
    [MinimumRefreshRateSeconds] INT            CONSTRAINT [DF_PM_Company_MinimumRefreshRate] DEFAULT ((5)) NULL,
    [AllowDailyImport]          BIT            CONSTRAINT [DF_PM_Company_AllowdailyImport] DEFAULT ((0)) NULL,
    [RiskModelID]               INT            NULL,
    [IsActive]                  BIT            CONSTRAINT [DF_PM_Company_IsActive] DEFAULT ((1)) NULL,
    CONSTRAINT [PK_PM_Company] PRIMARY KEY CLUSTERED ([PMCompanyID] ASC),
    CONSTRAINT [FK_PM_Company_PM_RiskModels] FOREIGN KEY ([RiskModelID]) REFERENCES [dbo].[PM_RiskModels] ([RiskModelID]),
    CONSTRAINT [FK_PM_Company_T_Company1] FOREIGN KEY ([NOMSCompanyID]) REFERENCES [dbo].[T_Company] ([CompanyID]),
    CONSTRAINT [FK_PM_Company_T_User] FOREIGN KEY ([AdminContactUserID]) REFERENCES [dbo].[T_CompanyUser] ([UserID])
);

