CREATE TABLE [dbo].[PM_PositionMaster] (
    [AssetID]                    INT           NOT NULL,
    [CallPut]                    INT           NOT NULL,
    [Multiplier]                 FLOAT (53)    NOT NULL,
    [NetPosition]                INT           NOT NULL,
    [SecFees]                    INT           NOT NULL,
    [StartQuantity]              INT           NOT NULL,
    [TaxLotID]                   INT           NOT NULL,
    [UnderlyingID]               INT           NOT NULL,
    [Commission]                 FLOAT (53)    NOT NULL,
    [CostBasis]                  FLOAT (53)    NOT NULL,
    [Fees]                       FLOAT (53)    NOT NULL,
    [StrikePrice]                FLOAT (53)    NOT NULL,
    [CreatedByID]                VARCHAR (100) NOT NULL,
    [CUSIP]                      VARCHAR (100) NOT NULL,
    [DerivativeRootSymbol]       VARCHAR (100) NOT NULL,
    [DerivativeUnderlyingSymbol] VARCHAR (100) NOT NULL,
    [FundID]                     INT           NULL,
    [FundName]                   VARCHAR (100) NOT NULL,
    [PositionType]               VARCHAR (100) NOT NULL,
    [Symbol]                     VARCHAR (100) NOT NULL,
    [ExpirationDate]             VARCHAR (100) NOT NULL,
    [PositionStartDate]          VARCHAR (100) NOT NULL,
    [UploadID]                   INT           CONSTRAINT [DF__PM_Positi__Uploa__298DC7FD] DEFAULT ((0)) NOT NULL,
    [AUECID]                     INT           NOT NULL,
    [ExchangeID]                 INT           NOT NULL,
    [SideTagValue]               VARCHAR (10)  NOT NULL,
    [CurrencyID]                 INT           NOT NULL,
    [VenueID]                    INT           NOT NULL,
    [CounterPartyID]             INT           NOT NULL,
    [TradingAccountID]           INT           NOT NULL,
    [UserID]                     INT           NOT NULL,
    [CompanyID]                  INT           NOT NULL,
    [TimeOfSave]                 DATETIME      NOT NULL,
    [StrategyID]                 INT           NULL,
    [StateIDForStrategy]         INT           NOT NULL,
    [Strategy]                   VARCHAR (50)  NULL
);

