CREATE TABLE [dbo].[PM_ReconciledTrades] (
    [ReconciledTradeID]     INT            NOT NULL,
    [ReconID]               INT            NOT NULL,
    [PMCompanyID]           INT            NOT NULL,
    [ThirdPartyID]          INT            NOT NULL,
    [CompanyFundID]         INT            NOT NULL,
    [SymbolID]              INT            NOT NULL,
    [AssetClassID]          INT            NOT NULL,
    [CurrencyID]            INT            NOT NULL,
    [CounterPartyVenueID]   INT            NOT NULL,
    [TradeID]               VARCHAR (50)   NULL,
    [SideID]                INT            NOT NULL,
    [TradeDate]             DATETIME       NOT NULL,
    [Position]              INT            CONSTRAINT [DF_PM_ReconciledTrades_StartOfDayQty] DEFAULT ((0)) NOT NULL,
    [AverageExecutionPrice] FLOAT (53)     NOT NULL,
    [ReconcileStatus]       BIT            NOT NULL,
    [SecurityCode]          NVARCHAR (100) NOT NULL,
    [SettlementDate]        DATETIME       NULL,
    [UnderlyingID]          INT            NULL,
    [ExchangeID]            INT            NULL,
    [ExternalFund]          NVARCHAR (100) NULL,
    [Strategy]              NVARCHAR (100) NULL,
    [CostBasis]             FLOAT (53)     NULL,
    [DayStartPositions]     INT            NOT NULL,
    [Multiplier]            FLOAT (53)     NULL,
    [Sector]                NVARCHAR (100) NULL,
    [UserMark]              FLOAT (53)     NULL,
    [ExecutedQuantity]      INT            NULL,
    [CUSIP]                 NVARCHAR (100) NULL,
    [ISIN]                  NVARCHAR (100) NULL,
    [Sedol]                 NVARCHAR (100) NULL,
    [RIC]                   NVARCHAR (100) NULL,
    [BloombergCode]         NVARCHAR (100) NULL,
    [OpenTradeCode]         INT            NOT NULL,
    [ClosedStatus]          INT            NOT NULL,
    CONSTRAINT [PK_PM_ReconciledTrades] PRIMARY KEY CLUSTERED ([ReconciledTradeID] ASC),
    CONSTRAINT [FK__PM_Reconc__SideI__34AA74EE] FOREIGN KEY ([SideID]) REFERENCES [dbo].[T_Side] ([SideID]),
    CONSTRAINT [FK_PM_ReconciledTrades_PM_Company] FOREIGN KEY ([PMCompanyID]) REFERENCES [dbo].[PM_Company] ([PMCompanyID]),
    CONSTRAINT [FK_PM_ReconciledTrades_PM_CompanyRecon] FOREIGN KEY ([ReconID]) REFERENCES [dbo].[PM_CompanyRecon] ([ReconID]),
    CONSTRAINT [FK_PM_ReconciledTrades_T_Asset] FOREIGN KEY ([AssetClassID]) REFERENCES [dbo].[T_Asset] ([AssetID]),
    CONSTRAINT [FK_PM_ReconciledTrades_T_CompanyFunds] FOREIGN KEY ([CompanyFundID]) REFERENCES [dbo].[T_CompanyFunds] ([CompanyFundID]),
    CONSTRAINT [FK_PM_ReconciledTrades_T_CounterPartyVenue] FOREIGN KEY ([CounterPartyVenueID]) REFERENCES [dbo].[T_CounterPartyVenue] ([CounterPartyVenueID]),
    CONSTRAINT [FK_PM_ReconciledTrades_T_Currency] FOREIGN KEY ([CurrencyID]) REFERENCES [dbo].[T_Currency] ([CurrencyID]),
    CONSTRAINT [FK_PM_ReconciledTrades_T_Symbol] FOREIGN KEY ([SymbolID]) REFERENCES [dbo].[T_Symbol] ([SymbolID]),
    CONSTRAINT [FK_PM_Reconciledtrades_T_ThirdParty] FOREIGN KEY ([ThirdPartyID]) REFERENCES [dbo].[T_ThirdParty] ([ThirdPartyID]),
    CONSTRAINT [FK_PM_ReconciledTrades_T_UnderLying] FOREIGN KEY ([UnderlyingID]) REFERENCES [dbo].[T_UnderLying] ([UnderLyingID])
);

