CREATE TABLE [dbo].[PM_Taxlots_DeletedAudit] (
    [TaxLotID]                     VARCHAR (50)     NOT NULL,
    [Symbol]                       VARCHAR (100)    NOT NULL,
    [TaxLotOpenQty]                FLOAT (53)       NOT NULL,
    [AvgPrice]                     FLOAT (53)       NOT NULL,
    [TimeOfSaveUTC]                DATETIME         NULL,
    [GroupID]                      NVARCHAR (50)    NULL,
    [AUECModifiedDate]             DATETIME         NOT NULL,
    [FundID]                       INT              NULL,
    [Level2ID]                     INT              NULL,
    [OpenTotalCommissionandFees]   FLOAT (53)       NULL,
    [ClosedTotalCommissionandFees] FLOAT (53)       NULL,
    [PositionTag]                  INT              NULL,
    [OrderSideTagValue]            NCHAR (10)       NULL,
    [TaxLotClosingId]              UNIQUEIDENTIFIER NULL,
    [ParentRow_Pk]                 BIGINT           NULL,
    [AccruedInterest]              FLOAT (53)       CONSTRAINT [DF_PM_Taxlots_DeletedAudit_AccruedInterest] DEFAULT ((0)) NULL,
    [FXRate]                       FLOAT (53)       NULL,
    [FXConversionMethodOperator]   VARCHAR (3)      NULL,
    [ExternalTransId]              VARCHAR (100)    NULL,
    [TradeAttribute1]              VARCHAR (200)    NULL,
    [TradeAttribute2]              VARCHAR (200)    NULL,
    [TradeAttribute3]              VARCHAR (200)    NULL,
    [TradeAttribute4]              VARCHAR (200)    NULL,
    [TradeAttribute5]              VARCHAR (200)    NULL,
    [TradeAttribute6]              VARCHAR (200)    NULL,
    [LotId]                        VARCHAR (200)    NULL,
    [AdditionalTradeAttributes] NVARCHAR(MAX) DEFAULT NULL
);

