CREATE TABLE [dbo].[T_AUECMapping] (
    [AUECID]                INT           NOT NULL,
    [ExchangeIdentifier]    VARCHAR (MAX) NULL,
    [Year]                  VARCHAR (20)  NULL,
    [Month]                 VARCHAR (20)  NULL,
    [Day]                   VARCHAR (20)  NULL,
    [Type]                  VARCHAR (20)  NULL,
    [Strike]                VARCHAR (20)  NULL,
    [ExchangeToken]         VARCHAR (MAX) NULL,
    [PSRootToken]           VARCHAR (MAX) NULL,
    [PSFormatString]        VARCHAR (MAX) NULL,
    [TranslateRoot]         BIT           NOT NULL,
    [TranslateType]         BIT           NOT NULL,
    [ExerciseStyle]         VARCHAR (MAX) NULL,
	[EsignalFormatString]   VARCHAR (MAX) NULL,
    [EsignalOptionFormatString]   VARCHAR (MAX) NULL,
    [BloombergOptionFormatString] VARCHAR (MAX) NULL,
    [EsignalRootToken]      VARCHAR (MAX) NULL,
    [BloombergRootToken]    VARCHAR (MAX) NULL,
    [EsignalExchangeCode]	VARCHAR (20) NULL, 
    [FactSetExchangeCode]	VARCHAR (20) NULL, 
    [FactSetRegionCode]		VARCHAR (20) NULL, 
    [FactSetFormatString]	VARCHAR(MAX) NULL,
    [ActivFormatString]		VARCHAR(MAX) NULL,
    [BloombergCompositeCode]	VARCHAR (20) NULL,
    [BloombergExchangeCode]	VARCHAR (20) NULL,
    [BloombergFormatString] VARCHAR(MAX) NULL,
    PRIMARY KEY CLUSTERED ([AUECID] ASC)
);

