CREATE TABLE [dbo].[T_AUECSide] (
    [AUECSideID] INT IDENTITY (1, 1) NOT NULL,
    [AUECID]     INT NOT NULL,
    [SideID]     INT NOT NULL,
    CONSTRAINT [PK_T_AUECSide] PRIMARY KEY CLUSTERED ([AUECSideID] ASC)
);

