CREATE TABLE [dbo].[T_BTSavedBasketOrders] (
    [SavedBasketID]     VARCHAR (50)  NOT NULL,
    [SavedOrderID]      VARCHAR (200) NOT NULL,
    [SideTagValue]      VARCHAR (10)  NULL,
    [Symbol]            VARCHAR (100) NULL,
    [ExchangeID]        INT           NULL,
    [Quantity]          FLOAT (53)    NULL,
    [AvgPrice]          FLOAT (53)    NULL,
    [TradingAccountID]  INT           NULL,
    [AUECID]            INT           NULL,
    [AssetID]           INT           NULL,
    [UnderlyingID]      INT           NULL,
    [CompanyUserID]     INT           NULL,
    [Price]             FLOAT (53)    NULL,
    [ExecutionInst]     VARCHAR (50)  NULL,
    [OrderTypeTagValue] VARCHAR (50)  NULL,
    [TimeInForce]       VARCHAR (50)  NULL,
    [CounterPartyID]    INT           NULL,
    [VenueID]           INT           NULL,
    [DiscOffset]        FLOAT (53)    NULL,
    [PegDiff]           FLOAT (53)    NULL,
    [PNP]               INT           NULL,
    [StopPrice]         FLOAT (53)    NULL,
    [FundID]            INT           NULL,
    [StrategyID]        INT           NULL,
    CONSTRAINT [PK_T_BTSavedBasketOrders] PRIMARY KEY CLUSTERED ([SavedOrderID] ASC),
    CONSTRAINT [FK_T_BTSavedBasketOrders_T_BTSavedBaskets] FOREIGN KEY ([SavedBasketID]) REFERENCES [dbo].[T_BTSavedBaskets] ([SavedBasketID])
);

