CREATE TABLE [dbo].[T_BTUpLoadedBasketOrders] (
    [BasketID]            VARCHAR (50)  NOT NULL,
    [ClientOrderID]       VARCHAR (200) NOT NULL,
    [SideTagValue]        VARCHAR (10)  NULL,
    [Symbol]              VARCHAR (100) NULL,
    [ExchangeID]          INT           NULL,
    [Quantity]            FLOAT (53)    NULL,
    [AvgPrice]            FLOAT (53)    NULL,
    [TradingAccountID]    INT           NULL,
    [AUECID]              INT           NULL,
    [AssetID]             INT           NULL,
    [UnderlyingID]        INT           NULL,
    [CompanyUserID]       INT           NULL,
    [Price]               FLOAT (53)    NULL,
    [ExecutionInst]       VARCHAR (50)  NULL,
    [OrderTypeTagValue]   VARCHAR (50)  NULL,
    [TimeInForce]         VARCHAR (50)  NULL,
    [CounterPartyID]      INT           NULL,
    [VenueID]             INT           NULL,
    [DiscOffset]          FLOAT (53)    NULL,
    [PegDiff]             FLOAT (53)    NULL,
    [PNP]                 INT           NULL,
    [StopPrice]           FLOAT (53)    NULL,
    [ParentClientOrderID] VARCHAR (50)  NOT NULL,
    [FundID]              INT           NULL,
    [StrategyID]          INT           NULL,
    CONSTRAINT [PK_T_BTUpLoadedBasketOrders_1] PRIMARY KEY CLUSTERED ([ParentClientOrderID] ASC),
    CONSTRAINT [FK_T_BTUpLoadedBasketOrders_T_BTUploadedBaskets] FOREIGN KEY ([BasketID]) REFERENCES [dbo].[T_BTUploadedBaskets] ([BasketID])
);

