CREATE TABLE [dbo].[T_CashActivity] (
    [CashActivityID]   VARCHAR (50)   NOT NULL,
    [ActivityID]       INT            NULL,
    [FKID]             VARCHAR (3000) NULL,
    [Subactivity]      VARCHAR (50)   NULL,
    [Symbol]           VARCHAR (300)  NULL,
    [FundID]           INT            NULL,
    [Date]             DATETIME       NULL,
    [CurrencyID]       INT            NULL,
    [LeadCurrencyID]   INT            NULL,
    [VsCurrencyID]     INT            NULL,
    [ClosedQty]        VARCHAR (50)   NULL,
    [TaxlotID]         VARCHAR (300)  NULL,
    [Amount]           VARCHAR (50)   NULL,
    [Commission]       FLOAT (53)     CONSTRAINT [DF_T_Activity_Commission] DEFAULT ((0)) NULL,
    [OtherBrokerFees]  FLOAT (53)     CONSTRAINT [DF_T_Activity_OtherBrokerFees] DEFAULT ((0)) NULL,
    [StampDuty]        FLOAT (53)     CONSTRAINT [DF_T_Activity_StampDuty] DEFAULT ((0)) NULL,
    [TransactionLevy]  FLOAT (53)     CONSTRAINT [DF_T_Activity_TransactionLevy] DEFAULT ((0)) NULL,
    [ClearingFee]      FLOAT (53)     CONSTRAINT [DF_T_Activity_ClearingFee] DEFAULT ((0)) NULL,
    [TaxOnCommissions] FLOAT (53)     CONSTRAINT [DF_T_Activity_TaxOnCommissions] DEFAULT ((0)) NULL,
    [MiscFees]         FLOAT (53)     CONSTRAINT [DF_T_Activity_MiscFees] DEFAULT ((0)) NULL,
    [FXRate]           FLOAT (53)     NULL,
    [ActivitySource]   VARCHAR (300)  NULL,
    [ActivityNumber]   INT            NULL,
    [Description]      VARCHAR (3000) NULL,
    [UniqueKey]        VARCHAR (300)  NULL,
    [ActivityType]     INT            NULL,
    CONSTRAINT [PK_T_CashActivity] PRIMARY KEY CLUSTERED ([CashActivityID] ASC)
);

