CREATE TABLE [dbo].[T_ClientFills] (
    [Fills_PK]              INT           IDENTITY (1, 1) NOT NULL,
    [ExecutionID]           VARCHAR (50)  NULL,
    [MsgType]               VARCHAR (10)  NULL,
    [MsgSeqNumber]          VARCHAR (50)  NULL,
    [TargetCompID]          VARCHAR (50)  NULL,
    [SenderCompID]          VARCHAR (50)  NULL,
    [TargetSubID]           VARCHAR (50)  NULL,
    [ExecTransType]         CHAR (10)     NULL,
    [ClOrderID]             VARCHAR (50)  NOT NULL,
    [OrderID]               VARCHAR (500)  NULL,
    [OrigClOrderID]         VARCHAR (50)  NULL,
    [Symbol]                VARCHAR (100) NULL,
    [SideID]                CHAR (10)     NULL,
    [Quantity]              FLOAT (53)    NULL,
    [OrderTypeID]           CHAR (10)     NULL,
    [Price]                 FLOAT (53)    NULL,
    [StopPrice]             FLOAT (53)    NULL,
    [TimeInForceID]         CHAR (10)     NULL,
    [LastShares]            FLOAT (53)    NULL,
    [LastPx]                FLOAT (53)    NULL,
    [AveragePrice]          FLOAT (53)    NULL,
    [CumQty]                FLOAT (53)    NULL,
    [LeavesQty]             FLOAT (53)    NULL,
    [LastMkt]               VARCHAR (50)  NULL,
    [OrderStatus]           CHAR (10)     NULL,
    [OrderRejReason]        VARCHAR (50)  NULL,
    [CxlRejectReason]       VARCHAR (50)  NULL,
    [ExecType]              VARCHAR (50)  NULL,
    [TransactTime]          VARCHAR (50)  NULL,
    [SendingTime]           VARCHAR (50)  NULL,
    [InsertionTime]         DATETIME      NULL,
    [FillRecieveServerTime] VARCHAR (50)  NULL,
    [Text]                  VARCHAR (200) NULL,
    [NirvanaSeqNumber]      BIGINT        NULL,
    [SenderSubID]           VARCHAR (50)  NULL,
    CONSTRAINT [PK__T_ClientFills__32230DFE] PRIMARY KEY CLUSTERED ([Fills_PK] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK__T_ClientF__ClOrd__4CD7043A] FOREIGN KEY ([ClOrderID]) REFERENCES [dbo].[T_ClientSub] ([ClOrderID])
);

