CREATE TABLE [dbo].[T_ClientSub] (
    [ClOrderID]           VARCHAR (50)  NOT NULL,
    [ParentClOrderID]     VARCHAR (50)  NOT NULL,
    [OrigClOrderID]       VARCHAR (50)  NULL,
    [Quantity]            FLOAT (53)    NULL,
    [Price]               FLOAT (53)    NULL,
    [MsgType]             VARCHAR (10)  NULL,
    [OrderID]             VARCHAR (500)  NULL,
    [ExecutionInst]       VARCHAR (50)  NULL,
    [OrderTypeTagValue]   CHAR (10)     NULL,
    [TimeInForce]         CHAR (10)     NULL,
    [CounterPartyID]      INT           NULL,
    [VenueID]             INT           NULL,
    [DiscrOffset]         FLOAT (53)    NULL,
    [PegDiff]             VARCHAR (50)  NULL,
    [PNP]                 INT           NULL,
    [StopPrice]           FLOAT (53)    NULL,
    [TargetCompID]        VARCHAR (50)  NULL,
    [TargetSubID]         VARCHAR (50)  NULL,
    [Text]                VARCHAR (50)  NULL,
    [ServerTime]          VARCHAR (50)  NULL,
    [InsertionTime]       DATETIME      NULL,
    [StagedOrderID]       VARCHAR (50)  NULL,
    [NirvanaMsgType]      INT           NULL,
    [HandlingInst]        CHAR (10)     NULL,
    [LocateReqd]          BIT           NULL,
    [ShortRebate]         FLOAT (53)    NULL,
    [FundID]              INT           NULL,
    [StrategyID]          INT           NULL,
    [BorrowerID]          VARCHAR (50)  NULL,
    [SecurityType]        VARCHAR (20)  NULL,
    [MaturityYearMonth]   VARCHAR (20)  NULL,
    [StrikePrice]         FLOAT (53)    NULL,
    [PutOrCall]           INT           NULL,
    [OpenClose]           CHAR (10)     NULL,
    [ClientOrderID]       VARCHAR (50)  NOT NULL,
    [ParentClientOrderID] VARCHAR (50)  NOT NULL,
    [UserID]              INT           NOT NULL,
    [NirvanaSeqNumber]    INT           NULL,
    [CMTA]                VARCHAR (20)  NULL,
    [GiveUpID]            INT           NULL,
    [GiveUp]              VARCHAR (20)  NULL,
    [UnderlyingSymbol]    VARCHAR (20)  NULL,
    [AlgoStrategyID]      VARCHAR (50)  NULL,
    [AlgoParameters]      VARCHAR (500) NULL,
    CONSTRAINT [PK__T_ClientSub__340B5670] PRIMARY KEY CLUSTERED ([ClOrderID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK__T_ClientS__Paren__4DCB2873] FOREIGN KEY ([ParentClOrderID]) REFERENCES [dbo].[T_ClientOrder] ([ParentClOrderID])
);

