CREATE TABLE [dbo].[T_CounterParty] (
    [CounterPartyID]         INT           IDENTITY (1, 1) NOT NULL,
    [FullName]               VARCHAR (50)  NOT NULL,
    [ShortName]              VARCHAR (50)  NOT NULL,
    [Address]                VARCHAR (100) NULL,
    [Phone]                  VARCHAR (20)  NOT NULL,
    [Fax]                    VARCHAR (20)  NULL,
    [ContactName1]           VARCHAR (50)  NOT NULL,
    [Title1]                 VARCHAR (50)  NULL,
    [EMail1]                 VARCHAR (50)  NOT NULL,
    [ContactName2]           VARCHAR (50)  NULL,
    [Title2]                 VARCHAR (50)  NULL,
    [EMail2]                 VARCHAR (50)  NULL,
    [CounterPartyTypeID]     INT           NOT NULL,
    [Address2]               VARCHAR (50)  NULL,
    [CountryID]              INT           NULL,
    [StateID]                INT           NULL,
    [Zip]                    VARCHAR (50)  NULL,
    [ContactName1_LastName]  VARCHAR (50)  NULL,
    [ContactName1_WorkPhone] VARCHAR (50)  NULL,
    [ContactName1_Cell]      VARCHAR (50)  NULL,
    [ContactName2_LastName]  VARCHAR (50)  NULL,
    [ContactName2_WorkPhone] VARCHAR (50)  NULL,
    [ContactName2_Cell]      VARCHAR (50)  NULL,
    [City]                   VARCHAR (50)  NULL,
    [IsAlgoBroker] BIT NULL DEFAULT 0, 
    [IsOTDorEMS] BIT DEFAULT(0) NOT NULL,
    CONSTRAINT [PK_T_CounterParty] PRIMARY KEY CLUSTERED ([CounterPartyID] ASC)
);

