CREATE TABLE [dbo].[T_CompanyUser] (
    [UserID]            INT          IDENTITY (1, 1) NOT NULL,
    [FirstName]         VARCHAR (50) NOT NULL,
    [LastName]          VARCHAR (50) NULL,
    [Login]             VARCHAR (50) NOT NULL,
    [Password]          VARCHAR (100) NOT NULL,
    [ShortName]         VARCHAR (50) NOT NULL,
	[FactSetUsernameAndSerialNumber] VARCHAR (200) NOT NULL DEFAULT '',
	[MarketDataAccessIPAddresses]   VARCHAR (200) NOT NULL DEFAULT '',
    [Title]             VARCHAR (50) NULL,
    [Address1]          VARCHAR (50) NOT NULL,
    [Address2]          VARCHAR (50) NULL,
    [CountryID]         INT          NOT NULL,
    [StateID]           INT          NOT NULL,
    [Zip]               VARCHAR (50) NULL,
    [EMail]             VARCHAR (50) NOT NULL,
    [TelphoneWork]      VARCHAR (50) NOT NULL,
    [TelphoneHome]      VARCHAR (50) NULL,
    [TelphoneMobile]    VARCHAR (50) NOT NULL,
    [Fax]               VARCHAR (50) NULL,
    [IsActive]          INT          CONSTRAINT [df_T_CompanyUser_IsActive] DEFAULT ((1)) NULL,
    [TelphonePager]     VARCHAR (50) NULL,
    [CompanyID]         INT          NOT NULL,
    [TradingPermission] INT          NOT NULL,
    [City]              VARCHAR (50) NULL,
    [Region]            VARCHAR (50) NULL,
	[IsFactSetSupportUser] BIT DEFAULT 0,
    [RoleID]            INT          CONSTRAINT [DF_T_CompanyUser_RoleID] DEFAULT ((0)) NOT NULL,
    [IsAllGroupsAccess] BIT          CONSTRAINT [DF_T_CompanyUser_IsAllGroupsAccess] DEFAULT ((0)) NULL,
    [ActivUsername] VARCHAR(200) NOT NULL DEFAULT '', 
    [ActivPassword] VARCHAR(200) NOT NULL DEFAULT '', 
    [SamsaraAzureId] VARCHAR(200) NOT NULL DEFAULT '',
    [HasPowerBIAccess] BIT DEFAULT 0,
    [SapiUsername] VARCHAR(200) NOT NULL DEFAULT ''
    CONSTRAINT [PK_T_CompanyUser] PRIMARY KEY CLUSTERED ([UserID] ASC),
    CONSTRAINT [FK_T_CompanyUser_T_Company] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[T_Company] ([CompanyID]),
    CONSTRAINT [IX_T_CompanyUser] UNIQUE NONCLUSTERED ([Login] ASC),
    CONSTRAINT [UX_CONSTRAINT_SHORTNAME] UNIQUE NONCLUSTERED ([ShortName] ASC)
);

