CREATE TABLE [dbo].[T_CompanyClient] (
    [CompanyClientID]           INT          IDENTITY (1, 1) NOT NULL,
    [ClientName]                VARCHAR (50) NOT NULL,
    [MailingAddress1]           VARCHAR (50) NOT NULL,
    [MailingAddress2]           VARCHAR (50) NULL,
    [CompanyType]               INT          NOT NULL,
    [Telephone]                 VARCHAR (50) NOT NULL,
    [Fax]                       VARCHAR (50) NULL,
    [PrimaryContactFirstName]   VARCHAR (50) NOT NULL,
    [PrimaryContactLastName]    VARCHAR (50) NULL,
    [PrimaryContactTitle]       VARCHAR (50) NULL,
    [PrimaryContactEmail]       VARCHAR (50) NOT NULL,
    [PrimaryContactTelephone]   VARCHAR (50) NOT NULL,
    [PrimaryContactCell]        VARCHAR (50) NULL,
    [SecondaryContactFirstName] VARCHAR (50) NULL,
    [SecondaryContactLastName]  VARCHAR (50) NULL,
    [SecondaryContactTitle]     VARCHAR (50) NULL,
    [SecondryContactEmail]      VARCHAR (50) NULL,
    [SecondaryContactTelephone] VARCHAR (50) NULL,
    [SecondaryContactCell]      VARCHAR (50) NULL,
    [CompanyID]                 INT          NOT NULL,
    [ShortName]                 VARCHAR (50) NULL,
    [CountryID]                 INT          NULL,
    [StateID]                   INT          NULL,
    [Zip]                       VARCHAR (50) NULL,
    CONSTRAINT [PK_T_CompanyClient] PRIMARY KEY CLUSTERED ([CompanyClientID] ASC),
    CONSTRAINT [FK_T_CompanyClient_T_Company] FOREIGN KEY ([CompanyID]) REFERENCES [dbo].[T_Company] ([CompanyID])
);

