CREATE TABLE [dbo].[T_Company] (
    [CompanyID]                  INT           IDENTITY (1, 1) NOT NULL,
    [Name]                       VARCHAR (50)  NOT NULL,
    [Address1]                   VARCHAR (100) NOT NULL,
    [Address2]                   VARCHAR (100) NULL,
    [CompanyTypeID]              INT           NOT NULL,
    [Telephone]                  VARCHAR (20)  NOT NULL,
    [Fax]                        VARCHAR (20)  NULL,
    [PrimaryContactFirstName]    VARCHAR (50)  NOT NULL,
    [PrimaryContactLastName]     VARCHAR (50)  NULL,
    [PrimaryContactTitle]        VARCHAR (50)  NULL,
    [PrimaryContactEMail]        VARCHAR (50)  NOT NULL,
    [PrimaryContactTelephone]    VARCHAR (50)  NOT NULL,
    [PrimaryContactCell]         VARCHAR (50)  NULL,
    [ShortName]                  VARCHAR (50)  NULL,
    [Login]                      VARCHAR (50)  NULL,
    [Password]                   VARCHAR (50)  NULL,
    [CountryID]                  INT           NULL,
    [StateID]                    INT           NULL,
    [Zip]                        VARCHAR (50)  NULL,
    [BaseCurrencyID]             INT           NULL,
    [SupportsMultipleCurrencies] INT           NULL,
    [City]                       VARCHAR (50)  NULL,
    [DefaultAUECID]              INT           CONSTRAINT [DF_T_Company_DefaultAUECID] DEFAULT ((1)) NULL,
    [Region]                     VARCHAR (50)  NULL,
    [TimeZone]                   INT           CONSTRAINT [DF_T_Company_TimeZone] DEFAULT ((0)) NOT NULL,
    [AlertEmails]                VARCHAR (500) NULL,
    [IsActive]                   BIT           DEFAULT ((1)) NOT NULL,
	[SendAllocationsViaFix]		 BIT		   DEFAULT ((0)) NOT NULL,
    CONSTRAINT [PK_T_Company] PRIMARY KEY CLUSTERED ([CompanyID] ASC)
);

