CREATE TABLE [dbo].[T_DeletedTaxLots] (
    [TaxLotID]                          VARCHAR (50)  NOT NULL,
    [Symbol]                            VARCHAR (50)  NOT NULL,
    [OrderSideTagValue]                 VARCHAR (5)   NOT NULL,
    [CounterPartyID]                    INT           NULL,
    [VenueID]                           INT           NULL,
    [AUECID]                            INT           NOT NULL,
    [TaxlotQty]                         FLOAT (53)    NOT NULL,
    [AvgPrice]                          FLOAT (53)    NOT NULL,
    [Level2Percentage]                  FLOAT (53)    NOT NULL,
    [AUECLocalDate]                     DATETIME      NOT NULL,
    [AssetID]                           INT           NOT NULL,
    [UnderlyingID]                      INT           NOT NULL,
    [ExchangeID]                        INT           NOT NULL,
    [CurrencyID]                        INT           NOT NULL,
    [FundID]                            INT           NOT NULL,
    [SettlementDate]                    DATETIME      NULL,
    [Commission]                        FLOAT (53)    NULL,
    [GroupID]                           VARCHAR (50)  NOT NULL,
    [CumQty]                            FLOAT (53)    NOT NULL,
    [Quantity]                          FLOAT (53)    NOT NULL,
    [OtherBrokerFees]                   FLOAT (53)    NULL,
    [TaxLotState]                       INT           NOT NULL,
    [GroupRefID]                        BIGINT        NOT NULL,
    [OrderTypeTagValue]                 VARCHAR (1)   NULL,
    [Level1AllocationID]                VARCHAR (50)  NOT NULL,
    [StampDuty]                         FLOAT (53)    NULL,
    [TransactionLevy]                   FLOAT (53)    NULL,
    [ClearingFee]                       FLOAT (53)    NULL,
    [TaxOnCommissions]                  FLOAT (53)    NULL,
    [MiscFees]                          FLOAT (53)    NULL,
    [AssetMultiplier]                   FLOAT (53)    NULL,
    [PBID]                              INT           CONSTRAINT [DF_T_DeletedTaxLots_PBID] DEFAULT ((0)) NOT NULL,
    [FXRate]                            FLOAT (53)    CONSTRAINT [DF_T_DeletedTaxLots_FXRate] DEFAULT ((0)) NOT NULL,
    [FXConversionMethodOperator]        VARCHAR (3)   CONSTRAINT [DF_T_DeletedTaxLots_FXConversionMethodOperator] DEFAULT ('M') NOT NULL,
    [ProcessDate]                       DATETIME      CONSTRAINT [DF_T_DeletedTaxLots_ProcessDate] DEFAULT (((1)/(1))/(1800)) NOT NULL,
    [OriginalPurchaseDate]              DATETIME      CONSTRAINT [DF_T_DeletedTaxLots_OriginalPurchaseDate] DEFAULT (((1)/(1))/(1800)) NOT NULL,
    [AccruedInterest]                   FLOAT (53)    NULL,
    [BenchMarkRate]                     FLOAT (53)    NULL,
    [Differential]                      FLOAT (53)    NULL,
    [SwapDescription]                   VARCHAR (500) NULL,
    [DayCount]                          INT           NULL,
    [FirstResetDate]                    DATETIME      NULL,
    [IsSwapped]                         BIT           NULL,
    [FXRate_Taxlot]                     FLOAT (53)    NULL,
    [FXConversionMethodOperator_Taxlot] VARCHAR (5)   NULL,
    [Level2ID]                          INT           NULL,
    [Description]                       VARCHAR (500) NULL,
    [LotId]                             VARCHAR (200) NULL,
    [ExternalTransId]                   VARCHAR (100) NULL,
    [TradeAttribute1]                   VARCHAR (200) NULL,
    [TradeAttribute2]                   VARCHAR (200) NULL,
    [TradeAttribute3]                   VARCHAR (200) NULL,
    [TradeAttribute4]                   VARCHAR (200) NULL,
    [TradeAttribute5]                   VARCHAR (200) NULL,
    [TradeAttribute6]                   VARCHAR (200) NULL,
    [FileFormatID]                      INT           CONSTRAINT [DF_T_DeletedTaxlots] DEFAULT ((0)) NULL,
    [SecFee]                            FLOAT (53)    NULL,
    [OccFee]                            FLOAT (53)    NULL,
    [OrfFee]                            FLOAT (53)    NULL,
    [ClearingBrokerFee]                 FLOAT (53)    NULL,
    [SoftCommission]                    FLOAT (53)    NULL,
    [TransactionType]                   VARCHAR (200) DEFAULT ('') NOT NULL,
    [InternalComments]                  VARCHAR (500) NULL,
    [SettlCurrency]                     INT           NULL,
    [OptionPremiumAdjustment]           FLOAT (53)    NULL,
    [AdditionalTradeAttributes] NVARCHAR(MAX) DEFAULT NULL
);


GO
CREATE NONCLUSTERED INDEX [IX_T_DeletedTaxLots]
    ON [dbo].[T_DeletedTaxLots]([TaxLotID] ASC);

