CREATE TABLE [dbo].[T_Group] (
    [GroupRefID]                 BIGINT           IDENTITY (1, 1) NOT NULL,
    [GroupID]                    VARCHAR (50)     NOT NULL,
    [OrderSideTagValue]          VARCHAR (3)      NOT NULL,
    [Symbol]                     VARCHAR (100)    NOT NULL,
    [OrderTypeTagValue]          VARCHAR (3)      NOT NULL,
    [CounterPartyID]             INT              NOT NULL,
    [VenueID]                    INT              NOT NULL,
    [TradingAccountID]           INT              NOT NULL,
    [AUECID]                     INT              NOT NULL,
    [CumQty]                     FLOAT (53)       NOT NULL,
    [AllocatedQty]               FLOAT (53)       NOT NULL,
    [Quantity]                   FLOAT (53)       NOT NULL,
    [AvgPrice]                   FLOAT (53)       NOT NULL,
    [IsPreAllocated]             BIT              NOT NULL,
    [ListID]                     VARCHAR (50)     NOT NULL,
    [UserID]                     INT              NOT NULL,
    [ISProrataActive]            BIT              NOT NULL,
    [AutoGrouped]                BIT              NOT NULL,
    [StateID]                    INT              NOT NULL,
    [IsBasketGroup]              BIT              NULL,
    [BasketGroupID]              VARCHAR (50)     NULL,
    [IsManualGroup]              BIT              DEFAULT ((0)) NOT NULL,
    [AllocationDate]             DATETIME         NOT NULL,
    [SettlementDate]             DATETIME         NULL,
    [AssetID]                    INT              NULL,
    [UnderLyingID]               INT              NULL,
    [ExchangeID]                 INT              NULL,
    [CurrencyID]                 INT              NULL,
    [Description]                VARCHAR (MAX)    NULL,
    [AUECLocalDate]              DATETIME         NOT NULL,
    [IsSwapped]                  BIT              NULL,
    [FXRate]                     FLOAT (53)       NULL,
    [FXConversionMethodOperator] VARCHAR (3)      NULL,
    [TaxlotClosingID_Fk]         UNIQUEIDENTIFIER NULL,
    [Commission]                 FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [OtherBrokerFees]            FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [StampDuty]                  FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [TransactionLevy]            FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [ClearingFee]                FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [TaxOnCommissions]           FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [MiscFees]                   FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [AccruedInterest]            FLOAT (53)       CONSTRAINT [DF_T_Group_AccruedInterest] DEFAULT ((0)) NULL,
    [ProcessDate]                DATETIME         DEFAULT (((1)/(1))/(1800)) NOT NULL,
    [OriginalPurchaseDate]       DATETIME         DEFAULT (((1)/(1))/(1800)) NOT NULL,
    [ModifiedUserID]                 INT              NULL,
    [ModifiedDate]               DATETIME         NULL,
    [IsModified]                 BIT              NULL,
    [AllocationSchemeID]         INT              DEFAULT ((0)) NOT NULL,
    [CommissionSource]           INT              DEFAULT ('1') NOT NULL,
    [TradeAttribute1]            VARCHAR (200)    NULL,
    [TradeAttribute2]            VARCHAR (200)    NULL,
    [TradeAttribute3]            VARCHAR (200)    NULL,
    [TradeAttribute4]            VARCHAR (200)    NULL,
    [TradeAttribute5]            VARCHAR (200)    NULL,
    [TradeAttribute6]            VARCHAR (200)    NULL,
    [TaxlotIdsWithAttributes]    NVARCHAR (500)   NULL,
    [TransactionType]            VARCHAR (50)     NULL,
    [SecFee]                     FLOAT (53)       CONSTRAINT [DF_T_Group_SecFee] DEFAULT ((0)) NOT NULL,
    [OccFee]                     FLOAT (53)       CONSTRAINT [DF_T_Group_OccFee] DEFAULT ((0)) NOT NULL,
    [OrfFee]                     FLOAT (53)       CONSTRAINT [DF_T_Group_OrfFee] DEFAULT ((0)) NOT NULL,
    [ClearingBrokerFee]          FLOAT (53)       CONSTRAINT [DF_T_Group_ClearingBrokerFee] DEFAULT ((0)) NOT NULL,
    [SoftCommission]             FLOAT (53)       CONSTRAINT [DF_T_Group_SoftCommission] DEFAULT ((0)) NOT NULL,
    [NotionalChange]             FLOAT (53)       DEFAULT ((0)) NOT NULL,
    [NirvanaProcessDate]         DATETIME         CONSTRAINT [DF_T_Group_NirvanaProcessDate] DEFAULT (((1800)-(1))-(1)) NULL,
    [TransactionSource]          INT              NULL,
    [InternalComments]           VARCHAR (MAX)    NULL,
    [SettlCurrency]              INT              NULL,
    [OptionPremiumAdjustment]    FLOAT (53)       CONSTRAINT [DF_T_Group_OptionPremiumAdjustment] DEFAULT ((0)) NULL,
    [ChangeType]                 INT              DEFAULT ((3)) NOT NULL,
    [IsCommissionChanged]        BIT              DEFAULT ((0)) NOT NULL,
    [IsSoftCommissionChanged]    BIT              DEFAULT ((0)) NOT NULL,
    [OriginalAllocationPreferenceID]  INT		  NULL,
	[BorrowerID]          VARCHAR (50)   NULL,
	[BorrowBroker]        VARCHAR(50) NULL,
	[ShortRebate]         FLOAT (53)     NULL,
    [AdditionalTradeAttributes] NVARCHAR(MAX) DEFAULT NULL
    PRIMARY KEY CLUSTERED ([GroupID] ASC), 
    CONSTRAINT [FK_T_Group_T_GroupState] FOREIGN KEY ([StateID]) REFERENCES [dbo].[T_GroupState] ([StateID]), 
);


GO
CREATE NONCLUSTERED INDEX [ix_T_Group_AUECLocalDate]
    ON [dbo].[T_Group]([AUECLocalDate] ASC);

