CREATE TABLE [dbo].[T_Level2Allocation] (
    [TaxLotID]                   VARCHAR (50)  NOT NULL,
    [GroupID]                    VARCHAR (50)  NULL,
    [Level1AllocationID]         VARCHAR (50)  NULL,
    [Level2ID]                   INT           NULL,
    [Level2Percentage]           FLOAT (53)    NULL,
    [TaxLotQty]                  FLOAT (53)    NULL,
    [Commission]                 FLOAT (53)    NULL,
    [OtherBrokerFees]            FLOAT (53)    NULL,
    [StampDuty]                  FLOAT (53)    NULL,
    [TransactionLevy]            FLOAT (53)    NULL,
    [ClearingFee]                FLOAT (53)    NULL,
    [TaxOnCommissions]           FLOAT (53)    NULL,
    [MiscFees]                   FLOAT (53)    NULL,
    [TaxLotState]                INT           NULL,
    [AccruedInterest]            FLOAT (53)    NULL,
    [FXRate]                     FLOAT (53)    NULL,
    [FXConversionMethodOperator] VARCHAR (3)   NULL,
    [ExternalTransId]            VARCHAR (100) NULL,
    [TradeAttribute1]            VARCHAR (200) NULL,
    [TradeAttribute2]            VARCHAR (200) NULL,
    [TradeAttribute3]            VARCHAR (200) NULL,
    [TradeAttribute4]            VARCHAR (200) NULL,
    [TradeAttribute5]            VARCHAR (200) NULL,
    [TradeAttribute6]            VARCHAR (200) NULL,
    [LotId]                      VARCHAR (200) NULL,
    [SecFee]                     FLOAT (53)    NULL,
    [OccFee]                     FLOAT (53)    NULL,
    [OrfFee]                     FLOAT (53)    NULL,
    [ClearingBrokerFee]          FLOAT (53)    NULL,
    [SoftCommission]             FLOAT (53)    NULL,
    [NotionalChange]             FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [SettlCurrency]              INT           NULL,
    [OptionPremiumAdjustment]    FLOAT (53)    NULL,
    [AdditionalTradeAttributes] NVARCHAR(MAX) DEFAULT NULL
    CONSTRAINT [PK__T_Level2Allocati__48BC5A93] PRIMARY KEY CLUSTERED ([TaxLotID] ASC) WITH (FILLFACTOR = 100),
    CONSTRAINT [FK__T_Level2A__Level__49B07ECC] FOREIGN KEY ([Level1AllocationID]) REFERENCES [dbo].[T_FundAllocation] ([AllocationId]),
    CONSTRAINT [FK_T_CompanyStrategy_T_Level2Allocation] FOREIGN KEY ([Level2ID]) REFERENCES [dbo].[T_CompanyStrategy] ([CompanyStrategyID])
);

