CREATE TABLE [dbo].[T_ReportPreferences] (
    [ReportID]                                             VARCHAR (100) NOT NULL,
    [IsPerformanceMD]                                      BIT           NOT NULL,
    [FutureMV_ZeroOrEndingMVOrUnrealized]                  INT           NOT NULL,
    [FXMV_ZeroOrEndingMVOrUnrealized]                      INT           NOT NULL,
    [SwapMV_ZeroOrEndingMVOrUnrealized]                    INT           NOT NULL,
    [InternationalFutOptionsMV_ZeroOrEndingMVOrUnrealized] INT           NOT NULL,
    [TotalCostASZero_Futures]                              INT           NULL,
    [TotalCostASZero_FutOptions]                           BIT           NOT NULL,
    [TotalCostASZero_FX]                                   INT           NULL,
    [TotalCostASZero_Swaps]                                BIT           NOT NULL,
    [IncludeFXPNLinEquity]                                 BIT           NOT NULL,
    [IncludeFXPNLinEquityOption]                           BIT           NOT NULL,
    [IncludeFXPNLinFX]                                     BIT           NOT NULL,
    [IncludeFXPNLinFutures]                                BIT           NOT NULL,
    [IncludeFXPNLinSwaps]                                  BIT           NOT NULL,
    [IncludeFXPNLinInternationalFutOptions]                BIT           NOT NULL,
    [IncludeFXPNLinOther]                                  BIT           NOT NULL,
    [IncludeCommissionInPNL_Equity]                        BIT           NOT NULL,
    [IncludeCommissionInPNL_EquityOption]                  BIT           NOT NULL,
    [IncludeCommissionInPNL_Futures]                       BIT           NOT NULL,
    [IncludeCommissionInPNL_FutOptions]                    BIT           NOT NULL,
    [IncludeCommissionInPNL_Swaps]                         BIT           NOT NULL,
    [IncludeCommissionInPNL_FX]                            BIT           NOT NULL,
    [IncludeCommissionInPNL_Other]                         BIT           NOT NULL,
    [IntradayNAV_AnalyticsOrDataDumpOrGrossExposure]       INT           DEFAULT ((1)) NOT NULL,
    [AnalyticsNAV_SavedOrCalculatedOrGrossExposure]        INT           DEFAULT ((1)) NOT NULL,
    [PNLContribution_AgainstGroupACBorAgainstGroupPNL]     INT           DEFAULT ((1)) NOT NULL,
    [LongShortPNL_ByMVOrByExposure]                        BIT           DEFAULT ('true') NOT NULL,
    PRIMARY KEY CLUSTERED ([ReportID] ASC)
);

