CREATE TABLE [dbo].[T_RoutingLogicMemoryRL] (
    [MemoryID]                  VARCHAR (50) NOT NULL,
    [RLID]                      INT          NULL,
    [RLName]                    VARCHAR (50) NULL,
    [AUECID]                    INT          NULL,
    [AssetID]                   INT          NULL,
    [AssetName]                 CHAR (50)    NULL,
    [UnderLyingID]              INT          NULL,
    [UnderLyingName]            CHAR (50)    NULL,
    [ExchangeName]              CHAR (50)    NULL,
    [TradingAccountID0]         INT          NULL,
    [TradingAccountName0]       CHAR (50)    NULL,
    [CounterPartyID0]           INT          NULL,
    [CounterPartyName0]         CHAR (50)    NULL,
    [VenueID0]                  INT          NULL,
    [VenueName0]                CHAR (50)    NULL,
    [TradingAccountID1]         INT          NULL,
    [TradingAccountName1]       CHAR (50)    NULL,
    [CounterPartyID1]           INT          NULL,
    [CounterPartyName1]         CHAR (50)    NULL,
    [VenueID1]                  INT          NULL,
    [VenueName1]                CHAR (50)    NULL,
    [TradingAccountID2]         INT          NULL,
    [TradingAccountName2]       CHAR (50)    NULL,
    [CounterPartyID2]           INT          NULL,
    [CounterPartyName2]         CHAR (50)    NULL,
    [VenueID2]                  INT          NULL,
    [VenueName2]                CHAR (50)    NULL,
    [TradingAccountDefaultID]   INT          NULL,
    [TradingAccountNameDefault] CHAR (50)    NULL,
    [ParameterID0]              INT          NULL,
    [ParameterValue0]           CHAR (50)    NULL,
    [JoinCondition0]            INT          NULL,
    [OperatorID0]               INT          NULL,
    [ParameterID1]              INT          NULL,
    [ParameterValue1]           CHAR (50)    NULL,
    [JoinCondition1]            INT          NULL,
    [OperatorID1]               INT          NULL,
    [ParameterID2]              INT          NULL,
    [ParameterValue2]           CHAR (50)    NULL,
    [JoinCondition2]            INT          NULL,
    [OperatorID2]               INT          NULL,
    CONSTRAINT [PK_T_RoutingLogicMemoryRL] PRIMARY KEY CLUSTERED ([MemoryID] ASC)
);

