CREATE TABLE [dbo].[T_SubAccountMappingPSR](
	[FieldID] [int] NOT NULL,
	[SubAccountID] [int] NOT NULL,
 CONSTRAINT [PK_T_SubAccountMappingPSR] PRIMARY KEY CLUSTERED 
(
	[FieldID] ASC,
	[SubAccountID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]