CREATE TABLE [dbo].[T_ThirdPartyFFGenerationDate] (
    [TaxlotID]                   NVARCHAR (50)  NULL,
    [thirdPartyID]               INT            NULL,
    [fileFormatID]               INT            NULL,
    [GenerationDate]             DATETIME       NULL,
    [TradeDate]                  DATETIME       NULL,
    [SideID]                     VARCHAR (5)    NULL,
    [CounterpartyID]             INT            NULL,
    [ExecutedQuantity]           INT            NULL,
    [AvgPrice]                   FLOAT (53)     NULL,
    [SettlmentDate]              DATETIME       NULL,
    [FXRate]                     FLOAT (53)     NULL,
    [Commission]                 FLOAT (53)     NULL,
    [OtherBrokerFees]            FLOAT (53)     NULL,
    [StampDuty]                  FLOAT (53)     NULL,
    [TransactionLevy]            FLOAT (53)     NULL,
    [ClearingFee]                FLOAT (53)     NULL,
    [MiscFees]                   FLOAT (53)     NULL,
    [VenueID]                    INT            NULL,
    [FXConversionMethodOperator] NVARCHAR (1)   NULL,
    [ProcessDate]                DATETIME       NULL,
    [OriginalPurchaseDate]       DATETIME       NULL,
    [Description]                NVARCHAR (500)  NULL,
    [AccruedInterest]            FLOAT (53)     NULL,
    [UnderlyingDelta]            FLOAT (53)     NULL,
    [LotID]                      NVARCHAR (200) NULL,
    [CommissionAmount]           FLOAT (53)     NULL,
    [CommissionRate]             FLOAT (53)     NULL,
    [SecFee]                     FLOAT (53)     NULL,
    [OccFee]                     FLOAT (53)     NULL,
    [OrfFee]                     FLOAT (53)     NULL,
    [ClearingBrokerFee]          FLOAT (53)     NULL,
    [SoftCommission]             FLOAT (53)     NULL,
    [SoftCommissionAmount]       FLOAT (53)     NULL,
    [TransactionType]            NVARCHAR (20)  NULL,
    [SettlCurrency]              INT            NULL,
    [AmendTaxLotId1]             VARCHAR (50)   NULL,
    [AmendTaxLotId2]             VARCHAR (50)   NULL,
    [TaxOnCommissions]           FLOAT (53)     NULL,
    [GroupID]                    VARCHAR (50)   NULL,
    [Level2ID]                   INT            NULL,
    [ExternalTransId]            VARCHAR (100)  NULL,
    [TransactionSource]          INT            NULL
);

