CREATE TABLE [dbo].[T_ThirdPartyFFRunFundDetails] (
    [FFRunFundDetailID]    INT             IDENTITY (1, 1) NOT NULL,
    [ThirdPartyFFRunID]    INT             NULL,
    [Side]                 NVARCHAR (50)   NULL,
    [Symbol]               NVARCHAR (50)   NULL,
    [ExecQty]              FLOAT (53)      NULL,
    [AveragePrice]         FLOAT (53)      NULL,
    [OrderTypeTag]         NVARCHAR (100)  NULL,
    [OrderType]            NVARCHAR (50)   NULL,
    [AssetID]              INT             NULL,
    [Asset]                NVARCHAR (50)   NULL,
    [UnderLyingID]         INT             NULL,
    [UnderLying]           NVARCHAR (50)   NULL,
    [ExchangeID]           INT             NULL,
    [Exchange]             NVARCHAR (50)   NULL,
    [CurrencyID]           INT             NULL,
    [Currency]             NVARCHAR (50)   NULL,
    [AUECID]               INT             NULL,
    [SecFees]              FLOAT (53)      NULL,
    [CommissionRate]       FLOAT (53)      NULL,
    [CommissionCharged]    FLOAT (53)      NULL,
    [GrossAmt]             FLOAT (53)      NULL,
    [NetAmt]               FLOAT (53)      NULL,
    [SecurityIDType]       NVARCHAR (50)   NULL,
    [CommissionRateTypeID] INT             NULL,
    [CommissionRateType]   NVARCHAR (50)   NULL,
    [CompanyCVID]          INT             NULL,
    [CVName]               NVARCHAR (50)   NULL,
    [CVIdentifier]         NVARCHAR (50)   NULL,
    [Percentage]           FLOAT (53)      NULL,
    [OrderQty]             FLOAT (53)      NULL,
    [EntityID]             NVARCHAR (100)  NULL,
    [CounterPartyID]       INT             NULL,
    [CounterParty]         NVARCHAR (50)   NULL,
    [AlllocQty]            FLOAT (53)      NULL,
    [TotalQty]             FLOAT (53)      NULL,
    [FundName]             NVARCHAR (50)   NULL,
    [FundMappedName]       NVARCHAR (50)   NULL,
    [FundAccountNo]        NVARCHAR (50)   NULL,
    [FundTypeID]           INT             NULL,
    [FundType]             NCHAR (10)      NULL,
    [CompanyFundID]        INT             NULL,
    [PutOrCall]            INT             NULL,
    [CurrencySymbol]       VARCHAR (50)    NULL,
    [StrikePrice]          NUMERIC (18, 4) NULL,
    [ExpirationDate]       VARCHAR (50)    NULL,
    [SettlementDate]       VARCHAR (50)    NULL,
    [VenueID]              INT             NULL,
    [VenueName]            VARCHAR (50)    NULL,
    [CUSIP]                VARCHAR (100)   NULL,
    [ISIN]                 VARCHAR (100)   NULL,
    [SEDOL]                VARCHAR (100)   NULL,
    [RIC]                  VARCHAR (100)   NULL,
    [BBCode]               VARCHAR (100)   NULL,
    [FullSecurityName]     VARCHAR (200)   NULL,
    [PBUniqueID]           BIGINT          NULL,
    [AllocationSeqNo]      INT             NULL,
    [OtherBrokerFee]       FLOAT (53)      NULL,
    [TaxLotStateID]        INT             NULL,
    [ClearingBrokerFee]    FLOAT (53)      NULL,
    CONSTRAINT [PK_T_ThirdPartyFFRunFundDetails] PRIMARY KEY CLUSTERED ([FFRunFundDetailID] ASC),
    CONSTRAINT [FK_T_ThirdPartyFFRunFundDetails_T_ThirdPartyFFRunReport] FOREIGN KEY ([ThirdPartyFFRunID]) REFERENCES [dbo].[T_ThirdPartyFFRunReport] ([ThirdPartyFFRunID])
);

