CREATE TABLE [dbo].[T_ThirdParty] (
    [ThirdPartyID]             INT          IDENTITY (1, 1) NOT NULL,
    [ThirdPartyName]           VARCHAR (50) NOT NULL,
    [Description]              TEXT         NULL,
    [ThirdPartyTypeID]         INT          NOT NULL,
    [ShortName]                VARCHAR (50) NOT NULL,
    [ContactPerson]            VARCHAR (50) NOT NULL,
    [Address1]                 VARCHAR (50) NOT NULL,
    [Address2]                 VARCHAR (50) NULL,
    [CellPhone]                VARCHAR (50) NULL,
    [WorkTelephone]            VARCHAR (50) NOT NULL,
    [Fax]                      VARCHAR (50) NULL,
    [Email]                    VARCHAR (50) NOT NULL,
    [CountryID]                INT          NULL,
    [StateID]                  INT          NULL,
    [Zip]                      VARCHAR (50) NULL,
    [ContactPersonLastName]    VARCHAR (50) NULL,
    [ContactPersonTitle]       VARCHAR (50) NULL,
    [ContactPersonFax]         VARCHAR (50) NULL,
    [ContactPersonWorkPhone]   VARCHAR (50) NULL,
    [SymbolConvention]         INT          NULL,
    [SecurityIdentifierTypeID] INT          NULL,
    [BrokerCode]               VARCHAR (50) NULL,
    [isActive]                 BIT          DEFAULT ((1)) NOT NULL,
    [DataSourceID]             INT          NULL,
    [StatusID]                 INT          NULL,
    [ImportMethod]             TINYINT      NULL,
    [ImportFormat]             TINYINT      NULL,
    [DataSourceTableName]      NCHAR (50)   NULL,
    [CounterPartyID]           INT          NULL
    CONSTRAINT [PK_T_ThirdParty] PRIMARY KEY CLUSTERED ([ThirdPartyID] ASC),
    CONSTRAINT [FK_T_ThirdParty_T_ThirdPartyType] FOREIGN KEY ([ThirdPartyTypeID]) REFERENCES [dbo].[T_ThirdPartyType] ([ThirdPartyTypeID])
);

