CREATE TABLE [dbo].[T_TicketSettings] (
    [DefaultTicketID]        VARCHAR (200) NOT NULL,
    [AssetID]                INT           NOT NULL,
    [AUECID]                 INT           NOT NULL,
    [DisplayColor]           VARCHAR (50)  NULL,
    [DisplayPosition]        VARCHAR (20)  NULL,
    [ButtonName]             VARCHAR (50)  NOT NULL,
    [Description]            VARCHAR (50)  NOT NULL,
    [IsHotButton]            VARCHAR (10)  NULL,
    [Side]                   VARCHAR (10)  NULL,
    [FundID]                 INT           NULL,
    [StrategyID]             INT           NULL,
    [ClearingFirmID]         INT           NULL,
    [Quantity]               INT           NULL,
    [OrderTypeID]            VARCHAR (10)  NULL,
    [TimeInForceID]          VARCHAR (10)  NULL,
    [ExecutionInstructionID] VARCHAR (10)  NULL,
    [HandlingInstructionID]  VARCHAR (10)  NULL,
    [TradingAccountID]       INT           NULL,
    [PegOffSet]              VARCHAR (20)  NULL,
    [Discr]                  VARCHAR (20)  NULL,
    [DisplayQuantity]        INT           NULL,
    [Random]                 INT           NULL,
    [PNP]                    INT           NULL,
    [CompanyUserID]          INT           NULL,
    [LimitType]              INT           NULL,
    [LimitOffset]            VARCHAR (20)  NULL,
    [UnderLyingID]           INT           NOT NULL,
    [CounterPartyID]         INT           NOT NULL,
    [VenueID]                INT           NOT NULL,
    PRIMARY KEY CLUSTERED ([DefaultTicketID] ASC) WITH (FILLFACTOR = 100)
);

