CREATE TABLE [dbo].[T_TradingTicketPrefrencesSettings] (
    [TradingTicketPrefrencesSettingsID] INT          IDENTITY (1, 1) NOT NULL,
    [AssetID]                           VARCHAR (50) NULL,
    [UnderlyingID]                      VARCHAR (50) NULL,
    [TradingAccountID]                  VARCHAR (50) NULL,
    [FundID]                            VARCHAR (50) NULL,
    [StrategyID]                        VARCHAR (50) NULL,
    [BrokerID]                          VARCHAR (50) NULL,
    [IsDefaultCV]                       VARCHAR (6)  NULL,
    [Quantity]                          VARCHAR (50) NULL,
    [DisplayQuantity]                   VARCHAR (50) NULL,
    [QuantityIncrement]                 VARCHAR (50) NULL,
    [PriceLimitIncrement]               VARCHAR (50) NULL,
    [StopPriceIncrement]                VARCHAR (50) NULL,
    [PegOffset]                         VARCHAR (50) NULL,
    [DiscrOffset]                       VARCHAR (50) NULL,
    [CounterPartyID]                    VARCHAR (50) NULL,
    [VenueID]                           VARCHAR (50) NULL,
    [OrderTypeID]                       VARCHAR (50) NULL,
    [ExecutionInstructionID]            VARCHAR (50) NULL,
    [HandlingInstructionID]             VARCHAR (50) NULL,
    [TIF]                               VARCHAR (50) NULL,
    [CVTradingAccountID]                VARCHAR (50) NULL,
    [CVFundID]                          VARCHAR (50) NULL,
    [CVStrategyID]                      VARCHAR (50) NULL,
    [CVBrokerID]                        VARCHAR (50) NULL,
    [CVBorrowerFirmID]                  VARCHAR (50) NULL,
    [CompanyUserID]                     INT          NULL,
    [CMTAID]                            INT          NULL,
    [GiveUpID]                          INT          NULL,
    [OrderSideID]                       VARCHAR (50) NULL,
    [SettlCurrency]                     INT          DEFAULT ((0)) NOT NULL,
    [IsQuantityDefaultValueChecked]     VARCHAR(6) NULL, 
    CONSTRAINT [PK_T_TradingTicketPrefrencesSettings] PRIMARY KEY CLUSTERED ([TradingTicketPrefrencesSettingsID] ASC)
);

