CREATE TABLE [dbo].[T_TradedOrders] (
    [CLOrderID]                  VARCHAR (50)   NULL,
    [GroupID]                    VARCHAR (50)   NULL,
    [OrderSidetagValue]          VARCHAR (3)    NULL,
    [Symbol]                     VARCHAR (100)  NULL,
    [OrderTypeTagValue]          VARCHAR (3)    NULL,
    [CounterPartyID]             INT            NULL,
    [VenueID]                    INT            NULL,
    [TradingAccountID]           INT            NULL,
    [FundID]                     INT            NULL,
    [StrategyID]                 INT            NULL,
    [AUECID]                     INT            NULL,
    [AveragePrice]               FLOAT (53)     NULL,
    [Quantity]                   FLOAT (53)     NULL,
    [CumQty]                     FLOAT (53)     NULL,
    [Price]                      FLOAT (53)     NULL,
    [NirvanaSeqNumber]           BIGINT         NULL,
    [InsertionTime]              DATETIME       NULL,
    [AvgPrice]                   FLOAT (53)     NULL,
    [MsgType]                    VARCHAR (10)   NULL,
    [OrderStatus]                VARCHAR (3)    NULL,
    [ExecType]                   VARCHAR (50)   NULL,
    [LeavesQty]                  FLOAT (53)     NULL,
    [LastPx]                     FLOAT (53)     NULL,
    [LastShares]                 FLOAT (53)     NULL,
    [UserID]                     INT            NULL,
    [OrigClOrderID]              VARCHAR (50)   NULL,
    [ParentClOrderID]            VARCHAR (50)   NOT NULL,
    [ClientOrderID]              VARCHAR (50)   NULL,
    [ParentClientOrderID]        VARCHAR (50)   NULL,
    [OrderStatusTagValue]        VARCHAR (3)    NULL,
    [TransactTime]               VARCHAR (50)   NULL,
    [OpenClose]                  VARCHAR (3)    NULL,
    [NirvanaMsgType]             INT            NULL,
    [OrderID]                    VARCHAR (500)   NULL,
    [SettlementDate]             DATETIME       NULL,
    [AlgoStrategyID]             VARCHAR (50)   NULL,
    [AlgoParameters]             VARCHAR (500)  NULL,
    [ExecutionInst]              VARCHAR (50)   NULL,
    [TimeInForce]                VARCHAR (3)    NULL,
    [HandlingInst]               VARCHAR (3)    NULL,
    [AUECLocalDate]              DATETIME       NOT NULL,
    [Text]                       VARCHAR (200)  NULL,
    [Expr1]                      INT            NULL,
    [AvgFxRateForTrade]          FLOAT (53)     NULL,
    [SenderSubID]                VARCHAR (50)   NULL,
    [IsInternal]                 INT            CONSTRAINT [DF_T_TradedOrders_IsInternal1] DEFAULT ((1)) NOT NULL,
    [StrikePrice]                FLOAT (53)     NULL,
    [PutOrCall]                  INT            NULL,
    [FXRate]                     FLOAT (53)     NULL,
    [FXConversionMethodOperator] CHAR (5)       NULL,
    [ExpirationDate]             DATETIME       NULL,
    [ProcessDate]                DATETIME       CONSTRAINT [DF_T_TradedOrders_ProcessDate] DEFAULT (((1)/(1))/(1800)) NULL,
    [OriginalPurchaseDate]       DATETIME       CONSTRAINT [DF_T_TradedOrders_OriginalPurchaseDate] DEFAULT (((1)/(1))/(1800)) NULL,
    [ModifiedUserID]                 INT            NULL,
    [ModifiedDate]               DATETIME       NULL,
    [IsModified]                 BIT            NULL,
    [MultiTradeName]             NVARCHAR (500) NULL,
    [ImportFileID]               INT            NULL,
    [TradeAttribute1]            VARCHAR (200)  DEFAULT ('') NULL,
    [TradeAttribute2]            VARCHAR (200)  DEFAULT ('') NULL,
    [TradeAttribute3]            VARCHAR (200)  DEFAULT ('') NULL,
    [TradeAttribute4]            VARCHAR (200)  DEFAULT ('') NULL,
    [TradeAttribute5]            VARCHAR (200)  DEFAULT ('') NULL,
    [TradeAttribute6]            VARCHAR (200)  DEFAULT ('') NULL,
    [InternalComments]           VARCHAR (500)  NULL,
    [SettlCurrency]              INT            NULL,
    [ChangeType]                 INT            DEFAULT ((3)) NOT NULL,
	[OriginalAllocationPreferenceID]  INT       NULL,
	[TransactionSource]			 INT			DEFAULT 0 NULL,
    [AdditionalTradeAttributes] NVARCHAR(MAX) 	NULL
    CONSTRAINT [FK_T_TradedOrders_T_ImportFileLog] FOREIGN KEY ([ImportFileID]) REFERENCES [dbo].[T_ImportFileLog] ([ImportFileID]),
); --ON [PS_Year] ([AUECLocalDate]);


GO
CREATE NONCLUSTERED INDEX [_dta_index_T_TradedOrders_9_1557020728__K53_1]
    ON [dbo].[T_TradedOrders]([GroupID] ASC);
    -- ON [PS_Year] ([AUECLocalDate]);

