CREATE TABLE [dbo].[T_UserOptionModelInput] (
    [ID]                        BIGINT        IDENTITY (1, 1) NOT NULL,
    [Symbol]                    VARCHAR (100) NOT NULL,
    [HistoricalVolatility]      FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [HistoricalVolatilityUsed]  BIT           CONSTRAINT [DF_T_UserOptionModelInput_HistoricalVolatilityUsed] DEFAULT ((0)) NOT NULL,
    [UserVolatility]            FLOAT (53)    CONSTRAINT [DF_T_UserOptionModelInput_UserVolatility] DEFAULT ((0)) NOT NULL,
    [UserVolatilityUsed]        BIT           CONSTRAINT [DF_T_UserOptionModelInput_UserVolatilityUsed] DEFAULT ((0)) NOT NULL,
    [UserInterestRate]          FLOAT (53)    CONSTRAINT [DF_T_UserOptionModelInput_UserInterestRate] DEFAULT ((0)) NOT NULL,
    [UserInterestRateUsed]      BIT           CONSTRAINT [DF_T_UserOptionModelInput_UserInterestRateUsed] DEFAULT ((0)) NOT NULL,
    [UserDividend]              FLOAT (53)    CONSTRAINT [DF_T_UserOptionModelInput_UserDividend] DEFAULT ((0)) NOT NULL,
    [UserDividendUsed]          BIT           CONSTRAINT [DF_T_UserOptionModelInput_UserDividendUsed] DEFAULT ((0)) NOT NULL,
    [UserStockBorrowCost]       FLOAT (53)    CONSTRAINT [DF_T_UserOptionModelInput_UserStockBorrowCost] DEFAULT ((0)) NOT NULL,
    [UserStockBorrowCostUsed]   BIT           CONSTRAINT [DF_T_UserOptionModelInput_UserStockBorrowCostUsed] DEFAULT ((0)) NOT NULL,
    [UserDelta]                 FLOAT (53)    CONSTRAINT [DF_T_UserOptionModelInput_UserDelta] DEFAULT ((1)) NOT NULL,
    [UserDeltaUsed]             BIT           CONSTRAINT [DF_T_UserOptionModelInput_UserDeltaUsed] DEFAULT ((0)) NOT NULL,
    [UserLastPrice]             FLOAT (53)    CONSTRAINT [DF_T_UserOptionModelInput_UserLastPrice] DEFAULT ((0)) NOT NULL,
    [UserLastPriceUsed]         BIT           CONSTRAINT [DF_T_UserOptionModelInput_UserLastPriceUsed] DEFAULT ((0)) NOT NULL,
    [UserForwardPoints]         FLOAT (53)    DEFAULT ('0') NOT NULL,
    [UserForwardPointsUsed]     BIT           DEFAULT ('0') NOT NULL,
    [UserProxySymbolUsed]       BIT           DEFAULT ((0)) NULL,
    [UserTheoreticalPriceUsed]  BIT           NULL,
    [UserSharesOutstandingUsed] BIT           DEFAULT ((0)) NOT NULL,
    [UserSharesOutstanding]     FLOAT (53)    DEFAULT ((0)) NOT NULL,
	[SMUserSharesOutstandingUsed] BIT         DEFAULT ((0)) NOT NULL,
    [SMUserSharesOutstanding]   FLOAT (53)    DEFAULT ((0)) NOT NULL,
    [UserClosingMarkUsed]       BIT           DEFAULT ((0)) NOT NULL,
    [IsManuallyAdded]           BIT           DEFAULT ((0)) NULL,
    CONSTRAINT [PK_T_UserOptionModelInput] PRIMARY KEY CLUSTERED ([ID] ASC)
);

