CREATE TABLE [dbo].[T_XmlData4] (
    [Side]                 VARCHAR (50)  NULL,
    [Symbol]               VARCHAR (50)  NULL,
    [ExecQty]              FLOAT (53)    NULL,
    [AveragePrice]         FLOAT (53)    NULL,
    [OrderTypeTag]         VARCHAR (100) NULL,
    [OrderType]            VARCHAR (50)  NULL,
    [AssetID]              INT           NULL,
    [Asset]                VARCHAR (50)  NULL,
    [UnderLyingID]         INT           NULL,
    [UnderLying]           VARCHAR (50)  NULL,
    [ExchangeID]           INT           NULL,
    [Exchange]             VARCHAR (50)  NULL,
    [CurrencyID]           INT           NULL,
    [Currency]             VARCHAR (50)  NULL,
    [AUECID]               INT           NULL,
    [SecFees]              FLOAT (53)    NULL,
    [CommissionRate]       FLOAT (53)    NULL,
    [CommissionCharged]    FLOAT (53)    NULL,
    [GrossAmt]             FLOAT (53)    NULL,
    [NetAmt]               FLOAT (53)    NULL,
    [SecurityIDType]       VARCHAR (50)  NULL,
    [CommissionRateTypeID] INT           NULL,
    [CommissionRateType]   VARCHAR (50)  NULL,
    [CompanyCVID]          INT           NULL,
    [CVName]               VARCHAR (50)  NULL,
    [CVIdentifier]         VARCHAR (50)  NULL,
    [Percentage]           FLOAT (53)    NULL,
    [OrderQty]             BIGINT        NULL,
    [EntityID]             VARCHAR (50)  NULL,
    [OrderTag]             VARCHAR (50)  NULL,
    [CounterPartyID]       INT           NULL,
    [CounterParty]         VARCHAR (50)  NULL,
    [TradAccntID]          INT           NULL,
    [AlllocQty]            FLOAT (53)    NULL,
    [TotalQty]             BIGINT        NULL,
    [FundName]             VARCHAR (50)  NULL,
    [FundMappedName]       VARCHAR (50)  NULL,
    [FundAccountNo]        VARCHAR (50)  NULL,
    [FundTypeID]           INT           NULL,
    [FundType]             VARCHAR (10)  NULL,
    [CompanyFundID]        INT           NULL
);

