CREATE TABLE [dbo].[TempPositionsAndAllocatedTrades] (
    [TaxLotID]         VARCHAR (50)     NULL,
    [TradeDate]        DATETIME         NULL,
    [SideID]           VARCHAR (3)      NULL,
    [Side]             VARCHAR (20)     NULL,
    [Symbol]           VARCHAR (100)    NULL,
    [Quantity]         INT              NULL,
    [AveragePrice]     FLOAT (53)       NULL,
    [FundID]           INT              NULL,
    [FundName]         VARCHAR (100)    NULL,
    [IsPosition]       BIT              NULL,
    [AUECID]           INT              NULL,
    [PositionID]       UNIQUEIDENTIFIER NULL,
    [StartTaxLotID]    VARCHAR (50)     NULL,
    [Status]           INT              NULL,
    [OpenClose]        CHAR (1)         NULL,
    [RealizedPNL]      FLOAT (53)       NULL,
    [StartingQuantity] INT              NULL,
    [Commission]       FLOAT (53)       NULL,
    [Fees]             FLOAT (53)       NULL,
    [Notional]         FLOAT (53)       NULL,
    [CounterPartyID]   INT              NULL,
    [VenueID]          INT              NULL,
    [ISBasketOrder]    BIT              NULL,
    [RuleID]           INT              NULL,
    [IsTaxLotActive]   BIT              NULL,
    [Multiplier]       FLOAT (53)       CONSTRAINT [DF__TempPosit__Multi__20A37C41] DEFAULT ((1)) NULL
);

