CREATE TABLE [dbo].[TempPositions] (
    [PositionID]            UNIQUEIDENTIFIER NULL,
    [NetQuantity]           INT              NULL,
    [ModifiedByID]          INT              NULL,
    [RealizedPNL]           FLOAT (53)       NULL,
    [ApplicationTaxLotID]   INT              NULL,
    [Symbol]                VARCHAR (100)    NULL,
    [FundID]                INT              NULL,
    [ThirdPartyID]          INT              NULL,
    [CostBasis]             FLOAT (53)       NULL,
    [PositionType]          INT              NULL,
    [AUECID]                INT              NULL,
    [StartQuantity]         INT              NULL,
    [SymbolConventionID]    INT              NULL,
    [Description]           VARCHAR (4000)   NULL,
    [CounterPartyID]        INT              NULL,
    [OtherCounterPartyName] VARCHAR (200)    NULL,
    [VenueID]               INT              NULL,
    [OtherVenueName]        VARCHAR (200)    NULL,
    [Multiplier]            FLOAT (53)       NULL,
    [StrategyID]            INT              NULL,
    [Asset]                 VARCHAR (100)    NULL,
    [Underlying]            VARCHAR (100)    NULL,
    [Exchange]              VARCHAR (100)    NULL,
    [Currency]              VARCHAR (100)    NULL,
    [InstrumentType]        VARCHAR (10)     NULL,
    [Commission]            FLOAT (53)       NULL,
    [Fees]                  FLOAT (53)       NULL
);

