CREATE TABLE [dbo].[TempFundPositionsForDate] (
    [TaxLotID]                      VARCHAR (50)     NULL,
    [TradeDate]                     DATETIME         NULL,
    [SideID]                        VARCHAR (3)      NULL,
    [Side]                          VARCHAR (20)     NULL,
    [Symbol]                        VARCHAR (100)    NULL,
    [OpenQuantity]                  INT              NULL,
    [AveragePrice]                  FLOAT (53)       NULL,
    [FundID]                        INT              NULL,
    [FundName]                      VARCHAR (100)    NULL,
    [IsPosition]                    BIT              NULL,
    [AUECID]                        INT              NULL,
    [PositionID]                    UNIQUEIDENTIFIER NULL,
    [RealizedPNL]                   FLOAT (53)       NULL,
    [StartingQuantity]              INT              NULL,
    [Commission]                    FLOAT (53)       NULL,
    [Fees]                          FLOAT (53)       NULL,
    [Multiplier]                    FLOAT (53)       CONSTRAINT [DF__TempFundP__Multi__1AA08A28] DEFAULT ((1)) NULL,
    [ParentPositionBalanceQuantity] INT              NULL,
    [MarkPriceForMonth]             FLOAT (53)       NULL,
    [MonthsProfit]                  FLOAT (53)       NULL,
    [SymbolAveragePrice]            FLOAT (53)       NULL,
    [ThirdPartyID]                  INT              NULL,
    [TodayMark]                     FLOAT (53)       NULL,
    [YesterdayMark]                 FLOAT (53)       NULL,
    [DayPNL]                        FLOAT (53)       NULL,
    [SettlementDate]                DATETIME         NULL,
    [VsCurrencyID]                  INT              NULL
);

