package prana.basketComplianceService.amqpCollectors;
import java.util.Date;

public class TaxlotEntities {
	String basketId  = "";
	String taxlotId  = "";
	String clOrderId  = "";
	String userId  = "";
	String taxlotType  = "";
	String taxlotState  = "";
	String symbol  = "";
	String underlyingSymbol  = "";
	String orderSideTagValue  = "";
	String orderTypeTagValue  = "";
	String conversionMethodOperator  = "";
	String tif  = "";
	String orderSide  = "";
	String counterParty  = "";
	String venue  = "";
	String orderType  = "";
	String underlyingAsset  = "";
	Date auecLocalDate;
	Date settlementDate;
	boolean	isSwapped = false;
	boolean	isWhatIfTradeStreamRequired = false;
	int accountId = 0;
	int counterPartyId = 0;
	int venueId = 0;
	int strategyId = 0;
	int sideMultiplier = 0;
	double quantity = 0.0;
	double avgPrice = 0.0;
	double benchMarkRate = 0.0;
	double differential = 0.0;
	double swapNotional = 0.0;
	double dayCount = 0.0;
	double avgFxRateForTrade = 0.0;
	double limitPrice = 0.0;
	double stopPrice = 0.0;
	int assetId = 0;
	String asset = "";
	int auecId = 0;
	double multiplier = 0.0;
	String tradeAttribute1 = "";
	String tradeAttribute2 = "";
	String tradeAttribute3 = "";
	String tradeAttribute4 = "";
	String tradeAttribute5 = "";
	String tradeAttribute6 = "";
}
