using Infragistics.Win.UltraWinGrid;
using Prana.BusinessObjects;
using Prana.BusinessObjects.AppConstants;
using Prana.BusinessObjects.PositionManagement;
using Prana.LogManager;
using Prana.PM.BLL;
using Prana.PM.DAL;
using Prana.Utilities.MiscUtilities;
using Prana.Utilities.UI.UIUtilities;
using System;
using System.IO;
using System.Windows.Forms;

namespace Prana.PM.Admin.UI.Controls
{
    public partial class CtrlRunDownloadSetup : UserControl
    {

        private UploadClientSetUpList _setUploadList = new UploadClientSetUpList();

        // Applicatipon startup path
        //static string _starpUpPath = System.Windows.Forms.Application.StartupPath;


        UltraGridBand _gridBandRunUploadSetUp = null;

        Prana.BusinessObjects.PositionManagement.CompanyNameID _companyNameIDVaue = null;

        #region Grid Column Names

        const string COL_CompanyUploadSetupID = "CompanyUploadSetupID";
        const string COL_CompanyNameIDValue = "CompanyNameIDValue";
        const string COL_CompanyID = "CompanyID";
        const string COL_DataSourceNameIDValue = "DataSourceNameIDValue";
        const string COL_ThirdPartyID = "ThirdPartyID";
        const string COL_AutoImport = "AutoImport";
        const string COL_AutoTime = "AutoTime";
        const string COL_FTPServer = "FTPServer";
        const string COL_FTPFilePath = "FTPFilePath";
        const string COL_Port = "Port";
        const string COL_UserName = "UserName";
        const string COL_Password = "Password";
        const string COL_DirPath = "DirPath";
        const string COL_FileName = "FileName";
        const string COL_Status = "Status";
        const string COL_NumberOfRecords = "TotalRecords";
        const string COL_TableTypeID = "TableTypeID";
        const string COL_FileLayoutType = "FileLayoutType";

        #endregion Grid Column Names



        /// <summary>
        /// Initializes a new instance of the <see cref="CtrlRunUploadSetup"/> class.
        /// Contains InitializeComponent() method which is generated by the designer itself. 
        /// </summary>
        public CtrlRunDownloadSetup()
        {
            InitializeComponent();
        }

        /// <summary>
        /// Handles the Load event of the CtrlRunUploadSetup control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void CtrlRunUploadSetup_Load(object sender, EventArgs e)
        {

        }

        /// <summary>
        /// Handles the Click event of the btnCancel control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void btnCancel_Click(object sender, EventArgs e)
        {
            try
            {
                //foreach (SetUploadClient item in this._setUploadList)
                //{
                //    item.CancelEdit();

                //}

                //this._setUploadList.CancelEdit();
                //this.FindForm().Close();
                _setUploadList.CancelEdit();
                //TODO:  have to check why it is working as its this clear functionality's flow is quite different from other controls. 
                _setUploadList.BeginEdit(); //For a change had to apply the begin edit here as clear functionality just worked after trying too many times. 

            }
            catch (Exception ex)
            {

                // Invoke our policy that is responsible for making sure no secure information
                // gets out of our layer.
                MessageBox.Show(ex.Message.ToString());
                bool rethrow = Logger.HandleException(ex, LoggingConstants.POLICY_LOGANDSHOW);
                if (rethrow)
                {
                    throw;
                }
            }
        }

        /// <summary>
        /// Handles the Click event of the btnRemove control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void btnRemove_Click(object sender, EventArgs e)
        {
            gridRunUploadSetUp.ActiveRow.Delete(true);
            this.bindingSourceRunUploadSetUp.ResetBindings(false);
        }

        /// <summary>
        /// Handles the Click event of the btnSave control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void btnSave_Click(object sender, EventArgs e)
        {
            try
            {
                bool isCollectionValid = true;
                foreach (SetUploadClient setUploadClient in _setUploadList)
                {
                    if (!setUploadClient.IsValid)
                    {
                        isCollectionValid = false;
                        break;
                    }
                }
                if (isCollectionValid)
                {
                    _setUploadList.ApplyEdit();
                    //foreach (SetUploadClient item in this._setUploadList)
                    //{
                    //    //item.ApplyEdit();
                    //}
                    //This adds the binary converted content in the all SetUploadClients in SetUploadList
                    SetXSLTBinaryData(_setUploadList);
                    RunUploadManager.SaveRunUploadSetupList(_setUploadList);

                    //Additional code for separately saving the XSLT Files
                    // THIS CODE COULD BE REMOVED LATER IF A SOLUTION TO XML SERIALIZATION ISSUE IS FOUND
                    //SetXSLTBinaryData(_setUploadList);  
                    //RunUploadManager.SaveRunUploadSetupListAndXSLT(_setUploadList);                   
                    //_setUploadList.BeginEdit();
                    MessageBox.Show(this, "Run Upload information saved !", "Import Setup", MessageBoxButtons.OK, MessageBoxIcon.Information);
                    InitializeControl();
                }
            }
            catch (Exception ex)
            {

                // Invoke our policy that is responsible for making sure no secure information
                // gets out of our layer.
                bool rethrow = Logger.HandleException(ex, LoggingConstants.POLICY_LOGANDSHOW);
                if (rethrow)
                {
                    throw;
                }
            }
        }

        private static void SetXSLTBinaryData(UploadClientSetUpList _setUploadList)
        {
            foreach (SetUploadClient item in _setUploadList)
            {
                item.LastSaveTime = DateTime.UtcNow.Date;
                item.MappingFileType = Convert.ToInt32(Prana.Global.ApplicationConstants.MappingFileType.PMImportXSLT);
                // If a file is not reselected or newly entered...
                // ...then the data already present is not to be modified in db
                if (item.DataSourceXSLT.Contains("\\"))
                {
                    item.DataSourceXSLTBinaryData = TransformToBinary(item.DataSourceXSLT);
                    item.DataSourceXSLT = GetFileNameFromPath(item.DataSourceXSLT);
                }
            }
        }

        private static string GetFileNameFromPath(string path)
        {
            return path.Substring(path.LastIndexOf("\\") + 1);
        }

        private static byte[] TransformToBinary(string path)
        {
            // Get binary only if the file is reselected else no need to send data to db
            if (path != "" && path.Contains("\\"))
            {
                FileStream fs = null;
                BinaryReader br = null;
                fs = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
                br = new BinaryReader(fs);
                byte[] data = new byte[fs.Length];
                int length = (int)fs.Length;
                br.Read(data, 0, length);

                if (fs != null)
                {
                    fs.Close();
                    // br.Close();
                }

                return data;
            }
            else
            {
                return null;
            }
        }

        /// <summary>
        /// Handles the Click event of the btnEdit control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void btnEdit_Click(object sender, EventArgs e)
        {

        }


        /// <summary>
        /// Populates the upload set up details.
        /// </summary>
        /// <param name="selectedTreeNodeID">The selected tree node ID.</param>
        public void PopulateUploadSetUpDetails(Prana.BusinessObjects.PositionManagement.CompanyNameID companyNameIDVaue)
        {
            try
            {
                //btnCancel.Visible = false;
                //_setUploadList.BeginEdit();
                _companyNameIDVaue = companyNameIDVaue;
                if (companyNameIDVaue.ID <= 0)
                {
                    RefreshControls();
                }
                else
                {
                    //_setUploadList.BeginEdit();
                    // get FTP File Path
                    InitializeControl();
                }
            }
            catch (Exception ex)
            {
                string s = ex.Message;
                throw;
            }
        }
        //string _filePath = Application.StartupPath + @"\DataSource Files\";
        private void InitializeControl()
        {

            _setUploadList = RunUploadManager.GetRunUploadSetupDetails(_companyNameIDVaue);
            _setUploadList.BeginEdit();
            bindingSourceRunUploadSetUp.DataSource = _setUploadList;
            gridRunUploadSetUp.DataSource = _setUploadList;
            BindGridComboBoxes();
        }

        public void RefreshControls()
        {
            _setUploadList = new UploadClientSetUpList();
            gridRunUploadSetUp.DataSource = _setUploadList;
        }


        //private UltraDropDown _layoutTypeList = new UltraDropDown();
        /// <summary>
        /// Binds the grid combo boxes.
        /// </summary>
        private void BindGridComboBoxes()
        {

            try
            {
                SortableSearchableList<ThirdPartyNameID> dataSourceNameIDList = Prana.PM.DAL.DataSourceManager.RetrieveDataSourceNames(true, false);
                SortableSearchableList<ThirdPartyNameID> dataSourceNameIDListUpdated = new SortableSearchableList<ThirdPartyNameID>();
                foreach (ThirdPartyNameID dataSourceNameID in dataSourceNameIDList)
                {
                    DataSourceTable dataSourceTable = Prana.PM.DAL.DataSourceManager.GetDataSourceTable(dataSourceNameID.ID);
                    //if (dataSourceTable.TableName != null || dataSourceNameID.ID == -1)                   
                    // {
                    dataSourceNameIDListUpdated.Add(dataSourceNameID);
                    //}
                }

                //cmbDataSources.DataSource = DataSourceNameIDList.GetInstance().Retrieve;
                cmbDataSources.DataSource = null;
                cmbDataSources.DataSource = dataSourceNameIDListUpdated;
                cmbDataSources.DisplayMember = "ShortName";
                cmbDataSources.ValueMember = "ID";
                Utils.UltraDropDownFilter(cmbDataSources, "ShortName");

                TableTypeList tableTypeList = DataSourceManager.GetTableTypes(false);
                cmbTableTypes.DataSource = null;
                cmbTableTypes.DataSource = tableTypeList;
                cmbTableTypes.DisplayMember = "TableTypeName";
                cmbTableTypes.ValueMember = "TableTypeID";
                Utils.UltraDropDownFilter(cmbTableTypes, "TableTypeName");
                cmbTableTypes.Text = "Transaction";


                cmbLayoutTypes.DisplayMember = "DisplayText";
                cmbLayoutTypes.ValueMember = "Value";
                cmbLayoutTypes.DataSource = null;
                cmbLayoutTypes.DataSource = EnumHelper.ConvertEnumForBindingWithAssignedValues(typeof(DataSourceFileLayout));
                Utils.UltraDropDownFilter(cmbLayoutTypes, "DisplayText");



                //_layoutTypeList.DataSource = 
                //_layoutTypeList.DisplayMember = "Name";
                //_layoutTypeList.ValueMember = "Value";
                //Utils.UltraDropDownFilter(_layoutTypeList, "Name");

                //Type enumType = typeof(Prana.PM.MultiLayoutParse.DataSourceFileLayout);
                //string[] members = Enum.GetNames(enumType); 
                //foreach (string member in members)
                //{
                //    string name = member;
                //    object value = Enum.Parse(enumType, name);

                //}      
            }
            catch (Exception ex)
            {
                string s = ex.Message;
                throw;
            }

        }

        /// <summary>
        /// Handles the InitializeLayout event of the gridRunUploadSetUp control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="Infragistics.Win.UltraWinGrid.InitializeLayoutEventArgs"/> instance containing the event data.</param>
        private void gridRunUploadSetUp_InitializeLayout(object sender, InitializeLayoutEventArgs e)
        {
            //gridRunUploadSetUp.DisplayLayout.AutoFitStyle = AutoFitStyle.ResizeAllColumns;
            gridRunUploadSetUp.DisplayLayout.ScrollBounds = ScrollBounds.ScrollToLastItem;
            gridRunUploadSetUp.DisplayLayout.Override.AllowAddNew = AllowAddNew.Yes;
            gridRunUploadSetUp.DisplayLayout.Override.AllowDelete = Infragistics.Win.DefaultableBoolean.False;
            gridRunUploadSetUp.DisplayLayout.Override.AllowGroupBy = Infragistics.Win.DefaultableBoolean.False;
            gridRunUploadSetUp.DisplayLayout.Override.RowSelectors = Infragistics.Win.DefaultableBoolean.True;
            gridRunUploadSetUp.DisplayLayout.Override.AllowColSwapping = AllowColSwapping.NotAllowed;
            gridRunUploadSetUp.DisplayLayout.Override.HeaderAppearance.TextHAlign = Infragistics.Win.HAlign.Center;


            _gridBandRunUploadSetUp = gridRunUploadSetUp.DisplayLayout.Bands[0];
            _gridBandRunUploadSetUp.Override.AllowColSwapping = AllowColSwapping.NotAllowed;

            //UltraGridColumn colStatus = _gridBandRunUploadSetUp.Columns[COL_Status];
            //colStatus.Hidden = true;

            UltraGridColumn colID = _gridBandRunUploadSetUp.Columns[COL_CompanyUploadSetupID];
            colID.Hidden = true;

            //UltraGridColumn colTotalRecords = _gridBandRunUploadSetUp.Columns[COL_NumberOfRecords];
            //colTotalRecords.Hidden = true;


            UltraGridColumn colCompanyNameID = _gridBandRunUploadSetUp.Columns[COL_CompanyNameIDValue];
            colCompanyNameID.Hidden = true;


            UltraGridColumn colCompanyID = _gridBandRunUploadSetUp.Columns[COL_CompanyID];
            colCompanyID.Hidden = true;

            //colCompanyID.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.DropDownList;
            //colCompanyID.ButtonDisplayStyle = ButtonDisplayStyle.Always;
            ////Get the list of all companies.
            //colCompanyID.ValueList = cmbCompanies;
            //colCompanyID.Header.Caption = "Company";
            //colCompanyID.Header.VisiblePosition = 1;

            UltraGridColumn colDataSourceNameID = _gridBandRunUploadSetUp.Columns[COL_DataSourceNameIDValue];
            colDataSourceNameID.Hidden = true;

            UltraGridColumn colThirdPartyID = _gridBandRunUploadSetUp.Columns[COL_ThirdPartyID];
            colThirdPartyID.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.DropDownList;
            colThirdPartyID.ButtonDisplayStyle = ButtonDisplayStyle.Always;
            colThirdPartyID.ValueList = cmbDataSources;
            colThirdPartyID.Header.Caption = "Upload ThirdParty";
            colThirdPartyID.Header.VisiblePosition = 2;

            UltraGridColumn colTableTypeID = _gridBandRunUploadSetUp.Columns[COL_TableTypeID];
            colTableTypeID.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.DropDownList;
            colTableTypeID.ButtonDisplayStyle = ButtonDisplayStyle.Always;
            colTableTypeID.ValueList = cmbTableTypes;
            colTableTypeID.Header.Caption = "Table Type";
            colTableTypeID.Header.VisiblePosition = 3;
            colTableTypeID.Width = 85;

            UltraGridColumn colTableFormatName = _gridBandRunUploadSetUp.Columns["TableFormatName"];
            colTableFormatName.ButtonDisplayStyle = ButtonDisplayStyle.Always;
            colTableFormatName.CellActivation = Activation.AllowEdit;
            colTableFormatName.Header.VisiblePosition = 4;
            colTableFormatName.Header.Caption = "Table Type Format Name";
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns["TableFormatName"].Nullable = Infragistics.Win.UltraWinGrid.Nullable.EmptyString;

            UltraGridColumn colAutoImport = _gridBandRunUploadSetUp.Columns[COL_AutoImport];
            colAutoImport.Header.Caption = "Enable Local Auto Import";
            //colAutoImport.Hidden = true;
            colAutoImport.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.CheckBox;

            colAutoImport.Header.VisiblePosition = 5;

            UltraGridColumn colAutoTime = _gridBandRunUploadSetUp.Columns[COL_AutoTime];
            colAutoTime.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.TimeWithSpin;
            colAutoTime.Header.Caption = "Auto Time";
            colAutoTime.Header.VisiblePosition = 6;
            colAutoTime.Hidden = true;// By Sandeep as on 16-Nov-2006

            UltraGridColumn colFTPFilePath = _gridBandRunUploadSetUp.Columns[COL_FTPFilePath];
            colFTPFilePath.Header.Caption = "FTP File Path";
            colFTPFilePath.Header.VisiblePosition = 7;
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns[COL_FTPFilePath].Nullable = Infragistics.Win.UltraWinGrid.Nullable.EmptyString;

            UltraGridColumn colFTPServer = _gridBandRunUploadSetUp.Columns[COL_FTPServer];
            colFTPServer.Header.Caption = "FTP Server";
            colFTPServer.Header.VisiblePosition = 8;
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns[COL_FTPServer].Nullable = Infragistics.Win.UltraWinGrid.Nullable.EmptyString;

            UltraGridColumn colServerPort = _gridBandRunUploadSetUp.Columns[COL_Port];
            colServerPort.Header.Caption = "Server Port";
            colServerPort.Header.VisiblePosition = 9;
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns[COL_Port].Nullable = Infragistics.Win.UltraWinGrid.Nullable.EmptyString;
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns[COL_Port].InvalidValueBehavior = InvalidValueBehavior.RevertValueAndRetainFocus;

            UltraGridColumn colUserName = _gridBandRunUploadSetUp.Columns[COL_UserName];
            colUserName.Header.Caption = "User Name";
            colUserName.Header.VisiblePosition = 10;
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns[COL_UserName].Nullable = Infragistics.Win.UltraWinGrid.Nullable.EmptyString;

            UltraGridColumn colPassword = _gridBandRunUploadSetUp.Columns[COL_Password];
            colPassword.Header.Caption = "Password";
            colPassword.Header.VisiblePosition = 11;
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns[COL_Password].Nullable = Infragistics.Win.UltraWinGrid.Nullable.EmptyString;

            UltraGridColumn colDirPath = _gridBandRunUploadSetUp.Columns[COL_DirPath];
            colDirPath.Header.VisiblePosition = 12;
            colDirPath.Header.Caption = "Dir Path";
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns[COL_DirPath].CellActivation = Activation.AllowEdit;
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns[COL_DirPath].Nullable = Infragistics.Win.UltraWinGrid.Nullable.EmptyString;

            UltraGridColumn colFileName = _gridBandRunUploadSetUp.Columns[COL_FileName];
            colFileName.Header.VisiblePosition = 13;
            colFileName.Header.Caption = "File Name";
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns[COL_FileName].Nullable = Infragistics.Win.UltraWinGrid.Nullable.EmptyString;

            UltraGridColumn colFileLayoutType = _gridBandRunUploadSetUp.Columns[COL_FileLayoutType];
            colFileLayoutType.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.DropDownList;
            colFileLayoutType.ButtonDisplayStyle = ButtonDisplayStyle.Always;
            colFileLayoutType.ValueList = cmbLayoutTypes;
            colFileLayoutType.Header.VisiblePosition = 14;
            colFileLayoutType.Header.Caption = "File Layout";
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns[COL_FileLayoutType].Nullable = Infragistics.Win.UltraWinGrid.Nullable.EmptyString;

            UltraGridColumn colDataSourceXSLT = _gridBandRunUploadSetUp.Columns["DataSourceXSLT"];
            colDataSourceXSLT.ButtonDisplayStyle = ButtonDisplayStyle.Always;
            colDataSourceXSLT.CellActivation = Activation.NoEdit;
            colDataSourceXSLT.Header.VisiblePosition = 15;
            colDataSourceXSLT.Header.Caption = "ThirdParty XSLT";
            gridRunUploadSetUp.DisplayLayout.Bands[0].Columns["DataSourceXSLT"].Nullable = Infragistics.Win.UltraWinGrid.Nullable.EmptyString;


            if (!_gridBandRunUploadSetUp.Columns.Exists("SelectXSLT"))
            {
                UltraGridColumn colXSLTSelectButton = _gridBandRunUploadSetUp.Columns.Add("SelectXSLT");
                colXSLTSelectButton.Style = Infragistics.Win.UltraWinGrid.ColumnStyle.Button;
                colXSLTSelectButton.ButtonDisplayStyle = ButtonDisplayStyle.Always;
                colXSLTSelectButton.Header.VisiblePosition = 16;
                colXSLTSelectButton.Header.Caption = "Select XSLT";
                colXSLTSelectButton.NullText = "Select XSLT";
                colXSLTSelectButton.Width = 75;
                colXSLTSelectButton.Hidden = false;
            }

        }

        /// <summary>
        /// Handles the Click event of the btnAddNew control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void btnAddNew_Click(object sender, EventArgs e)
        {

            try
            {
                if (_companyNameIDVaue == null)
                {
                    return;
                }

                SetUploadClient item = new SetUploadClient();
                item.CompanyID = _companyNameIDVaue.ID;
                item.ThirdPartyID = -1;
                item.AutoTime = new DateTime(DateTime.UtcNow.Year, DateTime.UtcNow.Month, DateTime.UtcNow.Day);

                item.FTPFilePath = string.Empty;
                item.FTPServer = string.Empty;
                //item.Port
                item.UserName = string.Empty;
                item.Password = string.Empty;
                item.DirPath = Application.StartupPath + @"\DataSource Files\";
                item.FileName = string.Empty;
                item.DataSourceXSLT = string.Empty;
                item.TableFormatName = string.Empty;
                _setUploadList.Add(item);
            }
            catch (Exception ex)
            {

                // Invoke our policy that is responsible for making sure no secure information
                // gets out of our layer.
                bool rethrow = Logger.HandleException(ex, LoggingConstants.POLICY_LOGONLY);

                if (rethrow)
                {
                    throw;
                }
            }

        }

        private void gridRunUploadSetUp_CellChange(object sender, CellEventArgs e)
        {
            string check = "True";
            string auto = gridRunUploadSetUp.ActiveRow.Cells[COL_AutoImport].Text.ToString();
            if (auto == check)
            {
                gridRunUploadSetUp.ActiveRow.Cells[COL_AutoTime].Activation = Activation.AllowEdit;
            }
            else
            {
                gridRunUploadSetUp.ActiveRow.Cells[COL_AutoTime].Activation = Activation.Disabled;
            }
        }

        /// <summary>
        /// Handles the AfterRowActivate event of the gridRunUploadSetUp control.
        /// </summary>
        /// <param name="sender">The source of the event.</param>
        /// <param name="e">The <see cref="System.EventArgs"/> instance containing the event data.</param>
        private void gridRunUploadSetUp_AfterRowActivate(object sender, EventArgs e)
        {

        }

        private void gridRunUploadSetUp_BeforeRowActivate(object sender, RowEventArgs e)
        {

            //SetUploadClient activeItem = (SetUploadClient)e.Row.ListObject;
            //int indexOfItem = this._setUploadList.IndexOf(activeItem);
            //this._setUploadList[indexOfItem].BeginEdit();
        }

        private void gridRunUploadSetUp_Error(object sender, Infragistics.Win.UltraWinGrid.ErrorEventArgs e)
        {
            e.Cancel = true;
        }

        private void gridRunUploadSetUp_ClickCellButton(object sender, CellEventArgs e)
        {
            if (string.Equals(e.Cell.Column.Key, "SelectXSLT"))
            {
                string title = "Select XSLT ";
                string buttonKey = "SelectXSLT";
                string fileWithPath = GetFileName(title, buttonKey);
                if (!String.IsNullOrEmpty(fileWithPath))
                {
                    gridRunUploadSetUp.ActiveRow.Cells["DataSourceXSLT"].Value = fileWithPath;
                }

            }
        }

        private string GetFileName(string title, string buttonKey)
        {
            OpenFileDialog openFileDialog1 = new OpenFileDialog();
            openFileDialog1.InitialDirectory = "DeskTop";
            openFileDialog1.Title = title;
            if (buttonKey == "SelectXSLT")
            {
                openFileDialog1.Filter = "XSLT Files (*.xslt)|*.xslt";
            }
            string strFileName = string.Empty;
            if (openFileDialog1.ShowDialog() == DialogResult.OK)
            {
                strFileName = openFileDialog1.FileName;
            }
            return strFileName;

        }

    }
}
