GO
CREATE TABLE [dbo].[T_NT_AcctwiseStatus](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[AsOfDate] [smalldatetime] NOT NULL,
	[AcctId] [int] NOT NULL,
 CONSTRAINT [PK_T_NT_AcctwiseStatus] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO