SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[T_NT_ApprovedGenericPNL](
	[AsOfDate] [smalldatetime] NOT NULL,
	[CheckSumId] [varbinary](16) NOT NULL,
	[AcctId] [int] NOT NULL,
	[AcctName] [varchar](max) NOT NULL,
	[RunDate] [datetime] NOT NULL,
	[Symbol] [varchar](max) NOT NULL,
	[UnderlyingSymbol] [varchar](max) NOT NULL,
	[TradeDate] [datetime] NOT NULL,
	[ClosingDate] [datetime] NULL,
	[Open_CloseTag] [varchar](max) NOT NULL,
	[UdaSector] [varchar](max) NOT NULL,
	[UdaSubSector] [varchar](max) NOT NULL,
	[UdaCountry] [varchar](max) NOT NULL,
	[Strategy] [varchar](max) NOT NULL,
	[SymbolDescription] [varchar](max) NOT NULL,
	[UnderlyingSymbolDescription] [varchar](max) NOT NULL,
	[BloombergSymbol] [varchar](max) NOT NULL,
	[PutOrCall] [varchar](max) NOT NULL,
	[ExpirationDate] [datetime] NULL,
	[StrikePrice] [float] NOT NULL,
	[Delta] [float] NOT NULL,
	[Beta] [float] NOT NULL,
	[ImpliedVol] [float] NULL,
	[Asset] [varchar](max) NOT NULL,
	[SetupAsset] [varchar](max) NOT NULL,
	[CommissionAndFees] [bit] NOT NULL,
	[FXPNL] [bit] NOT NULL,
	[PriceMultiplier] [float] NOT NULL,
	[DeltaAdjPosMultiplier] [bit] NOT NULL,
	[ZeroOrEndingMVOrUnrealized] [int] NOT NULL,
	[CouponRate] [bit] NOT NULL,
	[BlackScholesOrBlack76] [bit] NOT NULL,
	[Side] [varchar](max) NOT NULL,
	[TradeCurrency] [varchar](max) NOT NULL,
	[OpeningFXRate] [float] NOT NULL,
	[BeginningFXRate] [float] NOT NULL,
	[EndingFXRate] [float] NOT NULL,
	[TotalCostLocal] [float] NOT NULL,
	[BeginningMarketValueLocal] [float] NOT NULL,
	[EndingMarketValueLocal] [float] NOT NULL,
	[TotalOpenCommissionAndFeesLocal] [float] NOT NULL,
	[TotalClosedCommissionAndFeesLocal] [float] NOT NULL,
	[DividendLocal] [float] NOT NULL,
	[TotalCostBase] [float] NOT NULL,
	[BeginningMarketValueBase] [float] NOT NULL,
	[EndingMarketValueBase] [float] NOT NULL,
	[TotalOpenCommissionAndFeesBase] [float] NOT NULL,
	[TotalClosedCommissionAndFeesBase] [float] NOT NULL,
	[DividendBase] [float] NOT NULL,
	[BeginningQuantity] [float] NOT NULL,
	[EndingQuantity] [float] NOT NULL,
	[Quantity] [float] NOT NULL,
	[UnitCostLocal] [float] NOT NULL,
	[BeginningPriceLocal] [float] NOT NULL,
	[ClosingPriceLocal] [float] NOT NULL,
	[EndingPriceLocal] [float] NOT NULL,
	[UnderlyingSymbolPriceLocal] [float] NOT NULL,
	[UnitCostBase] [float] NOT NULL,
	[BeginningPriceBase] [float] NOT NULL,
	[ClosingPriceBase] [float] NOT NULL,
	[EndingPriceBase] [float] NOT NULL,
	[UnderlyingSymbolPriceBase] [float] NOT NULL,
	[SideMultiplier] [float] NOT NULL,
	[Multiplier] [float] NOT NULL,
	[UnderlyingDelta] [float] NOT NULL,
	[TaxlotID] [varchar](50) NOT NULL,
	[TaxlotClosingID] [uniqueidentifier] NULL,
	[DaySplitFactor] [float] NOT NULL,
	[TillSplitFactor] [float] NOT NULL,
	[K0] [float] NULL,
	[K1] [float] NULL,
	[K2] [float] NULL,
	[AveDaystoLiquidate] [float] NULL,
	[DaysToLiquidate] [float] NULL,
	[AveNDaysTradingVolume] [float] NULL,
	[AveNDaysTradingValueLocal] [float] NULL,
	[AveNDaysTradingValueBase] [float] NULL,
	[BeginningDelta] [float] NOT NULL,
	[BeginningUnderlyingSymbolPriceLocal] [float] NOT NULL,
	[BeginningUnderlyingSymbolPriceBase] [float] NOT NULL,
 CONSTRAINT [PK_T_NT_ApprovedGenericPNL] PRIMARY KEY CLUSTERED 
(
	[AsOfDate] ASC,
	[CheckSumId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO