
IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='T_CA_RuleLevelUserPermissionTemp')
BEGIN
	DROP TABLE T_CA_RuleLevelUserPermissionTemp
END

IF EXISTS(SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME='T_CA_RuleLevelUserPermission')
BEGIN
	SELECT * INTO T_CA_RuleLevelUserPermissionTemp
	FROM T_CA_RuleLevelUserPermission
END
	
