CREATE PROCEDURE [dbo].[P_GetLastManualOrderTradesData]
	@LastManualOrderRunTriggerTime DATETIME,
	@AUECId int 
AS
	SELECT MsgType,
		TradingAccountID,
		ClOrderID ,
		AUECLocalDate,
		Quantity,
		SenderSubID,
		FundID,
		ExecutionInst,
		HandlingInst,
		OrderTypeTagValue,
		OrderSideTagValue,
		Symbol,
		TimeInForce,
		CounterPartyID,
		SendingTime,
		CurrencyID,
		OrderID,
		ExecType,
		LastPrice,
		LeavesQty,
		AvgPrice,
		OrderStatusTagValue,
		OrderTypeID,
		OrigClOrderID,
		CumQty,
		ExchangeID,
		ExecTransType,
		AUECID,
		LastShares
		FROM ( SELECT
		sub.MsgType,
		grp.TradingAccountID,
		sub.ClOrderID,
		ord.AUECLocalDate,
		sub.Quantity,
		ord.SenderSubID,
		sub.FundID,
		sub.ExecutionInst,
		sub.HandlingInst,
		sub.OrderTypeTagValue,
		ord.OrderSidetagValue as OrderSideTagValue,
		ord.Symbol,
		sub.TimeInForce,
		sub.CounterPartyID,
		fills.SendingTime,
		grp.CurrencyID,
		sub.OrderID,
		fills.ExecType,
		fills.LastPx as LastPrice,
		fills.LeavesQty,
		fills.AveragePrice as AvgPrice,
		fills.OrderStatus as OrderStatusTagValue,
		fills.OrderTypeID,
		sub.OrigClOrderID,
		fills.CumQty,
		fills.ExchangeID,
		fills.ExecTransType,
		grp.AUECID,
		fills.LastShares,
		ROW_NUMBER() OVER (
			PARTITION BY sub.ClOrderID
		    ORDER BY sub.InsertionTime, fills.CumQty) AS RowNumber
		FROM T_Sub as sub inner join T_TradedOrders as ord On sub.ClOrderID = ord.CLOrderID AND sub.StagedOrderID != ord.CLOrderID inner join T_Group AS grp ON ord.GroupID = grp.GroupID INNER JOIN T_Fills AS fills ON fills.ClOrderID = sub.ClOrderID
		WHERE grp.AUECID = @AUECId AND sub.StagedOrderID <> '' AND sub.IsManualOrder = 1  AND sub.InsertionTime > @LastManualOrderRunTriggerTime) AS Final
		WHERE RowNumber  = 1

	
	SELECT MsgType,
		TradingAccountID,
		ClOrderID ,
		AUECLocalDate,
		Quantity,
		SenderSubID,
		FundID,
		ExecutionInst,
		HandlingInst,
		OrderTypeTagValue,
		OrderSideTagValue,
		Symbol,
		TimeInForce,
		CounterPartyID,
		SendingTime,
		CurrencyID,
		OrderID,
		ExecType,
		LastPrice,
		LeavesQty,
		AvgPrice,
		OrderStatusTagValue,
		OrderTypeID,
		OrigClOrderID,
		CumQty,
		ExchangeID,
		ExecTransType,
		AUECID,
		LastShares
		FROM ( SELECT
		fills.MsgType,
		grp.TradingAccountID,
		sub.ClOrderID,
		ord.AUECLocalDate,
		sub.Quantity,
		ord.SenderSubID,
		sub.FundID,
		sub.ExecutionInst,
		sub.HandlingInst,
		sub.OrderTypeTagValue,
		ord.OrderSidetagValue as OrderSideTagValue,
		ord.Symbol,
		sub.TimeInForce,
		sub.CounterPartyID,
		fills.SendingTime,
		grp.CurrencyID,
		sub.OrderID,
		fills.ExecType,
		fills.LastPx as LastPrice,
		fills.LeavesQty,
		fills.AveragePrice as AvgPrice,
		fills.OrderStatus as OrderStatusTagValue,
		fills.OrderTypeID,
		sub.OrigClOrderID,
		fills.CumQty,
		fills.ExchangeID,
		fills.ExecTransType,
		grp.AUECID,
		fills.LastShares,
		ROW_NUMBER() OVER (
			PARTITION BY sub.ClOrderID
		    ORDER BY sub.InsertionTime DESC, fills.CumQty DESC) AS RowNumber
		FROM T_Sub as sub inner join T_TradedOrders as ord On sub.ClOrderID = ord.CLOrderID AND sub.StagedOrderID != ord.CLOrderID inner join T_Group AS grp ON ord.GroupID = grp.GroupID INNER JOIN T_Fills AS fills ON fills.ClOrderID = sub.ClOrderID
		WHERE grp.AUECID = @AUECId AND sub.StagedOrderID  <> '' AND sub.IsManualOrder = 1 AND fills.InsertionTime > @LastManualOrderRunTriggerTime) AS Final
		WHERE RowNumber  = 1

RETURN 0