CREATE PROCEDURE [dbo].[P_GetCurrencies]
AS
SELECT DISTINCT C.CURRENCYID
	,C.CURRENCYNAME
	,C.CURRENCYSYMBOL
FROM T_CURRENCY C
	--Rajat commented the following line 26 Sep 2006   
	--JOIN T_CURRENCYCONVERSION CC ON CC.FROMCURRENCYID = C.CURRENCYID OR CC.TOCURRENCYID = C.CURRENCYID  
