  
  
CREATE PROCEDURE [dbo].[P_SaveAlgoSyntheticReplaceOrderRequest] (  
@ClOrdID varchar(50),  
@TransactionTime varchar(50),  
@DiscretionOffset float,  
@ExecInst varchar(50),  
@HandlingInst char,  
@MsgType varchar(50),  
@OrderID varchar(500),  
@Side char,  
@OrderStatus char,  
@OrderType char,  
@OrigClOrderID varchar(50) ,  
@PegDiff float,  
@PNP int,  
@Price float,  
@Quantity float,  
@StopPrice float,  
--@SenderCompID varchar(50),  
--@SenderSubID,  
@Symbol varchar(50),  
@TargetCompID varchar(50),  
@TargetSubID varchar(50),  
@TimeInForce char,  
@Venue int,  
@ParentClOrderID varchar(50),  
@LocateReqd bit,  
@BorrowerID varchar(50),  
@ShortRebate float,  
@TradingAccountID int,  
@CompanyUserID int,  
@CounterPartyID int,  
@AuecID int,  
@StagedID varchar(50),  
@NirvanaMsgType int,  
--@DiscretionInst float,  
--@SendingTime varchar(50),  
@Text varchar(200),  
@StrategyID int,  
@FundID int,  
--@listID varchar(20),  
--@waveID varchar(20),  
@SecurityType varchar(20),  
@PutOrCall int,  
@MaturityMonthYear varchar(20),  
@StrikePrice float,  
@OpenClose char,  
@parentClientOrderID varchar(50),  
@clientOrderID varchar(50),  
  
--@TransactionTime varchar(50)  
@cmta varchar(20),  
@GiveUp varchar(20),  
@UnderlyingSymbol varchar(50),  
--@strikePrice float,  
@expirationDate varchar(20),  
@settlementDate varchar(20),  
@algoStrategyID varchar(10),  
@algoStrategyParameters varchar(500),  
@algoSyntheticRPLParent varchar(50)  
)  
  
   
AS  
Declare @result int  
  
 --Insert  
  
 --if ((@MsgType!='G' or  @MsgType!='F'))  
--if(@ParentClOrderID=@ClOrdID)  
begin  
Insert into AlgoSyntheticReplaceOrders  
(  
ClOrderID,  
TransactionTime,  
DiscretionOffset,  
ExecInst,  
HandlingInst,  
MsgType,  
OrderID,  
Side,  
OrderStatus,  
OrderType,  
OrigClOrderID,  
PegDiff,  
PNP,  
Price,  
Quantity,  
StopPrice,  
Symbol,  
TargetCompID,  
TargetSubID,  
TimeInForce,  
Venue,  
ParentClOrderID,  
LocateReqd,  
BorrowerID,  
ShortRebate,  
TradingAccountID,  
CompanyUserID,  
CounterPartyID,  
AuecID,  
StagedID,  
NirvanaMsgType,  
OrderText,  
StrategyID,  
FundID,  
SecurityType,  
PutOrCall,  
MaturityMonthYear,  
StrikePrice,  
OpenClose,  
ParentClientOrderID,  
ClientOrderID,  
Cmta,  
GiveUp,  
UnderlyingSymbol,  
ExpirationDate,  
SettlementDate,  
AlgoStrategyID,  
AlgoStrategyParameters,  
InsertionTime,  
AlgoSyntheticRPLParent  
   )  
Values(   
@ClOrdID ,  
@TransactionTime ,  
@DiscretionOffset ,  
@ExecInst ,  
@HandlingInst ,  
@MsgType ,  
@OrderID ,  
@Side ,  
@OrderStatus ,  
@OrderType ,  
@OrigClOrderID ,  
@PegDiff ,  
@PNP ,  
@Price ,  
@Quantity ,  
@StopPrice ,  
@Symbol ,  
@TargetCompID ,  
@TargetSubID ,  
@TimeInForce ,  
@Venue ,  
@ParentClOrderID ,  
@LocateReqd ,  
@BorrowerID ,  
@ShortRebate ,  
@TradingAccountID ,  
@CompanyUserID ,  
@CounterPartyID ,  
@AuecID ,  
@StagedID ,  
@NirvanaMsgType ,  
@Text ,  
@StrategyID ,  
@FundID ,  
--@listID ,  
--@waveID ,  
@SecurityType ,  
@PutOrCall ,  
@MaturityMonthYear,  
@StrikePrice ,  
@OpenClose,  
@parentClientOrderID,  
@clientOrderID,  
@cmta,  
@GiveUp,  
@UnderlyingSymbol,  
@expirationDate,  
@settlementDate,  
@algoStrategyID,  
@algoStrategyParameters,  
GetDate(),  
@algoSyntheticRPLParent  
)  
end  
  
--select * from AlgoSyntheticReplaceOrders  