create procedure [dbo].[P_SaveClosingTaxlots]
as
INSERT INTO [dbo].[PM_Taxlots]
           ([TaxLotID]
           ,[Symbol]
           ,[TaxLotOpenQty]
           ,[AvgPrice]
           ,[TimeOfSaveUTC]
           ,[GroupID]
           ,[AUECModifiedDate]
           ,[FundID]
           ,[Level2ID]
           ,[OpenTotalCommissionandFees]
           ,[ClosedTotalCommissionandFees]
           ,[PositionTag]
           ,[OrderSideTagValue]
           ,[TaxLotClosingId_Fk]
           ,[ParentRow_Pk]
           ,[AccruedInterest]
           ,[FXRate]
           ,[FXConversionMethodOperator]
           ,[ExternalTransId]
           ,[TradeAttribute1]
           ,[TradeAttribute2]
           ,[TradeAttribute3]
           ,[TradeAttribute4]
           ,[TradeAttribute5]
           ,[TradeAttribute6]
           ,[LotId]
           ,[NotionalChange]
           ,[NirvanaProcessDate]
           ,[SettlCurrency]
           ,[AdditionalTradeAttributes])
SELECT 
      [TaxLotID]
      ,[Symbol]
      ,[TaxLotOpenQty]
      ,[AvgPrice]
      ,[TimeOfSaveUTC]
      ,[GroupID]
      ,[AUECModifiedDate]
      ,[FundID]
      ,[Level2ID]
      ,[OpenTotalCommissionandFees]
      ,[ClosedTotalCommissionandFees]
      ,[PositionTag]
      ,[OrderSideTagValue]
      ,[TaxLotClosingId_Fk]
      ,[ParentRow_Pk]
      ,[AccruedInterest]
      ,[FXRate]
      ,[FXConversionMethodOperator]
      ,[ExternalTransId]
      ,[TradeAttribute1]
      ,[TradeAttribute2]
      ,[TradeAttribute3]
      ,[TradeAttribute4]
      ,[TradeAttribute5]
      ,[TradeAttribute6]
      ,[LotId]
      ,[NotionalChange]
      ,[NirvanaProcessDate]
      ,[SettlCurrency]
      ,[AdditionalTradeAttributes]
  FROM [dbo].[PM_Taxlots_Intermediate] 
  order by TaxLotID, TaxLotOpenQty DESC 

delete from PM_Taxlots_Intermediate
