  
  
CREATE PROCEDURE [dbo].[P_SaveClientOrderRequest] (    
@ClOrdID varchar(50),    
@TransactionTime varchar(50),    
@DiscretionOffset float,    
@ExecInst varchar(50),    
@HandlingInst char,    
@MsgType varchar(50),    
@OrderID varchar(500),    
@Side char,    
@OrderStatus char,    
@OrderType char,    
@OrigClOrderID varchar(50) ,    
@PegDiff float,    
@PNP int,    
@Price float,    
@Quantity float,    
@StopPrice float,    
--@SenderCompID varchar(50),    
--@SenderSubID,    
@Symbol varchar(50),    
@TargetCompID varchar(50),    
@TargetSubID varchar(50),    
@TimeInForce char,    
@Venue int,    
@ParentClOrderID varchar(50),    
@LocateReqd bit,    
@BorrowerID varchar(50),    
@ShortRebate float,    
@TradingAccountID int,    
@CompanyUserID int,    
@CounterPartyID int,    
@AuecID int,    
@StagedID varchar(50),    
@NirvanaMsgType int,    
--@DiscretionInst float,    
--@SendingTime varchar(50),    
@Text varchar(200),    
@StrategyID int,    
@FundID int,    
@listID varchar(20),    
@waveID varchar(20),    
@SecurityType varchar(20),    
@PutOrCall int,    
@MaturityMonthYear varchar(20),    
@StrikePrice float,    
@OpenClose char,    
@parentClientOrderID varchar(50),    
@clientOrderID varchar(50),    
    
--@TransactionTime varchar(50)    
@cmta varchar(20),    
@GiveUp varchar(20),    
@UnderlyingSymbol varchar(50),    
--@strikePrice float,    
@expirationDate varchar(20),    
--@settlementDate datetime,    
@algoStrategyID varchar(10),    
@algoStrategyParameters varchar(500)    
)    
    
     
AS    
Declare @result int    
    
 --Insert    
    
 --if ((@MsgType!='G' or  @MsgType!='F'))    
if(@ParentClOrderID=@ClOrdID)    
begin    
Insert into T_ClientOrder    
(    
ParentClOrderID,    
Symbol,    
OrderSideTagValue,    
ServerTime,    
TradingAccountID,    
AUECID,    
InsertionTime,    
ListID,    
WaveID,    
StrikePrice,    
ExpirationDate  
  
   )    
Values(     
@ClOrdID  ,    
@Symbol  ,    
@Side  ,    
@TransactionTime  ,    
--@IsStaged,    
--@IsManual,    
@TradingAccountID,    
@AuecID,    
GetUTCDate(),    
@listID,    
@waveID,    
@strikePrice,    
@expirationDate  
    
)    
end    
    
    
Insert into T_ClientSub    
(    
ParentClOrderID,    
ClOrderID,    
DiscrOffset,    
ExecutionInst,    
HandlingInst,    
MsgType,    
OrderID,    
OrderTypeTagValue,    
OrigClOrderID   ,    
PegDiff  ,    
PNP ,    
Price  ,    
Quantity  ,    
StopPrice  ,    
TargetCompID  ,    
TargetSubID  ,    
TimeInForce  ,    
VenueID,    
--IsSubOrder,    
--IsStaged,    
CounterPartyID,    
ServerTime,    
StagedOrderID,    
InsertionTime,    
NirvanaMsgType,    
Text,    
LocateReqd,    
BorrowerID,    
ShortRebate,    
StrategyID,    
FundID,    
SecurityType,    
PutOrCall,    
MaturityYearMonth,    
StrikePrice,    
OpenClose,    
ClientOrderID,    
ParentClientOrderID,    
UserID,    
CMTA,    
GiveUpID,    
UnderlyingSymbol,    
AlgoStrategyID,    
AlgoParameters    
)    
Values(    
@ParentClOrderID,    
 @ClOrdID  ,    
    
--@DiscretionInst  ,    
@DiscretionOffset  ,    
    
@ExecInst  ,    
@HandlingInst  ,    
    
@MsgType  ,    
@OrderID  ,    
@OrderType  ,    
@OrigClOrderID   ,    
@PegDiff  ,    
@PNP ,    
@Price  ,    
@Quantity  ,    
@StopPrice  ,    
@TargetCompID  ,    
@TargetSubID  ,    
@TimeInForce  ,    
@Venue  ,    
--@IsSubOrder,    
--@IsStaged,    
@CounterPartyID,    
@TransactionTime,    
@StagedID,    
GetUTCDate(),    
@NirvanaMsgType,    
@Text,    
@LocateReqd ,    
@BorrowerID ,    
@ShortRebate,    
@StrategyID,    
@FundID ,    
@SecurityType,    
@PutOrCall ,    
@MaturityMonthYear,    
@StrikePrice,    
@OpenClose,    
@clientOrderID,    
@parentClientOrderID,    
@CompanyUserID,    
@cmta,    
@GiveUp,    
@UnderlyingSymbol,    
@algoStrategyID ,    
@algoStrategyParameters    
)  