using System;
using System.Collections.Generic;

namespace Prana.KafkaWrapper
{
    public class RequestResponseModel
    {
        private string errorMsg;

        public RequestResponseModel() { IsSuccess = true; }

        public RequestResponseModel(int companyUserID,
            string data,
            string correlationId = null)
        {
            RequestID = Guid.NewGuid();
            CompanyUserID = companyUserID;
            Data = data;
            IsSuccess = true;

            if (correlationId == null)
            {
                correlationId = GetCorrelationId() + "-SYS";  //it mean generated by event/System and not by http request
            }
            CorrelationId = correlationId;
        }

        public Guid RequestID { get; set; }
        public int CompanyUserID { get; set; }
        public string Data { get; set; }

        //Let it be string type, sometime if fr some where UI fail to generate Correlationid, then we are setting default Http RequestId as correlationId, which is string type. Also, Dont give it a setter. 
        public string CorrelationId { get; set; }

        public bool IsSuccess { get; private set; }    //do not make setter public, to make it false, set the Error Msg value

        public string ErrorMsg
        {
            get { return errorMsg; }
            set
            {
                if (!string.IsNullOrEmpty(value))
                {
                    IsSuccess = false;
                    errorMsg = value;
                }
            }
        }

        public bool IsDisplayError { get; set; } = false;

        //This is an extra field for the requirement of compressed data or any custom data to be sent in future
        public dynamic CustomData { get; set; } = null;

        public int StatusCode { get; set; }

        //this would be static and public as this would be used in main service gateway proj
        public static string GetCorrelationId()
        {
            var rand = new Random().Next(100, 1000).ToString();
            var corrId = ((long)(DateTime.UtcNow - new DateTime(1970, 1, 1)).TotalMilliseconds).ToString();
            return corrId + "" + rand;
        }
    }

    public class ServiceException : Exception
    {
        public ServiceException(
            string errorMsg,
            bool isDisplayError) : base(errorMsg)
        {
            this.IsDisplayError = isDisplayError;
        }

        public bool IsDisplayError { get; }
    }
}
