<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2007

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce 2007 Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/ThirdPartyFlatFileDetailCollection">
		<ThirdPartyFlatFileDetailCollection>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation">C:/UpdatedTP/Prana_Final.xsd</xsl:attribute>
			<xsl:for-each select="ThirdPartyFlatFileDetail">
 <xsl:if test="AssetID=1 or AssetID=2 or AssetID=3"> 
				<ThirdPartyFlatFileDetail>				 
					
					<xsl:for-each select="CompanyID">
						<CompanyID>
							<xsl:value-of select="."/>
						</CompanyID>
					</xsl:for-each>
					<xsl:for-each select="ThirdPartyID">
						<ThirdPartyID>
							<xsl:value-of select="."/>
						</ThirdPartyID>
					</xsl:for-each>	
					
			<!--         
					<xsl:for-each select="FundName">
						<FundName>
							<xsl:value-of select="."/>
						</FundName>
					</xsl:for-each>   				 -->
					<xsl:for-each select="FundMappedName">
						<AccountCode>
							<xsl:value-of select="."/>
						</AccountCode>
					</xsl:for-each>
					<xsl:for-each select="TradeRefID">
						<Serial>
							<xsl:value-of select="."/>
						</Serial>
					</xsl:for-each>
					
					<xsl:for-each select="Symbol">
						<Product>
							<xsl:value-of select="."/>
						</Product>
					</xsl:for-each>  			

		<!--			<xsl:for-each select="Symbol">
						<SecurityCodeType>
							<xsl:value-of select="'SY-Symbol'"/>
						</SecurityCodeType>
					</xsl:for-each> 					-->

					
		<!--			<xsl:for-each select="PutOrCall">
						<PutOrCall>
							<xsl:value-of select="."/>
						</PutOrCall>
					</xsl:for-each>          -->

<!--       Asset   -->			
			<xsl:if test="Asset='Equity' and PutOrCall= -2147483648">  
					<xsl:for-each select="Asset">
						<TradeType>
							<xsl:value-of select="'EQ'"/>
						</TradeType>
					</xsl:for-each>
			</xsl:if>  
			
			<xsl:if test="Asset='EquityOption'and PutOrCall='PUT'">  
					<xsl:for-each select="Asset">
						<TradeType>
							<xsl:value-of select="'TP'"/>
						</TradeType>
					</xsl:for-each>
			</xsl:if> 

			<xsl:if test="Asset='EquityOption'and PutOrCall='CALL'">  
					<xsl:for-each select="Asset">
						<TradeType>
							<xsl:value-of select="'TC'"/>
						</TradeType>
					</xsl:for-each>
			</xsl:if>  					

			
			<xsl:if test="Asset='FutureOption'">  
					<xsl:for-each select="Asset">
						<TradeType>
							<xsl:value-of select="'FO'"/>
						</TradeType>
					</xsl:for-each>
			</xsl:if> 

			
			<xsl:if test="Asset='Future'">  
					<xsl:for-each select="Asset">
						<TradeType>
							<xsl:value-of select="'FT'"/>
						</TradeType>
					</xsl:for-each>
			</xsl:if> 

<!--       Asset End  -->
					<xsl:for-each select="SettlementDate">
						<PromtDate>
							<xsl:value-of select="."/>
						</PromtDate>
					</xsl:for-each>
					<xsl:for-each select="StrikePrice">
						<StrikePrice>
							<xsl:value-of select="."/>
						</StrikePrice>
					</xsl:for-each>
					
					<xsl:for-each select="AveragePrice">
						<TradePrice>
							<xsl:value-of select="."/>
						</TradePrice>
					</xsl:for-each>					

				<xsl:if test ="Side='Buy' or Side='Buy to Close' or Side='Buy to Cover' or Side='Buy to Open'">  
					<xsl:for-each select="AllocatedQty">
						<Contracts>
							<xsl:value-of select="."/>
						</Contracts>
					</xsl:for-each>
				</xsl:if> 
				<xsl:if test="Side='Sell short' or Side='Sell' or Side='Sell to Open' or Side='Sell to Close'">  
					<xsl:for-each select="AllocatedQty">
						<Contracts>
							<xsl:value-of select=".*-1"/>
						</Contracts>
					</xsl:for-each>
				</xsl:if>  

					
					<xsl:for-each select="CounterParty">
						<ExecBroker>
							<xsl:value-of select="."/>
						</ExecBroker>
					</xsl:for-each>
					
							

<!--       FUND          -->					


					<xsl:for-each select="CompanyFundID">
						<CompanyFundID>
							<xsl:value-of select="."/>
						</CompanyFundID>
					</xsl:for-each>
				

				<!--	<xsl:for-each select="FundAccountNo">
						<FundAccountNo>
							<xsl:value-of select="."/>
						</FundAccountNo>
					</xsl:for-each>                   		 -->

<!--      FUND END       -->	
				
					<xsl:for-each select="TradeDate">
						<TradeDate>
							<xsl:value-of select="."/>
						</TradeDate>
					</xsl:for-each>	

				
					<xsl:for-each select="Symbol">
						<TransactionType>
							<xsl:value-of select="'NEW'"/>
						</TransactionType>
					</xsl:for-each>	

<!--   Side     -->

					<xsl:for-each select="SideTag">
						<SideTag>
							<xsl:value-of select="."/>
						</SideTag>
					</xsl:for-each>	
				


	<!--	<xsl:if test="Side='Buy'">
				<xsl:for-each select="Side">
  				    <ActionCode>					
   				      <xsl:value-of select="'BUY'"/> 	
				    </ActionCode>					
				</xsl:for-each>
			</xsl:if>

			<xsl:if test="Side='Buy to Open'">
				<xsl:for-each select="Side">
  				    <ActionCode>					
   				      <xsl:value-of select="'BUY'"/> 	
				    </ActionCode>					
				</xsl:for-each>
			</xsl:if>

			<xsl:if test="Side='Buy to Close'">
				<xsl:for-each select="Side">
  				    <ActionCode>					
   				      <xsl:value-of select="'BC'"/> 	
				    </ActionCode>					
				</xsl:for-each>
			</xsl:if>


			<xsl:if test="Side='Buy to Cover'">
				<xsl:for-each select="Side">
  				    <ActionCode>					
   				      <xsl:value-of select="'BC'"/> 	
				    </ActionCode>					
				</xsl:for-each>
			</xsl:if>


			<xsl:if test="Side='Sell'">
				<xsl:for-each select="Side">
  				    <ActionCode>					
   				      <xsl:value-of select="'SELL'"/> 	
				    </ActionCode>					
				</xsl:for-each>
			</xsl:if>

			<xsl:if test="Side='Sell to Close'">
				<xsl:for-each select="Side">
  				    <ActionCode>					
   				      <xsl:value-of select="'SELL'"/> 	
				    </ActionCode>					
				</xsl:for-each>
			</xsl:if>

			<xsl:if test="Side='Sell short'">
				<xsl:for-each select="Side">
  				    <ActionCode>					
   				      <xsl:value-of select="'SS'"/> 	
				    </ActionCode>					
				</xsl:for-each>
			</xsl:if>

			<xsl:if test="Side='Sell to Open'">
				<xsl:for-each select="Side">
  				    <ActionCode>					
   				      <xsl:value-of select="'SELL'"/> 	
				    </ActionCode>					
				</xsl:for-each>
			</xsl:if>				-->					 

<!--   Side End    -->				

					

					<xsl:for-each select="AssetID">
						<AssetID>
							<xsl:value-of select="."/>
						</AssetID>
					</xsl:for-each>
					
	<!--				<xsl:for-each select="NetAmount">
						<NetAmount>
							<xsl:value-of select="."/>
						</NetAmount>
					</xsl:for-each>					 -->

					<xsl:for-each select="CurrencyID">
						<CurrencyID>
							<xsl:value-of select="."/>
						</CurrencyID>
					</xsl:for-each>
				
	<!--				<xsl:for-each select="CurrencyName">
						<SettleCurrency>
							<xsl:value-of select="."/>
						</SettleCurrency>
					</xsl:for-each>

 			              <xsl:for-each select="Commission">
						<Commission>
							<xsl:value-of select="."/>
						</Commission>
					</xsl:for-each>					
					<xsl:for-each select="CommissionCharged">
						<CommCode>
							<xsl:value-of select="'G'"/>
						</CommCode>
					</xsl:for-each>
					<xsl:for-each select="CommissionCharged">
						<Commission>
							<xsl:value-of select="."/>
						</Commission>
					</xsl:for-each>                           -->

					<xsl:for-each select="CounterPartyID">
						<CounterPartyID>
							<xsl:value-of select="."/>
						</CounterPartyID>
					</xsl:for-each>
					



			 	 	
		
				 					                                       

					<xsl:for-each select="ExchangeID">
						<ExchangeID>
							<xsl:value-of select="."/>
						</ExchangeID>
					</xsl:for-each>
	<!--				<xsl:for-each select="Exchange">
						<Exchange>
							<xsl:value-of select="."/>
						</Exchange>
					</xsl:for-each>                                 -->

					

				

		<!--			<xsl:for-each select="OrderTypeTag">
						<OrderTypeTag>
							<xsl:value-of select="."/>
						</OrderTypeTag>
					</xsl:for-each>					
					<xsl:for-each select="OrderType">
						<OrderType>
							<xsl:value-of select="."/>
						</OrderType>
					</xsl:for-each>					-->
					
					<xsl:for-each select="UnderLyingID">
						<UnderLyingID>
							<xsl:value-of select="."/>
						</UnderLyingID>
					</xsl:for-each>
		<!--			<xsl:for-each select="UnderLying">
						<UnderLying>
							<xsl:value-of select="."/>
						</UnderLying>
					</xsl:for-each>                                 -->
					
					
					
					
					
					

					
					<xsl:for-each select="AUECID">
						<AUECID>
							<xsl:value-of select="."/>
						</AUECID>
					</xsl:for-each>
					
		
			<!--		<xsl:for-each select="SecFees">
						<SecFees>
							<xsl:value-of select="."/>
						</SecFees>
					</xsl:for-each>     
					<xsl:for-each select="ClearingFee">
						<ClearingFee>
							<xsl:value-of select="."/>
						</ClearingFee>
					</xsl:for-each>                                
					<xsl:for-each select="GrossAmount">
						<GrossAmount>
							<xsl:value-of select="."/>
						</GrossAmount>
					</xsl:for-each>					-->
					
	<!--				<xsl:for-each select="SecurityIDType">
						<SecurityIDType>
							<xsl:value-of select="."/>
						</SecurityIDType>
					</xsl:for-each>	
				-->
					<xsl:for-each select="CommissionRateTypeID">
						<CommissionRateTypeID>
							<xsl:value-of select="."/>
						</CommissionRateTypeID>
					</xsl:for-each>
			<!--		<xsl:for-each select="CommissionRateType">
						<CommissionRateType>
							<xsl:value-of select="."/>
						</CommissionRateType>
					</xsl:for-each>				-->					
					
	<!--				<xsl:for-each select="SavePath">
						<SavePath>
							<xsl:value-of select="."/>
						</SavePath>
					</xsl:for-each>
					<xsl:for-each select="NamingConvention">
						<NamingConvention>
							<xsl:value-of select="."/>
						</NamingConvention>
					</xsl:for-each>                               -->
					<xsl:for-each select="CVID">
						<CVID>
							<xsl:value-of select="."/>
						</CVID>
					</xsl:for-each>
		<!-- 			<xsl:for-each select="CVName">
						<CVName>
							<xsl:value-of select="."/>
						</CVName>
					</xsl:for-each>				
					<xsl:for-each select="CVIdentifier">
						<CVIdentifier>
							<xsl:value-of select="."/>
						</CVIdentifier>
					</xsl:for-each>					 -->			      
					<xsl:for-each select="CompanyFundTypeID">
						<CompanyFundTypeID>
							<xsl:value-of select="."/>
						</CompanyFundTypeID>
					</xsl:for-each>
		<!-- 			<xsl:for-each select="CompanyFundType">
						<CompanyFundType>
							<xsl:value-of select="."/>
						</CompanyFundType>
					</xsl:for-each>					 -->
					<xsl:for-each select="ThirdPartyTypeID">
						<ThirdPartyTypeID>
							<xsl:value-of select="."/>
						</ThirdPartyTypeID>
					</xsl:for-each>
		<!--			<xsl:for-each select="ThirdPartyType">
						<ThirdPartyType>
							<xsl:value-of select="."/>
						</ThirdPartyType>
					</xsl:for-each>    				  
					<xsl:for-each select="CompanyIdentifier">
						<CompanyIdentifier>
							<xsl:value-of select="."/>
						</CompanyIdentifier>
					</xsl:for-each>    				 
					<xsl:for-each select="Percentage">
						<Percentage>
							<xsl:value-of select="."/>
						</Percentage> 
					</xsl:for-each>    				  -->
					<xsl:for-each select="TradingAccount">
						<TradingAccount>
							<xsl:value-of select="."/>
						</TradingAccount>
					</xsl:for-each>
					<xsl:for-each select="CompanyCVID">
						<CompanyCVID>
							<xsl:value-of select="."/>
						</CompanyCVID>
					</xsl:for-each>				
		<!--			<xsl:for-each select="VenueID">
						<VenueID>
							<xsl:value-of select="."/>
						</VenueID>
					</xsl:for-each>
					<xsl:for-each select="VenueName">
						<VenueName>
							<xsl:value-of select="."/>
						</VenueName>
					</xsl:for-each>
					<xsl:for-each select="OrderQty">
						<OrderQty>
							<xsl:value-of select="."/>
						</OrderQty>
					</xsl:for-each>					  -->
					<xsl:for-each select="EntityID">
						<EntityID>
							<xsl:value-of select="."/>
						</EntityID>
					</xsl:for-each>
					<xsl:for-each select="OrderID">
						<OrderID>
							<xsl:value-of select="."/>
						</OrderID>
					</xsl:for-each>
					
					<xsl:for-each select="TradAccntID">
						<TradAccntID>
							<xsl:value-of select="."/>
						</TradAccntID>
					</xsl:for-each>			             
				</ThirdPartyFlatFileDetail>
</xsl:if> 
			</xsl:for-each>
		</ThirdPartyFlatFileDetailCollection>
	</xsl:template>
</xsl:stylesheet>
