<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2007

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce 2007 Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="xs">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template match="/ThirdPartyFlatFileDetailCollection">
		<ThirdPartyFlatFileDetailCollection>
			<xsl:attribute name="xsi:noNamespaceSchemaLocation">C:/UpdatedTP/ThirdPartyOne_Final.xsd</xsl:attribute>
			<xsl:for-each select="ThirdPartyFlatFileDetail">
				<ThirdPartyFlatFileDetail>
					<xsl:for-each select="Trade_Reference">
						<TradeRefID>
							<xsl:value-of select="."/>
						</TradeRefID>
					</xsl:for-each>
					<xsl:for-each select="CompanyID">
						<CompanyID>
							<xsl:value-of select="."/>
						</CompanyID>
					</xsl:for-each>
					<xsl:for-each select="ThirdPartyID">
						<ThirdPartyID>
							<xsl:value-of select="."/>
						</ThirdPartyID>
					</xsl:for-each>
					<xsl:for-each select="ThirdParty">
						<ThirdParty1>
							<xsl:value-of select="."/>
						</ThirdParty1>
					</xsl:for-each>
<!--              SIDE          -->
					<xsl:for-each select="SideID">
						<SideID>
							<xsl:value-of select="."/>
						</SideID>
					</xsl:for-each>
					<xsl:if test="ActionCode='BUY'">
						<xsl:for-each select="ActionCode">
							<Side>
								<xsl:value-of select="'Buy'"/>
							</Side>
						</xsl:for-each>
					</xsl:if>
					<xsl:if test="ActionCode='BC'">
						<xsl:for-each select="ActionCode">
							<Side>
								<xsl:value-of select="'Buy to Close'"/>
							</Side>
						</xsl:for-each>
					</xsl:if>
					<xsl:if test="ActionCode='SELL'">
						<xsl:for-each select="ActionCode">
							<Side>
								<xsl:value-of select="'Sell'"/>
							</Side>
						</xsl:for-each>
					</xsl:if>
					<xsl:if test="ActionCode='SS'">
						<xsl:for-each select="ActionCode">
							<Side>
								<xsl:value-of select="'Sell short'"/>
							</Side>
						</xsl:for-each>
					</xsl:if>
<!--              SIDE   ENDS       -->
					<xsl:for-each select="SecurityID">
						<Symbol>
							<xsl:value-of select="."/>
						</Symbol>
					</xsl:for-each>
					<xsl:for-each select="Quantity">
						<ExecutedQty>
							<xsl:value-of select="."/>
						</ExecutedQty>
					</xsl:for-each>
					<xsl:for-each select="PriceReported">
						<AveragePrice>
							<xsl:value-of select="."/>
						</AveragePrice>
					</xsl:for-each>
					<xsl:for-each select="CompanyFundID">
						<CompanyFundID>
							<xsl:value-of select="."/>
						</CompanyFundID>
					</xsl:for-each>
					<xsl:for-each select="FundName">
						<FundName1>
							<xsl:value-of select="."/>
						</FundName1>
					</xsl:for-each>
					<xsl:for-each select="UBSAccount">
						<FundMappedName>
							<xsl:value-of select="."/>
						</FundMappedName>
					</xsl:for-each>
					<xsl:for-each select="FundAccountNo">
						<FundAccountNo1>
							<xsl:value-of select="."/>
						</FundAccountNo1>
					</xsl:for-each>
					<xsl:for-each select="OrderTypeTag">
						<OrderTypeTag>
							<xsl:value-of select="."/>
						</OrderTypeTag>
					</xsl:for-each>
					<xsl:for-each select="OrderType">
						<OrderType1>
							<xsl:value-of select="."/>
						</OrderType1>
					</xsl:for-each>
					<xsl:for-each select="AssetID">
						<AssetID>
							<xsl:value-of select="."/>
						</AssetID>
					</xsl:for-each>
					<xsl:for-each select="Asset">
						<Asset1>
							<xsl:value-of select="."/>
						</Asset1>
					</xsl:for-each>
					<xsl:for-each select="UnderLyingID">
						<UnderLyingID>
							<xsl:value-of select="."/>
						</UnderLyingID>
					</xsl:for-each>
					<xsl:for-each select="UnderLying">
						<UnderLying1>
							<xsl:value-of select="."/>
						</UnderLying1>
					</xsl:for-each>
					<xsl:for-each select="ExchangeID">
						<ExchangeID>
							<xsl:value-of select="."/>
						</ExchangeID>
					</xsl:for-each>
					<xsl:for-each select="Exchange">
						<Exchange1>
							<xsl:value-of select="."/>
						</Exchange1>
					</xsl:for-each>
					<xsl:for-each select="CurrencyID">
						<CurrencyID>
							<xsl:value-of select="."/>
						</CurrencyID>
					</xsl:for-each>
					<xsl:for-each select="SettleCurrency">
						<CurrencyName>
							<xsl:value-of select="."/>
						</CurrencyName>
					</xsl:for-each>
					<xsl:for-each select="AUECID">
						<AUECID>
							<xsl:value-of select="."/>
						</AUECID>
					</xsl:for-each>
					<xsl:for-each select="SecFees">
						<SecFees1>
							<xsl:value-of select="."/>
						</SecFees1>
					</xsl:for-each>
					<xsl:for-each select="Commission">
						<Commission1>
							<xsl:value-of select="."/>
						</Commission1>
					</xsl:for-each>
					<xsl:for-each select="Commission">
						<CommissionCharged>
							<xsl:value-of select="."/>
						</CommissionCharged>
					</xsl:for-each>
					<xsl:for-each select="OtherBrokerFee">
						<OtherBrokerFee>
							<xsl:value-of select="."/>
						</OtherBrokerFee>
					</xsl:for-each>
					<xsl:for-each select="GrossAmount">
						<GrossAmount1>
							<xsl:value-of select="."/>
						</GrossAmount1>
					</xsl:for-each>
					<xsl:for-each select="NetAmount">
						<NetAmount>
							<xsl:value-of select="."/>
						</NetAmount>
					</xsl:for-each>
					<xsl:for-each select="SecurityIDType">
						<SecurityIDType1>
							<xsl:value-of select="."/>
						</SecurityIDType1>
					</xsl:for-each>
					<xsl:for-each select="CommissionRateTypeID">
						<CommissionRateTypeID>
							<xsl:value-of select="."/>
						</CommissionRateTypeID>
					</xsl:for-each>
					<xsl:for-each select="CommissionRateType">
						<CommissionRateType1>
							<xsl:value-of select="."/>
						</CommissionRateType1>
					</xsl:for-each>
					<xsl:for-each select="TradeDate">
						<TradeDate>
							<xsl:value-of select="."/>
						</TradeDate>
					</xsl:for-each>
					<xsl:for-each select="SavePath">
						<SavePath>
							<xsl:value-of select="."/>
						</SavePath>
					</xsl:for-each>
					<xsl:for-each select="NamingConvention">
						<NamingConvention>
							<xsl:value-of select="."/>
						</NamingConvention>
					</xsl:for-each>
					<xsl:for-each select="CVID">
						<CVID>
							<xsl:value-of select="."/>
						</CVID>
					</xsl:for-each>
					<xsl:for-each select="CVName">
						<CVName1>
							<xsl:value-of select="."/>
						</CVName1>
					</xsl:for-each>
					<xsl:for-each select="CVIdentifier">
						<CVIdentifier1>
							<xsl:value-of select="."/>
						</CVIdentifier1>
					</xsl:for-each>
					<xsl:for-each select="CompanyFundTypeID">
						<CompanyFundTypeID>
							<xsl:value-of select="."/>
						</CompanyFundTypeID>
					</xsl:for-each>
					<xsl:for-each select="CompanyFundType">
						<CompanyFundType1>
							<xsl:value-of select="."/>
						</CompanyFundType1>
					</xsl:for-each>
					<xsl:for-each select="ThirdPartyTypeID">
						<ThirdPartyTypeID>
							<xsl:value-of select="."/>
						</ThirdPartyTypeID>
					</xsl:for-each>
					<xsl:for-each select="ThirdPartyType">
						<ThirdPartyType1>
							<xsl:value-of select="."/>
						</ThirdPartyType1>
					</xsl:for-each>
					<xsl:for-each select="CompanyIdentifier">
						<CompanyIdentifier1>
							<xsl:value-of select="."/>
						</CompanyIdentifier1>
					</xsl:for-each>
					<xsl:for-each select="Percentage">
						<Percentage1>
							<xsl:value-of select="."/>
						</Percentage1>
					</xsl:for-each>
					<xsl:for-each select="TradingAccount">
						<TradingAccount>
							<xsl:value-of select="."/>
						</TradingAccount>
					</xsl:for-each>
					<xsl:for-each select="CompanyCVID">
						<CompanyCVID>
							<xsl:value-of select="."/>
						</CompanyCVID>
					</xsl:for-each>				
					<xsl:for-each select="VenueID">
						<VenueID>
							<xsl:value-of select="."/>
						</VenueID>
					</xsl:for-each>
					<xsl:for-each select="VenueName">
						<VenueName>
							<xsl:value-of select="."/>
						</VenueName>
					</xsl:for-each>
					<xsl:for-each select="OrderQty">
						<OrderQty>
							<xsl:value-of select="."/>
						</OrderQty>
					</xsl:for-each>
					<xsl:for-each select="EntityID">
						<EntityID>
							<xsl:value-of select="."/>
						</EntityID>
					</xsl:for-each>
					<xsl:for-each select="OrderID">
						<OrderID>
							<xsl:value-of select="."/>
						</OrderID>
					</xsl:for-each>
					<xsl:for-each select="CounterPartyID">
						<CounterPartyID>
							<xsl:value-of select="."/>
						</CounterPartyID>
					</xsl:for-each>
					
					<xsl:for-each select="ExecBroker">
						<CounterParty>
							<xsl:value-of select="."/>
						</CounterParty>
					</xsl:for-each>
					<xsl:for-each select="TradAccntID">
						<TradAccntID>
							<xsl:value-of select="."/>
						</TradAccntID>
					</xsl:for-each>
					<xsl:for-each select="Quantity">
						<AllocatedQty>
							<xsl:value-of select="."/>
						</AllocatedQty>
					</xsl:for-each>
					<xsl:for-each select="TotalQty">
						<TotalQty>
							<xsl:value-of select="."/>
						</TotalQty>
					</xsl:for-each>

					<xsl:for-each select="SettleDate">
						<SettlementDate>
							<xsl:value-of select="."/>
						</SettlementDate>
					</xsl:for-each>


					<xsl:for-each select="SettleCurrency">
						<CurrencySymbol>
							<xsl:value-of select="."/>
						</CurrencySymbol>
					</xsl:for-each>
				</ThirdPartyFlatFileDetail>
			</xsl:for-each>
		</ThirdPartyFlatFileDetailCollection>
	</xsl:template>
</xsl:stylesheet>
