// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
using Nirvana.Admin.RiskManagement.Controls;
using Infragistics.Win.UltraWinGrid;
namespace TestProject
{
    /// <summary>
    ///This is a test class for Nirvana.Admin.RiskManagement.Controls.TradingAccount and is intended
    ///to contain all Nirvana.Admin.RiskManagement.Controls.TradingAccount Unit Tests
    ///</summary>
    [TestClass()]
    public class TradingAccountTest
    {


        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion


        /// <summary>
        ///A test for Dispose (bool)
        ///</summary>
        [DeploymentItem("Nirvana.Admin.RiskManagement.dll")]
        [TestMethod()]
        public void DisposeTest()
        {
            TradingAccount target = new TradingAccount();

            TestProject.Nirvana_Admin_RiskManagement_Controls_TradingAccountAccessor accessor = new TestProject.Nirvana_Admin_RiskManagement_Controls_TradingAccountAccessor(target);

            bool disposing = false; // TODO: Initialize to an appropriate value

            accessor.Dispose(disposing);

            Assert.Inconclusive("A method that does not return a value cannot be verified.");
        }

        /// <summary>
        ///A test for InitializeComponent ()
        ///</summary>
        [DeploymentItem("Nirvana.Admin.RiskManagement.dll")]
        [TestMethod()]
        public void InitializeComponentTest()
        {
            TradingAccount target = new TradingAccount();

            TestProject.Nirvana_Admin_RiskManagement_Controls_TradingAccountAccessor accessor = new TestProject.Nirvana_Admin_RiskManagement_Controls_TradingAccountAccessor(target);

            accessor.InitializeComponent();

            Assert.Inconclusive("A method that does not return a value cannot be verified.");
        }

        /// <summary>
        ///A test for TradingAccount ()
        ///</summary>
        [TestMethod()]
        public void ConstructorTest()
        {
            TradingAccount target = new TradingAccount();

            // TODO: Implement code to verify target
            Assert.Inconclusive("TODO: Implement code to verify target");
        }

        /// <summary>
        ///A test for ultraCombo3_InitializeLayout (object, Infragistics.Win.UltraWinGrid.InitializeLayoutEventArgs)
        ///</summary>
        [DeploymentItem("Nirvana.Admin.RiskManagement.dll")]
        [TestMethod()]
        public void ultraCombo3_InitializeLayoutTest()
        {
            TradingAccount target = new TradingAccount();

            TestProject.Nirvana_Admin_RiskManagement_Controls_TradingAccountAccessor accessor = new TestProject.Nirvana_Admin_RiskManagement_Controls_TradingAccountAccessor(target);

            object sender = null; // TODO: Initialize to an appropriate value

            InitializeLayoutEventArgs e = null; // TODO: Initialize to an appropriate value

            accessor.ultraCombo3_InitializeLayout(sender, e);

            Assert.Inconclusive("A method that does not return a value cannot be verified.");
        }

    }


}
