GO
/****** Object:  StoredProcedure [dbo].[P_NT_GenericPNL]    Script Date: 05/13/2015 16:36:32 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
/* Usage:
Exec P_NT_GenericPNL '01/01/2014','08/07/2014'
Exec P_NT_GenericPNL '01/01/2014','06/07/2014','06/07/2014'
*/
-- =============================================
CREATE PROCEDURE [dbo].[P_NT_GenericPNL] 
-- Add the parameters for the stored procedure here
@StartDate datetime,
@EndDate datetime,
@AsOfDate datetime = Null
AS
BEGIN
-- SET NOCOUNT ON added to prevent extra result sets from
-- interfering with SELECT statements.
--SET NOCOUNT ON;
SET NOCOUNT OFF;
SET FMTONLY OFF;
-- Insert statements for procedure here 

If @AsOfDate Is Null 
Begin 
Select [CheckSumId]
      ,[AcctId]
      ,[AcctName]
      ,[RunDate]
      ,[Symbol]
      ,[UnderlyingSymbol]
      ,[TradeDate]
      ,[ClosingDate]
      ,[Open_CloseTag]
      ,[UdaSector]
      ,[UdaSubSector]
      ,[UdaCountry]
      ,[Strategy]
      ,[SymbolDescription]
      ,[UnderlyingSymbolDescription]
      ,[BloombergSymbol]
      ,[PutOrCall]
      ,[ExpirationDate]
      ,[StrikePrice]
      ,[Delta]
      ,[Beta]
      ,[ImpliedVol]
      ,[Asset]
      ,[SetupAsset]
      ,[CommissionAndFees]
      ,[FXPNL]
      ,[PriceMultiplier]
      ,[DeltaAdjPosMultiplier]
      ,[ZeroOrEndingMVOrUnrealized]
      ,[CouponRate]
      ,[BlackScholesOrBlack76]
      ,[Side]
      ,[TradeCurrency]
      ,[OpeningFXRate]
      ,[BeginningFXRate]
      ,[EndingFXRate]
      ,[TotalCostLocal]
      ,[BeginningMarketValueLocal]
      ,[EndingMarketValueLocal]
      ,[TotalOpenCommissionAndFeesLocal]
      ,[TotalClosedCommissionAndFeesLocal]
	  ,[DividendLocal]
      ,[TotalCostBase]
      ,[BeginningMarketValueBase]
      ,[EndingMarketValueBase]
      ,[TotalOpenCommissionAndFeesBase]
      ,[TotalClosedCommissionAndFeesBase]
	  ,[DividendBase]
      ,[BeginningQuantity]
      ,[EndingQuantity]
      ,[Quantity]
      ,[UnitCostLocal]
      ,[BeginningPriceLocal]
      ,[ClosingPriceLocal]
      ,[EndingPriceLocal]
      ,[UnderlyingSymbolPriceLocal]
      ,[UnitCostBase]
      ,[BeginningPriceBase]
      ,[ClosingPriceBase]
      ,[EndingPriceBase]
      ,[UnderlyingSymbolPriceBase]
      ,[SideMultiplier]
      ,[Multiplier]
      ,[UnderlyingDelta]
      ,[TaxlotID]
      ,[TaxlotClosingID]
      ,[DaySplitFactor]
      ,[TillSplitFactor]
      ,[K0]
      ,[K1]
      ,[K2]
      ,[AveDaystoLiquidate]
      ,[DaysToLiquidate]
      ,[AveNDaysTradingVolume]
      ,[AveNDaysTradingValueLocal]
      ,[AveNDaysTradingValueBase]
      ,[BeginningDelta]
      ,[BeginningUnderlyingSymbolPriceLocal]
      ,[BeginningUnderlyingSymbolPriceBase]
From T_NT_GenericPNL Where Rundate Between @StartDate And @EndDate 
End 
Else 
Begin 
Select [CheckSumId]
      ,[AcctId]
      ,[AcctName]
      ,[RunDate]
      ,[Symbol]
      ,[UnderlyingSymbol]
      ,[TradeDate]
      ,[ClosingDate]
      ,[Open_CloseTag]
      ,[UdaSector]
      ,[UdaSubSector]
      ,[UdaCountry]
      ,[Strategy]
      ,[SymbolDescription]
      ,[UnderlyingSymbolDescription]
      ,[BloombergSymbol]
      ,[PutOrCall]
      ,[ExpirationDate]
      ,[StrikePrice]
      ,[Delta]
      ,[Beta]
      ,[ImpliedVol]
      ,[Asset]
      ,[SetupAsset]
      ,[CommissionAndFees]
      ,[FXPNL]
      ,[PriceMultiplier]
      ,[DeltaAdjPosMultiplier]
      ,[ZeroOrEndingMVOrUnrealized]
      ,[CouponRate]
      ,[BlackScholesOrBlack76]
      ,[Side]
      ,[TradeCurrency]
      ,[OpeningFXRate]
      ,[BeginningFXRate]
      ,[EndingFXRate]
      ,[TotalCostLocal]
      ,[BeginningMarketValueLocal]
      ,[EndingMarketValueLocal]
      ,[TotalOpenCommissionAndFeesLocal]
      ,[TotalClosedCommissionAndFeesLocal]
	  ,[DividendLocal]
      ,[TotalCostBase]
      ,[BeginningMarketValueBase]
      ,[EndingMarketValueBase]
      ,[TotalOpenCommissionAndFeesBase]
      ,[TotalClosedCommissionAndFeesBase]
	  ,[DividendBase]
      ,[BeginningQuantity]
      ,[EndingQuantity]
      ,[Quantity]
      ,[UnitCostLocal]
      ,[BeginningPriceLocal]
      ,[ClosingPriceLocal]
      ,[EndingPriceLocal]
      ,[UnderlyingSymbolPriceLocal]
      ,[UnitCostBase]
      ,[BeginningPriceBase]
      ,[ClosingPriceBase]
      ,[EndingPriceBase]
      ,[UnderlyingSymbolPriceBase]
      ,[SideMultiplier]
      ,[Multiplier]
      ,[UnderlyingDelta]
      ,[TaxlotID]
      ,[TaxlotClosingID]
      ,[DaySplitFactor]
      ,[TillSplitFactor]
      ,[K0]
      ,[K1]
      ,[K2]
      ,[AveDaystoLiquidate]
      ,[DaysToLiquidate]
      ,[AveNDaysTradingVolume]
      ,[AveNDaysTradingValueLocal]
      ,[AveNDaysTradingValueBase]
      ,[BeginningDelta]
      ,[BeginningUnderlyingSymbolPriceLocal]
      ,[BeginningUnderlyingSymbolPriceBase]
From T_NT_ApprovedGenericPNL Where Rundate Between @StartDate And @EndDate And AsOfDate = @AsOfDate
End 

END

GO