// The following code was generated by Microsoft Visual Studio 2005.
// The test owner should check each test for validity.
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.Text;
using System.Collections.Generic;
namespace Nirvana.PricingAnalysisModels.Tests
{
    /// <summary>
    ///This is a test class for Nirvana.PricingAnalysisModels.WinDalePricingAnalysisAdapter and is intended
    ///to contain all Nirvana.PricingAnalysisModels.WinDalePricingAnalysisAdapter Unit Tests
    ///</summary>
    [TestClass()]
    public class WinDalePricingAnalysisAdapterTest
    {
        private TestContext testContextInstance;

        /// <summary>
        ///Gets or sets the test context which provides
        ///information about and functionality for the current test run.
        ///</summary>
        public TestContext TestContext
        {
            get
            {
                return testContextInstance;
            }
            set
            {
                testContextInstance = value;
            }
        }
        #region Additional test attributes
        // 
        //You can use the following additional attributes as you write your tests:
        //
        //Use ClassInitialize to run code before running the first test in the class
        //
        //[ClassInitialize()]
        //public static void MyClassInitialize(TestContext testContext)
        //{
        //}
        //
        //Use ClassCleanup to run code after all tests in a class have run
        //
        //[ClassCleanup()]
        //public static void MyClassCleanup()
        //{
        //}
        //
        //Use TestInitialize to run code before running each test
        //
        //[TestInitialize()]
        //public void MyTestInitialize()
        //{
        //}
        //
        //Use TestCleanup to run code after each test has run
        //
        //[TestCleanup()]
        //public void MyTestCleanup()
        //{
        //}
        //
        #endregion

        [TestMethod()]
        [ExpectedException(typeof(ArgumentException), "PricingAnalysisModelsEnum with 'None' value was inappropriately allowed.")]
        public void NonePricingAnalysisModelsEnumTest()
        {
            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.None;
        }

        [TestMethod()]
        [ExpectedException(typeof(ArgumentException), "One or more unexpected values supplied in the arguments.")]
        public void WrongArgumentsGetCallPriceTest()
        {
            double StockPrice = double.MinValue;
            double ExercisePrice = double.MinValue;
            double InterestRate = double.MinValue;
            double TimeToMaturity = double.MinValue;
            double Volatility = double.MinValue;
            double Dividend = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            double callprice = pricingAnalysisModel.GetCallPrice(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend);
        }

        [TestMethod()]
        [ExpectedException(typeof(ArgumentException), "One or more unexpected values supplied in the arguments.")]
        public void WrongArgumentsGetPutPriceTest()
        {
            double StockPrice = double.MinValue;
            double ExercisePrice = double.MinValue;
            double InterestRate = double.MinValue;
            double TimeToMaturity = double.MinValue;
            double Volatility = double.MinValue;
            double Dividend = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            double putprice = pricingAnalysisModel.GetPutPrice(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend);
        }

        [TestMethod()]
        [ExpectedException(typeof(ArgumentException), "One or more unexpected values supplied in the arguments.")]
        public void WrongArgumentsGetDeltaTest()
        {
            double StockPrice = double.MinValue;
            double ExercisePrice = double.MinValue;
            double InterestRate = double.MinValue;
            double TimeToMaturity = double.MinValue;
            double Volatility = double.MinValue;
            double Dividend = double.MinValue;
            double cDelta = double.MinValue;
            double pDelta = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            pricingAnalysisModel.GetDelta(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend,ref cDelta,ref pDelta);
        }

        [TestMethod()]
        [ExpectedException(typeof(ArgumentException), "One or more unexpected values supplied in the arguments.")]
        public void WrongArgumentsGetThetaTest()
        {
            double StockPrice = double.MinValue;
            double ExercisePrice = double.MinValue;
            double InterestRate = double.MinValue;
            double TimeToMaturity = double.MinValue;
            double Volatility = double.MinValue;
            double Dividend = double.MinValue;
            double cTheta = double.MinValue;
            double pTheta = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            pricingAnalysisModel.GetTheta(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend,ref cTheta,ref pTheta);
            //GetPricingAnalysisModel
        }

        [TestMethod()]
        [ExpectedException(typeof(ArgumentException), "One or more unexpected values supplied in the arguments.")]
        public void WrongArgumentsGetGammaTest()
        {
            double StockPrice = double.MinValue;
            double ExercisePrice = double.MinValue;
            double InterestRate = double.MinValue;
            double TimeToMaturity = double.MinValue;
            double Volatility = double.MinValue;
            double Dividend = double.MinValue;
            double Gamma = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            pricingAnalysisModel.GetGamma(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend,ref Gamma);
            //GetPricingAnalysisModel
        }

        [TestMethod()]
        [ExpectedException(typeof(ArgumentException), "One or more unexpected values supplied in the arguments.")]
        public void WrongArgumentsGetVegaTest()
        {
            double StockPrice = double.MinValue;
            double ExercisePrice = double.MinValue;
            double InterestRate = double.MinValue;
            double TimeToMaturity = double.MinValue;
            double Volatility = double.MinValue;
            double Dividend = double.MinValue;
            double Vega = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            pricingAnalysisModel.GetVega(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend,ref Vega);
            //GetPricingAnalysisModel
        }

        [TestMethod()]
        [ExpectedException(typeof(ArgumentException), "One or more unexpected values supplied in the arguments.")]
        public void WrongArgumentsGetRhoTest()
        {
            double StockPrice = double.MinValue;
            double ExercisePrice = double.MinValue;
            double InterestRate = double.MinValue;
            double TimeToMaturity = double.MinValue;
            double Volatility = double.MinValue;
            double Dividend = double.MinValue;
            double cRho = double.MinValue;
            double pRho = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            pricingAnalysisModel.GetRho(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend,ref cRho,ref pRho);
            //GetPricingAnalysisModel
        }

        [TestMethod()]
        [ExpectedException(typeof(ArgumentException), "One or more unexpected values supplied in the arguments.")]
        public void WrongArgumentsGetImpliedVolatilityTest()
        {
            double StockPrice = double.MinValue;
            double ExercisePrice = double.MinValue;
            double InterestRate = double.MinValue;
            double TimeToMaturity = double.MinValue;
            double Dividend = double.MinValue;
            double callPrice = double.MinValue;
            int maxIteration = int.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            double? impliedVolitility = pricingAnalysisModel.GetImpliedVolatility(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Dividend,callPrice,maxIteration);
            //GetPricingAnalysisModel
        }

        [TestMethod()]
        [ExpectedException(typeof(ArgumentException), "One or more unexpected values supplied in the arguments.")]
        public void WrongArgumentsGetImpliedVolatilityPutTest()
        {
            double StockPrice = double.MinValue;
            double ExercisePrice = double.MinValue;
            double InterestRate = double.MinValue;
            double TimeToMaturity = double.MinValue;
            double Dividend = double.MinValue;
            double putprice  = double.MinValue;
            int maxIteration = int.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;

            double? impliedVolatilityPut = pricingAnalysisModel.GetImpliedVolatilityPut(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Dividend,putprice,maxIteration);
        }


        /// <summary>
        /// Tests the call price value.
        /// </summary>
        [Owner("Rajat"), DataSource("System.Data.SqlClient", "Data Source=VS20052K3E;Initial Catalog=NirvanaUnitTestDB;User ID=sa;Password=NIRvana2@@6", "GreeksVolatilityTest", DataAccessMethod.Sequential), TestMethod()]
        public void GetCallPriceTest()
        {
            double StockPrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.StockPrice]);
            double ExercisePrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.ExercisePrice]);
            double InterestRate = Convert.ToDouble(testContextInstance.DataRow[(int)Column.InterestRate]);
            double timeToMaturityinDays = Convert.ToDouble(testContextInstance.DataRow[(int)Column.TimeToMaturity]) ;
            double TimeToMaturity = Convert.ToDouble(timeToMaturityinDays/365);
            double Volatility = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Volatility]);
            double Dividend = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Dividend]);
            double expectedCallprice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.CallPrice]);

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            double ActualCallprice = Math.Round(pricingAnalysisModel.GetCallPrice(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend),4);

            Assert.AreEqual(expectedCallprice, ActualCallprice, "Call Price computation incorrect");
        }

        /// <summary>
        /// Tests the put price .
        /// </summary>
        [Owner("Rajat"), DataSource("System.Data.SqlClient", "Data Source=VS20052K3E;Initial Catalog=NirvanaUnitTestDB;User ID=sa;Password=NIRvana2@@6", "GreeksVolatilityTest", DataAccessMethod.Sequential), TestMethod()]
        public void GetPutPriceTest()
        {
            double StockPrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.StockPrice]);
            double ExercisePrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.ExercisePrice]);
            double InterestRate = Convert.ToDouble(testContextInstance.DataRow[(int)Column.InterestRate]);
            double timeToMaturityinDays = Convert.ToDouble(testContextInstance.DataRow[(int)Column.TimeToMaturity]);
            double TimeToMaturity = Convert.ToDouble(timeToMaturityinDays / 365);
            double Volatility = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Volatility]);
            double Dividend = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Dividend]);
            double expectedPutprice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.PutPrice]);

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            double ActualPutprice = Math.Round(pricingAnalysisModel.GetPutPrice(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend), 4);

            Assert.AreEqual(expectedPutprice, ActualPutprice, "Put Price computation incorrect");
        }

        const int MAX_ITERATIONS = 300;

        [Owner("Rajat"), DataSource("System.Data.SqlClient", "Data Source=VS20052K3E;Initial Catalog=NirvanaUnitTestDB;User ID=sa;Password=NIRvana2@@6", "GreeksVolatilityTest", DataAccessMethod.Sequential), TestMethod()]
        public void GetDeltaTest()
        {
            double StockPrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.StockPrice]);
            double ExercisePrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.ExercisePrice]);
            double InterestRate = Convert.ToDouble(testContextInstance.DataRow[(int)Column.InterestRate]);
            double timeToMaturityinDays = Convert.ToDouble(testContextInstance.DataRow[(int)Column.TimeToMaturity]);
            double TimeToMaturity = Convert.ToDouble(timeToMaturityinDays / 365);
            double Volatility = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Volatility]);
            double Dividend = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Dividend]);
            double expectedCDelta = Convert.ToDouble(testContextInstance.DataRow[(int)Column.CallDelta]);
            double expectedPDelta = Convert.ToDouble(testContextInstance.DataRow[(int)Column.PutDelta]);

            double ActualCDelta = double.MinValue;
            double ActualPDelta = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;

            DateTime initialTime = DateTime.Now;
            for (int i = 0; i < MAX_ITERATIONS; i++)
            {
                pricingAnalysisModel.GetDelta(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend, ref ActualCDelta, ref ActualPDelta);
            }
            TimeSpan currentTime = DateTime.Now.Subtract(initialTime);
            
            Assert.AreEqual(expectedCDelta, Math.Round(ActualCDelta,4) , "Call Delta computation incorrect");
            Assert.AreEqual(expectedPDelta, Math.Round(ActualPDelta,4)  , "Put Delta computation incorrect");
        }


        [Owner("Rajat"), DataSource("System.Data.SqlClient", "Data Source=VS20052K3E;Initial Catalog=NirvanaUnitTestDB;User ID=sa;Password=NIRvana2@@6", "GreeksVolatilityTest", DataAccessMethod.Sequential), TestMethod()]
        public void GetThetaTest()
        {
            double StockPrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.StockPrice]);
            double ExercisePrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.ExercisePrice]);
            double InterestRate = Convert.ToDouble(testContextInstance.DataRow[(int)Column.InterestRate]);
            double timeToMaturityinDays = Convert.ToDouble(testContextInstance.DataRow[(int)Column.TimeToMaturity]);
            double TimeToMaturity = Convert.ToDouble(timeToMaturityinDays / 365);
            double Volatility = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Volatility]);
            double Dividend = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Dividend]);
            double expectedCTheta = Convert.ToDouble(testContextInstance.DataRow[(int)Column.CallTheta]);
            double expectedPTheta = Convert.ToDouble(testContextInstance.DataRow[(int)Column.PutTheta]);

            double ActualCTheta = double.MinValue;
            double ActualPTheta = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;

            DateTime initialTime = DateTime.Now;
            for (int i = 0; i < MAX_ITERATIONS; i++)
            {
                pricingAnalysisModel.GetTheta(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend, ref ActualCTheta, ref ActualPTheta);
            }
            TimeSpan currentTime = DateTime.Now.Subtract(initialTime);

            Assert.AreEqual(expectedCTheta, Math.Round(ActualCTheta,4), "Call Theta computation incorrect");
            Assert.AreEqual(expectedPTheta, Math.Round(ActualPTheta,4), "Put Theta computation incorrect");
        }

        [Owner("Rajat"), DataSource("System.Data.SqlClient", "Data Source=VS20052K3E;Initial Catalog=NirvanaUnitTestDB;User ID=sa;Password=NIRvana2@@6", "GreeksVolatilityTest", DataAccessMethod.Sequential), TestMethod()]
        public void GetGammaTest()
        {
            double StockPrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.StockPrice]);
            double ExercisePrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.ExercisePrice]);
            double InterestRate = Convert.ToDouble(testContextInstance.DataRow[(int)Column.InterestRate]);
            double timeToMaturityinDays = Convert.ToDouble(testContextInstance.DataRow[(int)Column.TimeToMaturity]);
            double TimeToMaturity = Convert.ToDouble(timeToMaturityinDays / 365);
            double Volatility = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Volatility]);
            double Dividend = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Dividend]);
            double expectedGamma = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Gamma]);

            double ActualGamma = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;

            DateTime initialTime = DateTime.Now;
            for (int i = 0; i < MAX_ITERATIONS; i++)
            {
                pricingAnalysisModel.GetGamma(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend, ref ActualGamma);
            }
            TimeSpan currentTime = DateTime.Now.Subtract(initialTime);

            Assert.AreEqual(expectedGamma,Math.Round(ActualGamma,4) , "Gamma computation incorrect");
        }

        [Owner("Rajat"), DataSource("System.Data.SqlClient", "Data Source=VS20052K3E;Initial Catalog=NirvanaUnitTestDB;User ID=sa;Password=NIRvana2@@6", "GreeksVolatilityTest", DataAccessMethod.Sequential), TestMethod()]
        public void GetVegaTest()
        {
            double StockPrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.StockPrice]);
            double ExercisePrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.ExercisePrice]);
            double InterestRate = Convert.ToDouble(testContextInstance.DataRow[(int)Column.InterestRate]);
            double timeToMaturityinDays = Convert.ToDouble(testContextInstance.DataRow[(int)Column.TimeToMaturity]);
            double TimeToMaturity = Convert.ToDouble(timeToMaturityinDays / 365);
            double Volatility = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Volatility]);
            double Dividend = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Dividend]);
            double expectedVega = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Vega]);

            double ActualVega = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            DateTime initialTime = DateTime.Now;
            for (int i = 0; i < MAX_ITERATIONS; i++)
            {
                pricingAnalysisModel.GetVega(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend, ref ActualVega);
            }
            TimeSpan currentTime = DateTime.Now.Subtract(initialTime);

            Assert.AreEqual(expectedVega, Math.Round(ActualVega,4), "Vega computation incorrect");
        }

        [Owner("Rajat"), DataSource("System.Data.SqlClient", "Data Source=VS20052K3E;Initial Catalog=NirvanaUnitTestDB;User ID=sa;Password=NIRvana2@@6", "GreeksVolatilityTest", DataAccessMethod.Sequential), TestMethod()]
        public void GetRhoTest()
        {
            double StockPrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.StockPrice]);
            double ExercisePrice = Convert.ToDouble(testContextInstance.DataRow[(int)Column.ExercisePrice]);
            double InterestRate = Convert.ToDouble(testContextInstance.DataRow[(int)Column.InterestRate]);
            double timeToMaturityinDays = Convert.ToDouble(testContextInstance.DataRow[(int)Column.TimeToMaturity]);
            double TimeToMaturity = Convert.ToDouble(timeToMaturityinDays / 365);
            double Volatility = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Volatility]);
            double Dividend = Convert.ToDouble(testContextInstance.DataRow[(int)Column.Dividend]);
            double expectedCRho = Convert.ToDouble(testContextInstance.DataRow[(int)Column.CallRho]);
            double expectedPRho = Convert.ToDouble(testContextInstance.DataRow[(int)Column.PutRho]);

            double ActualCRho = double.MinValue;
            double ActualPRho = double.MinValue;

            IPricingAnalysisModel pricingAnalysisModel = PricingAnalysisModelFactory.GetPricingAnalysisModel();
            pricingAnalysisModel.CurrentPricingAnalysisModel = PricingAnalysisModelsEnum.Black_Scholes;
            DateTime initialTime = DateTime.Now;
            for (int i = 0; i < MAX_ITERATIONS; i++)
            {
                pricingAnalysisModel.GetRho(StockPrice, ExercisePrice, InterestRate, TimeToMaturity, Volatility, Dividend, ref ActualCRho, ref ActualPRho);
            }
            TimeSpan currentTime = DateTime.Now.Subtract(initialTime);

            Assert.AreEqual(expectedCRho, Math.Round(ActualCRho,4), "Call Rho computation incorrect");
            Assert.AreEqual(expectedPRho, Math.Round(ActualPRho,4), "Put Rho computation incorrect");
        }




    }

    /// <summary>
    /// Ideally it should read the column from the database instead of hard coding it
    /// </summary>
    enum Column
    {
        StockPrice,
        ExercisePrice,
        InterestRate,
        TimeToMaturity,
        Volatility,
        Dividend,
        CallPrice,
        PutPrice,
        CallDelta,
        PutDelta,
        CallTheta,
        PutTheta,
        Gamma,
        Vega,
        CallRho,
        PutRho,
        ImpliedVolatility,
        ImpliedVolatilityPut
    }



}
